### PR TITLE
fix!: Use dedicated mapping for Vaadin push endpoint

### LINKED ISSUE #14641: Websocket in combination with AJP broken behind reverse-proxy in 23.2.
### Description of the bug

Previously websocket connections could be forwarded by using a separate location in the httpd configuration like so `<Location /web/vaadinServlet/>` allowing this connection to be used with http / websockets - after 23.2 the websockets connection is not routed tho `/web/vaadinServlet/` anymore, instead it goes straigth to the `/web/?v-r=push...` where the connection can't be established because `/web/**` forwards to AJP, which DOES not support websockets.

Example exception:

```log

'HTTP upgrade is not supported by this protocol' Requested resource was: '/web/?v-r=push&v-uiId=1&v-pushId=0ce8ff89-eae1-4612-9a12-3383167a2d5b&X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=3.1.2-javascript&X-Atmosphere-Transport=websocket&X-Atmosphere-TrackMessageSize=true&Content-Type=application/json;%20charset=UTF-8&X-atmo-protocol=true'

```

### Expected behavior

Websockets should be handled by a separat endpoint `/web/vaadinServlet/` like done since V8.

### Minimal reproducible example

.

### Versions

- Vaadin / Flow version: 23.2
- Java version: 11
- OS version: xx
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

### PR DESCRIPTION
**Pull request by tepi**
Removes pushUrl configuration option, and instead maps push always to a dedicated path (/VAADIN/push).

Related-to #14641

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java [hunk 1]
```diff
@@ -236,6 +245,17 @@ public AtmosphereFramework addInitParameter(String name,
         return atmosphere;
     }
 
+    private static String findFirstUrlMapping(ServletConfig config) {
+        String name = config.getServletName();
+        String firstMapping = "/";
+        if (name != null) {
+            ServletRegistration reg = config.getServletContext()
+                    .getServletRegistrations().get(name);
+            firstMapping = reg.getMappings().stream().findFirst().orElse("/");
```
Comment (mshabarov) [inline flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java:254]: I propose to sort the mappings before taking the first one to make it deterministic and return the same mapping always.

**Review by mshabarov — CHANGES_REQUESTED** [review]

**Comment by tepi** [comment]
Note: if this is merged, we also need the change the push configuration documentation accordingly

**Review by mshabarov — APPROVED** [review]
