### PR TITLE
fix: support Range requests with either start or end byte index omitted

### LINKED ISSUE #9083: Local video cannot be displayed on iPad
[minimal-project.zip](https://github.com/vaadin/flow/files/5310767/minimal-project.zip)

### Description of the bug
When I try to link to, or integrate it as video tag, a local video, iPad Safari browser does not display anything.
It works on PC with Firefox, Edge and Chrome browsers.

### Minimal reproducible example

```
final Html videoHtml = new Html("<video controls='' autoplay='' src='_video_file_server_can_locally_access_such_as_css_or_js_files.mp4_' type='video/mp4' playsInline />");
final Anchor videoLink = new Anchor("_video_file_server_can_locally_access_such_as_css_or_js_files.mp4_","video");
layout.add(videoHtml, videoLink);
```

### Expected behavior
Video is displayed on iPad Safari browser, like it is on PC browsers.
### Actual behavior
Player does not start and tells the video is invalid
### Versions:
    - Vaadin / Flow version: 14.X
    - Java version: 8
    - OS version: iOS 14.0.1
    - Browser version (if applicable): Safari 14
    - Application Server (if applicable): Tomcat 8
    - IDE (if applicable): Eclipse 2019-09

### PR DESCRIPTION
**Pull request by joheriks**
Supports headers of the type `Range: -123` and `Range: 123-`. This
format was accidentally omittted in the previous implementation and 
Firefox and Chromium now use it.

Fixes #9083.

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java [hunk 1]
```diff
@@ -198,8 +198,16 @@ private void writeRangeContents(String range, HttpServletResponse response,
 
         List<Pair<Long, Long>> ranges = new ArrayList<>();
         while (rangeMatcher.find()) {
-            final long start = Long.parseLong(rangeMatcher.group(1));
-            final long end = Long.parseLong(rangeMatcher.group(2));
+            String startGroup = rangeMatcher.group(1);
+            String endGroup = rangeMatcher.group(2);
+            if (startGroup.isEmpty() && endGroup.isEmpty()) {
+                response.setContentLengthLong(0L);
+                response.setStatus(416); // Range Not Satisfiable
```
Comment (denis-anisimov) [inline flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java:205]: Seems this code branch is not tested ?

**Review by denis-anisimov — CHANGES_REQUESTED** [review]

File: flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java (hunk 1 above)
Comment (joheriks) [reply flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java:205]: Done.

**Review by denis-anisimov — APPROVED** [review]

**Comment by mshabarov** [comment]
Cherry picked to `5.0`

**Comment by taefi** [comment]
Cherry-picked to `4.0`
