### PR TITLE
fix(TypeScript): binder should allow typing decimal numbers

### LINKED ISSUE #9521: Binding to a double using a TS form does not work
### Minimal reproducible example
1. Go to https://start.vaadin.com/?preset=fusion
2. Change view type to "master-detail" and download
3. Change the type of `phone` in `Person.java` to `double`
4. Remove the data generation code from `DateGenerator`
5. Run the project and try to set the value of phone to `12.2`.

### Expected behavior
You can type "12.2" in the field

### Actual behavior
When you type "12." the value changes to "12" and it is impossible to input a decimal number.

### Versions:
    - Vaadin / Flow version: 18rc1

### LINKED ISSUE #9522: Binding a field to a NumberModel should not change an invalid input to NaN
### Minimal reproducible example
1. Go to https://start.vaadin.com/?preset=fusion
2. Change view type to "master-detail" and download
3. Change the type of `phone` in `Person.java` to `double`
4. Remove the data generation code from `DateGenerator`
5. Run the project and type e.g. "," in the phone field

### Expected behavior
The field value becomes "," and it turns red to indicate it is invalid

### Actual behavior
The field value becomes "NaN" and is shown as being valid

### Versions:
    - Vaadin / Flow version: 18rc1

### PR DESCRIPTION
**Pull request by platosha**
Fixes #9521
Fixes #9522

### CODE REVIEW

File: flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts [hunk 1]
```diff
@@ -56,15 +56,30 @@ export class Required<T> extends AbstractValidator<T> {
   }
 }
 
-function _asValidatorAttributes(attrs: ValueNumberAttributes | number | string | PatternAttributes | RegExp) {
+function _asValidatorAttributes(attrs: ValueNumberAttributes | number | string | PatternAttributes | string | RegExp) {
```
Comment (haijian-vaadin) [inline flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts:59]: redundant `string`?

**Review by haijian-vaadin — CHANGES_REQUESTED** [review]
Also, could we have a test for the fix?

**Comment by platosha** [comment]
@haijian-vaadin added tests, there is one ensuring that the value is not reset from the binder while typing.

**Comment by haijian-vaadin** [comment]
It looks good now, just found another issue. If I type `12,5` or `12,kjsdf` into the field, I don't get a validation error, the data is saved as 12. Could this be fixed in this PR, so should it be in another ticket?

**Comment by platosha** [comment]
@haijian-vaadin thanks for pointing out, fixed here also

**Comment by haijian-vaadin** [comment]
There are some lint errors for Models.ts file

**Comment by platosha** [comment]
@haijian-vaadin oh, I always forget those, fixed 😅

File: flow-client/src/test/frontend/form/FieldTests.ts [hunk 2]
```diff
@@ -311,6 +394,76 @@ suite("form/Field", () => {
...
+          // Invalid separator
+          [',', NaN],
+          [',2', NaN],
+          ['1,', NaN],
+          ['1,2', NaN]
+        ];
+
+        for (const [inputValue, expectedNumber] of cases) {
+          for (const eventName of ['input', 'change']) {
+            debugger;
```
Comment (haijian-vaadin) [inline flow-client/src/test/frontend/form/FieldTests.ts:440]: remove debugger?

File: flow-client/src/test/frontend/form/ValidatorsTests.ts [hunk 3]
```diff
@@ -120,6 +121,18 @@ suite("form/Validators", () => {
     assert.isFalse(validator.validate(true));
   });
 
+  test('IsNumber', () => {
+    const validator = new IsNumber();
+    assert.isNotTrue(validator.impliesRequired);
+    assert.isTrue(validator.validate(0));
+    assert.isTrue(validator.validate(1));
+    assert.isTrue(validator.validate(1.2));
```
Comment (haijian-vaadin) [inline flow-client/src/test/frontend/form/ValidatorsTests.ts:129]: Maybe we could add validations for `1,2`, `1,abc`, `abc` etc?

File: flow-client/src/test/frontend/form/FieldTests.ts (hunk 2 above)
Comment (haijian-vaadin) [inline flow-client/src/test/frontend/form/FieldTests.ts:440]: remove debugger?

**Review by haijian-vaadin — CHANGES_REQUESTED** [review]
It works! Good job! Found some minors things that could be improved.

File: flow-client/src/test/frontend/form/ValidatorsTests.ts (hunk 3 above)
Comment (platosha) [reply flow-client/src/test/frontend/form/ValidatorsTests.ts:129]: This validator cannot check those cases — it only works on the `number` data type, which is the only type `NumberModel` works with.

File: flow-client/src/test/frontend/form/FieldTests.ts (hunk 2 above)
Comment (platosha) [reply flow-client/src/test/frontend/form/FieldTests.ts]: done

**Review by haijian-vaadin — APPROVED** [review]
