### PR TITLE
fix: Use UI identity for background change detection in Effect

### LINKED ISSUE #23979: isBackgroundChange() is false for changes triggered by other users
### Description of the bug

`EffectContext.isBackgroundChange` returns `false` for changes that are triggered by another user.

### Expected behavior

Expected that changes from another user would be marked as background changes.

### Minimal reproducible example

```java
@Route
public class MainView extends VerticalLayout {
    private static final SharedValueSignal<Boolean> signal = new SharedValueSignal<>(true);

    public MainView() {
        Span span = new Span();
        span.bindText(() -> signal.get().toString()).onChange(context -> {
            System.out.println("Background change: " + context.isBackgroundChange());
        });
        add(span);

        add(new Button("Toggle from UI",click -> {
            signal.update(x -> !x);
        }));
        
        add(new Button("Toggle from background thread",click -> {
            Thread.startVirtualThread(() -> signal.update(x -> !x));
        }));
    }
}
```

1. Open the same UI in two separate browsers so that they use separate sessions
2. Click the "Toggle from UI" button
3. Notice that `Background change: false` is printed twice. Expected to get one case with `true` and another with `false`.

Note that the "Toggle from background thread" button works as expected - changes triggered in that way are reported as background changes for both users.

### Versions

- Vaadin / Flow version: Vaadin 25.1.0-rc2

### PR DESCRIPTION
**Pull request by Artur-**
EffectContext.isBackgroundChange() always returned false for shared signals modified by another user's session because the check only looked at VaadinRequest.getCurrent(), which is non-null on any request thread. Now Effect tracks its owner UI and compares UI.getCurrent() against it, correctly detecting cross-session changes as background changes.

Fixes #23979

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/signals/impl/Effect.java [hunk 1]
```diff
@@ -60,6 +61,8 @@ public class Effect implements Serializable {
 
     private final AtomicBoolean invalidateScheduled = new AtomicBoolean(false);
 
+    private transient volatile @Nullable UI ownerUI;
```
Comment (Legioth) [inline flow-server/src/main/java/com/vaadin/flow/signals/impl/Effect.java]: Why transient? The effect should only be serialized together with the UI that it belongs to?
Why volatile? The UI is set only when activating an effect, which only happens when the session is locked?

File: flow-server/src/main/java/com/vaadin/flow/signals/impl/Effect.java [hunk 2]
```diff
@@ -212,7 +215,13 @@ private boolean onDependencyChange(boolean immediate) {
                     "Infinite loop detected between effect updates. This effect is deactivated.");
         }
 
-        invalidatedFromBackground = VaadinRequest.getCurrent() == null;
+        if (ownerUI != null) {
+            UI currentUI = UI.getCurrent();
+            invalidatedFromBackground = currentUI == null
```
Comment (Legioth) [inline flow-server/src/main/java/com/vaadin/flow/signals/impl/Effect.java]: Redundant null check that makes the logic more difficult to understand. We already tested that `ownerUI` is not null which means that if `currrentUI` is null, then the `currentUI != ownerUI` check would also be true.

File: flow-server/src/main/java/com/vaadin/flow/signals/impl/Effect.java [hunk 3]
```diff
@@ -212,7 +215,13 @@ private boolean onDependencyChange(boolean immediate) {
...
+                    || currentUI != ownerUI;
+        } else {
+            invalidatedFromBackground = VaadinRequest.getCurrent() == null;
```
Comment (Legioth) [inline flow-server/src/main/java/com/vaadin/flow/signals/impl/Effect.java:221]: We no longer have any test for this case. Is it still needed?

**Comment by Artur-** [comment]
Is there any benefit of backporting it in a different way?

**Comment by Legioth** [comment]
Adding API in patch releases goes against the intent of semantic versioning that we claim to follow at least to some extent. We probably need to clarify exactly what that means but that's a discussion for another forum. Backporting this PR as-is is relatively fine since the `Effect` class is anyway mostly intended for internal use even though there's also a possibility that applications or add-ons use it directly.
