### PR TITLE
fix: Prevent NPE in ShortcutRegistration when lifecycleOwner is null

### LINKED ISSUE #19769: ShortcutRegistration throws NPE
### Description of the bug

I see the exception below in the logs.
I can't reproduce it but I think this should be caught by the framework because there is no code of mine involved. 

```
java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.component.Component.isVisible()" because "component" is null
	at com.vaadin.flow.component.ShortcutRegistration.ancestorsOrSelfAreVisible(ShortcutRegistration.java:648) ~[flow-server-24.4.4.jar:24.4.4]
	at com.vaadin.flow.component.ShortcutRegistration.fireShortcutEvent(ShortcutRegistration.java:641) ~[flow-server-24.4.4.jar:24.4.4]
	at com.vaadin.flow.component.ShortcutRegistration.lambda$updateHandlerListenerRegistration$89e5c563$1(ShortcutRegistration.java:601) ~[flow-server-24.4.4.jar:24.4.4]
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:239) ~[flow-server-24.4.4.jar:24.4.4]
	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:488) ~[flow-server-24.4.4.jar:24.4.4]
	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:298) ~[flow-server-24.4.4.jar:24.4.4]
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:473) ~[flow-server-24.4.4.jar:24.4.4]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[na:na]
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:473) ~[flow-server-24.4.4.jar:24.4.4]
	at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:62) ~[flow-server-24.4.4.jar:24.4.4]
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:73) ~[flow-server-24.4.4.jar:24.4.4]
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:475) ~[flow-server-24.4.4.jar:24.4.4]
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$5(ServerRpcHandler.java:456) ~[flow-server-24.4.4.jar:24.4.4]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[na:na]
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:456) ~[flow-server-24.4.4.jar:24.4.4]
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:324) ~[flow-server-24.4.4.jar:24.4.4]
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:114) ~[flow-server-24.4.4.jar:24.4.4]
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-24.4.4.jar:24.4.4]
```

### Expected behavior

No NPE should be thrown.

### Minimal reproducible example

Unfortunately I cannot reproduce it.

### Versions

- Vaadin / Flow version: 24.4.8
- Java version: 21

### PR DESCRIPTION
**Pull request by Artur-**
Add null guard in fireShortcutEvent() to handle the case where a KeyDown event fires after the shortcut's lifecycle owner has been detached and remove() has set lifecycleOwner to null.

Fixes #19769

### CODE REVIEW

File: flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java [hunk 1]
```diff
@@ -614,6 +614,32 @@ public void constructedRegistration_lifecycleOnwerHasInvisibleParent_shorcutEven
         Assert.assertNull(event.get());
     }
 
+    @Test
+    public void constructedRegistration_lifecycleOwnerRemovedBeforeKeyEvent_noNPE() {
```
Comment (caalador) [inline flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java]: This tests passes even without the null check.
Running through the debugger we do not get any call to `fireShortcutEvent`.
Seems it's the listenOn component mock loop that breaks test functionality.

**Review by caalador — CHANGES_REQUESTED** [review]

**Review by caalador — APPROVED** [review]
