### PR TITLE
fix: Warn for duplicate npm classes (#13291)

### LINKED ISSUE #13285: npm/pnpm install does not show version conflicts
### Description of the bug

We have a large application, that defines npm packages using the flow annotation. We had now the case, that (p)npm install had run all the time despite there have been no changes to the npm packages. After some research we found, that there have been two different versions of the same npm package. 

While in earlier Vaadin versions npm install had shown warnings for conflicting versions, now it does not anymore neither with npm nor with pnpm.

### Expected behavior

Using (p)npm install should show version conflicts.

### Minimal reproducible example

1. Create a new app using the Vaadin starter.
2. Create two simple views, with an NpmPackage annotation, e.g. `@NpmPackage(value = "tippy.js", version = "6.3.5")` on one and `@NpmPackage(value = "tippy.js", version = "6.3.7")` on the second
3. Do the normal stuff to start the application. 
4. The package.json will now show one of the versions.
5. Now exchange the versions in the two views(so .7 to .5 and vice versa)
6. On the next startup the package json will have changed to the other version

Step 5 might seem a bit theoretical, but as Vaadin seem to use the "last" found version, this is necessary to show, how the version seems to be picked randomly from addons / other modules.

### Versions

- Vaadin / Flow version: 23
- Java version: 17
- OS version: Windows 10

### PR DESCRIPTION
**Pull request by caalador**
If encountering multiple NpmPackage
annotations with different versions log
a warning and inform of choice taken.

Fixes #13285

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java [hunk 1]
```diff
@@ -70,15 +71,21 @@
...
+
     /**
      * Creates a new scanner instance which discovers all dependencies in the
      * classpath.
      *
      * @param finder
      *            a class finder
+     * @param fallback
+     *            whether FullDependenciesScanner is used as fallback
+     * @param finder
```
Comment (mcollovati) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java:84]: Seems like `@param finder`  is duplicated

Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java:84]: removed

**Review by mcollovati — APPROVED** [review]
