### PR TITLE
Always update webpack.generated.js

### LINKED ISSUE #10932: webpack.generated.js is not overwritten when upgrading from 14.0.10 to 14.5.4
### Description of the bug / feature

If you have a 14.0.10 project and have committed `webpack.generated.js` to the repository, it seems that upgrading to 14.5.4 keeps using the old `webpack.generated.js`, which causes the project to fail completely because webpack output path has been changed between 14.0 and 14.5

### PR DESCRIPTION
**Pull request by Artur-**
## Description

Fixes #10932

## Type of change

- [X] Bugfix

### CODE REVIEW

**Review by caalador — DISMISSED** [review]

**Review by caalador — APPROVED** [review]

File: flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java [hunk 1]
```diff
@@ -227,6 +231,19 @@ public void should_Run_Updaters_when_NoWebpackFile() throws Exception {
         assertNotNull(getDevModeHandler());
     }
 
+    @Test
+    public void should_Always_Update_Generated_Webpack_Conf() throws Exception {
+        File generatedWebpackFile = new File(webpackFile.getParentFile(), FrontendUtils.WEBPACK_GENERATED);
+        try (FileWriter writer = new FileWriter(generatedWebpackFile)) {
+            IOUtils.write("Hello world", writer);
+            Assert.assertEquals("Hello world", IOUtils.toString(generatedWebpackFile.toURI(),StandardCharsets.UTF_8));
```
Comment (caalador) [inline flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java:239]:
```suggestion
            IOUtils.write("Hello world", writer);
            writer.flush();
            Assert.assertEquals("Hello world", IOUtils.toString(generatedWebpackFile.toURI(),StandardCharsets.UTF_8));
```

**Review by caalador — CHANGES_REQUESTED** [review]
Seems it won't actually write to the file before flushing.

**Review by caalador — APPROVED** [review]
