### PR TITLE
fix: limit the requested items to a given threshold

### LINKED ISSUE #18403: Should have a limit on the number of sub-level items that can be requested
### Description of the bug

https://github.com/vaadin/flow/pull/12003 has introduced a limit on the number of items that can be requested from the server. However, this limit currently only applies to root level items, and you can still request an unlimited number of sub-level items.

### Expected behavior

Sub-level items should have the same limit as root level items.

### Versions

- Vaadin / Flow version: 24.4 and earlier

### PR DESCRIPTION
**Pull request by mcollovati**
## Description

Limits the number of requested items from backend to a given threshold of ten pages. Exactly the same as #12003, but applied to HierarchicalDataCommunicator.

Fixes #18403

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Review by vursen — APPROVED** [review]

File: flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java [hunk 1]
```diff
@@ -332,6 +332,21 @@ public DataCommunicator(DataGenerator<T> dataGenerator,
...
+     * Computes the requested range, limiting the number of requested items to a
+     * given threshold of ten pages.
+     *
+     * @param start
+     *            the start of the requested range
+     * @param length
+     *            the end of the requested range
+     * @return
+     */
+    protected final Range computeRequestedRange(int start, int length) {
```
Comment (vursen) [inline flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java:349]: **nit:** Does it have to be protected?

```suggestion
   final Range computeRequestedRange(int start, int length) {
```

Comment (mcollovati) [reply flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java:349]: Yes, it needs to be protected; otherwise it cannot be reused by the HierarchicalDataCommunicator that is in another package

**Review by mshabarov — APPROVED** [review]

**Comment by mcollovati** [comment]
Flow 1.0 does not have `HierarchicalDataCommunicator`, it was introduced in Flow 1.2. I'll remove the target label
