### PR TITLE
fix: log limitation of adding new styles while switching themes

### LINKED ISSUE #10680: Custom theme component styles are not watched by webpack after theme swapping
### Description of the bug / feature
When swapping a custom theme name in `@Theme("my-theme")` and after live reload, webpack still watches to the previous theme component folder (`frontend/themes/my-theme/components/`) and doesn't watch for changes (add/delete component CSS files) in a new theme component folder.
### Minimal reproducible example
1. Download project from start.vaadin.com (choose v19, v20 pre or v14 pre)
2. Create another theme folder, say `other-theme`
3. Run project `mvn`
4. Change theme name from `myapp` to `other-theme`
5. Wait until live reload finishes
6. Add any css file into `other-theme/components`, notice no live-reload happens.
7. Add any css file into `myapp/components`, notice live-reload still works.
### Expected behavior
Live reload works only for active theme  folder.
### Actual behavior
Live reload works for old, but not for actual theme folder.
### Versions:
    - Vaadin / Flow version: V14.6.0.beta1, V19.0.4, V20.0.0.alpha7
    - Java version: 8
    - OS version: MacOS
    - Browser version (if applicable): Chrome 89
    - Application Server (if applicable): spring-boot
    - IDE (if applicable): IntellijJ Idea

### PR DESCRIPTION
**Pull request by taefi**
## Description

If there are more than one theme available in
themes folder, user can switch between them in
development mode by changing the name of the
theme in `@Theme`. As having a watch for adding
new styles in component folder is 'static' and could
not be changed to another theme folder dynamically, 
at least a log about this limitation can help the users.

Fixes #10680 

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

This PR does not change any existing behavior, just adds some logs that can help users to find out when a restart is needed to see the effect of their changes in the available themes.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js [hunk 1]
```diff
@@ -39,8 +42,25 @@ const nameRegex = /theme-(.*)\.generated\.js/;
 function processThemeResources(options, logger) {
   const themeName = extractThemeName(options.frontendGeneratedFolder);
   if (themeName) {
+    if (!prevThemeName && !firstThemeName) {
+      firstThemeName = themeName;
+    } else if ((prevThemeName && prevThemeName !== themeName && firstThemeName !== themeName)
```
Comment (mshabarov) [inline flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js:47]: Just in case: have you tested that this message does not appear after CSS change live reload _before_ theme swap and after CSS change live reload _after_ theme swap?

File: flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js [hunk 2]
```diff
@@ -39,8 +42,25 @@ const nameRegex = /theme-(.*)\.generated\.js/;
...
+      logger.warn("*******************************************************************");
+      logger.warn(warning);
+      logger.warn(description);
+      logger.warn("*******************************************************************");
+    }
+    prevThemeName = themeName;
+
     findThemeFolderAndHandleTheme(themeName, options, logger);
   } else {
+    prevThemeName = undefined;
```
Comment (mshabarov) [inline flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js:63]: Why is it necessary? If no @Theme annotation or theme name string is specified, then this variable should be undefined.

File: flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js [hunk 3]
```diff
@@ -39,8 +42,25 @@ const nameRegex = /theme-(.*)\.generated\.js/;
...
   const themeName = extractThemeName(options.frontendGeneratedFolder);
   if (themeName) {
+    if (!prevThemeName && !firstThemeName) {
+      firstThemeName = themeName;
+    } else if ((prevThemeName && prevThemeName !== themeName && firstThemeName !== themeName)
+        || (!prevThemeName && firstThemeName !== themeName)) {
+      const warning = `Attention: Active theme is switched to '${themeName}'.`
+      const description = `
+      Note that adding new style sheet files to '/themes/${themeName}/components', 
+      may not be taken into effect until the next application is restart.
```
Comment (mshabarov) [inline flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js:52]:
```suggestion
      may not be taken into effect until the next application restart.
```

File: flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js [hunk 4]
```diff
@@ -39,8 +42,25 @@ const nameRegex = /theme-(.*)\.generated\.js/;
...
+      Changes to existing style sheet files are being reloaded as before.`;
```
Comment (mshabarov) [inline flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js:53]: Good to describe what does 'existing' mean. Does it refer to files inside /themes/${prevThemeName}/components ?

File: flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js (hunk 1 above)
Comment (taefi) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js:47]: Yes, it is not appear on those situations. I tested the styles in styles.css and also the existing [component].css in both themes.

File: flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js (hunk 2 above)
Comment (taefi) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js:63]: `prevThemeName = undefined;` is needed in the situation that the user decides to comment or remove the `@Theme(...)` completely to see how the application looks without any theme. Then when the user brings back one of the themes, the previous theme should be `undefined` to enable us to detect the change.

Comment (taefi) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js:63]: `!prevThemeName && firstThemeName !== themeName` would be `true` when the user brings back the `@Theme(...)` with the themeName that is not the first theme that application started with.

Comment (taefi) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js:63]: The reason for having `prevThemeName` is that I was warning the user with a message like this: `The current theme is changed from 'prevThemeName' to 'themeName' ...`. 
Now that I changed the message to show only the current theme, maybe keeping the `prevThemeName` is irrelevant, right?

File: flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js (hunk 4 above)
Comment (taefi) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js:53]: I'm referring to the `already existing` css files under /components in both themes, no matter it is the first theme or not. It just cannot detect adding new files being added. Existing css files are watched because of the dependency tree.

Comment (taefi) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js:53]:
```suggestion
      Changes to already existing style sheet files are being reloaded as before.`;
```

Comment (mshabarov) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js:53]: Ah, thanks! You're right, reload works for all existing files, no matter of old or new theme.

File: flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js (hunk 2 above)
Comment (mshabarov) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js:63]: Thanks for clarifications! It does make sense.
Could you please add a comment explaining that case and what for `(!prevThemeName && firstThemeName !== themeName)` and `prevThemeName = undefined;` are used. It would help improve the readability.

Comment (mshabarov) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js:63]:
```java
      // Warning message is shown to the developer when:
      // 1. He is switching to any theme, which is differ from one being set up 
      // on application startup, by changing theme name in `@Theme()`
      // 2. He removes or comments out `@Theme()` to see how the app 
      // looks like without theming, and then again brings `@Theme()` back.
     const warning = `Attention: Active theme is switched to '${themeName}'.`

     // This is needed in the situation that the user decides to comment or 
     // remove the @Theme(...) completely to see how the application looks 
     // without any theme. Then when the user brings back one of the themes, 
     // the previous theme should be undefined to enable us to detect the change.
     prevThemeName = undefined;

```

Comment (taefi) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js:74]: Done.

**Review by mshabarov — APPROVED** [review]
