### PR TITLE
fix!: withStatusLabel now sets field invalid state for consistent visual feedback

### LINKED ISSUE #21707: Status label does not set a component invalid
### Description

DatePicker Vaadin version 24.7.5 has these visual states depending on the validation state if used with Binder, custom validators and a fallback parser at the DatePicker:

1. if empty (by user clear) but required: it has light red background (OK/expected main visual state)
2. if invalid by custom validators: it has no light red background  (Invalid/inconsistent visual state)
3. if invalid by unparsable user input: it has light red background (OK/expected) and the datePicker show the error itself (BUG, unexpected)

Point (3) is caused by the custom fallback parser (that was taken from the javadoc at the related method `DatePicker::setFallbackParser()` )

Pictures to these points:
1.
  Image
2. 
  Image
3. 
  Image

### Expected outcome

1. The DatePicker component should have consistent light red background at all if component is in invalid state regardless the causing validator or fallback parser or whatever. 
2. Also if the binding is using `withStatusLabel( errorLabel )` it should take that into consideration.

### Minimal reproducible example

See attached project.

[datepicker-issue-5-26-2025.zip](https://github.com/user-attachments/files/20442100/datepicker-issue-5-26-2025.zip)

### Steps to reproduce

1. Start the project
2. Select a valid date using the date picker dropdown
3. Select the input and clear it -> expected visual state
4. Select a invalid date (today or tomorrow) using the date picker dropdown -> unexpected visual state
5. Now type any character like an 'a' within the date picker input field -> bug; the error message is also rendered by the input field below itself, not only at the errorLabel

### Environment

Vaadin version(s): 24.7.5
OS: Windows 11

### Browsers

Issue is not browser related

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #21707

Previously, withStatusLabel() only updated the status label but did not set the field's invalid state, resulting in inconsistent visual feedback where fields would not show the red background indicator for validation errors.

This fix ensures that withStatusLabel() also delegates to the binder's handleValidationStatus() method, which properly sets/clears the field's invalid state through handleError()/clearError(). This provides consistent visual feedback (red background + status label) across all validation scenarios:
- Required field validation
- Custom validator failures
- Conversion errors
- Multiple validators

The fix maintains backward compatibility while addressing the inconsistency reported in the issue.

Changes:
- Updated withStatusLabel() to call binder.handleValidationStatus()
- Added 6 comprehensive tests for various validation scenarios
- Updated existing test to reflect new behavior
- Fixed test binder to properly call super.handleError()

### CODE REVIEW

File: flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java [hunk 1]
```diff
@@ -854,7 +854,10 @@ default BindingBuilder<BEAN, TARGET> withNullRepresentation(
          * {@link #withValidationStatusHandler(BindingValidationStatusHandler)}
          * method where the handler instance hides the {@code label} if there is
          * no error and shows it with validation error message if validation
-         * fails. It means that it cannot be called after
+         * fails. The handler also sets the field's invalid state to provide
+         * visual feedback (e.g., red background) for fields implementing
+         * {@link com.vaadin.flow.component.HasValidation}. It means that it
```
Comment (tepi) [inline flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java]: I'd move this new block higher up in the javadoc. Now it's unclear what the existing "It means it cannot be called after..." refers to - or rather, you could understand it referring to the field invalid state setting.

Comment (Artur-) [reply flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java]: Done

**Comment by Artur-** [comment]
Added two tests to ensure `withValidationStatusHandler` can be used when you can full control

**Comment by trendelmann** [comment]
Sorry, don't see that change/fix in 24.8.16, not in 24.9.13. Where/when is it deployed?
