### PR TITLE
Pin versions based on versions file provided by the Platform

### LINKED ISSUE #7451: Follow up #7432: Use readPackage hook to pin dependency versions with pnpm
- [x] Use `pnpmfile.js`  from #7432.
- [x] Correct the code a bit so that it doesn't fail in the corner cases.
- [x] Assume that `versions.json`  (or some other name) is available in the classpath (the exact location is TBD).
- [x] So there is no need to download it but just access it via the classpath.
- [x] Make it possible to read the file via `pnpmfile.js` (copy it to the `target`  folder ?)
- [x] Generate `pnpmfile.js` file in the  project folder before running `pnpm install` .

Testing with platform split out to #7493

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #7451

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/7456)

### CODE REVIEW

File: flow-server/src/main/resources/pnpmfile.js [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+
+function readPackage(pkg) {
+  const deps = versions;
+
+  const { dependencies } = pkg;
+
+  if (dependencies) {
+    for (let k in deps) {
+      if (dependencies[k] && dependencies[k] !== deps[k]) {
+        console.log(
```
Comment (web-padawan) [inline flow-server/src/main/resources/pnpmfile.js]: nit: probably better to remove before merging, there might be a lot of logging output.

File: flow-server/src/main/resources/pnpmfile.js [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+const packageJson = JSON.parse(fs.readFileSync('./package.json', 'utf-8'));
+
+const versionsFile = '[to-be-generated-by-flow]';
+
+if (!fs.existsSync(versionsFile)) {
+    return;
+}
+const versions = JSON.parse(fs.readFileSync(versionsFile, 'utf-8'));
+
+let vaadinDeps;
```
Comment (web-padawan) [inline flow-server/src/main/resources/pnpmfile.js]: nit: unused variable from the original script, please remove.

File: flow-server/src/main/resources/pnpmfile.js [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+  }
+};
+
+function getExactVersion(string) {
+  return string.replace('^', '');
+}
+
+
+function readPackage(pkg) {
+  const deps = versions;
```
Comment (web-padawan) [inline flow-server/src/main/resources/pnpmfile.js]: nit: this extra assignment is not necessary.

you can remove it and use `for (let k in versions) {` etc below.

File: flow-server/src/main/resources/pnpmfile.js [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+}
+const versions = JSON.parse(fs.readFileSync(versionsFile, 'utf-8'));
+
+module.exports = {
+  hooks: {
+    readPackage
+  }
+};
+
+function getExactVersion(string) {
```
Comment (web-padawan) [inline flow-server/src/main/resources/pnpmfile.js]: nit: this function can be removed altogether and there are extra newlines below it.

didn't notice this during the first review round, sorry about that.
