### PR TITLE
Fix the support for Java 17 (Theme editor)

### LINKED ISSUE #17834: Error when trying to update a Java code with a switch (Java 17)
### Description of the bug

If I'm running my application in dev mode and try to change the style of a code that contains a switch expression (https://docs.oracle.com/en/java/javase/17/language/switch-expressions.html#GUID-BA4F63E3-4823-43C6-A5F3-BAA4A2EF3ADC)

I have an error:
``` 
Caused by: com.github.javaparser.ParseProblemException: (line 37,col 16) Switch expressions are not supported.

	at com.github.javaparser.JavaParserAdapter.handleResult(JavaParserAdapter.java:83) ~[javaparser-core-3.25.5.jar:na]
	at com.github.javaparser.JavaParserAdapter.parse(JavaParserAdapter.java:107) ~[javaparser-core-3.25.5.jar:na]
	at com.github.javaparser.StaticJavaParser.parse(StaticJavaParser.java:253) ~[javaparser-core-3.25.5.jar:na]
	at com.vaadin.base.devserver.editor.Editor.parseSource(Editor.java:1100) ~[vaadin-dev-server-24.2.0.beta2.jar:na]
	at com.vaadin.base.devserver.editor.Editor.modifyClass(Editor.java:1038) ~[vaadin-dev-server-24.2.0.beta2.jar:na]
	at com.vaadin.base.devserver.themeeditor.JavaSourceModifier.setLocalClassName(JavaSourceModifier.java:91) ~[vaadin-dev-server-24.2.0.beta2.jar:na]
	at com.vaadin.base.devserver.themeeditor.JavaSourceModifier.lambda$setLocalClassName$25aa656f$1(JavaSourceModifier.java:78) ~[vaadin-dev-server-24.2.0.beta2.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
	at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2018) ~[flow-server-24.2.0.beta2.jar:24.2.0.beta2]

```

### Expected behavior

I would like to be able to use all the Java 17 features by default since Java 17 is required for Vaadin 24 and also be able to use Java 21 if my application is using Java 21.

### Minimal reproducible example

https://github.com/jcgueriaud1/test-theme-editor-java17

### Versions

- Vaadin / Flow version: 24.2.0.rc2
- Java version: 17 or more

### PR DESCRIPTION
**Pull request by jcgueriaud1**
## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes #17834  (issue)

Add the parser configuration in the Editor class to allow the switch expression to be parsed 

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

File: vaadin-dev-server/src/main/java/com/vaadin/base/devserver/editor/Editor.java [hunk 1]
```diff
@@ -1097,6 +1099,10 @@ public int removeComponentAttribute(File f, int componentCreateLineNumber,
     }
 
     protected CompilationUnit parseSource(String source) {
+        ParserConfiguration parserConfiguration = new ParserConfiguration();
+        parserConfiguration
+                .setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_17);
```
Comment (Artur-) [inline vaadin-dev-server/src/main/java/com/vaadin/base/devserver/editor/Editor.java:1104]: Shouldn't this be Java 21 today?

Comment (jcgueriaud1) [reply vaadin-dev-server/src/main/java/com/vaadin/base/devserver/editor/Editor.java:1104]: That's the maximum for the library: https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/ParserConfiguration.java#L164

**Review by MarcinVaadin — APPROVED** [review]
Fix ✅ 
Test ✅ 

Thanks for contributing!
