### PR TITLE
[Security Fix]Use Vaadin's own ObjectMapper instead of the one from Spring

### LINKED ISSUE #8010: Vaadin 15 exposes private properties in JSON responses of REST api
Since switching to Vaadin 15, I noticed my rest api is showing private and protected properties without getters. 
A stripped down test project confirms this behaviour starts when adding the Vaadin dependencies.
I am using Vaadin on top of Spring Boot

### PR DESCRIPTION
**Pull request by haijian-vaadin**
Fixes #8010

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/8016)

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java [hunk 1]
```diff
@@ -137,4 +146,30 @@ public VaadinConnectAccessChecker accessChecker() {
...
     }
+
+    /**
+     * Registers a {@link ObjectMapper} bean instance.
+     *
+     * @return the object mapper for endpoint.
+     */
+    @Bean
+    @Qualifier(VAADIN_ENDPOINT_MAPPER_BEAN_QUALIFIER)
+    ObjectMapper objectMapper(ApplicationContext context) {
```
Comment (knoobie) [inline flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java:157]:
```suggestion
    public ObjectMapper vaadinEndpointMapper(ApplicationContext context) {
```
Change method name to reflect the `Bean` that's going to be created. 

Optional/Personal opinion: I would wrap the `ObjectMapper` in an object `VaadinConnectMapper#getObjectMapper` and return `VaadinConnectMapper` here as `Bean`, so it's easy to differentiate between the normal `ObjectMapper` and the Object Vaadin is using internally.

File: flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java [hunk 2]
```diff
@@ -137,4 +146,30 @@ public VaadinConnectAccessChecker accessChecker() {
...
+            ObjectMapper objectMapper = new ObjectMapper();
+            JacksonProperties jacksonProperties = context
+                    .getBean(JacksonProperties.class);
+            if (jacksonProperties.getVisibility().isEmpty()) {
+                objectMapper.setVisibility(PropertyAccessor.ALL,
+                        JsonAutoDetect.Visibility.ANY);
+            }
+            return objectMapper;
+        } catch (Exception e) {
+            throw new IllegalStateException(String.format(
```
Comment (knoobie) [inline flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java:168]: The whole try/catch could be removed?

File: flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java [hunk 3]
```diff
@@ -136,15 +133,13 @@
      *            The servlet context for the controller.
      */
     public VaadinConnectController(
-            @Autowired(required = false) @Qualifier(VAADIN_ENDPOINT_MAPPER_BEAN_QUALIFIER) ObjectMapper vaadinEndpointMapper,
+            @Autowired @Qualifier(VAADIN_ENDPOINT_MAPPER_BEAN_QUALIFIER) ObjectMapper vaadinEndpointMapper,
```
Comment (knoobie) [inline flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java:136]: Autowired could be removed - every instance in the constructor is autowired. 

This has to be updated, if my comment from below is accepted.

File: flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfigurationTest.java [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+                .thenReturn(Collections.singletonMap(PropertyAccessor.ALL,
+                        JsonAutoDetect.Visibility.PUBLIC_ONLY));
+
+        ObjectMapper objectMapper = configuration.vaadinEndpointMapper(contextMock);
+
+        verify(contextMock, times(1)).getBean(JacksonProperties.class);
+
+        try{
+                String result = objectMapper.writeValueAsString(new Entity());
+                assertEquals("{\"name\":\"Bond\"}", result);
```
Comment (knoobie) [inline flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfigurationTest.java:41]: Was thinking about this.. is this the right way to test it? I didn't have to time to look into VaadinConnect, so I'm not sure if this could break any existing usecases you wanted to handle. 

What I would expect from the test: 
- Asking the ApplicationContext for two beans (normal ObjectMapper and the qualified ObjectMapper) 
- Normal ObjectMapper should have all configuration provided by the user 
- Qualified ObjectMapper should have all configuration Vaadin needs to work 
- Both ObjectMapper serialize the same object.. depending on the configuration of the normal ObjectMapper both serialized strings should not look the same. (for example one could use Getter and the other properties for Serialization) 

Or am I missing something?
