### PR TITLE
fix: handle inner classes in component tracker

### LINKED ISSUE #18216: [Component Tracker]Cannot open a component inside an inner class
### Description of the bug

I'm trying to open a component inside the component tab in the devtools.
The component is not opened in my IDE and I have a `System.out.println` in my IDE

### Expected behavior

I would like to see my IDE opened in the correct line or an explanation.

### Minimal reproducible example

https://github.com/jcgueriaud1/spring-petclinic-vaadin-flow/tree/accessibility

Run it, go to http://localhost:8080/owners/1 click on the H3 title Pets.

The IDE is not opened at the correct line and you can see the line in your logs:
image

The reason is that the classname: `org.springframework.samples.petclinic.ui.view.owner.OwnerDetailsView$PetsContainer`
does not end with the filename `OwnerDetailsView(.java)` because of the `$PetsContainer` (name of the internal class)
image

### Versions

- Vaadin / Flow version: 24.3.0.beta1
- Java version: 21

### PR DESCRIPTION
**Pull request by mcollovati**
## Description

ComponentTracker location fails to determine the source file for inner classes. This change tries to identify the enclosing class before matching with location filename.

Fixes #18216

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-server/src/test/java/com/vaadin/flow/ComponentTrackerLocationTest.java [hunk 1]
```diff
@@ -0,0 +1,131 @@
...
+                "whoCares", 99);
+        File expectedFile = fakeSrcDir.toPath()
+                .resolve(Path.of("com", "example", "app", "MyClass.java"))
+                .toFile();
+
+        File javaFile = location.findJavaFile(configuration);
+        Assert.assertEquals(expectedFile, javaFile);
+    }
+
+    static class A {
```
Comment (tltv) [inline flow-server/src/test/java/com/vaadin/flow/ComponentTrackerLocationTest.java:124]: Remove unused(?) classes

**Review by tltv — CHANGES_REQUESTED** [review]

File: flow-server/src/test/java/com/vaadin/flow/ComponentTrackerLocationTest.java (hunk 1 above)
Comment (mcollovati) [reply flow-server/src/test/java/com/vaadin/flow/ComponentTrackerLocationTest.java:124]: Good catch! A leftover from a local test

File: flow-server/src/test/java/com/vaadin/flow/ComponentTrackerLocationTest.java [hunk 2]
```diff
@@ -0,0 +1,131 @@
...
+        static class B {
+            static class C {
+
+            }
+        }
+    }
```
Comment (mcollovati) [inline flow-server/src/test/java/com/vaadin/flow/ComponentTrackerLocationTest.java:130]:
```suggestion
```

**Review by tltv — APPROVED** [review]
