### PR TITLE
Repopulate empty model lists on detach.

### LINKED ISSUE #4283: Too complex polymer template causes exception if contained in dialog and opened twice
We have a weird issue with polymer component in a dialog. If its opened twice we get exception: “Assertion error: Don’t know how to convert node without map or list features”. It is probably connected to polymer template model, because if the model interface contains just simple string field it works fine, but if there is list of any objects it starts to fail. Even List<String> as a field type causes this to happen.

This started happening after updating to RC1 and still happens with RC3

PolymerTemplate is added to Dialog in server side and shown by calling Dialog.setOpened. 

Following code snippet demonstrates model used. With only name as field everything works fine.

`public interface Model extends TemplateModel {
		//List<String> getFail();
	       //void setFail(List<String> alternatives);
		String getName();
		void setName(String name);
    }`

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Closes #4283

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeList.java [hunk 1]
```diff
@@ -480,4 +480,10 @@ private void adjustChanges(int removeChangeIndex,
         }
     }
 
+    @Override
+    public void onDetach() {
```
Comment (denis-anisimov) [inline flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeList.java]: Could you please provide a unit test for this?

Comment (SomeoneToIgnore) [reply flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeList.java]: Done.
