### PR TITLE
fix(TailwindCSS): use hmr instead of full page reload for updating Tailwind CSS

### LINKED ISSUE #22722: Enabling Tailwind and hot deploy results in full page reload every time a Java file changes
### Description of the bug

After enabling the Tailwind feature flag and enabling hot deploy mode any change in a Java file (and saving it to disk) results in a full page reload. Presumably because all Java files are detected as a dependency in the Vite build? As mentioned in https://github.com/vaadin/flow/issues/22721, Tailwind is essentially useless during development if you do not use hot deploy so this will affect everyone using Tailwind.

Without using hotswap this behavior doesn't help at all as, even though the CSS is potentially updated with new Tailwind classes from the Vite build, the DOM is not updated because the Java class is not recompiled and hot swapped in the JVM.

With hotswap adding or removing Tailwind classes basically works. However it also essentially breaks hot swap as that should update the DOM in the current page instead of reloading the page on every change.

### Expected behavior

**Without hotswap**:
- It should not reload the page when saving the file
- It should reload the page if I recompile manually and use something like the Spring dev tools live reload, which would then result in having both the updated DOM and CSS in the browser

**With hotswap**:
- It should not reload the page when saving the file
- It should hot swap the DOM so that any new or removed Tailwind classes end up in the DOM
- It should hot swap the CSS so that any new or removed Tailwind classes end up in the CSS

### Minimal reproducible example

- Enable the Tailwind feature flag
- Enable hot deploy mode
- Start the app in dev mode with / without hotswap
- Change some Java file to add or remove Tailwind classes

### Versions

- Vaadin / Flow version: 25

### PR DESCRIPTION
**Pull request by platosha**
Fixes #22722

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindJs.java [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+ * Generate <code>tailwind.js</code> wrapper if it is missing in the generated
+ * frontend folder.
+ * <p>
+ * For internal use only. May be renamed or removed in a future release.
+ *
+ * @since 25.0
+ */
+public class TaskGenerateTailwindJs extends AbstractTaskClientGenerator {
+
+    private File tailwindJs;
```
Comment (mcollovati) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindJs.java]: nit: can be final

**Review by mcollovati — CHANGES_REQUESTED** [review]
Just a minor change. Other than that it seems to work fine.
