### PR TITLE
Live reload: construct correct push URL when both service URL (and context path) and liveReloadPath are given

### LINKED ISSUE #8541: Wrong push URL for JRebel / HotswapAgent live reload on 14.3
V14.3.0.alpha1
JRebel: 2020.2.2 (202005251048)

Started Spring applicatio with devtools enabled by running Application class directly. There is an error in browser console:

```
WebSocket connection to 'ws://localhost:8080/?v-r=push&refresh_connection' failed: Error during WebSocket handshake: Unexpected response code: 200
openDedicatedWebSocketConnection @ VaadinDevmodeGizmo.js?3e64:550
```
The URL is missing the `vaadinServlet` prefix.

### PR DESCRIPTION
**Pull request by joheriks**
Closes #8541. 

Note: Fix needs to be picked to master also, but will require some adaptation to the TS bootstrapping as the `flow-client` method for computing the URL with context root is not available there.

### CODE REVIEW

File: flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java [hunk 1]
```diff
@@ -94,9 +94,16 @@ public ApplicationConnection(
             Console.log(
                     "Vaadin application servlet version: " + servletVersion);
 
+            String reloadConnectionUrl;
+            if (applicationConfiguration.getLiveReloadPath() != null) {
+                reloadConnectionUrl = applicationConfiguration
+                        .getContextRootUrl()
+                        + applicationConfiguration.getLiveReloadPath();
+            } else {
+                reloadConnectionUrl = applicationConfiguration.getServiceUrl();
```
Comment (denis-anisimov) [inline flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java:103]: So the reload connection URL is just the same URL as the application URL?
Is it correct actually ?
Reload channel will use the application channel.
Won't they overlap ?

Comment (denis-anisimov) [reply flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java:103]: OR this is not a complete URL actually ?
Will it be used to append query parameters ?
Then from the comment above : looks like the name is confusing because it's not final URL....

Comment (jm-ferreira) [reply flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java:103]: If I'm not wrong a resource and query string are appended. In that sense it is not a _complete_ URL.

Comment (joheriks) [reply flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java:103]: This part of the code only constructs the first part of the URL, which in the normal case is the application URL. The exception is when there is a context-relative push URL (in case of Spring) and then we use that instead. The remainder of the URL (query parameters) are the same in both case.

Comment (denis-anisimov) [reply flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java:103]: I would may be call it `reloadConnectionBaseUri`.
But may be it doesn't really matter.

Comment (joheriks) [reply flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java]: Agree, that is a better name. Updated.
