### PR TITLE
Extend javadocs for Text and clarify not-supported API

### LINKED ISSUE #4882: Text Javadoc could be improved
`Text` Javadoc does not describe the component well enough. Even though `Text` extends `Component`, it is unclear that it can't be styled. An attempt to style a `Text` also results in an unclear error message:
>Caused by: java.lang.UnsupportedOperationException: This instance is immutable

Javadoc should provide more information and probably an `@see` to `Span`.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #4882

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/component/Text.java [hunk 1]
```diff
@@ -19,6 +19,15 @@
...
 /**
  * A component which encapsulates the given text in a text node.
+ * <p>
+ * Text node doesn't support setting any attribute or property so you may not
+ * use Element API (and {@link Text} doesn't provide any such contract) for
+ * setting attribute/property. It implies that you may not style this component
+ * as well. Any attempt to set attribute/property value throws an exception. The
+ * only available API for a {@link Text} component is set a text.
+ * <p>
+ * If you need a text component which can be styled then check {@code Span}
```
Comment (mshabarov) [inline flow-server/src/main/java/com/vaadin/flow/component/Text.java:29]: Minor: would it be better to have `@link` instead of `@code` for Span ref?

Comment (denis-anisimov) [reply flow-server/src/main/java/com/vaadin/flow/component/Text.java:29]: `link` doesn't work here since `Span` is a class in a different module which depends on `flow-server` and not vice-versa which is needed here.
