### PR TITLE
chore: fix ITs behavior inside OSGi

### LINKED ISSUE #9965: RerouteIT::testReroutingToErrorView is flaky
`RerouteIT.testReroutingToErrorView` sometimes fails.

https://bender.vaadin.com/viewLog.html?buildId=212186&tab=buildResultsDiv&buildTypeId=Flow_Flow24_Nightly_FlowFelixJettyIntegrationTests24

The screenshot shows a loading indicator so it might be a timing issue.

### PR DESCRIPTION
**Pull request by denis-anisimov**
fixes #9965

### CODE REVIEW

File: flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/routing/PushLayout.java [hunk 1]
```diff
@@ -31,6 +36,14 @@
 
     public PushLayout() {
         setId("push-layout");
+        Lookup lookup = VaadinService.getCurrent().getContext()
+                .getAttribute(Lookup.class);
+        if (lookup.lookup(OSGiMarker.class) == null) {
```
Comment (mshabarov) [inline flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/routing/PushLayout.java:41]: Who is supposed to put `OSGiMarker` service into Lookup?
Similar marker interface in `master` has an annotated implementation which, I guess, is taken up to the context if OSGi is used.
But what is the behaviour in 2.6?

Comment (denis-anisimov) [reply flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/routing/PushLayout.java:41]: Good catch. I forgot to put the service impl.

**Review by mshabarov — DISMISSED** [review]

**Review by mshabarov — APPROVED** [review]
