### PR TITLE
fix: add possibility to set header values for StreamResource

### LINKED ISSUE #5471: StreamResource should have method for setting "Content-Disposition" response header
StreamResource currently have methods for setting response headers for contentType and cacheTime.

It would be useful if we could set content disposition also. This could, for example, be used to force download of dynamic content (instead of opening it in browser) with header: Content-Disposition: attachment; filename="filename.jpg".

Content disposition could be set with dedicated method ```setContentDisposition(String value)``` or more generic ```setHeader(String name, String value)```?

### PR DESCRIPTION
**Pull request by denis-anisimov**
fixes #5471

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java [hunk 1]
```diff
@@ -217,6 +222,53 @@ public ContentTypeResolver getContentTypeResolver() {
...
+        return this;
+    }
+
+    /**
+     * Gets the header {@code name} for the resource.
+     * 
+     * @param name
+     *            a header name
+     * @return an optional header, or an empty optional if it has not been set
+     */
```
Comment (caalador) [inline flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java:249]:
```suggestion
    /**
     * Gets the value for header {@code name} set for the resource.
     * 
     * @param name
     *            name of header to get value for
     * @return an optional with header value, or an empty optional if it has not been set
     */
```

**Review by caalador — APPROVED** [review]
Minor javadoc change that would make it a bit clearer on a read

**Review by caalador — DISMISSED** [review]

**Review by caalador — APPROVED** [review]
