### PR TITLE
fix: Set Content-Length header in InputStreamDownloadHandler (#22558)

### LINKED ISSUE #22558: InputStreamDownloadHandler does not set content length header in handleDownloadRequest
### Description

`Content-Length` response header is not set, even when length parameter is passed to various `DownloadHandler.XY` static methods, for example `fromInputStream`, which on background uses `InputStreamDownloadHandler`.

This is not happening when you use `forFile` method, which sets `Content-Length` response header, (at the end of the day, a input stream is also used in background). So what is the point of not setting `Content-Length` when using for example `fromInputStream` method?. 

One would expect when setting content length parameter to download response, it will be set to response header, whatever method he/she will use.

Setting `Content-Length` response header is on line 88 of `FileDownloadHandler`:  `downloadEvent.setContentLength(file.length())`.

### Expected outcome

Set content length in `fromInputStream` method as it is done in `forFile` method? Well, one could just modify downloadEvent directly, but why setting it in `forFile` method and not `fromInputStream` method? Even `forFile` method uses input stream in background.

### Minimal reproducible example

val handler = DownloadHandler.fromInputStream(downloadEvent ->
 new DownloadResponse(
  stream,
  name,
  type,
  length);
); // whatever length will be, it will not be set as Content-Length response header

### Steps to reproduce

Just use fromInputStream method

### Environment

Vaadin version(s): 24.9.3
OS: any

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by Artur-**
InputStreamDownloadHandler now properly sets the Content-Length HTTP header when provided in DownloadResponse, enabling browsers to display download progress and allowing TransferProgressListener implementations to calculate accurate progress percentages. This aligns behavior with FileDownloadHandler.

Fixes #22558

### CODE REVIEW

File: flow-server/src/test/java/com/vaadin/flow/server/streams/InputStreamDownloadHandlerTest.java [hunk 1]
```diff
@@ -101,15 +101,15 @@ public void onStart(TransferContext context) {
             public void onProgress(TransferContext context,
                     long transferredBytes, long totalBytes) {
                 transferredBytesRecords.add(transferredBytes);
-                Assert.assertEquals(-1, totalBytes);
+                Assert.assertEquals(165000, totalBytes);
```
Comment (mcollovati) [inline flow-server/src/test/java/com/vaadin/flow/server/streams/InputStreamDownloadHandlerTest.java]: nit: we could put byte array size in a constant and use it here and in `getBytes()` methods.

File: flow-server/src/main/java/com/vaadin/flow/server/streams/InputStreamDownloadHandler.java
Comment (mcollovati) [inline flow-server/src/main/java/com/vaadin/flow/server/streams/InputStreamDownloadHandler.java:103]: `TransferUtil.transfer(...)` return the number of bytes transferred. Would it make sense to use that value if  `DownloadEvent` content length is -1?

Comment (Artur-) [reply flow-server/src/main/java/com/vaadin/flow/server/streams/InputStreamDownloadHandler.java:103]: Doesn't that happen after the download is finished?

File: flow-server/src/test/java/com/vaadin/flow/server/streams/InputStreamDownloadHandlerTest.java (hunk 1 above)
Comment (Artur-) [reply flow-server/src/test/java/com/vaadin/flow/server/streams/InputStreamDownloadHandlerTest.java]: Done

File: flow-server/src/main/java/com/vaadin/flow/server/streams/InputStreamDownloadHandler.java
Comment (mcollovati) [reply flow-server/src/main/java/com/vaadin/flow/server/streams/InputStreamDownloadHandler.java:103]: Yeah, that's true. My bad.

**Review by mcollovati — APPROVED** [review]
