### PR TITLE
Fix the dependency of DevModeInitializer on ServletRegistration

### LINKED ISSUE #7542: DevModeHandler not initialized on WebSphere Application Server 9
Synopsis: `DevModeHandler` fails to start when deploying a devmode WAR packaged inside an EAR to WAS 9.0.5.21 using IntellIJ Ultimate's WebSphere integration. Deploying a production mode WAR using the same steps as below works.

To reproduce:
1. Install IBM WebSphere Application Server and create a standard profile using the included WebSphere Customization Toolbox.
2. Download [skeleton-starter-flow-ws.zip](https://github.com/vaadin/flow/files/4185340/skeleton-starter-flow-ws.zip) and import both `pom.xml` and `pom-ear.xml` into IntelliJ (Ultimate Edition). This is the basic skeleton starter with added IntelliJ run configuration and a pom for wrapping the built WAR file in an EAR file (as WAS cannot directly deploy WAR files.)
3. Run `mvn -f pom.xml install` to install the WAR and `mvn -f pom-ear.xml` to package it into an EAR file.
4. Update the existing run configuration or create a new configuration for the installed WebSphere that deploys the artifact `deployment:ear` to your WebSphere installation.
5. Run the configuration and navigate in a browser to `localhost:9080/base`.
6. Application fails with the following `NullPointerException` because `DevModeHandler` is never started (due to the test `registrations.isEmpty()` in `DevModeInitializer::onStartup` being positive).

```
[2/11/20 11:40:52:674 EET] 00000099 SystemErr     R [Thread-59] INFO com.vaadin.flow.server.osgi.OSGiAccess - Unable to detect used OSGi framework version due to null
[2/11/20 11:40:53:236 EET] 00000099 SystemErr     R [Thread-59] INFO com.vaadin.flow.server.startup.ServletDeployer - Automatically deploying Vaadin servlet with name com.vaadin.flow.server.startup.ServletDeployer to /*
[2/11/20 11:40:54:908 EET] 000000b7 SystemErr     R [WebContainer : 0] WARN com.vaadin.flow.server.DefaultDeploymentConfiguration - 
====================================================================
Vaadin is running in DEBUG MODE.
In order to run your application in production mode and disable debug features, you should enable it by setting the servlet init parameter productionMode to true.
See https://vaadin.com/docs/v14/flow/production/tutorial-production-mode-basic.html for more information about the production mode.
====================================================================
[2/11/20 11:41:15:189 EET] 000000b8 SystemErr     R [WebContainer : 1] ERROR com.vaadin.flow.server.DefaultErrorHandler - 
[2/11/20 11:41:15:189 EET] 000000b8 SystemErr     R java.lang.NullPointerException
[2/11/20 11:41:15:189 EET] 000000b8 SystemErr     R 	at com.vaadin.flow.server.frontend.FrontendUtils.getStatsAssetsByChunkName(FrontendUtils.java:693)
[2/11/20 11:41:15:189 EET] 000000b8 SystemErr     R 	at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.appendNpmBundle(BootstrapHandler.java:907)
[2/11/20 11:41:15:189 EET] 000000b8 SystemErr     R 	at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.setupFrameworkLibraries(BootstrapHandler.java:889)
[2/11/20 11:41:15:189 EET] 000000b8 SystemErr     R 	at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.setupDocumentHead(BootstrapHandler.java:768)
[2/11/20 11:41:15:189 EET] 000000b8 SystemErr     R 	at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.getBootstrapPage(BootstrapHandler.java:537)
[2/11/20 11:41:15:189 EET] 000000b8 SystemErr     R 	at com.vaadin.flow.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:478)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1545)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:247)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1235)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:779)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:478)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:179)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1124)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:82)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:963)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:382)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:465)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:532)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:318)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.ready(HttpInboundLink.java:289)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:214)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:113)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1909)
```

Versions:
- WebSphere Application Server 9.0.5.21
- Vaadin 14.2-SNAPSHOT
- Windows 10

### PR DESCRIPTION
**Pull request by mehdi-vaadin**
Fix #7542

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/7709)

### CODE REVIEW

File: flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java [hunk 1]
```diff
@@ -285,6 +286,7 @@ public void shouldThrow_tokenFileContainsNonExistingNpmFolderInDevMode()
                 tokenFile.getPath()));
     }
 
+    @Ignore("It relies only on servlet init params.")
```
Comment (caalador) [inline flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java]: What do you mean relies on init parameters? The code runs `readBuildInfo()` that reads the token file in `createInitParameters()`
