### PR TITLE
fix: Prevent stale JAR cache in `ReflectionsClassFinder` under Gradle daemon (CP: 24.9)

### LINKED ISSUE #15458: vaadinBuildFrontend irregularly failing with ZipException: ZipFile invalid LOC header (bad signature)
**Desktop (please complete the following information):**
 - OS: macOS 12.x, macOS 13.x, Ubuntu 22.4, Windows 11
 - JDK version: 11 (temurin + zulu tested)
 - Gradle version: 7.5.1
 - Vaadin Plugin version: 23.1.17

**Describe the bug**
Running `./gradlew vaadinBuildFrontend` sometimes fails with `ZipException: ZipFile invalid LOC header (bad signature)` ([Stacktrace1.txt](https://github.com/vaadin/vaadin-gradle-plugin/files/10153376/Stacktrace1.txt)).

There are days without the bug, there are others where every `vaadinBuildFrontend` causes the error.

Identified preconditions: The Bug only surfaces
- when there are changes made to the gradle project containing the Vaadin UI
- when the gradle daemon is used (from the 2nd run)
- ?

**Workaround**
Stop the daemon using `./gradlew --stop` and run the task again.

**To Reproduce**
Reproduction is not possible... it seems to be somewhat dependent on the changes made to the sources.

**Expected behavior**
successful frontend build

**Additional context**

### PR DESCRIPTION
**Pull request by mcollovati**
Close `URLClassLoader` on cleanup to release JAR file handles, and disable JVM-level JAR caching in `getResource()` by wrapping `jar:` URLs with a `URLStreamHandler` that sets `useCaches(false)`.

The Gradle daemon reuses JVMs across builds. When a sibling module's JAR is rewritten, two independent caching layers can hold stale file handles:
1. `URLClassLoader` internal cache (`URLClassPath` → `JarLoader`)
2. `JarFileFactory` static HashMap (populated via `JarURLConnection`)

The `URLClassLoader.close()` call addresses layer 1, but layer 2 is JVM-global and independent of the class loader. Setting `useCaches(false)` on `jar:` URL connections prevents `JarFileFactory` from caching `JarFile` instances, matching the approach used by Spring's `PathMatchingResourcePatternResolver` (SPR-4639).

Fixes #15458

### CODE REVIEW

File: flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt [hunk 1]
```diff
@@ -79,58 +79,62 @@ public abstract class VaadinBuildFrontendTask : DefaultTask() {
...
     public fun vaadinBuildFrontend() {
-        val config = adapter.get().config
-        logger.info("Running the vaadinBuildFrontend task with effective configuration $config")
-        // sanity check
+        try {
+            val config = adapter.get().config
+            logger.info("Running the vaadinBuildFrontend task with effective configuration $config")
+            // sanity check
         val tokenFile = BuildFrontendUtil.getTokenFile(adapter.get())
         check(tokenFile.exists()) { "token file $tokenFile doesn't exist!" }
```
Comment (caalador) [inline flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt]: These lines have not bee formatted to correct indentation after the added try{}

Comment (mcollovati) [reply flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt]: fixed

**Review by caalador — APPROVED** [review]
