### PR TITLE
fix: tailwind styles and add-on css import

### LINKED ISSUE #23082: Tailwind CSS @apply does not work in custom theme files in Vaadin Flow 25
### Description of the bug

The Tailwind @apply directive does not have any effect when used inside custom CSS files in Vaadin Flow 25 projects. Utility classes included via @apply do not appear in the compiled output: the corresponding CSS selectors are either empty or missing entirely, and components using these classes do not receive any styling—even after performing a full rebuild and restart of the application.

### Expected behavior

Styles from custom classes using Tailwind `@apply` should be processed and applied to components. For example, 
`.custom-hr {
     @apply h-[2px] bg-blue-200 w-full;
   } ` should generate CSS rules exactly as if the Tailwind utility classes were written inline on the component.

### Minimal reproducible example

1. Create a custom CSS file, e.g. `theme/styles.css` with the content:
   ```css
   .custom-hr {
     @apply h-[2px] bg-blue-200 w-full;
   }
   ```
2. Reference this CSS file in the theme or component.
3. Start the Vaadin Flow application (dev or prod mode).
4. Add an `Hr` Flow component and assign the custom class in Java:
   ```java
   Hr hr = new Hr();
   hr.addClassName("custom-hr");
   add(hr);
   ```
5. Open the application. The HR element does not show any styling from the custom class.
6. Inspect the resulting CSS/HTML. The `.custom-hr` class is empty or completely missing from the generated CSS.
7. This remains true even after a full build or server/application restart.

### Versions

- Vaadin / Flow version: 25.0.2
- Tailwind CSS: (as shipped with Vaadin 25.0.2)
- Node.js: 24.12.0 (LTS)
- Java version: 21 LTS
- IDE:  IntelliJ IDEA 2025.3.1

### LINKED ISSUE #23218: Tailwind breaks addon style imports
### Description of the bug

I wanted to add the [FullCalendar for Flow addon](https://vaadin.com/directory/component/full-calendar-flow) to a simple starter, that has Tailwind activated.

This lead to an issue with a css `@import` statement on the main addon stylesheet.
```
2026-01-15T08:23:08.501+01:00  INFO 31022 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 08:23:08 [vite] (client) Pre-transform error: Can't resolve 'full-calendar-theme-vaadin.css' in '/home/suebe/workspace/other/playground/src/main/frontend/generated/jar-resources/vaadin-full-calendar'
2026-01-15T08:23:08.501+01:00  INFO 31022 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   Plugin: @tailwindcss/vite:generate:serve
2026-01-15T08:23:08.501+01:00  INFO 31022 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   File: /home/suebe/workspace/other/playground/src/main/frontend/generated/jar-resources/vaadin-full-calendar/full-calendar-styles.css?inline
2026-01-15T08:23:08.629+01:00  INFO 31022 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 08:23:08 [vite] Internal server error: Can't resolve 'full-calendar-theme-vaadin.css' in '/home/suebe/workspace/other/playground/src/main/frontend/generated/jar-resources/vaadin-full-calendar'
2026-01-15T08:23:08.629+01:00  INFO 31022 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   Plugin: @tailwindcss/vite:generate:serve
2026-01-15T08:23:08.629+01:00  INFO 31022 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   File: /home/suebe/workspace/other/playground/src/main/frontend/generated/jar-resources/vaadin-full-calendar/full-calendar-styles.css?inline
...

```

The issue also appears, when I run a production build with `mvn clean package`.

With Tailwind disabled, everything works as expected.

The addon itself imports the style using `@CssImport`.

### Expected behavior

It should not break.

### Minimal reproducible example

* Download a vaadin starter. 
* Add the addon (see the link above)
* Activate tailwind
* Start the application or run a production build
* The error should appear

### Versions

- Vaadin / Flow version: 25.0.3
- Java version: 25
- OS version: Kubuntu
- Browser version (if applicable):

### PR DESCRIPTION
**Pull request by caalador**
Collect jar-resource and StyleSheet
css as imports into tailwind.css
Now tailwind knows to go through said
files and where they are located.

Fixes #23082
Fixes #23218

### CODE REVIEW

**Comment by caalador** [comment]
This still has the issue that full-calendar-styles.css contains `@import "full-calendar-theme-vaadin.css";` which is not found by tailwind except if it is updated to a relative import `@import "./full-calendar-theme-vaadin.css";`

Also to note if using Theme then there need to be a `@reference` in the css e.g.
```
@reference "tailwindcss";

.custom-hr {
  @apply h-[2px] bg-blue-200 w-full;
}
```

File: flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java [hunk 1]
```diff
@@ -39,10 +52,15 @@ public class TaskGenerateTailwindCss extends AbstractTaskClientGenerator {
...
     private static final String CUSTOM_IMPORT_MARKER = "/* #customImport# */";
+    private static final String CSS_IMPORT_MARKER = "/* #cssImport# */";
     private static final String TAILWIND_CUSTOM_CSS = "tailwind-custom.css";
+    private static final String STYLES_CSS = "styles.css";
+    private static final Logger log = LoggerFactory
+            .getLogger(TaskGenerateTailwindCss.class);
 
     private String relativeSourcePath;
     private String customImportReplacement;
+    private String themeImportReplacement;
```
Comment (mcollovati) [inline flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java]: nit: can be final

File: flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java [hunk 2]
```diff
@@ -98,4 +123,183 @@ protected File getGeneratedFile() {
...
+     *            the imports string builder
+     */
+    private static void addThemeImportIfAvailable(Options options,
+            StringBuilder imports) {
+
+        FrontendDependenciesScanner frontendDependenciesScanner = options
+                .getFrontendDependenciesScanner();
+        String themeName = "";
+        if (frontendDependenciesScanner != null) {
+            if (frontendDependenciesScanner.getThemeDefinition() != null) {
```
Comment (mcollovati) [inline flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java]: nit: we can perhaps combine the two conditions into one single if

File: flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java [hunk 3]
```diff
@@ -98,4 +123,183 @@ protected File getGeneratedFile() {
...
+
+            // Import styles.css if it exists
+            File stylesCss = new File(themeFolder, STYLES_CSS);
+            if (stylesCss.exists()) {
+                String relativePath = options.getFrontendGeneratedFolder()
+                        .toPath().relativize(stylesCss.toPath()).toString()
+                        .replace(File.separator, "/");
+                imports.append("@import '").append(relativePath).append("';\n");
+            }
+        }
```
Comment (mcollovati) [inline flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java:181]: Does this work also if the used theme is packaged as a JAR? Or is that case handled elsewhere?

File: flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java [hunk 4]
```diff
@@ -98,4 +123,183 @@ protected File getGeneratedFile() {
...
+     */
+    private void addCssImports(Options options, StringBuilder imports) {
+
+        Collection<String> cssImports = options.getFrontendDependenciesScanner()
+                .getCss().values().stream().flatMap(List::stream)
+                .map(CssData::getValue).collect(Collectors.toList());
+        cssImports.addAll(collectStyleSheetAnnotations(options));
+
+        // Import all @CssImport CSS files that exist in the frontend directory
+        if (cssImports != null) {
```
Comment (mcollovati) [inline flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java]: nit: cssImports cannot be null here

File: flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java [hunk 5]
```diff
@@ -98,4 +123,183 @@ protected File getGeneratedFile() {
...
+            Path frontendFolder = options.getFrontendGeneratedFolder()
+                    .getParentFile().toPath();
```
Comment (mcollovati) [inline flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java]: `frontendFolder` variable seems unused

File: flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java [hunk 6]
```diff
@@ -98,4 +123,183 @@ protected File getGeneratedFile() {
...
+        // Handle Frontend/ alias
+        if (cssPath.startsWith("Frontend/")) {
+            cssPath = cssPath.substring("Frontend/".length());
+        }
+        // Handle ./ prefix
+        if (cssPath.startsWith("./")) {
+            cssPath = cssPath.substring(2);
+        }
+
+        Path frontendFolder = options.getFrontendGeneratedFolder()
```
Comment (mcollovati) [inline flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java]: nit: I would maybe rename the variable to `frontendGeneratedFolder` otherwise it could be confusing when used later on

File: flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java [hunk 7]
```diff
@@ -98,4 +123,183 @@ protected File getGeneratedFile() {
...
+                return "Frontend/" + relativePath;
+            }
+        }
+        // Try resources directory
+        File resourcesFolder = options.getJavaResourceFolder();
+        if (resourcesFolder == null) {
+            resourcesFolder = options.getNpmFolder().toPath()
+                    .resolve("src/main/resources").toFile();
+        }
+        if (resourcesFolder != null && resourcesFolder.exists()) {
```
Comment (mcollovati) [inline flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java]: `resourcesFolder` cannot be null here

```suggestion
        if (resourcesFolder.exists()) {
```

Comment (mcollovati) [reply flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java]: Also, I wonder if we can directly compute the `src/main/resources/META-INF/resources` path and check for its existence, instead of doing two checks

File: flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java (hunk 1 above)
Comment (caalador) [reply flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java]: Goes for all 3

File: flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java (hunk 2 above)
Comment (caalador) [reply flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java]: Done. It had another branch in one iteration.

File: flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java (hunk 4 above)
Comment (caalador) [reply flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java]: removed if

File: flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java (hunk 5 above)
Comment (caalador) [reply flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java]: removed.

File: flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java (hunk 6 above)
Comment (caalador) [reply flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java]: It was actually the frontendFolder as we got generated and then the parent folder.
Updated to actual frontendGenerated

File: flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java (hunk 7 above)
Comment (caalador) [reply flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java]: We probably can. Updated.

File: flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java (hunk 3 above)
Comment (caalador) [reply flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTailwindCss.java:181]: No it will not handle a JAR packaged theme.
I would not expect any legacy theme to use tailwind `@apply` command styles, but added the check for jar-resource theme.

**Comment by caalador** [comment]
Added a note to documentation about the add-on import
https://github.com/vaadin/docs/pull/5101
