### PR TITLE
fix: Do not generate extra files

### LINKED ISSUE #16696: Do not generate package.json and Vite config files when use pre-compiled prod bundle
The following files are generated by Flow even if the pre-compiled production bundle is used:
 - package.json
- vite.generated.ts
- vite.config.ts

They are not needed, because no compilation or installation of frontend happens in this case.

### PR DESCRIPTION
**Pull request by caalador**
When using the production bundle
do not generate un-needed files
for npm and vite.

Fixes #16696

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java [hunk 1]
```diff
@@ -477,8 +477,9 @@ && frontendFileExists(localModulePath)) {
                     notFoundMessage(resourceNotFound, prefix, suffix));
         }
 
-        boolean devModeWithoutServer = !options.isProductionMode()
-                && !options.isFrontendHotdeploy() && !options.isBundleBuild();
+        boolean devModeWithoutServer = !(options.isProductionMode()
+                && options.isBundleBuild()) && !options.isFrontendHotdeploy()
+                && !options.isBundleBuild();
```
Comment (mshabarov) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java:482]: This might be simplified a bit:
```java
boolean needsNodeModules = options.isFrontendHotdeploy() || options.isBundleBuild();
        if (!npmNotFound.isEmpty() && getLogger().isInfoEnabled()
                && needsNodeModules) {
            getLogger().info(notFoundMessage(npmNotFound,
                    "Failed to find the following imports in the `node_modules` tree:",
                    getImportsNotFoundMessage()));
        }
```

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java [hunk 2]
```diff
@@ -227,8 +227,8 @@ public NodeTasks(Options options) {
             pwa = new PwaConfiguration();
         }
         commands.add(new TaskUpdateSettingsFile(options, themeName, pwa));
-        if (options.isProductionMode() || options.isFrontendHotdeploy()
-                || options.isBundleBuild()) {
+        if ((options.isProductionMode() && options.isBundleBuild())
```
Comment (mshabarov) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java:230]: Can we get rid of `(options.isProductionMode() && options.isBundleBuild())` in this condition, since `isBundleBuild` is supposed to signal about making a new bundle or not, with no matter is it prod or dev mode? Some tests would be broken (they were, when I did a similar change before), but this might be a matter of wrong expectation in tests.

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java [hunk 3]
```diff
@@ -474,7 +474,8 @@ String writePackageFile(JsonObject packageJson) throws IOException {
     String writePackageFile(JsonObject json, File packageFile)
             throws IOException {
         String content = stringify(json, 2) + "\n";
-        if (packageFile.exists() || options.isProductionMode()
+        if (packageFile.exists()
+                || (options.isProductionMode() && options.isBundleBuild())
```
Comment (mshabarov) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java:478]: Same here, can we exclude `options.isProductionMode() && options.isBundleBuild()`?

**Review by mshabarov — CHANGES_REQUESTED** [review]

File: flow-tests/test-express-build/test-prod-bundle-no-plugin/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/NoAppBundleIT.java [hunk 4]
```diff
@@ -0,0 +1,78 @@
...
+        String pageSource = driver.getPageSource();
+        Assert.assertFalse("Service Worker is not served properly",
+                pageSource.contains("Error 404 Not Found")
+                        || pageSource.contains("Could not navigate to"));
+    }
+
+    private void assertDefaultProdBundle(File baseDir) throws IOException {
+        try {
+            findElement(By.tagName("vaadin-dev-tools"));
+        } catch (NoSuchElementException e) {
```
Comment (mshabarov) [inline flow-tests/test-express-build/test-prod-bundle-no-plugin/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/NoAppBundleIT.java:66]: This is not needed, because this test module now runs with production always, so it is never in dev mode -> no need to check this.

File: flow-tests/test-express-build/test-prod-bundle-no-plugin/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/NoAppBundleIT.java [hunk 5]
```diff
@@ -0,0 +1,78 @@
...
+
+    @Test
+    public void noFrontendFilesCreated() throws IOException {
+        waitForElementPresent(By.id("hello-component"));
+
+        File baseDir = new File(System.getProperty("user.dir", "."));
+
+        // shouldn't create a dev-bundle
+        Assert.assertFalse("No dev-bundle should be created",
+                new File(baseDir, Constants.DEV_BUNDLE_LOCATION).exists());
```
Comment (mshabarov) [inline flow-tests/test-express-build/test-prod-bundle-no-plugin/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/NoAppBundleIT.java:33]: Also not needed, since this module runs in prod mode always.

File: flow-tests/test-express-build/test-prod-bundle-no-plugin/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/NoAppBundleIT.java (hunk 4 above)
Comment (caalador) [reply flow-tests/test-express-build/test-prod-bundle-no-plugin/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/NoAppBundleIT.java]: done
