### PR TITLE
fix: preserve URL-encoded characters in wildcard route parameters

### LINKED ISSUE #19788: @WildCardParameter reconstitutes parameters to String in wrong fashion
### Description of the bug

We utilize a url parameter to identify an entity for a particular page. The clients that use our product can define the IDs for this entity. In the case that this identifier contains the "/" character we (of course) encode this using URLEncoder when building the URL. In the page that uses the identifier setParameter is called. However, the / character in this case has become a real forward slash "/" instead of the translated URL encoding %2F .  It seems that the setParameter call comes from a "ui-navigate" event from client side. Here the route is set using:
 private getFlowRoutePath(context: NavigationParameters | Location): string {
    return decodeURIComponent(context.pathname).replace(this.baseRegex, '');
  }

which is on Flow.ts line 281-ish.
It seems because here the URI is decoded, the %2f is removed and on server side this interpreted as a normal forward slash

### Expected behavior

A wildcard parameter should not contain decoded %2f marks, or in fact any decoded marks, as that would constitute information loss. I would expect the ui-navigate event to __NOT__ have a decoded route, but the original one....

or maybe some other solution, but at least the @WildcardParameter should retain the non-decoded parts of the url.

### Minimal reproducible example

See https://github.com/roeltje25/issue-with-url-wildcard-parameter-working-example

0) navigate to https://localhost:8080/first  -> you should see empty form and "first" filled into Result box
1) when running try some parameter with a slash and press "Send"  -> should work ok, the url is adjusted accordingly with your input (encoded) and Result box filled in with same input
2) Now click on url box of browser and press enter -> this goes wrong, the %2f got translated to / and is removed in the Result box

### Versions

- Vaadin / Flow version: 24.4.8
- Java version: 21
- OS version: Windows 11
- Browser version (if applicable): Chrome 127
- Application Server (if applicable): (via spring boot maven plugin -> tomcat 10)
- IDE (if applicable): Eclipse / command line

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #19788

Changes:
- Client: Remove premature decoding of pathname in Flow.ts to preserve encoded characters like %2F in the URL sent to server
- Server: Add PathUtil.getSegmentsListWithDecoding() method that splits path by "/" then decodes each segment individually
- Server: Update RouteSegment to use segment decoding for route matching

This fix ensures that URL-encoded slashes (%2F) and other special characters in wildcard parameters are properly decoded while still distinguishing them from literal path separators. For example:
- /wild/a/b/c creates 3 segments: ["a", "b", "c"]
- /wild/a%2Fb%2Fc creates 1 segment that decodes to: ["a/b/c"]

Previously, the client decoded the entire pathname causing %2F to become "/" which the server then incorrectly split as path segments, resulting in data loss.

Tests added:
- PathUtil segment decoding with various encoded characters
- Wildcard parameter routing with encoded slashes and special chars
- URL generation documentation for pre-encoding requirements

### CODE REVIEW

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/ForwardingRequestWrapper.java [hunk 1]
```diff
@@ -38,6 +38,11 @@ public class ForwardingRequestWrapper extends HttpServletRequestWrapper {
 
     public ForwardingRequestWrapper(HttpServletRequest request) {
         super(request);
+        // Do not decode URLs to preserve encoded path separators (%2F).
+        // Decoding would cause incorrect baseHref calculation when paths
+        // contain encoded slashes (e.g., /a%2Fb should be one segment, not
+        // two).
+        urlPathHelper.setUrlDecode(false);
```
Comment (mcollovati) [inline vaadin-spring/src/main/java/com/vaadin/flow/spring/ForwardingRequestWrapper.java:45]: Could we add a test for this?

File: flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/EncodedParameterIT.java [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+        WebElement element = $(DivElement.class).id(ENCODED_CONTENT);
+
+        Assert.assertEquals(
+                "Element parameter should be received with encoding.", "a%2bb",
+                element.getText());
+
+        element = $(DivElement.class).id(DECODED_CONTENT);
+
+        Assert.assertEquals(
+                "Element parameter should be received with encoding.", "a+b",
```
Comment (mcollovati) [inline flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/EncodedParameterIT.java]: Can we change a bit the assertion message to make it different from the previous one?

Comment (caalador) [reply flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/EncodedParameterIT.java]: done

**Comment by mcollovati** [comment]
Tested locally with various configurations (context path, URL mapping) and characters, and it seems to work properly :+1:
