### PR TITLE
Treat URLs with "context" and "base" schemas as external 

### LINKED ISSUE #8290: JavaScript annotation doesn't work with context:// URLs in npm mode
I have the `@JavaScript("context://js/test.js")` attached to my route, in hopes to load JavaScript files as plain JS (not as a module) from `src/main/webapp/js/test.js`.

However, Vaadin tries to look up the javascript file from the `node_modules` and fails.

### Minimal reproducible example

1. The Skeleton Starter project: Add `@JavaScript("context://js/test.js")` annotation to the `MainView` class.
2. Run the Skeleton Starter.

### Expected behavior

The produced HTML page should load a script from `src/main/webapp/js/test.js`.

### Actual behavior

The webpack compilation fails with

```
 Failed to find the following imports in the `node_modules` tree:
      - context://js/test.js
  If the build fails, check that npm packages are installed.
```

### Versions:
    - Vaadin / Flow version: 4.1.27 / 2.1.9
    - Java version: 8
    - OS version:
    - Browser version (if applicable):
    - Application Server (if applicable):
    - IDE (if applicable): Intellij

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #8290

### CODE REVIEW

File: flow-tests/test-root-context/src/main/webapp/plain-script.js [hunk 1]
```diff
@@ -0,0 +1,4 @@
+var div = document.createElement("div");
+div.id="added-from-src-script";
+div.textContent="Hello from src script";
+document.body.insertBefore(div, document.body.firstChild);
```
Comment (caalador) [inline flow-tests/test-root-context/src/main/webapp/plain-script.js:4]: Missing new line, but not that critical as it's a test js file.
