### PR TITLE
fix!: prevent lumo utility classes to be imported automatically

### LINKED ISSUE #22467: Having a `theme.json` file present results in Lumo utilities being loaded (v25)
### Description of the bug

If the legacy theme folder contains a `theme.json` then, regardless what the content of that file is, the Lumo utility classes are loaded. In my case I have an empty JSON object in that file: `{}`. If there is no `theme.json` then utilities are not loaded.

This is not the case in v24, where utility classes are only loaded if `utility` is listed in `lumoImports`.

### Expected behavior

Either `lumoImports` should work correctly and only include utilities if `utility` is listed.

Or, if we want to drop support for `lumoImports` in v25, then utilities should never be loaded, unless they are explicitly added as an import through a CSS file, or through `StyleSheet`.

### Minimal reproducible example

- Clone this repo: https://github.com/sissbruecker/vaadin-25-theme-test
- In `lumo-theme-folder`, add a `theme.json` with this content: `{}`
- Run the app in `lumo-theme-folder` 
- Observe that Lumo utilities are loaded on the page

### Versions

- Vaadin / Flow version: 25 alpha 12
- Java version: 21

### PR DESCRIPTION
**Pull request by mcollovati**
Fixes #22467

### CODE REVIEW

File: flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js [hunk 1]
```diff
@@ -205,6 +205,16 @@ function getThemeProperties(themeFolder, options) {
...
   let themeJson = JSON.parse(themePropertyFileAsString);
   themeJson.autoInjectComponents = componentFeature;
+
+  if (themeJson.lumoImports) {
+    const themeName = basename(themeFolder);
+    logger.warn(
+      `The 'lumoImports' property detected in theme '${themeName}' is no longer supported in Vaadin 25. ` +
+        "All modules except 'utility' are now loaded automatically when extending Lumo theme. " +
+        "To load utility classes, add '@StyleSheet(Lumo.UTILITY_STYLESHEET)' annotation to 'AppShellConfigurator' implementor " +
+        'or "@import \'lumo/utility.css\';" to the theme styles.css file.'
```
Comment (knoobie) [inline flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js]: This line does not match your tests below or did I misinterpreted it? 

> @import '@vaadin/vaadin-lumo-styles/utility.css';

Comment (mcollovati) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js]: `lumo/utility.css` is provided by the `vaadin-lumo-theme` artifact, that is referenced in Flow to avoid cyclic dependencies.
An application using Lumo should have it on a classpath and import  `lumo/utility.css`

Comment (mcollovati) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js]: The constant in `Lumo` class has `lumo/utility.css` value as well.

Comment (sissbruecker) [inline flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js]:
```suggestion
        "To load utility classes, add '@StyleSheet(Lumo.UTILITY_STYLESHEET)' annotation to 'AppShellConfigurator' implementor"
```
We only mention / recommend using the `Lumo` constants in the docs, so maybe prefer that here as well.

File: flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js [hunk 2]
```diff
@@ -205,6 +205,16 @@ function getThemeProperties(themeFolder, options) {
   }
   let themeJson = JSON.parse(themePropertyFileAsString);
   themeJson.autoInjectComponents = componentFeature;
+
+  if (themeJson.lumoImports) {
+    const themeName = basename(themeFolder);
+    logger.warn(
```
Comment (sissbruecker) [inline flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js:211]: I was not able to observe this warning anywhere. Where should it show up? Should it be in the server logs instead?

Comment (mcollovati) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js:211]: You need to enable debug logs for dev server output tracker in dev mode (I don't remember the specific logger category right now)

File: flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js (hunk 1 above)
Comment (mcollovati) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js]: done

File: flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js (hunk 2 above)
Comment (mshabarov) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js:211]: If this needs a logging configuration, then most likely this would never be seen by users, maybe it's better to place this warning in Java?

Comment (mcollovati) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js:211]: Can probably be checked in `ThemeValidationUtil`

Comment (mcollovati) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js:211]: Added the log message in `TaskUpdateThemeImport`
