### PR TITLE
fix: Proper handling of href when the anchor is disabled/enabled

### LINKED ISSUE #10924: Anchor component improper implement of HasEnabled
B"H
follow this: https://stackoverflow.com/questions/13955667/disabled-href-tag/13955695
the setEnabled implementation not fit the html way of making <a> being disabled/enabled

Need some workaround implementation for this case e.g. set the href to none when it disabled

### PR DESCRIPTION
**Pull request by mstahv**
## Description

Disabling and enabling component using the Java API now works as expected. href is always saved in the component implementation, but not stored in element if disabled.

Fixes #10924

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

File: flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java [hunk 1]
```diff
@@ -170,9 +185,36 @@ public void setHref(AbstractStreamResource href) {
...
+        super.onEnabledStateChanged(enabled);
+        if (enabled) {
+            assignHref();
+        } else {
+            getElement().removeAttribute("href");
+        }
+    }
+
+    private void assignHref() {
+        if (href != null) {
```
Comment (joheriks) [inline flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java:208]: Could this `if` expression also contain the guard `isEnabled()`, as it would simplify the callers.

**Review by joheriks — CHANGES_REQUESTED** [review]

File: flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java (hunk 1 above)
Comment (mstahv) [reply flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java:208]: Then I'd refactor the change as we'd be doing conditional checks twice in onEnabledStateChange.

**Review by joheriks — DISMISSED** [review]

File: flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java [hunk 2]
```diff
@@ -170,9 +181,36 @@ public void setHref(AbstractStreamResource href) {
      * @return the href value, or <code>""</code> if no href has been set
      */
     public String getHref() {
+        if (href instanceof String) {
+            // let the method return the actual href string even if disabled
+            return (String) href;
+        }
+        // this only happens if StreamResource is in use, in that case
+        // the disabled Anchor returns null, otherwise some String.
```
Comment (caalador) [inline flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java:189]: Just an idea. Would it break much if for a streamResource we would return the `AbstractStreamResource::getName`  as `StreamResource for 'AbstractStreamResource::getName'`

As then at least it would be clear that there is something set to the anchor.

Comment (mstahv) [reply flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java:189]: Even though it still wouldn't work perfectly, that might be a tiny enhancement. That could help if people are testing the existence of href when the component is disabled like this:

if(getHref().isEmpty()) {
   // do stuff with things
}

I guess we can't really get the actual uri for the resources as it (might be it) is not attached when ancsdhor is disabled 🤔

I guess the academically correct way would be to deprecate setHref(StreamResource) and have setStreamResource method separately. Then we could have a symmetric getter for it.

Up to you to decide. I'd get this in now as this and refine if we get more input from the users.

Comment (caalador) [reply flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java:189]: Well there is the static method `StreamResourceRegistry.getURI(AbstractStreamResource)` which if registered will give the actual href.

Comment (mstahv) [reply flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java]: Checked the implementation and to me it looks like it should always return something sane. Pushed a change like that.

Comment (mstahv) [reply flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java]: No test for it though 😬

Comment (mstahv) [reply flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java]: Now the tests cover this as well

**Review by caalador — APPROVED** [review]
