### PR TITLE
fix: allow empty segments at start

### LINKED ISSUE #10729: After 14.5, Router HasUrlParameter @WildcardParameter doesn't support empty parameters anymore
### Description of the bug / feature
After 14.5, Router HasUrlParameter @WildcardParameter doesn't support empty parameters anymore. Works with 14.4.10. 
### Minimal reproducible example
```
@Route(value = "about", layout = MainView.class)
@PageTitle("About")
@CssImport("./views/about/about-view.css")
public class AboutView extends Div implements HasUrlParameter<String> {
    public AboutView() {
        addClassName("about-view");
        add(new Text("Content placeholder"));
    }
    @Override
    public void setParameter(BeforeEvent beforeEvent, @WildcardParameter String s) {
        System.out.println(">>>"+s);
    }
}
```
### Expected behavior
With code above the standard output for url `http://localhost:8080/about//2/3`, should be just:
`>>>/2/3`
### Actual behavior
The standard output is
```
>>>2/3
>>>VAADIN/build/webcomponentsjs/webcomponents-loader.js
>>>VAADIN/build/vaadin-gizmo-1f1e5ed60cb793a57317.cache.js
>>>VAADIN/static/client/client-4C23589935A74206212F474A719FC41C.cache.js
>>>VAADIN/build/vaadin-bundle-098d1f74dc147d6e9258.cache.js
>>>icons/icon-32x32.png
>>>manifest.webmanifest
>>>sw.js
>>>icons/icon-16x16.png
>>>icons/icon-96x96.png
```
### Versions:
    - Vaadin version: 14.5.3
    - Java version: Amazon Corretto 11.0.10
    - OS version: Windows 10 Pro

### PR DESCRIPTION
**Pull request by caalador**
Allow having empty segment as first segment
for parameters.

fixes #10729

### CODE REVIEW

File: flow-server/src/test/java/com/vaadin/flow/router/RouterConfigurationUrlResolvingTest.java [hunk 1]
```diff
@@ -146,6 +146,28 @@ public void url_resolves_correctly_for_optional_and_wild_parameters()
                 .getUrl(WildParameter.class, "there/are/many/of/us"));
     }
 
+    @Test
+    public void wildcardPathWithEmptyParameter_emptyParameterIsAvailable() {
```
Comment (pleku) [inline flow-server/src/test/java/com/vaadin/flow/router/RouterConfigurationUrlResolvingTest.java:150]: Can it be so that the wildcard route is mapped to `""` ? Then you would have "//" or "//foo" ?
If yes then should it be tested too ?

File: flow-server/src/main/java/com/vaadin/flow/router/internal/PathUtil.java [hunk 2]
```diff
@@ -105,4 +105,26 @@ public static String trimPath(String path) {
...
+    /**
+     * Trim the path by removing any leading whitespaces and trailing slashes
+     * and whitespaces.
+     *
+     * @param path
+     *            url path to trim.
+     * @return a String representing the input path without any leading and
+     *         trailing whitespaces and trailing slash.
+     */
+    public static String trimPathEnding(String path) {
```
Comment (pleku) [inline flow-server/src/main/java/com/vaadin/flow/router/internal/PathUtil.java:117]: The name of this method is slightly odd compared to the javadocs: "trim path ending" VS "trim whitespace and remove trailing slashes"

File: flow-server/src/main/java/com/vaadin/flow/router/internal/PathUtil.java [hunk 3]
```diff
@@ -105,4 +105,26 @@ public static String trimPath(String path) {
         return path;
     }
 
+    /**
+     * Trim the path by removing any leading whitespaces and trailing slashes
+     * and whitespaces.
+     *
+     * @param path
+     *            url path to trim.
```
Comment (pleku) [inline flow-server/src/main/java/com/vaadin/flow/router/internal/PathUtil.java:113]: apparently can be null which is considered as ""

**Review by pleku — CHANGES_REQUESTED** [review]
Couple of javadocs nits and one question

File: flow-server/src/test/java/com/vaadin/flow/router/RouterConfigurationUrlResolvingTest.java (hunk 1 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/router/RouterConfigurationUrlResolvingTest.java:150]: There is a problem that for the location there is the restiction that `Relative path cannot start with /` so a `Route("")` can not accept a `//Parameters/path` as it will leave a / as the initial parameter.

File: flow-server/src/main/java/com/vaadin/flow/router/internal/PathUtil.java (hunk 2 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/router/internal/PathUtil.java:117]: renamed

File: flow-server/src/main/java/com/vaadin/flow/router/internal/PathUtil.java (hunk 3 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/router/internal/PathUtil.java:113]: Changed so we don't accept null.

**Review by pleku — APPROVED** [review]
