### PR TITLE
fix: Sanitize percent characters in resource URLs

### LINKED ISSUE #22677: Download of files containing "%" in their name fails with Jetty 12
### Description of the bug

When a `DownloadHandler` uses "%" in its filename, Jetty 12 throws an exception and the download fails:

```
org.eclipse.jetty.http.BadMessageException: 400: Ambiguous URI path encoding
	at org.eclipse.jetty.server.internal.HttpConnection$HttpStreamOverHTTP1.headerComplete(HttpConnection.java:1339)
	at org.eclipse.jetty.server.internal.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1115)
	at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1404)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1706)
	at org.eclipse.jetty.server.internal.HttpConnection.parseRequestBuffer(HttpConnection.java:604)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:379)
	at org.eclipse.jetty.server.internal.HttpConnection$FillableCallback.succeeded(HttpConnection.java:1809)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:54)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:492)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.epcRunTask(AdaptiveExecutionStrategy.java:428)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:401)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:255)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:204)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:312)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:1009)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1239)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1194)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Expected behavior

It should be possible to download files whith "%" in their name.

### Minimal reproducible example

See https://github.com/mperktold/vaadin-jetty-12

It programmatically starts a Jetty server which shows a page with a download link.
The download fails because its name contains a "%".

### Versions

- Vaadin / Flow version: 24.9.4
- Java version: Eclipse Temurin 21.0.8
- OS version: Windows 11
- Application Server: Jetty 12.1.3

### PR DESCRIPTION
**Pull request by tltv**
Jetty 12 rejects URLs containing %25 (percent-encoded percent) as ambiguous URI path encoding, causing downloads to fail with HTTP 400 when filenames contain "%" characters.

Add UrlUtil.sanitizeForUrl() that replaces "%" with "_" in the URL path segment. The actual download filename from Content-Disposition is unaffected since each resource has a unique ID for lookup.

Fixes #22677

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/internal/UrlUtil.java [hunk 1]
```diff
@@ -191,6 +191,30 @@ public static String appendQueryParameter(String url, String name,
         return url + separator + name + "=" + value;
     }
 
+    /**
+     * Sanitizes a resource name for safe use in URL path segments.
```
Comment (Artur-) [inline flow-server/src/main/java/com/vaadin/flow/internal/UrlUtil.java]: This javadoc does not really make sense as the only thing it does is replace % with _. It also talks about where the result is used and about Content-Disposition - completely unrelated to URLs. Maybe the correct place would be in `StreamRequestHandler` if that's the only place there is a problem

File: flow-server/src/test/java/com/vaadin/flow/internal/UrlUtilTest.java [hunk 2]
```diff
@@ -204,4 +204,5 @@ void appendQueryParameter_nullValue_returnsOriginalUrl() {
                 null);
         assertEquals("/styles.css", result);
     }
+
```
Comment (Artur-) [inline flow-server/src/test/java/com/vaadin/flow/internal/UrlUtilTest.java]: This can be reverted also

File: flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java [hunk 3]
```diff
@@ -54,14 +53,11 @@ public void getDynamicVaadinPlusResource() throws IOException {
...
 
-    // Ignored due to
-    // https://github.com/jetty/jetty.project/issues/9444#issuecomment-1677068428
     @Test
-    @Ignore
     public void getDynamicVaadinPercentResource() throws IOException {
         open();
 
-        assertDownloadedContent("percent-link", "file%25.jpg");
+        assertDownloadedContent("percent-link", "file_.jpg");
```
Comment (Artur-) [inline flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java:60]: Does this really test anything now?

File: flow-server/src/main/java/com/vaadin/flow/internal/UrlUtil.java (hunk 1 above)
Comment (tltv) [reply flow-server/src/main/java/com/vaadin/flow/internal/UrlUtil.java]: Moved code to StreamRequestHandler.generateURI.

File: flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java (hunk 3 above)
Comment (tltv) [reply flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java:60]: Seems to assert that `file%.jpg` filename in StreamResource given to the anchor has url with has `file_.jpg` properly. Looks correct to me.

**Review by mshabarov — APPROVED** [review]
