### PR TITLE
fix: reset session field only when HTTP session is invalidated

### LINKED ISSUE #6959: Cannot invalidate HTTP session from SessionDestroyListener
In #6763 it's suggested that HttpSession can be invalidated from Vaadin SessionDestroyListener, however, when the listener is executed the wrapped session is null.

- Expected behavior:
  I should be able to invalidate the HttpSession after some period of inactivity.
- Actual behavior
  The HttpSession is not available after the Vaadin session has been destroyed.

Vaadin 14.0.11

[Example application](https://github.com/vaadin/flow/files/3851644/v14.zip)

The SessionDestroyListener is:
```
	public void serviceInit(ServiceInitEvent event) {
		event.getSource().addSessionDestroyListener(ev->{
			System.out.println("Vaadin session destroyed");
			VaadinSession vsession = ev.getSession();
			WrappedSession wsession = vsession.getSession();
			if (wsession==null) {
				System.out.println("wrapped session is null");
			} else {
				wsession.invalidate();
			}
		});
	}
```

### PR DESCRIPTION
**Pull request by denis-anisimov**
fixes #6959

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java [hunk 1]
```diff
@@ -416,6 +417,46 @@ public void createRequestHandlers_pwaHandlerIsInList_webComponentHandlersAreInLi
...
+            }
+        };
+
+        service.fireSessionDestroy(vaadinSession);
+
+        Assert.assertEquals(VaadinSessionState.CLOSED, stateRef.get());
+    }
+
+    @Test
+    public void removeFromHttpSession_setExplciitSessionCloseAttribute()
```
Comment (caalador) [inline flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java:439]:
```suggestion
    public void removeFromHttpSession_setExplicitSessionCloseAttribute()
```

File: flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java [hunk 2]
```diff
@@ -202,7 +205,21 @@ public void valueUnbound(HttpSessionBindingEvent event) {
             // it as soon as we acquire the lock.
             service.fireSessionDestroy(this);
         }
-        session = null;
+        // Vaadin session attribut is removed from HTTP session in two cases:
+        // either Vaadin session is closed explicitly by VaadinService or HTTP
+        // session is invalidated (and all attributes are removed from it). In
+        // the latter case the session field should be set to {@code null}
+        // Immediately to avoid using HTTP session object which is invalid (its
+        // methods throw exceptions).
```
Comment (caalador) [inline flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java:213]:
```suggestion
        // Vaadin session attribute is removed from HTTP session in two cases:
        // either Vaadin session is closed explicitly by VaadinService or HTTP
        // session is invalidated (and all attributes are removed from it). In
        // the latter case the session field should be set to {@code null}
        // immediately to avoid using HTTP session object which is invalid (all
        // methods throw exceptions).
```

**Review by caalador — CHANGES_REQUESTED** [review]
Some minor typos.

**Review by caalador — APPROVED** [review]
