### PR TITLE
fix: don't override web.xml, annotation config with classpath flow-build-info.json settings

### LINKED ISSUE #11479: Build info on classpath overrides parameters set in web.xml
### Description of the bug / feature
When using DevModeInitializer to get classes from annotations, a flow-build-info.json found on the classpath will override parameters set in web.xml.

Here's the code in question (DeploymentConfigurationFactory.java): 

```
  protected static Properties createInitParameters(
              Class<?> systemPropertyBaseClass, VaadinConfig vaadinConfig)
              throws VaadinConfigurationException {
          Properties initParameters = new Properties();
          readUiFromEnclosingClass(systemPropertyBaseClass, initParameters);
          readConfigurationAnnotation(systemPropertyBaseClass, initParameters);
  
          // Read default parameters from server.xml
          final VaadinContext context = vaadinConfig.getVaadinContext();
          for (final Enumeration<String> e = context.getContextParameterNames(); e
                  .hasMoreElements();) {
              final String name = e.nextElement();
              initParameters.setProperty(name, context.getContextParameter(name));
          }
  
          // Override with application config from web.xml
          for (final Enumeration<String> e = vaadinConfig
                  .getConfigParameterNames(); e.hasMoreElements();) {
              final String name = e.nextElement();
              initParameters.setProperty(name,
                      vaadinConfig.getConfigParameter(name));
          }
  
          readBuildInfo(systemPropertyBaseClass, initParameters,
                  vaadinConfig.getVaadinContext());  // this overrides config from web.xml, for example the frontend folder setting
          return initParameters;
      }

```

### Minimal reproducible example

Create two dependent projects in eclipse, build one then try to build the other. DevModeInitializer will override parameters in the second project if the flow-build-info.json for the first one is on the classpath. 

### Expected behavior

web.xml parameters should override any existing flow-build-info.json on the classpath

### Actual behavior
parameters from an existing flow-build-info.json on the classpath override those set in web.xml

If this is intended behavior, feel free to close. Otherwise, I can submit a PR changing the order, because I think that might make more intuitive sense for users. Right now, we have to delete the flow-build-info.json for our dependent, standalone Vaadin project so that we can compile a second project that uses the first as a dependency. 

### Versions:
    - Vaadin / Flow version: 14.6.5
    - Java version: OpenJDK 8
    - OS version: Manjaro
    - Browser version (if applicable): N/A
    - Application Server (if applicable): Jetty
    - IDE (if applicable): Eclipse

### PR DESCRIPTION
**Pull request by rudiejd**
## Description

flow-server was overriding parameters set in web.xml/annotations with those found in *any flow-build-info.json* on the classpath. Now it only overrides parameters which weren't already set. Fixes #11479.

## Type of change

- [X] Bugfix
- [ ] Feature

## Checklist
- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [X] The issue is created in the corresponding repository and I have referenced it.
- [X] I have added tests to ensure my change is effective and works as intended.
- [X] New and existing tests are passing locally with my change.
- [X] I have performed self-review and corrected misspellings.

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java [hunk 1]
```diff
@@ -123,8 +123,12 @@ private void readBuildInfo(Properties initParameters,
             JsonObject buildInfo = JsonUtil.parse(json);
             Map<String, String> properties = getConfigParametersUsingTokenData(
                     buildInfo);
-            initParameters.putAll(properties);
-
+            // only insert properties that haven't been defined
+            for (Map.Entry<String, String> e : properties.entrySet()) {
```
Comment (denis-anisimov) [inline flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java:127]: Don't use one letter variable.
`entry` instead of `e` would be better here.

File: flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java [hunk 2]
```diff
@@ -330,6 +330,29 @@ public void createInitParameters_valuesFromContextAreIgnored_valuesAreTakenFroms
         Assert.assertFalse(parameters.contains("bar"));
     }
 
+    @Test
+    public void createInitParameters_valuesFromTokenAreIgnored_valuesAreTakenFromservletConfig()
```
Comment (denis-anisimov) [inline flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java:334]: `valuesFromTokenAreIgnored`:
the second part of the name is usually precondition.
So it should say that properties are provided via init parameters and token file at the same time.
And the last part is a result : `valuesFromTokenFileOverridenByInitParams` e.g.

File: flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java [hunk 3]
```diff
@@ -330,6 +330,29 @@ public void createInitParameters_valuesFromContextAreIgnored_valuesAreTakenFroms
...
+        DeploymentConfigurationFactory factory = new DeploymentConfigurationFactory();
+
+        VaadinConfig config = mockTokenFileViaContextParam(
+                "{ '" + SERVLET_PARAMETER_PRODUCTION_MODE + "': true}");
+        Mockito.when(config.getConfigParameterNames())
+                .thenReturn(Collections.enumeration(
+                        Arrays.asList(SERVLET_PARAMETER_PRODUCTION_MODE,
+                                FrontendUtils.PARAM_TOKEN_FILE)));
+        Mockito.when(
+                config.getConfigParameter(SERVLET_PARAMETER_PRODUCTION_MODE))
```
Comment (denis-anisimov) [inline flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java:345]: That checks only one parameter.
 Don't know how hard it is but would be better to check every init parameter.
I think the values has only  two types: boolean and String.

So it should be possible to make to arrays of properties and go through these arrays and do the check

**Review by denis-anisimov — CHANGES_REQUESTED** [review]

File: flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java (hunk 3 above)
Comment (rudiejd) [reply flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java:351]: I added another boolean parameter, and added a string parameter so we can capture both types. I also added a parameter that isn't overridden by the servlet config.

Comment (rudiejd) [reply flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java:351]: should I do *all* init parameters? wasn't sure whether that is necessary since the behavior is the same

Comment (denis-anisimov) [reply flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java:351]: I would recommend to do it for all init parameters, yes.
It might be that the code may be modified so it works properly for most of parameters but is broken for one.

What I suggest is : split parameter names into two complementary set . One set contains parameters whose type is String and another with boolean type.
`InitParameters` class can be used to get all parameter names via reflection.
Then just use a couple of unit test methods: go through all the parameters and make a check.

Comment (rudiejd) [reply flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java:351]: okay, I think I'll just be hardcoding a set of string parameters (not sure how else to tell if value is a string, can't use getAssignableType or anything) and getting the boolean ones through reflection, then making assertions for each

File: flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java [hunk 4]
```diff
@@ -335,38 +339,77 @@ public void createInitParameters_valuesAreTakenFromservletConfigAndTokenFile_val
...
+            if (i < initParamFields.length - 1) {
+                mockTokenJsonString += ",";
+            }
+        }
+        mockTokenJsonString += " }";
+        VaadinConfig config = mockTokenFileViaContextParam(mockTokenJsonString);
+        List<String> allParamsList = new ArrayList<String>();
+        for (int i = 0; i < initParamFields.length; i++) {
+            String paramName = (String) initParamFields[i]
+                    .get(new InitParameters());
```
Comment (denis-anisimov) [inline flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java:376]: The field is static so there is no need to instantiate an object. `null` can be passed as an arg here.
But it's minor.

**Review by denis-anisimov — CHANGES_REQUESTED** [review]
Since there is an important request: add message to every assertion with a parameter name I would also like to ask to refactor the code to extract cycles which initializes mocks into separate methods to improve readability: the test itself may be very short if it just calls initializer methods.

**Comment by rudiejd** [comment]
> Since there is an important request: add message to every assertion with a parameter name I would also like to ask to refactor the code to extract cycles which initializes mocks into separate methods to improve readability: the test itself may be very short if it just calls initializer methods.

I have refactored the generation of the token and the mocking into two different private methods. I tried to make them a bit generic to encourage reuse for similar test cases

**Comment by rudiejd** [comment]
https://teamcity.vaadin.com/viewLog.html?buildId=85356&buildTypeId=Flow_FlowTests
can someone tell me why run validation is failing and/or re run? everything's passing locally

**Comment by denis-anisimov** [comment]
`flow-client` failed with unknown reason.
I've restarted the build.

**Comment by rudiejd** [comment]
@denis-anisimov same thing again. the client unit/integration tests run locally though, so i can't figure out if i broke something... it doesn't show any test as failing on teamcity either

**Review by denis-anisimov — APPROVED** [review]

**Comment by denis-anisimov** [comment]
There were some issues with builds.
Now they should be fixed.
At least `flow-client` validation has passed.
