### PR TITLE
fix: Update buildIdentifier comparison

### LINKED ISSUE #11352: Faulty comparison for buildIdentifier in FrontendVersion
FrontendVersion compares wrong the version when comparing the buildIdentifier string.

With input
`new FrontendVersion("2.0.0-alpha6").isOlderThan(new FrontendVersion("2.0.0-alpha13"))`
Expected 
  `true`
Actual
  `false`

### PR DESCRIPTION
**Pull request by caalador**
Fix buildIdentifier comparison so
values compare correctly.

fixes #11352

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java [hunk 1]
```diff
@@ -306,11 +315,28 @@ public int compareTo(FrontendVersion other) {
                     && other.buildIdentifier.isEmpty()) {
                 return -1;
             }
-            return buildIdentifier.compareToIgnoreCase(other.buildIdentifier);
+            return compareBuildIdentifier(other);
         }
         return 0;
     }
 
+    private int compareBuildIdentifier(FrontendVersion other) {
```
Comment (pleku) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java:323]: Just out of curiousity - what if someone uses e.g. `2.0.0.1` for some reason - does it end up to the build identifier ? Can you add a test that it wins over prerelease versions like `2.0.0-alpha5`.

Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java:323]: But ain't that eXo Versioning of Major.Minor.Maintenance.Patch-Qualifier and we support semantic versioning of Major.Minor.Revision-BuildIdentifier (we ofc actually accept . . . . instead of . . . - because it's simpler)
Also no it returns wrong as did the previous version.

Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java:323]: That should cover it also.

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java [hunk 2]
```diff
@@ -306,11 +315,35 @@ public int compareTo(FrontendVersion other) {
...
+                .matcher(buildIdentifier);
+        final Matcher otherMatcher = buildIdentifierParser
+                .matcher(other.buildIdentifier);
+        if (thisMatcher.groupCount() == 2 && otherMatcher.groupCount() == 2) {
+            thisMatcher.find();
+            otherMatcher.find();
+            if (thisMatcher.group(1).compareTo(otherMatcher.group(1)) != 0) {
+                // Empty alphabetical matcher is worth more than one with value
+                // so we need to reverse the check orderin that case.
+                if (otherMatcher.group(1).isEmpty()) {
```
Comment (pleku) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java:334]: I don't get this code and I think it is not just me - if the string for `otherMatcher.group(1)` is empty, why is it then compared ? Isn't it just the case that there is no _string_ group for that one and thus the numeric value will mean that it is newer ?

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java [hunk 3]
```diff
@@ -199,6 +199,28 @@ public void newerVersionByBuildIdentifier() {
...
+
+        assertTrue("same versions should equal",
+                test.isEqualTo(new FrontendVersion("2.0.0.alpha20")));
+    }
+
+    @Test
+    public void testAgainstVersionWithValueInBuildInfo() {
+        FrontendVersion test = new FrontendVersion("2.0.0-alpha3");
+        assertTrue("2.0.0-alpha3 should be older than 2.0.0.5",
+                test.isOlderThan(new FrontendVersion("2.0.0.5")));
```
Comment (pleku) [inline flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java:221]: Please test also that it works the other way around

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java [hunk 4]
```diff
@@ -199,6 +199,28 @@ public void newerVersionByBuildIdentifier() {
...
+    }
```
Comment (pleku) [inline flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java:222]: Please add a test that `2.0.0.6` is older than `2.0.0.11` for both ways

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java [hunk 5]
```diff
@@ -199,6 +199,28 @@ public void newerVersionByBuildIdentifier() {
                 test.isNewerThan(new FrontendVersion("2.0.0-RC1")));
     }
 
+    @Test
+    public void buildIdentifierNumbers_returnsAsExpected() {
+
+        FrontendVersion test = new FrontendVersion("2.0.0-alpha6");
+        assertTrue("2.0.0-alpha6 should be older than 2.0.0-alpha13",
+                test.isOlderThan(new FrontendVersion("2.0.0-alpha13")));
```
Comment (pleku) [inline flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java:207]: Looking at the code logic, I wonder if all the comparisons here should be double checked the other way too, e.g. 
```java
assertFalse("2.0.0-alpha13 should not be older than 2.0.0-alpha20",
                new FrontendVersion("2.0.0-alpha13").isOlderThan(test));
```

**Review by pleku — CHANGES_REQUESTED** [review]

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java (hunk 2 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java]: Fixed. Also other issues in the check.

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java (hunk 5 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java:207]: added older newer checks for multiple choices.

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java (hunk 4 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java:250]: added

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java (hunk 3 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java]: added older newer checks for multiple choices.

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java [hunk 6]
```diff
@@ -306,11 +315,34 @@ public int compareTo(FrontendVersion other) {
...
         return 0;
     }
 
+    private int compareBuildIdentifier(FrontendVersion other) {
+        final Matcher thisMatcher = buildIdentifierParser
+                .matcher(buildIdentifier);
+        final Matcher otherMatcher = buildIdentifierParser
+                .matcher(other.buildIdentifier);
+        if (thisMatcher.find() && otherMatcher.find()) {
+            if (thisMatcher.group(1).compareTo(otherMatcher.group(1)) != 0) {
```
Comment (pleku) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java:329]: Shouldn't this ignore the case like below? In the unlikely event that someone would have caps on?

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java [hunk 7]
```diff
@@ -199,6 +199,56 @@ public void newerVersionByBuildIdentifier() {
...
+
+        test = new FrontendVersion("2.0.0.alpha20");
```
Comment (pleku) [inline flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java:209]: There is a dot here instead of dash but that is fine

**Review by pleku — CHANGES_REQUESTED** [review]
Almost, one minor comment

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java (hunk 6 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java]: done

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java (hunk 7 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java]: done

**Review by manolo — APPROVED** [review]

**Comment by manolo** [comment]
Tested manually in my local and works ok.

**Review by pleku — APPROVED** [review]
