### PR TITLE
fix: delay web-component bootstrap during dev-bundle creation

### LINKED ISSUE #18283: Exported web-component not working during dev bundle creation
### Description of the bug

In an application using an exported web-component, loading of the component may fail if the browser page is opened during a dev-bundle creation.

The reason is that the request to the exported web-component JavaScript returns the dev-bundle creation HTML page,  as shown in the following browser console log

`[SEVERE] http://localhost:8888/web-component/themed-component.js - Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`

All works fine if reload the page after the bundle is created

### Expected behavior

The web-component JavaScript should be loaded correctly and the web-component should work after the dev-bundle creation is completed.

### Minimal reproducible example

In the `flow-tests/test-express-build/test-embedding-express-build` perform a `mvn clean` and then `mvn jetty:run`.
Navigate to http://localhost:8888/index.html while the dev-bundle creation is in progress.

Verify in the browser console and network tools that the web-component JS is not loaded correctly.

### Versions

- Vaadin / Flow version: 24.3.0

### PR DESCRIPTION
**Pull request by mcollovati**
## Description

When a Flow component is embedded as a web-component, the bootstrap process may fail if the dev-bundle is still under creation, because an HTML page is returned instead of the javascript initialization code. This change waits for dev-bundle to be ready before loading the web-components bootstrap script.

Fixes #18283

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-tests/test-express-build/test-embedding-express-build/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java [hunk 1]
```diff
@@ -122,6 +124,8 @@ public void applicationTheme_GlobalCss_isUsedOnlyInEmbeddedComponent() {
     private void validateEmbeddedComponent(TestBenchElement themedComponent,
             String target) {
         String imageUrl = themedComponent.getCssValue("background-image");
+        System.out.println("================================= " + imageUrl);
```
Comment (tepi) [inline flow-tests/test-express-build/test-embedding-express-build/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java:127]: Is this sysout intentional?

Comment (mcollovati) [reply flow-tests/test-express-build/test-embedding-express-build/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java:127]: I would say no :smile: 
Thanks for pointing out :+1:

Comment (mcollovati) [reply flow-tests/test-express-build/test-embedding-express-build/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java]: removed

**Review by tepi — APPROVED** [review]
