### PR TITLE
fix: Do not copy bundle lock for major upgrade

### LINKED ISSUE #22775: Upgrade to Vaadin 25 fails if old target/dev-bundle is present
### Description of the bug

I have an existing Vaadin 24.9.5 application using a dev bundle. If I just update the version numbers in `pom.xml` for Vaadin 25.0.0-beta5 and run in dev mode, then it seems like npm doesn't install e.g. Vaadin components in the root of `node_modules` but instead nested inside `@vaadin/react-components`.

This in turn leads to a `Failed to find the following imports in the node_modules tree` warning with lots of listed packages, followed by `Rollup failed to resolve import "@vaadin/vertical-layout/vaadin-vertical-layout.js` followed by spamming the console with `java.lang.IllegalStateException: com.vaadin.flow.server.ExecutionFailedException: Vite build exited with a non zero status` stacktraces.

### Expected behavior

Expected that the version change would either just work or fail with a more actionable error message.

### Minimal reproducible example

1. Get the latest 24.9 version from https://github.com/vaadin/skeleton-starter-flow-spring
2. Force a dev bundle to be built by adding an empty `test.js` file in `src/main/frontend` and reference it with `@JsModule("./test.js")` on the `MainView` class.
3. Run the application in dev mode to trigger building the bundle
4. Upgrade to Vaadin 25 in `pom.xml` by setting `<java.version>21</java.version>`, `<vaadin.version>25.0.0-beta5</vaadin.version>` and for the Spring Boot parent `<version>4.0.0-RC2</version>`
5. Run again and observe the broken build
6. Delete `package.json`, `package-lock.json`, `node_modules/` and `target/dev-bundle/`
7. Run again and observe that it works

### Versions

- Vaadin / Flow version: 25.0.0-beta5

### PR DESCRIPTION
**Pull request by caalador**
Fixes #22775

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java [hunk 1]
```diff
@@ -1560,4 +1564,137 @@ public static boolean isTailwindCssEnabled(Options options) {
...
+                    .get(NodeUpdater.VAADIN_VERSION).asString());
+            FrontendVersion platformsVersion = new FrontendVersion(
+                    platformVersion.get());
+            return jsonVersion.getMajorVersion() != platformsVersion
+                    .getMajorVersion();
+        }
+        return false;
+    }
+
+    private static JsonNode getBundleVaadinVersion(File buildDirectory)
```
Comment (tltv) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java]: Rename to `getBundleVaadinContent` just to not give any wrong idea since return value isn't a version node.

Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java]: Renamed
