### PR TITLE
fix: router-link postpone navigation

### LINKED ISSUE #17528: RouterLink url behaviour when using BeforeLeaveEvent.postpone
### Description of the bug

When postponing a navigation with the BeforeLeaveListeners `postpone()` method the url gets lost.

1. Open the example

Working example (`UI.getCurrent().navigate()`):
3. Click on Report 4
4. Click on the button and watch the url inside your browser
5. It should stay the same

Broken example (`RouterLink`): 
3. Click on Report 5
4. Click the link with an random uuid
5. Click yes
6. Repeat from 4 and watch the uuid disappear from the url again and again

### Expected behavior

The url should stay the same as before and not navigate to the parent.

### Minimal reproducible example

Implementation without `RouterLink`:
https://github.com/FelixGaebler/vaadin-bugs/tree/master/src/main/java/de/dataport/bugs/views/report4

Implementation with `RouterLink`:
https://github.com/FelixGaebler/vaadin-bugs/tree/master/src/main/java/de/dataport/bugs/views/report5

### Versions

- Vaadin / Flow version: 24.1.5
- Java version: 17
- OS version: Ubuntu 22

### PR DESCRIPTION
**Pull request by caalador**
Fixes issue with update timing
when postponing a router-link
as the navigation goes through
the vaadin-router.

Fixes #17528

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/component/UI.java [hunk 1]
```diff
@@ -1721,7 +1722,12 @@ public void connectClient(String flowRoutePath, String flowRouteQuery,
             navigateToClient(getForwardToClientUrl());
             acknowledgeClient();
         } else if (isPostponed()) {
-            cancelClient();
+            BeforeLeaveEvent.ContinueNavigationAction continueNavigationAction = getInternals()
+                    .getContinueNavigationAction();
+            continueNavigationAction
+                    .setProceedCallback(this::acknowledgeClient);
+            continueNavigationAction.setCancelCallback(this::cancelClient);
```
Comment (mcollovati) [inline flow-server/src/main/java/com/vaadin/flow/component/UI.java:1729]: Do I get it right that potential callbacks set by the developer on `ContinuationNavigationAction` are always overwritten by the UI callbacks?
If so, we should probably document it in `ContinuationNavigationAction` javadocs.

Or would it make sense to compose existing callbacks with the on from UI?

File: flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java [hunk 2]
```diff
@@ -77,10 +82,33 @@ public void proceed() {
...
+                    event = new NavigationEvent(event.getSource(),
+                            event.getLocation(), event.getUI(),
+                            NavigationTrigger.PROGRAMMATIC);
+                }
                 handler.handle(event);
                 setReferences(null, null);
             }
         }
+
+        public void cancel() {
```
Comment (mcollovati) [inline flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java:101]: Needs javadocs

File: flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java [hunk 3]
```diff
@@ -77,10 +82,33 @@ public void proceed() {
...
+            cancelCallback.execute();
+        }
+
+        public void setProceedCallback(Command proceedCallback) {
```
Comment (mcollovati) [inline flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java:105]: Needs javadocs

File: flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java [hunk 4]
```diff
@@ -77,10 +82,33 @@ public void proceed() {
...
+            this.proceedCallback = proceedCallback;
+        }
+
+        public void setCancelCallback(Command cancelCallback) {
```
Comment (mcollovati) [inline flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java:109]: Needs javadocs

File: flow-server/src/main/java/com/vaadin/flow/component/UI.java (hunk 1 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/component/UI.java:1729]: The proceed and cancel callbacks are only for internal use as they are meant to notify the client and fulfill the waiting promise. 
Removed methods and use direct exec calls instead so there can be no confusion on the usage.

File: flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java [hunk 5]
```diff
@@ -40,6 +41,10 @@ public class ContinueNavigationAction implements Serializable {
 
         private NavigationHandler handler = null;
         private NavigationEvent event = null;
+        private Command proceedCallback = () -> {
+        };
+        private Command cancelCallback = () -> {
+        };
```
[the remark this answers is not in the document]
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java:47]: Removed the empty no op commands

File: flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java (hunk 3 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java:105]: removed method

File: flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java (hunk 4 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java:109]: removed method

File: flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java (hunk 2 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java:101]: added javadoc

**Review by mcollovati — APPROVED** [review]
