### PR TITLE
test: Navigation test between modes

### LINKED ISSUE #9134: Navigation from a TypeScript view to a Java view is broken
With Vaadin 17.0.6 / Flow 5.0-SNAPSHOT navigation from a TypeScript view to a Java view is broken. This looks like a regression in Flow 5.0 because with Vaadin 17.0.6 / Flow 4.0.2 navigation works as expected.

Screen Recording 2020-10-07 at 11 28 PM

**Steps to reproduce**
 1. create a project on start.vaadin.com
     - general settings
        image
     - views (all but the "Hello World" view are TypeScript + HTML (default), the "Hello World" view is Java)
        image
 2. download the project and override the version of Flow to 5.0-SNAPSHOT
 3. run the project with `mvn`
 4. open http://localhost:8080/about
 5. click at the "Hello World" link in the navigation menu
 6. see that the hello world view is NOT rendered

### PR DESCRIPTION
**Pull request by caalador**
Test navigating from clinet view to server-side
view and server to client.

Closes #9134

### CODE REVIEW

File: flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/NavigateBetweenViewsIT.java [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+
+        Assert.assertThat(getDriver().getCurrentUrl(),
+                CoreMatchers.endsWith("/hello"));
+
+        $(NativeButtonElement.class).id(NAVIGATE_ABOUT).click();
+
+        // Wait for component inside shadowroot as there is no vaadin
+        // to wait for as with server-side
+        waitUntil(
+                input -> getInShadowRoot(findElement(By.tagName("about-view")),
```
Comment (denis-anisimov) [inline flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/NavigateBetweenViewsIT.java:43]: It's better to avoid `getInShadowRoot` usage.
`$("about-view").id("navigate-hello")`

File: flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/NavigateBetweenViewsIT.java [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+
+    @Test
+    public void openTsView_navigateToFlow_navigationSuccessful() {
+        getDriver().get(getRootURL() + "/");
+        waitForDevServer();
+
+        // Wait for component inside shadowroot as there is no vaadin
+        // to wait for as with server-side
+        waitUntil(
+                input -> getInShadowRoot(findElement(By.tagName("about-view")),
```
Comment (denis-anisimov) [inline flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/NavigateBetweenViewsIT.java:60]: See above about `getInShadowRoot`

File: flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/NavigateBetweenViewsIT.java [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+                        By.id("navigate-hello")).isDisplayed());
+
+        getInShadowRoot(findElement(By.tagName("about-view")),
+                By.id("navigate-hello")).click();
+
+        Assert.assertThat(getDriver().getCurrentUrl(),
```
Comment (denis-anisimov) [inline flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/NavigateBetweenViewsIT.java:66]: Is it enough to check the URL only ?
Should it also check that the content of the page is expected ?

**Review by denis-anisimov — CHANGES_REQUESTED** [review]

**Review by denis-anisimov — APPROVED** [review]
