### PR TITLE
fix: Do not use hardcoded target directory

### LINKED ISSUE #10335: Make hard-coded 'target/' folder configurable
Certain places in Flow contain hard-coded Maven-style 'target/' folders, while Gradle use 'build/'. For example:
* the `VaadinConnectTsGenerator` class - the `outputFolder` field.
* `FrontendUtils.TARGET`
* Possibly others?

### Versions:
    - Vaadin / Flow version: 20 / 7.0.0.alpha1

### PR DESCRIPTION
**Pull request by caalador**
Any code writing to the build directory should
not depend on a hardcoded `target` directory
as for instance gradle uses `build` and it may
be configured also in Maven.

Fixes #10335

### CODE REVIEW

File: flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt [hunk 1]
```diff
@@ -122,7 +116,7 @@ class MiscSingleModuleTest : AbstractGradleTest() {
         )
 
         val build: BuildResult =
-            testProject.build("-Pvaadin.productionMode", "clean", "build")
```
Comment (taefi) [inline flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt:125]: Are these *clean*s removed because of having no effect as `testProject` is created before each task?

Comment (caalador) [reply flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt:125]: The build fails the `clean` step due to clean being `UP-TO-DATE` instead of `SUCCESS`

File: flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java [hunk 2]
```diff
@@ -183,6 +184,10 @@ public void setup() throws Exception {
                 FrontendTools.DEFAULT_NODE_VERSION);
         ReflectionUtils.setVariableValueInObject(mojo, "nodeDownloadRoot",
                 NodeInstaller.DEFAULT_NODEJS_DOWNLOAD_ROOT);
+        ReflectionUtils.setVariableValueInObject(mojo, "projectBasedir",
```
Comment (taefi) [inline flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java:187]: Is the `dir` in `projectBasedir` not camel-case intentionally?

File: flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java [hunk 3]
```diff
@@ -268,6 +273,38 @@ public void should_copyProjectFrontendResources()
...
+                .of(flowResourcesFolder.listFiles()).map(File::getName)
+                .collect(Collectors.toSet());
+
+        projectFrontendResources.forEach(fileName -> {
+            Assert.assertTrue(String.format(
+                    "Expected the copied file '%s' to be in the project resources",
+                    fileName), filesInFlowResourcesFolder.contains(fileName));
+        });
+    }
+
```
Comment (taefi) [inline flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java:307]: Should we add another test to make sure when the `projectBuildDir` is set to `build`, nothing is created in the maven default `target` folder?

File: flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java [hunk 4]
```diff
@@ -15,6 +15,11 @@
  */
 package com.vaadin.flow.component.polymertemplate;
 
+import static com.vaadin.flow.server.frontend.FrontendUtils.FLOW_NPM_PACKAGE_NAME;
+import static elemental.json.JsonType.ARRAY;
+import static elemental.json.JsonType.OBJECT;
+import static elemental.json.JsonType.STRING;
+
```
Comment (taefi) [inline flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java:22]: These import statics are better to be moved below other imports.

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java [hunk 5]
```diff
@@ -311,13 +316,17 @@ public void should_setServiceWorkerEntryPoint_fromCurrentFolder_when_CustomServi
 
     protected void createWebpackUpdater() {
         webpackUpdater = new TaskUpdateWebpack(frontendFolder, baseDir,
-                new File(baseDir, TARGET + "webapp"),
-                new File(baseDir, TARGET + "classes"), WEBPACK_CONFIG,
+                new File(baseDir, "target/webapp"),
+                new File(baseDir, "target/classes"), WEBPACK_CONFIG,
```
Comment (taefi) [inline flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java:320]:
```suggestion
                new File(baseDir, TARGET + "/webapp"),
                new File(baseDir, TARGET + "/classes"), WEBPACK_CONFIG,
```

**Review by taefi — CHANGES_REQUESTED** [review]
Please consider sonar deprecation comments where possible.

File: flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java (hunk 2 above)
Comment (caalador) [reply flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java:187]: It's from the refactoring so probably not intentional, but not a part for this PR.

**Review by taefi — APPROVED** [review]
