### PR TITLE
fix: don't fire shortcut event if ancestor of component is not visible

### LINKED ISSUE #7033: Shortcut events triggered although lifecycleOwner's parent is not visible
Shortcut events are triggered as long as the component is visible and enabled.
However, if the parent component of lifecycleOwner is hidden, shortcut events are still triggered.
Here is a small code to generate the issue:
```Java
public MainView() {
        Button button = new Button("Click me",
                e -> Notification.show("Button is clicked"));
        button.addClickShortcut(Key.ENTER);
        VerticalLayout layout = new VerticalLayout(button);
        Button hideShow = new Button("Hide/Show");
        TextArea textArea = new TextArea();
        textArea.setVisible(false);
        hideShow.addClickListener(evt -> {
        	layout.setVisible(!layout.isVisible());
        	textArea.setVisible(!textArea.isVisible());
        });
        add(layout, textArea, hideShow);
    }
```

When `Hide/Show` button is clicked, the layout that contains the button is hidden.
Whenever enter key is pressed in textarea, the button click event is triggered.

Vaadin version: 14.0.14
Flow version: 2.0.18
Chrome version: 78

### PR DESCRIPTION
**Pull request by denis-anisimov**
fixes #7033

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java [hunk 1]
```diff
@@ -556,6 +553,24 @@ private void updateHandlerListenerRegistration(int listenOnIndex) {
         }
     }
 
+    private void fireShortcutEvent(Component component) {
+        if (ancestorsAreVisible(lifecycleOwner)
```
Comment (mshabarov) [inline flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java:557]: I'd prefer to extract checking `lifecycleOwner` from `ancestorsAreVisible` to outside, like:
```java
if (lifecycleOwner.isVisible() && lifecycleOwner
                                    .getElement().isEnabled() && ancestorsAreVisible(lifecycleOwner)) {
...
}
```
Because `ancestorsAreVisible` gives an impression that the `lifecycleOwner` is not checked within this method.
Or rename the method to prompt the reader that the `lifecycleOwner` is also checked inside, e.g. `componentAndAncestorsAreVisible`.
But this is minor and perhaps just my feeling.

File: flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java [hunk 2]
```diff
@@ -556,6 +553,24 @@ private void updateHandlerListenerRegistration(int listenOnIndex) {
...
+                && lifecycleOwner.getElement().isEnabled()) {
+            invokeShortcutEventListener(component);
+        }
+    }
+
+    private boolean ancestorsAreVisible(Component component) {
+        if (!component.isVisible()) {
```
Comment (mshabarov) [inline flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java:564]: Should we check `isEnabled()` for the parent components as well?

Comment (denis-anisimov) [reply flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java:564]: No, It already do it internally.

File: flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java [hunk 3]
```diff
@@ -419,6 +421,106 @@ public void listenOnComponentHasElementLocatorJs_allowBrowserDefault_JsExecution
...
+        clientResponse();
+
+        listenOn[0].getEventBus()
+                .fireEvent(new KeyDownEvent(listenOn[0], Key.KEY_A.toString()));
+
+        Assert.assertNull(event.get());
+    }
+
+    @Test
+    public void constructedRegistration_lifecycleOnwerAncestorsAreVisible_shorcutEventIsNotFired() {
```
Comment (mshabarov) [inline flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java:477]:
```suggestion
    public void constructedRegistration_lifecycleOnwerAncestorsAreVisible_shorcutEventIsFired() {
```

**Review by mshabarov — DISMISSED** [review]

File: flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java (hunk 1 above)
Comment (denis-anisimov) [reply flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java:557]: `ancestorsAreVisible` requires dramatic implementation change to avoid checking the passed component visibility.
Method name is a bit confusing indeed but I dislike the methods with `Or`  or `And` in the names.
For private method the name could be good enough.
But it's changed.

**Review by mshabarov — APPROVED** [review]

File: flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java (hunk 3 above)
Comment (denis-anisimov) [reply flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java]: done

**Review by mshabarov — APPROVED** [review]

**Comment by mshabarov** [comment]
@denis-anisimov please re-sign the CLA.
