### PR TITLE
fix: propagate node settings to frontendTools

### LINKED ISSUE #22846: Gradle plugin 24.8+ not take Vaadin configuration in build.gradle
### Description of the bug

I am using Vaadin with Gradle `8.12` and the `com.vaadin` gradle plugin.

Since I move the plugin to version `24.8` up to `24.9.5`, the configuration in `build.gradle` is not read. Everything work with plugin version `24.7.X`

```
plugins {
	....
	id 'java'
	id 'com.vaadin'
}

 ....

vaadin {
    nodeVersion = 'v24.4.1'    // Vaadin 24 requires at least 18
    nodeDownloadRoot = "https://otherrepo.example.com/org/nodejs/node/"
}
```

Log when I execute the `VaadinPrepareFrontend`
```
Couldn't find node.exe. Installing Node and npm to C:\Users\my-user\.vaadin.
Installing node version v22.17.0
Downloading https://nodejs.org/dist/v22.17.0/node-v22.17.0-win-x64.zip to C:\Users\my-user\.vaadin\node-v22.17.0-win-x64.zip
```

As you can see the `nodeVersion` and `nodeDownloadRoot` is not used.

### Expected behavior

I am expecting the vaadin-plugin should download the correct `nodeVersion` from the correct `nodeDownloadRoot`

### Minimal reproducible example

To ensure the behaviour is not link to my project, I have clone: https://github.com/vaadin/base-starter-spring-gradle

and add into the `build.gradle`:
```
vaadin {
    nodeVersion = 'v24.4.1'
}
```

Then run the gradle task: `vaadinPrepareFrontend --info`
With the folowing result:

```
Couldn't find node.exe. Installing Node and npm to C:\Users\my-user\.vaadin.
Installing node version v22.17.0
Downloading https://nodejs.org/dist/v22.17.0/node-v22.17.0-win-x64.zip to C:\Users\my-user\.vaadin\node-v22.17.0-win-x64.zip
```

### Versions

- Vaadin Gradle Plugin: 24.8+
- Java version: 21
- OS version: W10
- Gradle: 8.7+

### PR DESCRIPTION
**Pull request by caalador**
Have the correct settings for
FrontendToolsSettings in gradle toolsSettings.

Dev mode should also read the node settings
when starting the dev server if available.

Fixes #22846

### CODE REVIEW

File: flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt [hunk 1]
```diff
@@ -622,10 +622,18 @@ public class PluginEffectiveConfiguration(
...
             FrontendUtils.getVaadinHomeDirectory()
                 .absolutePath
         }
+
+        frontendToolsSettings.nodeDownloadRoot = URI.create(nodeDownloadRoot.get())
+        frontendToolsSettings.nodeVersion = nodeVersion.get()
+        frontendToolsSettings.isUseGlobalPnpm = useGlobalPnpm.get()
+        frontendToolsSettings.isForceAlternativeNode = requireHomeNodeExec.get()
+        frontendToolsSettings.isIgnoreVersionChecks = frontendIgnoreVersionChecks.get()
+        println("Added frontend tools settings! " + frontendToolsSettings.nodeVersion)
```
Comment (tltv) [inline flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt]: println here and line after that doesn't look necessary.

Comment (caalador) [reply flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt]: Yes println was for debugging that I saw the dynamic plugin was used. the last line is the same as `return frontendToolsSettings;` which is required as else the provider is not getting the frontendToolsSettings object.

Removed println.
