### PR TITLE
Avoid NPEs in WebBrowser

### LINKED ISSUE #6955: WebBrowser.isX throws a NPE if there is no user agent
`Flow 2.0.17`
If there is no user agent string available in `WebBrowser.updateRequestDetails` (which can happen if the request comes e.g. from a bot), methods like `WebBrowser.isWindows` that rely on the existence of `browserDetails` will throw a `NullPointerException`. This will cause extra noise on the logs on apps that get crawled by bots.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #6955

### CODE REVIEW

File: flow-server/src/test/java/com/vaadin/flow/server/WebBrowserTest.java [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+        Assert.assertFalse(browser.isIPhone());
+    }
+
+    @Test
+    public void isChromeOS_noDetails_returnsFalse() {
+        WebBrowser browser = new WebBrowser();
+
+        Assert.assertFalse(browser.isChromeOS());
+    }
+}
```
Comment (joheriks) [inline flow-server/src/test/java/com/vaadin/flow/server/WebBrowserTest.java:71]: Again not blocking this, but how about less redundancy by moving the `WebBrowser` to a field?

File: flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java [hunk 2]
```diff
@@ -205,6 +205,9 @@ public int getBrowserMinorVersion() {
      *         Linux or if no information on the browser is present
      */
     public boolean isLinux() {
+        if (browserDetails == null) {
+            return false;
+        }
```
Comment (joheriks) [inline flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java:210]: Couldn't all these `if (browserDetails == null)` guards be removed if the `browserDetails` field was initialized with a default value (in which all fields are anyway `false` or `-1`).

Comment (denis-anisimov) [reply flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java:210]: That was my original intention.

But then I've realized that there is already a plenty of methods which has impl with checking `browserDetails == null`.

So I decided to follow the existing pattern because:
- I'm too lazy to rewrite all the existing code
- even though I was sure that the new code that I was going to write will work correctly I was not sure that the existing code won't be broken with the default initialization like `new BrowserDetails("");`.
- decided to keep have consistent code
