### PR TITLE
fix: Always use defined node version

### LINKED ISSUE #12686: Running devMode doesn't respect nodeVersion given in plugin configuration
### Description of the bug

Starting up a project with `requireHomeNodeExec` and `nodeVersion` defined in for the plugin does install and use a node to `~/.vaadin`, but does not use the defined nodeVersion instead using the `DEFAULT_NODE_VERSION`

### Expected behavior

Defined version should be installed and not the default version

### Minimal reproducible example

- Define to any v14 demo to the maven plugin the configuration:
```
<configuration>
  <requireHomeNodeExec>true</requireHomeNodeExec>
  <nodeVersion>v17.2.0</nodeVersion>
</configuration>
```
- Run `mvn`
- See that the installed version is not 17.2.0, but the default 14.15.4

### Versions

- Vaadin / Flow version: 14+

### PR DESCRIPTION
**Pull request by caalador**
If defined always use the node version
and download root url is defined.

Closes #12686

### CODE REVIEW

File: flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java [hunk 1]
```diff
@@ -208,6 +211,14 @@ public static File propagateBuildInfo(PluginAdapterBase adapter) {
         buildInfo.put(SERVLET_PARAMETER_INITIAL_UIDL,
                 adapter.eagerServerLoad());
         buildInfo.put(NPM_TOKEN, adapter.npmFolder().getAbsolutePath());
+        buildInfo.put(NODE_VERSION, adapter.nodeVersion());
+        try {
+            buildInfo.put(NODE_DOWNLOAD_ROOT,
+                    adapter.nodeDownloadRoot().toString());
+        } catch (URISyntaxException e) {
+            LoggerFactory.getLogger("BuildInfo")
+                    .error("NODE_DOWNLOAD_ROOT defined incorrectly", e);
```
Comment (joheriks) [inline flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java:220]: Should the logged error contain the literal value of `NODE_DOWNLOAD_ROOT` (`node.download.root`) instead

**Review by joheriks — CHANGES_REQUESTED** [review]

File: flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java (hunk 1 above)
Comment (caalador) [reply flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java]: clarified.

**Review by joheriks — APPROVED** [review]

**Review by joheriks — APPROVED** [review]
