### PR TITLE
Store webpack dev server port in tempfile named from JVM unique constant and project folder

### LINKED ISSUE #8723: Random minimize/maximize of terminal window caused by multiple webpack-dev-server instances after saving java files
### Description of the bug
Terminal window gets randomly minimized and maximized after saving java files.
Seems to be caused by having multiple webpack-dev-server instances running.

### Minimal reproducible example
It happens after running `jetty:run` in a clean checkout of https://github.com/vaadin/skeleton-starter-flow and start doing java code changes. Don't have steps to reproduce it consistently but it's been happening daily.

<details>
<summary>Build log of last restarts</summary>
<p>

```
[INFO] restarting o.e.j.m.p.JettyWebAppContext@2123af21{/,[file://projectPath/skeleton-starter-flow/src/main/webapp/, jar:file:///Usersusername.m2/repository/com/vaadin/flow-data/4.0.0.alpha2/flow-data-4.0.0.alpha2.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/flow-client/4.0.0.alpha2/flow-client-4.0.0.alpha2.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-select-flow/4.0.0.alpha1/vaadin-select-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-text-field-flow/4.0.0.alpha1/vaadin-text-field-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/org/webjars/npm/vaadin__vaadin-mobile-drag-drop/1.0.0/vaadin__vaadin-mobile-drag-drop-1.0.0.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-date-picker-flow/4.0.0.alpha1/vaadin-date-picker-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/org/webjars/npm/mobile-drag-drop/2.3.0-rc.1/mobile-drag-drop-2.3.0-rc.1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-context-menu-flow/5.0.0.alpha1/vaadin-context-menu-flow-5.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-grid-flow/6.0.0.alpha1/vaadin-grid-flow-6.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-grid-pro-flow/4.0.0.alpha1/vaadin-grid-pro-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-combo-box-flow/5.0.0.alpha1/vaadin-combo-box-flow-5.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/flow-dnd/4.0.0.alpha2/flow-dnd-4.0.0.alpha2.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-time-picker-flow/4.0.0.alpha1/vaadin-time-picker-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/flow-server/4.0.0.alpha2/flow-server-4.0.0.alpha2.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-iron-list-flow/4.0.0.alpha1/vaadin-iron-list-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-menu-bar-flow/3.0.0.alpha1/vaadin-menu-bar-flow-3.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/flow-push/4.0.0.alpha2/flow-push-4.0.0.alpha2.jar!/META-INF/resources],AVAILABLE}{file://projectPath/skeleton-starter-flow/src/main/webapp/}
[INFO] Stopped o.e.j.m.p.JettyWebAppContext@2123af21{/,file://projectPath/skeleton-starter-flow/src/main/webapp/,UNAVAILABLE}{file://projectPath/skeleton-starter-flow/src/main/webapp/}
[INFO] Webapp source directory = projectPath/skeleton-starter-flow/src/main/webapp
[INFO] Reload Mechanic: automatic
[INFO] nonBlocking:false
[INFO] Classes = projectPath/skeleton-starter-flow/target/classes
[INFO] Context path = /
[INFO] Tmp directory = projectPath/skeleton-starter-flow/target/tmp
[INFO] Web defaults = org/eclipse/jetty/webapp/webdefault.xml
[INFO] Web overrides =  none
[INFO] web.xml file = null
[INFO] Webapp directory = projectPath/skeleton-starter-flow/src/main/webapp
[INFO] Scanning elapsed time=125ms
[INFO] Initializing AtmosphereFramework
[Scanner-10] INFO com.vaadin.flow.server.startup.VaadinAppShellInitializer - Using org.vaadin.example.AppShell class for configuring `index.html` response
[Scanner-10] INFO com.vaadin.flow.server.startup.DevModeInitializer - Starting dev-mode updaters in projectPath/skeleton-starter-flow folder.
[Scanner-10] INFO com.vaadin.flow.server.frontend.scanner.FullDependenciesScanner - Visited 100 classes. Took 11 ms.
[ForkJoinPool.commonPool-worker-5] INFO com.vaadin.flow.server.frontend.TaskGeneratePackageJson - writing file projectPath/skeleton-starter-flow/target/flow-frontend/package.json.
[ForkJoinPool.commonPool-worker-5] INFO com.vaadin.flow.server.frontend.TaskGeneratePackageJson - writing file projectPath/skeleton-starter-flow/target/flow-frontend/form/package.json.
[ForkJoinPool.commonPool-worker-5] INFO com.vaadin.flow.server.frontend.TaskGenerateIndexHtml - writing file 'projectPath/skeleton-starter-flow/target/index.html'
[ForkJoinPool.commonPool-worker-5] INFO com.vaadin.flow.server.frontend.TaskGenerateIndexTs - writing file 'projectPath/skeleton-starter-flow/target/index.ts'
[ForkJoinPool.commonPool-worker-5] INFO com.vaadin.flow.server.connect.generator.OpenApiSpecGenerator - Parsing java files from [projectPath/skeleton-starter-flow/src/main/java]
[Scanner-10] INFO com.vaadin.flow.server.startup.ServletDeployer - Automatically deploying Vaadin servlet Cwitoh mnapmei cloim.nvaga.di.n..f
low.server.str[tu3p.S4ermvlℹet
                              e[p3lo9ymer  t [/*
C9o0mm｢wCompiling...
ℹ                                       ompiCloimnpgi.l.i.n
g.. opimpiling...
ℹ
3m4pmiℹliVaadin application has been deployed and started to the context path "/".
Comd m｣pilng ｢wdm[4lm3｣
g..90m｢wd｣
3m9ℹm:9ℹng39m [39m[39m: C3omp 4Co m ...
ℹ｢｢wdm｣: Compiling...
mpilℹ9ilin9g0m｢wdm｣39minw9dmg. .
m: Co[[.. 
｣C990m｢3mpil9wdm｣｢: ompiCowdm9m:m: iCompil ｣pillin9m: ComCompiling...i
nng...g
.pgin.ilin..g
...g
...
..
ℹ ｢wdm｣: Compiling...
[INFO] Started o.e.j.m.p.JettyWebAppContext@2123af21{/,[file://projectPath/skeleton-starter-flow/src/main/webapp/, jar:file:///Usersusername.m2/repository/com/vaadin/flow-data/4.0.0.alpha2/flow-data-4.0.0.alpha2.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/flow-client/4.0.0.alpha2/flow-client-4.0.0.alpha2.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-select-flow/4.0.0.alpha1/vaadin-select-flow-4.0.0.alpha1.jar!/META-INF/reso[86%dules...]
e [80%K[2[[G81[88%%] O] Optimptizimie modzue modulesle...
[8KKK1
22KK1GA[%[1A KptG[81%] imOptimiizzee  modulesmo...o.d
dle[2s.Ktimize modules...
[1[[K2[[AG822K% GO[p8t8i%m]i zOep tmiomdiuzlee sm.o.d.ud8in5.f%l]ow .sOerpvetr.icomnnieczt.ege nemraotodr.uOpleenAspi.Sp.ec.Generato
les.2.Kre r[e 2noK cn[ne1ctA n[dp2oiKns[ tGo [ge8n5er%at]e. 
[[K2[[AG822K% GO[p8t9i%m]i zOep tmiomdiuzlee sm.o.d.u
[95%] Optimize modules...
ℹ ｢atl｣: Checking started in a separate process...
[95%] Optimize modules...
ℹ ｢atl｣: Checking started in a separate process...
[85%] Optimize modules...
[ForkJoinPool.commonPool-worker-5] INFO com.vaadin.flow.server.frontend.TaskUpdatePackages - Skipping `pnpm install`.
          [mGi[z8e5 %m]o dOuplteism.ize mo..
[91%] Optimize moduleods...u
[95%] Optimize modules...
ℹ ｢atl｣: Checking started in a separate process...
[K2%] Optim[G[95%ize ] Emmit files...
[95%] Optimize modules...
ℹ ｢atl｣: Checking started in a separate process...
[95%] Optimize modules...
ℹ ｢atl｣: Checking started in a separate process...
[95%] Optimize modules...
ℹ ｢atl｣: Checking started in a separate process...
[95%] Optimize modules...
ℹ ｢atl｣: Checking started in a separate process...
[95%] Optimize modules...
ℹ ｢atl｣: Checking started in a separate process...
[95%] Optimize modules...
ℹ ｢atl｣: Checking started in a separate process...
[98%] Emmit files...
[98%] Emmit files...
ℹ ｢wdm｣: Hash: b55a35368c1ec8703b70
Version: webpack 4.42.0
Time: 459ms
Built at: 07/16/2020 3:25:00 PM
     Asset       Size  Chunks             Chunk Names
index.html  986 bytes          [emitted]  
 + 8 hidden assets
Entrypoint bundle = build/vaadin-bundle-d7eff93a8424e75950b6.cache.js
Entrypoint export [big] = build/vaadin-export-c17667f172d3b3dcf6f3.cache.js
[../target/index.ts] 1.43 KiB {bundle} [built]
    + 560 hidden modules
om [ 9"0imn｢dwedxm.｣h[m3l9"m::
 Ha s h :   516 0a1s9seect6
43  44eb0351 b4
 EVnetrrypoint  u ndesiofi       Snen: wed er= bpinvideack 4.4x.ng tht2.0
mlT
imh  e  [..e 'stats.json' fi/nod: 450mse_modules/.pnlepm
/Br deguilt isynamtat: ry.icalnpm07ℹs.oly.rg39m 9/h
    0m｢wdm16/｣ebpA392020m:Kc[G H 3:25:as[9k-p8%h: b55a3536800c1ec8703] lugin/3.2.Emb7 P0
mit0Ver fileMs
si_won:   ...
[100%] Busein-50bun0m｢wdlb6.cache.js
e-Entdmryd7poin｣ export [befig[3] =f9 bu9m: ild/vaa3adin-exCpo8mpoi42lertd 4esu-ccc75es17sful9ly6.5
0b6ufink Nlmto daulamenis
----------------- Frontend compiled successfully. ----------------- 3:25:00 P  in:2/lib/loader.js!../t     [emitM
t e  a5:rg  Assd]etet00 by 0./i         Size  Chunks  nd4e73s 
6.7cafche1.7j2sd
3b3dEcnft6rfy3p.ociancth ee.xjpso.esdd
rt [..[bi/tg]arget =/ind bex.ts] u1.4il3 d/KiB va{bundleadin} [bu-eilt]NF9O co8m.v6aadi n.fblowy.setrveer.frsont end .Ta skU pdat eIm por ts  - N o j s m[oduelesm toi upxp    + 560 hidden moduleorsr
tC-hci1ld html-webpack-plu76gin 67forf1 "72ind3bdex.h[tFomrkJolinP"ool:.co
mm3onPdo olc- wofr k6e r-f5 ] 3I1NF.O  com.vaaadin.sflosw.seervter.
DevMocdeHanadlecr -h Steart.ingj w ebpa ck- dev-serverortds.jds' efilne
 Es 3tryp hsetsidoide
ntr[y.p.o/itnatr guentd/eifnidneexd. t=s ]i n1d.e4x3. hKtimBl O  com=.v
{b  un  [dle}.. [/nbuodile_t]mond.nTastkUp datbeImupornts d- Nlo jes m odu=les  to bupduatei '/lUsedrs/g/uilvle/aproajecdts/iskenlet-on-bstaurtenr-fdlowl/taerge-t/frdontdu l e s /+. p5n6p0m /hriedgdiesnt rmyo.dnuplmejss
.oCrhgi/lhdt mhlt-mwle-bwpeabcpkac-pk-luplgin/u3gin .f2.0_or webp"iack@4.4ndex.html"2.0/:
no d   e_mod 1 asules/htset
m l - w Entrypoebint unpdeackfi-plugneind = /lindex.hibtml
/l o   [ad../nodere_modu.jles/.pnpm/res!gistry.npmjs.or..g/html/ta-webprgack-pet/ilundgin/3.2e.0_x.wehtbpmlack@] 1.4.4132.0/ KnoiB de_{0}mod [ulbues/htiltml]
-webp        + ack-plugi3n/ hiddlienb/l moaodderu.ljess!../target/i
ndex.hm4ml]ℹ.13 3K9imB 90m1}｢wdm [b｣i[3lt]9m: Compil
ed s  ucce      + 3 hissdden modulefullsy
.
ℹ
----------------- Frontend compiled successfully. -----------------

[39m ｢wdm｣: Compiled successfully.

----------------- Frontend compiled successfully. -----------------
ℹ ｢wdm｣: Hash: 56019ec64344eb0351b4
Version: webpack 4.42.0
Time: 482ms
Built at: 07/16/2020 3:25:00 PM
     Asset       Size  Chunks             Chunk Names
index.html  986 bytes          [emitted]  
 + 8 hidden assets
Entrypoint bundle = build/vaadin-bundle-d7eff93a8424e75950b6.cache.js
Entrypoint export [big] = build/vaadin-export-c17667f172d3b3dcf6f3.cache.js
[../target/index.ts] 1.43 KiB {bundle} [built]
    + 560 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [../node_modules/.pnpm/registry.npmjs.org/html-webpack-plugin/3.2.0_webpack@4.42.0/node_modules/html-webpack-plugin/lib/loader.js!../target/index.html] 1.13 KiB {1} [built]
        + 3 hidden modules
ℹ ｢wdm｣: Compiled successfully.

----------------- Frontend compiled successfully. -----------------
[98%] Emmit files...
ℹ ｢wdm｣: Hash: 56019ec64344eb0351b4
Version: webpack 4.42.0
Time: 503ms
Built at: 07/16/2020 3:25:00 PM
     Asset       Size  Chunks             Chunk Names
index.html  986 bytes          [emitted]  
 + 8 hidden assets
Entrypoint bundle = build/vaadin-bundle-d7eff93a8424e75950b6.cache.js
Entrypoint export [big] = build/vaadin-export-c17667f172d3b3dcf6f3.cache.js
[../target/index.ts] 1.43 KiB {bundle} [built]
    + 560 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
.j[95% und]so Emmietf files...the 'stats[2intK
n' ifilned =e  inddex.htymlnamic
a    ll[../node_ymodule.
[100%] Build fin.j.son' file di-pshed at y.
[98%] Emm94sader.js!.. bKal1Ay 0./lo4y.2K
it
[[Ki/tales.1A..
ÿ100%¦ Build finished at 15:25:00 by 0.509s
ml¦ 1.13 KiB ¨1¼ ÿbuilt¦
        + 3 hidden modules
ℹ ｢wdm｣: Compiled successfully.

----------------- Frontend compiled successfully. -----------------

^ÿÿ?1;2cℹ ｢wdm｣: Hash: 56019ec64344eb0351b4
Version: webpack 4.42.0
Time: 516ms
Built at: 07/16/2020 3:25:00 PM
     Asset       Size  Chunks             Chunk Names
index.html  986 bytes          ÿemitted¦  
 + 8 hidden assets
Entrypoint bundle = build/vaadin-bundle-d7eff93a8424e75950b6.cache.js
Entrypoint export ÿbig¦ = build/vaadin-export-c17667f172d3b3dcf6f3.cache.js
ÿ../target/index.ts¦ 1.43 KiB ¨bundle¼ ÿbuilt¦
    + 560 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    ÿ../node_modules/.pnpm/registry.npmjs.org/html-webpack-plugin/3.2.0_webpack¾4.42.0/node_modules/html-webpack-plugin/lib/loader.js!../target/index.html¦ 1.13 KiB ¨1¼ÿbuilt¦
        + 3 hidden modules
ℹ ｢wdm｣: Compiled successfully.

----------------- Frontend compiled successfully. -----------------

ℹ ｢wdm｣: Hash: 56019ec64344eb0351b4
Version: webpack 4.42.0
Time: 514ms
Built at: 07/16/2020 3:25:00 PM
     Asset       Size  Chunks             Chunk Names
index.html  986 bytes          ÿemitted¦  
 + 8 hidden assets
Entrypoint bd34en mmoduℹe39sadin-bundle-d7eff93a8424e75950b6.cache.js
m hÿ9il0md ｢whtdmml｣ÿ3eb9mpa: ckHa-pshlu: gib5n 5afo35r 36"i8cnd1eexc8.h70tm3bl"70:
ÿ../target/index.ts¦ 1.43 KiB ¨bundle¼ ÿbuilt¦
     Ve1 rsasiosen:tules
  w e b pEanctkr y4p.o4i2n.t0 "index.html":
unTdiemfei:n e5d5 3=m indexs
.Bhutimllpoint undefined = index.html
t   a t :ÿ .0.7//n1o6d/e2_0m2o0d u3l:e2s5/:.0p0n pPmM/pack-plugin/3.2.0_webpack¾4.42.0/node_modules/html-webpack-plugin/lib/loader.js!../target/index.html¦ 1.13 KiB ¨1¼ÿre   gi  stAsryset.n  pm  js.or  g/ht Sml-ize we Chunkbpas    ck-  plug    in   /3Ch.2un.0k _Nawemebps
acink¾de4.x.4html  92.0/node_modules/html-webpack-plugin/lib/loader.js!../target/index.html¦ 1.13 KiB ¨1¼ ÿbuilt¦
        + 3 hidden modulesully.
ℹ ｢wdm｣: Compiled successfully.
----------------- Frontend compiled successfully. -----------------
----------------- Frontend compiled successfully. -----------------
ℹ ｢wdm｣: Hash: 56019ec64344eb0351b4
86 bytes          ÿemitted¦  
 + 8 hidden assets
Entrypoint bundle = build/vaadin-bundle-d7eff93a8424e75950b6.cache.js
Entrypoint export ÿbig¦ = build/vaadin-export-c17667f172d3b3dcf6f3.cache.js
ÿ../target/index.ts¦ 1.43 KiB ¨bundle¼ ÿbuilt¦
    + 560 hidden modules
Child html-webpack-plugin for "index.html":ff93a8424e75950b6.cache.js
     1 assetxport ÿbig¦ = build/vaadin-export-c17667f172d3b3dcf6f3.cache.js
    Entrypoint undefined = index.html¼ ÿbuilt¦
    ÿ../node_modules/.pnpm/registry.npmjs.org/html-webpack-plugin/3.2.0_webpack¾4.42.0/node_modules/html-webpack-plugin/lib/loader.js!../target/index.html¦ 1.13 KiB ¨0¼ÿbuilt¦
        + 3 hidden modules
ℹ ｢wdm｣: Compiled successfully.

----------------- Frontend compiled successfully. -----------------


------------------ Starting Frontend compilation. ------------------
ÿForkJoinPool.commonPool-worker-5¦ INFO com.vaadin.flow.server.DevModeHandler - Running webpack to compile frontend resources. This may take a moment, please stand by...
ÿ10%¦ Build modules...(0 of 0 modules )
ℹ ｢wds｣: Project is running at http://localhost:56138/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /VAADIN/
ÿ19%¦ Build modules...(79 of 90 modules frontend/styles/vaadin-text-field-styles
.css)
ℹ ｢atl｣: Using typescript¾3.8.3 from typescript
ℹ ｢atl｣: Using tsconfig.json from projectPath/skeleton-starter-flow/tsconfig.json
ÿINFO¦ restarting o.e.j.m.p.JettyWebAppContext¾2123af21¨/,ÿfile://projectPath/skeleton-starter-flow/src/main/webapp/, jar:file:///Usersusername.m2/repository/com/vaadin/flow-data/4.0.0.alpha2/flow-data-4.0.0.alpha2.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/flow-client/4.0.0.alpha2/flow-client-4.0.0.alpha2.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-select-flow/4.0.0.alpha1/vaadin-select-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-text-field-flow/4.0.0.alpha1/vaadin-text-field-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/org/webjars/npm/vaadin__vaadin-mobile-drag-drop/1.0.0/vaadin__vaadin-mobile-drag-drop-1.0.0.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-date-picker-flow/4.0.0.alpha1/vaadin-date-picker-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/org/webjars/npm/mobile-drag-drop/2.3.0-rc.1/mobile-drag-drop-2.3.0-rc.1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-context-menu-flow/5.0.0.alpha1/vaadin-context-menu-flow-5.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-grid-flow/6.0.0.alpha1/vaadin-grid-flow-6.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-grid-pro-flow/4.0.0.alpha1/vaadin-grid-pro-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-combo-box-flow/5.0.0.alpha1/vaadin-combo-box-flow-5.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/flow-dnd/4.0.0.alpha2/flow-dnd-4.0.0.alpha2.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-time-picker-flow/4.0.0.alpha1/vaadin-time-picker-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/flow-server/4.0.0.alpha2/flow-server-4.0.0.alpha2.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-iron-list-flow/4.0.0.alpha1/vaadin-iron-list-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-menu-bar-flow/3.0.0.alpha1/vaadin-menu-bar-flow-3.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/flow-push/4.0.0.alpha2/flow-push-4.0.0.alpha2.jar!/META-INF/resources¦,AVAILABLE¼¨file://projectPath/skeleton-starter-flow/src/main/webapp/¼
ÿINFO¦ Stopped o.e.j.m.p.JettyWebAppContext¾2123af21¨/,file://projectPath/skeleton-starter-flow/src/main/webapp/,UNAVAILABLE¼¨file://projectPath/skeleton-starter-flow/src/main/webapp/¼
ÿINFO¦ Webapp source directory = projectPath/skeleton-starter-flow/src/main/webapp
ÿINFO¦ Reload Mechanic: automatic
ÿINFO¦ nonBlocking:false
ÿINFO¦ Classes = projectPath/skeleton-starter-flow/target/classes
ÿINFO¦ Context path = /
ÿINFO¦ Tmp directory = projectPath/skeleton-starter-flow/target/tmp
ÿINFO¦ Web defaults = org/eclipse/jetty/webapp/webdefault.xml
ÿINFO¦ Web overrides =  none
ÿ22%¦ Build modules...(101 of 139 modules 
node_modules/.pnpm/registry.npmjs.org/¾vaadin/vaadin-tabs/3.2.0-alpha2/node_modu
ÿ27%¦ Build modules...(140 of 167 modules 
ÿ28%¦ Build modules...(146 of 168 modules 
ÿ28%¦ Build modules...(151 of 169 modules 
node_modules/.pnpm/registry.npmjs.org/¾vaadin/vaadin-themable-mixin/1.6.1/node_m
odules/¾vaadin/vaadin-themable-mixin/vaadin-themable-mixin.js)
ÿForkJoinPool.commonPool-worker-14¦ INFO com.vaadin.flow.server.frontend.TaskGeneratePackageJson - writing file projectPath/skeleton-starter-flow/target/flow-frontend/package.json.
ÿForkJoinPool.commonPool-worker-14¦ INFO com.vaadin.flow.server.frontend.TaskGeneratePackageJson - writing file projectPath/skeleton-starter-flow/target/flow-frontend/form/package.json.
ÿForkJoinPool.commonPool-worker-14¦ INFO com.vaadin.flow.server.frontend.TaskGenerateIndexHtml - writing file 'projectPath/skeleton-starter-flow/target/index.ÿ28%¦ Build modules...(153 of 169 modules 
ÿ28%¦ Build modules...(154 of 169 modules 
node_modules/.pnpm/registry.npmjs.org/¾vaadin/vaadin-themable-mixin/1.6.1/node_m
ÿ29%¦ Build modules...(157 of 169 modules 
node_modules/.pnpm/registry.npmjs.org/¾vaadin/vaadin-themable-mixin/1.6.1/node_m
ÿ29%¦ Build modules...(161 of 169 modules 
node_modules/.pnpm/registry.npmjs.org/¾vaadin/vaadin-themable-mixin/1.6.1/node_m
odules/¾vaadin/vaadin-themable-mixin/vaadin-themable-mixin.js)
ÿINFO¦ Started o.e.j.m.p.JettyWebAppContext¾2123af21¨/,ÿfile://projectPath/skeleton-starter-flow/src/main/webapp/, jar:file:///Usersusername.m2/repository/com/vaadin/flow-data/4.0.0.alpha2/flow-data-4.0.0.alpha2.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/flow-client/4.0.0.alpha2/flow-client-4.0.0.alpha2.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-select-flow/4.0.0.alpha1/vaadin-select-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-text-field-flow/4.0.0.alpha1/vaadin-text-field-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/org/webjars/npm/vaadin__vaadin-mobile-drag-drop/1.0.0/vaadin__vaadin-mobile-drag-drop-1.0.0.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-date-picker-flow/4.0.0.alpha1/vaadin-date-picker-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/org/webjars/npm/mobile-drag-drop/2.3.0-rc.1/mobile-drag-drop-2.3.0-rc.1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-context-menu-flow/5.0.0.alpha1/vaadin-context-menu-flow-5.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-grid-flow/6.0.0.alpha1/vaadin-grid-flow-6.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-grid-pro-flow/4.0.0.alpha1/vaadin-grid-pro-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-combo-box-flow/5.0.0.alpha1/vaadin-combo-box-flow-5.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/flow-dnd/4.0.0.alpha2/flow-dnd-4.0.0.alpha2.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-time-picker-flow/4.0.0.alpha1/vaadin-time-picker-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/flow-server/4.0.0.alpha2/flow-server-4.0.0.alpha2.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-iron-list-flow/4.0.0.alpha1/vaadin-iron-list-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-menu-bar-flow/3.0.0.alpha1/vaadin-menu-bar-flow-3.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/flow-push/4.0.0.alpha2/flow-push-4.0.0.alpha2.jar!/META-INF/resources¦,AVAILABLE¼¨file://projectPath/skeleton-starter-flow/src/main/webapp/¼
ÿINFO¦ Restart completed at Thu Jul 16 15:25:05 EEST 2020
CCCoommppiilliinngg......

ℹoCCoComompipilmpiommÿpilingCoCom39mpimp..34mplingingling.....
.iling...
ℹℹ
34mling. ℹn9mm 
4mℹÿ90m g.ÿ3
ÿÿ03m4｢mwℹdÿ｣3ÿm3 9ÿ:9 0Cmo｢mwpdiml｣i 
｢wÿ34｢wdm｣
[98%] Emmit files...
[32%] Build modules...(183 of 206 modules 
node_modules/.pnpm/registry.npmjs.org/cookieconsent/3.1.1/node_modules/cookiecon
ℹ ｢wdm｣: Hash: 56019ec64344eb0351b4
Version: webpack 4.42.0
Time: 491msize modules...
Built at: 07/16/2020 3:25:06 PMseparate process...
       1iAd[e2nK [sGs[e3t2s%
] BEntrypoint bundle = build/vaadin-bundle-d7eff93a8424e75950b6.cache.js
Entrypoint uild modexport [big] = buluies...(183 of ld/vaadin-ex20port-c17667f172d3b3dcf6f3.cache.js
[32%] Build modules...(et/index.ts] 1.43 KiB 184 of 207 mod{bundle} [built]
u l e s 
 + node_mo560 dules/.pnpm/registry.npmjs.org/@hidden mpolodules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
ymer/polymer/3.2.0/node_mo    [../node_modules/.pnpm/registry.npmjs.org/html-webpack-plugin/3.2.0_webpack@4.42.0/node_modules/html-webpack-plugin/lib/loader.js!../target/index.html] 1.13 KiB {1} [built]
        + 3 hidden modules
ℹ ｢wdm｣: Compiled successfully.

----------------- Frontend compiled successfully. -----------------

[32%] Build modules...(187 of 207 modules 
node_modules/.pnpm/registry.npmjs.org/@polymer/polymer/3.2.0/nℹ ｢wdodem｣: Hash: b55a35368c1ec8703b70
_mVoedursion: webpack 4.42.0
Time: 514ms
Built at: 07/16/2020 3:25:06 PM
     Asset       Size  Chunks             Chunk Names
ilndex.html e s/@poly9m8
6 beyrt/epso l y m e r / l i b /[uetmiiltst/ead]  
 + 8 hidden assets
Entrypoint bundle = build/vaadin-bundle-d7eff93a8424e75950b6.cache.js
Entrypoint export [big] = build/vaadin-export-c17667f172d3b3dcf6f3.cache.js
[../target/index.ts] 1.43 KiB {bundle} [built]
    + 560 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [../node_modules/.pnpm/registry.npmjs.org/html-webpack-plugin/3.2.0_webpack@4.42.0/node_modules/html-webpack-plugin/lib/loader.js!../target/index.html] 1.13 KiB {0} [rbuilt]
        + 3 hidden modules
ℹ ｢wdm｣: Compiled successfully.

[33%] Build modules...(188 of 207 modules 
node_modules/.pnpm/registry.npmjs.org/@polymer/polymer/3.2.0/node_modules/@polym
er/polymer/lib/utils/array-splice.js)
ℹ ｢wdm｣: Hash: b55a35368c1ec8703b70
Version: webpack 4.42.0
Time: 517ms
Built at: 07/16/2020 3:25:06 PM
     Asset       Size  Chunks             Chunk Names
index.html  986 bytes          [emitted]  
 + 8 hidden assets
Entrypoint bundle = build/vaadin-bundle-d7eff93a8424e75950b6.cache.js
Entrypoint export [big] = build/vaadin-export-c17667f172d3b3dcf6f3.cache.js
[../target/index.ts] 1.43 KiB {bundle} [built]
    + 560 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [../node_modules/.pnpm/registry.npmjs.org/html-webpack-plugin/3.2.0_webpack@4.42.0/node_modules/html-webpack-plugin/lib/loader.js!../target/index.html] 1.13 KiB {0} [built]
        + 3 hidden modules
ℹ ｢wdm｣: Compiled successfully.

----------------- Frontend compiled successfully. -----------------

ℹ ｢wdm｣: Hash: b55a35368c1ec8703b70
Version: webpack 4.42.0
Time: 527ms
Built at: 07/16/2020 3:25:06 PM
     Asset       Size  Chunks             Chunk Names
index.html  986 bytes          [emitted]  
 + 8 hidden assets
Entrypoint bundle = build/vaadin-bundle-d7eff93a8424e75950b6.cache.js
Entrypoint export [big] = build/vaadin-export-c17667f172d3b3dcf6f3.cache.js
[../target/index.ts] 1.43 KiB {bundle} [built]
    + 560 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [../node_modules/.pnpm/registry.npmjs.org/html-webpack-plugin/3.2.0_webpack@4.42.0/node_modules/html-webpack-plugin/lib/loader.js!../target/index.html] 1.13 KiB {0} [built]
        + 3 hidden modules
ℹ ｢wdm｣: Compiled successfully.

----------------- Frontend compiled successfully. -----------------

[98%] Emmit files...
ℹ ｢wdm｣: Hash: 56019ec64344eb0351b4
                 [4.4G2.0
[T1i0me:0 5%]34 Buildms 
fBiuniilsth eadt :a t0 71/51:62/52:00260  b3y: 205.:50368 sPM

    [A2sKs[t1 A [ 2 K [SGize  Chunks             Chunk Names
index.html  986 bytes          [emitted]  
 + 8 hidden assets
Entrypoint bundle = build/vaadin-bundle-d7eff93a8424e75950b6.cache.js
Entrypoint export [big] = build/vaadin-export-c17667f172d3b3dcf6f3.cache.js
[../target/index.ts] 1.43 KiB {bundle} [built]
    + 560 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [../node_modules/.pnpm/registry.npmjs.org/html-webpack-plugin/3.2.0_webpack@4.42.0/node_modules/html-webpack-plugin/lib/loader.js!../target/index.html] 1.13 KiB  {    1}   [  buServiinlgt ]t
he 's t a t s . json ' + f 3il hie dddyenna mmiodcaulllesy.

[ll10y.0%u2KK9[mG｢[w9d8m%｣][E3m9mmi:t  Cfoimlpeisl.e.d. 
[33%] Build modules...(190 of 209 modules 
node_modules/.pnpm/registry.npmjs.org/@vaadin/vaadin-lumo-styles/1.6.0/node_modu
les/@vaadin/vaadin-lumo-styles/mixins/required-field.js)
ℹ ｢wdm｣: Hash: b55a35368c1ec8703b70
Version: webpack 4.42.0
Time: 547ms
Built at: 07/16/2020 3:25:06 PM
     Asset       Size  Chunks             Chunk Names
index.html  986 bytes          [emitted]  
 + 8 hidden assets
Entrypoint bundle = build/vaadin-bundle-d7eff93a8424e75950b6.cache.js
Entrypoint export [big] = build/vaadin-export-c17667f172d3b3dcf6f3.cache.js
[../target/index.ts] 1.43 KiB {bundle} [built]
    + 560 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [../node_modules/.pnpm/registrypmmℹjs[39m r/html-webpack-p[90m｢luwdm｣gi/3.2.09m_we:bpack H@4a.42.0/node_mosh:du 560les19e/hc643t44eb0m351l-webpabck-plugin/l4
ib/loVaersionder.js!../ta:rg wet/indebpex.hatml] 1.13 KiB {0} [built]
ck 4 . 4 2 . 0 
                        n m[

9 1 so
f0  209 mℹ ｢wdm｣ Am｢wdm｣: Hash: b55asset       Size  Chunks             Chunk Names
index.html  986 bytes odules 
node_modu9les/.pnpm/registry.npmj  353       [emitted]  
 + 8 hiddens.m: Compiled successfully.org/ 68assets
Entrypoint bundle = build@v
aad
----------------- Frontend compiled successfully. -----------------

/vcaadin-buinnd1ele-d7eff93a8424e75950b6.cache.js
Entrypoint export [big] = build/vaadin-export-c17667f172d3b3dcf6f3.cache.js
[../target/index.ts] 1.43 KiB {bundle} [built]
    + 560 hidden modules
Child ht/vmc8l-webpack-plugain703b70
V fadin-lumo-styles/1.6.0/node_modu
les/@vaadin/vaadinor "indexer.html":
-     1 asset
    Esionntrypoint undefined = ilnd: wex.html
    [../node_modules/.pnpm/registry.npmjs.org/html-webpack-plugin/3.2.0_webpack@4.42.0/node_modules/html-webpack-plugin/lib/loader.js!../target/index.html] 1.13 KiB {1} [built]
        + 3 hidden modules
mo-sty34mℹs/ebpack 4.42.0
Time: 549ms
m[39m iBuxin｢wdm｣: Compiled sucsilt at: 07/16/2020 3/required-field.js)
ces:25s:f06 PM
u l l y . A
ss
----------------- Frontend compiled successfully. -----e---t  ---------
   ex.html":
3   4m  1 asseℹks             Chunk Names
9m    Entrypoint unde ｢fwdm｣: Cinompeid = lineddex. shtucmlce
ss f u l l[y.../ns
ode_mooint bundle = build/vaadin-bundle-d7eff93a8424e75950b6.cache.js
----------------- Frontend compiled successfully. -----------------cache.js
[../target/index.ts] 1.43 KiB {bundle} [built]
dules/.pnpm/registry.npmjs.org/html-webpack-plugin/3.2.0_webpack@4.42.0/node_modules/html-webpack-plugin/lib/loader.js!../target/index.html] 1.13 KiB {0} [built]

----------------- Frontend compiled successfully. ----2K-----------

[G[20%] Build modules...(81 of 103 modules .ajsdin] -4app-9la7 youbytes t{/0t}he [bmuiel/lut]mo/
ersusername.m2/repository/org/webjars/npm/vaadin__vaadin-mobile-drag-drop/1.0.0/vaadin__vaadin-mobile-drag-drop-1.0.0.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-date-picker-flow/4.0.0.alpha1/vaadin-date-picker-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/org/webjars/npm/mobile-drag-drop/2.3.0-rc.1/mobile-drag-drop-2.3.0-rc.1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-context-menu-flow/5.0.0.alpha1/vaadin-context-menu-flow-5.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-grid-flow/6.0.0.alpha1/vaadin-grid-flow-6.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-grid-pro-flow/4.0.0.alpha1/vaadin-grid-pro-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-combo-box-flow/5.0.0.alpha1/vaadin-combo-box-flow-5.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/flow-dnd/4.0.0.alpha2/flow-dnd-4.0.0.alpha2.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-time-picker-flow/4.0.0.alpha1/vaadin-time-picker-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/flow-server/4.0.0.alpha2/flow-server-4.0.0.alpha2.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-iron-list-flow/4.0.0.alpha1/vaadin-iron-list-flow-4.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/vaadin-menu-bar-flow/3.0.0.alpha1/vaadin-menu-bar-flow-3.0.0.alpha1.jar!/META-INF/resources, jar:file:///Usersusername.m2/repository/com/vaadin/flow-push/4.0.0.alpha2/flow-push-4.0.0.alpha2.jar!/META-INF/resources],AVAILABLE}{file://projectPath/skeleton-starter-flow/src/main/webapp/}
[INFO] Restart completed at Thu Jul 16 15:26:15 EEST 2020
CompilingCo.m.Compiling.piClCCompiling...

.mping.C.omomComCpipipiling...
.
i3n4g..mℹ.
ℹ 3ℹm｢wdm｣: Compilin ｢wdm｣
ℹℹ ｢wdm｣: Compilllomping.ining...
93m 9:[ 9C0omm｢pwidlingg..[34mℹm..
..
m｣: Cog.....
i
p 39il4m[3lin4mℹn0m9m｢wg.[3ℹ..[39m..d
m｣ omp 9m .
9304mmil0m｢wing｢wdmℹ9m｣dm.[
39m: Com ｢[9piling...
｣dm｣｢9m: dm[39m:｣om[3 C9mpil: omCoinmpilping..g.ili...

ng...
[ForkJoinPool.commonPool-worker-0] INFO com.vaadin.flow.server.connect.generator.OpenApiSpecGenerator - There are no connect endpoints to generate.
[ForkJoinPool.commonPool-worker-0] INFO com.vaadin.flow.server.frontend.TaskUpdatePackages - Skipping `pnpm install`.
[ForkJoinPool.commonPool-worker-0] INFO com.vaadin.flow.server.frontend.TaskCopyFrontendFiles - Copying frontend resources from jar files ...
pKmize K[1odules.G[..As...
[82%] Optimize modules...
O[t2iKm[z1eA o[2K[ulG[es..82.
G] [70%] B

[ O..ptimiz81Ales.%]2K
 1A5%] Optmo[2Kmize mo[Gdules...[88%] Opdutimi
[88%] odules..Ops...t
imi.%] Optimize  modulOeptims...

K89%] O[G[22K2K2K
   2K

-K2[i2mKi[e1 Am[d2uKl[sG.[.7.4
ze[86 m%] Optiodmize modules...ules.
AKKG[8G[88%]6%]  OOptimptizei[i2ze mo mKoddululs..As...
[2KG[88%] O2K
date /[Us2erKs/u[il1leA/r[oj2ecKts[keGle[to7n-6s%ta]rt erO-fplotw/itarget/frontend/gmeneirazteed- flmowo-idmpuorltse.jss'. f.il.e
[77%] Optimize modules[.Fo.rk.Jo
[71%] Optimize modules...
.vaadin.flow.server.frontend.TaskUpdateImports - o [js2 mKod[le1s Atou[pd2atKe /[UsGers[/g7ui7ll%e/]pr ojOecpts/sk eleton-sOtaprtteri-mfliowz/tear gemt/ofdrountleneds/g.en.er.a
ted-flow-impot[s.2d.Kts [fi1leA
        G][8 Op8%] Optimiz Opte timoimize modules...
dumize les...
       OptiG[mize modul7%] O[1ptAmi[2Ke modul[G[8es8%] ..Op.
.%[uildOp mG[] Optimiz.[es.1A
mi89e modules...9
[71%][1   2Km mmize m[ododullul1odoules...i
[90%]  Optimize modules...OpAod..K
[9[G[2Ke mG[s...
 e modules..
  90%odules...
[9fs...9[0For%kJoi]nPo ol.lcommoenPosol.-worlker-0] eINsFO. com.vaadOin.flpow.smerver..DevtModeHiandmler .- Ru.nninOgp webtpaicmk tio co
[es..98A].d Op i%]n tia  Osemizpaptrae mteim podroizcess.u..e m
 ℹod ｢es..atulel｣:.
[m2mKi[ 1f[2ilAsK
924K% 1OAp[i2mKi[eG [m9G[98%od] 2%]Emulesmi Opt ..fitimle.
s.2KizKOp[190Ai[2%] OKi[Gpt[9ze5%im]  mEmizmiodut e mfileleodus.s....les.
 mo2 K du[le95   %]s. OSept..imrviz
e[m2inKd[1g tAl[2Khe [G['s93s.%] Otapt..imits.ze
 ℹmjsod ｢ules.on..ati G[fiG[le91%s.94..] 
'[fl｣:il2K  Chdy[1Anaeckinm[c2ag stallK.rt.Emmodmi.
[uletes.98.. p Kpa seti1Aipaze[2 mraodK
...               ile..s.
O[t2iKm[z1eA [o2dKu
ℹ ｢[94tl2K｣:%] Tm Opte:Aimizms2K
           le BG[s.95ui%].. Eldmm
i[ 2 fKi[ini1lAeshs...
92K   GS[3844mervℹ4[39min 7[9g 0m595｢wthdm0b6｣ [3.ca9m'sta: cheHatssh.j: .jso56s
0E1n9etcr6ypno'i f43ilnt ee 44ebdyxpna03miorca51llt y.b4
[[i2gK][=w] dm5%]｣m
bp/vaac[98k adi4.%] 42n-.0Em
exTimimepo: t 35rt-1mfiles
cB1s.76ui67..[12bK4
f[722Kd[b13dclt af6A3.t:ca[2ch 0e.Ks7/1edmi iacn t a k sefipa4.ralete42 ps.roc.0
G[[.1.0/ta6/rge0%]t/i2020nd Buiex. 3:tsld f] 26:1.inis4315  KheiBPM {bud nd
l e }  [ b uAisastelt]t  15  
   :2    Si6z:e1 5  by  + 0.Ch43563sun
0[h2iKdksen[1 m  odAl  es[2K:7/] 16 1/2Emm02ms
 C h i l d   h t mClh-uwnekb pac-NamplGgesin4m f
oirn d"eixn.dhetxm.lh t m9lℹ
   [9 b0m 1｢wytdm as｣s[3se9m  : t  ..  .
H as  h:    5   60En19   ectr64[emi34yp4ettb0oi35ed1bnt4s.Ch..n'
]V e rl1A   dy2K  aG[  95mi%]    Ecamm  itlly. f  il
  u+ 8si hndidondeefn : wasinseebptsed
acEn = trk 4ypinoi.42ntde b.0unx.hdl
eT i=m eb:u i4l4dtm/v6msaal
d i n - b[u.nd.l/en-odd7ee_fmfo9d3ual8e4s2/.
pBnupiml/tr4eeg atis75tr: 0y.950bnp7/mj6.s.16orcag//20htchml20-we.eb 3:2pajsck6:1-p
lEungtirny/p3o.i5 nt2. ePM
x p o r t  A[sbsiegt]   =   b u i lSdi/zv0_waae  diebpn-Chexacpounkrtk@-cs  174.66  7f42172d3b3dc f6f3.cache  .   .0  js C/nhu
n[k. .N/atmaersg
et/iindnedoedxx.h.ts]e 1tml  9.4_mo3 86 bKiBd u{lbeusn/dhtmytl-lewees bp} ack-p  lug[bin   /luiib  /lltoa  de]
r . j s !+. [e560 hidden modules
Child html-.w/etbapragetmi/ickndttex-p.hedtmlul]]   1gin.1
3  + 8 hi ddKiBenfor a {ss "et1}s
iEnndterxy.photimnlt" :b
  [ b  un 1 auilssdle et
t  ] 
 =  E buinltdry/pvaa dioin-  bundnt le-d7  effund93a8 + 42ef4e3 h75950inedb6.ciddeac = ihen mo.jndes
duElnetsr
yp.ht34oimℹmlt39
  m ex[90  [m｢powd..m｣rt39 [m:od Cobigmpie_le] d modusuccessfully.

----------------- Frontend compiled successfully. ----------------=-

l build/evsa/a.pdinpmn-exp/orretg-ics1t7r6y6.7nfp1m7j2sd.3obr3gd/chft6mfl3-.wceabcphaec.kj-sp
lugi[n./.3/.t2a.r0g_ewte/bipnadcekx@4.t.4s] 2.01./nod43e_ KmodiB {ulebus/ndhtmle} l-w[bebuipaltck]
-p l u g i+n /5l6i0b /hliodader.djesn! m..odu/tarlgees
t/Cihnidelxd.html] ht 1.m13 l-weKibpB {ac1} k-[bpluiugltin]
      f o  r+  "3i nhdiedxd.ehnt mmlo"d:u
les  
  [13 4amsℹs[t3
9m   [ 9E0nmt｢rwydpmo｣i[t3 9umn:d eCfoimnpeidl e=d  isnudcecxe.shstfmull
ly . 
  [..
----------------- Frontend compiled successfully. -----------------

/node_modules/.pnpm/registry.npmjs.org/html-webpack-plugin/3.2.0_webpack@4.42.0/node_modules/html-webpack-plugin/lib/loader.js!../target/index.html] 1.13 KiB {1} [built]
        + 3 hidden modules
ℹ ｢wdm｣: Compiled successfully.

----------------- Frontend compiled successfully. -----------------

[10%] Build modules...(0 of 0 modules )
ℹ ｢wds｣: Project is running at http://localhost:56447/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /VAADIN/
[19%] Build modules...(79 of 91 modules frontend/styles/vaadin-text-field-styles
.css)
[95%] Optimize modules...
ℹ ｢atl｣: Checking started in a separate process...
[98%] Emmit files...
ℹ ｢wdm｣: Hash: b55a35368c1ec8703b70
Version: webpack 4.42.0
Time: 5001ms
Built at: 07/16/2020 3:26:22 PM
                                            Asset       Size  Chunks                                Chunk Names
     build/vaadin-0-1fa89442cd3ecad1a1fa.cache.js   16.2 MiB       0  [emitted] [immutable]  [big]  
     build/vaadin-1-f18a7c62aba62b6605eb.cache.js    333 KiB       1  [emitted] [immutable]         
     build/vaadin-2-ad32959753005684e4df.cache.js    349 KiB       2  [emitted] [immutable]         
     build/vaadin-3-0f8424cb7ffacc6b2407.cache.js   21.7 KiB       3  [emitted] [immutable]         
     build/vaadin-4-e427401563cac39efb81.cache.js    341 KiB       4  [emitted] [immutable]         
     build/vaadin-5-ce457b4e5df946990577.cache.js   86.3 KiB       5  [emitted] [immutable]         
build/vaadin-bundle-d7eff93a8424e75950b6.cache.js    289 KiB  bundle  [emitted] [immutable]         bundle
build/vaadin-export-c17667f172d3b3dcf6f3.cache.js   16.5 MiB  export  [emitted] [immutable]  [big]  export
                                       index.html  986 bytes          [emitted]                     
Entrypoint bundle = build/vaadin-bundle-d7eff93a8424e75950b6.cache.js
Entrypoint export [big] = build/vaadin-export-c17667f172d3b3dcf6f3.cache.js
[../node_modules/.pnpm/registry.npmjs.org/@polymer/iron-icon/3.0.1/node_modules/@polymer/iron-icon/iron-icon.js] 5.5 KiB {export} {0} [built]
[../node_modules/.pnpm/registry.npmjs.org/@polymer/iron-list/3.1.0/node_modules/@polymer/iron-list/iron-list.js] 59.3 KiB {export} {0} [built]
[../node_modules/.pnpm/registry.npmjs.org/@vaadin/router/1.7.2/node_modules/@vaadin/router/dist/vaadin-router.js] 90.7 KiB {bundle} [built]
[../node_modules/.pnpm/registry.npmjs.org/@vaadin/vaadin-accordion/1.2.0-alpha1/node_modules/@vaadin/vaadin-accordion/theme/lumo/vaadin-accordion.js] 78 bytes {export} {0} [built]
[../node_modules/.pnpm/registry.npmjs.org/@vaadin/vaadin-app-layout/2.2.0-alpha1/node_modules/@vaadin/vaadin-app-layout/theme/lumo/vaadin-app-layout.js] 81 bytes {export} {0} [built]
[../node_modules/.pnpm/registry.npmjs.org/@vaadin/vaadin-app-layout/2.2.0-alpha1/node_modules/@vaadin/vaadin-app-layout/theme/lumo/vaadin-drawer-toggle.js] 87 bytes {export} {0} [built]
[../node_modules/.pnpm/registry.npmjs.org/@vaadin/vaadin-board/2.2.0-alpha1/node_modules/@vaadin/vaadin-board/vaadin-board-row.js] 86 bytes {export} {0} [built]
[../node_modules/.pnpm/registry.npmjs.org/@vaadin/vaadin-board/2.2.0-alpha1/node_modules/@vaadin/vaadin-board/vaadin-board.js] 78 bytes {export} {0} [built]
[../node_modules/.pnpm/registry.npmjs.org/@vaadin/vaadin-button/2.4.0-alpha1/node_modules/@vaadin/vaadin-button/theme/lumo/vaadin-button.js] 73 bytes {export} {0} [built]
[../node_modules/.pnpm/registry.npmjs.org/@vaadin/vaadin-charts/7.0.0-alpha8/node_modules/@vaadin/vaadin-charts/src/vaadin-chart.js] 58.5 KiB {export} {0} [built]
[../node_modules/.pnpm/registry.npmjs.org/@vaadin/vaadin-checkbox/2.4.0-alpha3/node_modules/@vaadin/vaadin-checkbox/theme/lumo/vaadin-checkbox-group.js] 127 bytes {export} {0} [built]
[../node_modules/.pnpm/registry.npmjs.org/@vaadin/vaadin-checkbox/2.4.0-alpha3/node_modules/@vaadin/vaadin-checkbox/theme/lumo/vaadin-checkbox.js] 77 bytes {export} {0} [built]
[../node_modules/.pnpm/registry.npmjs.org/@vaadin/vaadin-combo-box/5.3.0-alpha5/node_modules/@vaadin/vaadin-combo-box/theme/lumo/vaadin-combo-box.js] 171 bytes {export} {0} [built]
[../target/frontend/generated-flow-imports.js] 5.36 KiB {export} {1} [built]
[../target/index.ts] 1.43 KiB {bundle} [built]
    + 546 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [../node_modules/.pnpm/registry.npmjs.org/html-webpack-plugin/3.2.0_webpack@4.42.0/node_modules/html-webpack-plugin/lib/loader.js!../target/index.html] 1.13 KiB {0} [built]
    [../node_modules/.pnpm/registry.npmjs.org/lodash/4.17.19/node_modules/lodash/lodash.js] 530 KiB {0} [built]
    [../node_modules/.pnpm/registry.npmjs.org/webpack/4.42.0_webpack@4.42.0/node_modules/webpack/buildin/global.js] 472 bytes {0} [built]
    [../node_modules/.pnpm/registry.npmjs.org/webpack/4.42.0_webpack@4.42.0/node_modules/webpack/buildin/module.js] 497 bytes {0} [built]
ℹ ｢wdm｣: Compiled successfully.

----------------- Frontend compiled successfully. -----------------

[ForkJoinPool.commonPool-worker-0] INFO com.vaadin.flow.server.DevModeHandler - Started webpack-dev-server. Time: 7419ms


```

</p>
</details>

<details>
<summary>Output from `ps aux | grep node`</summary>
<p>

```
63936   0.0  1.4  6608792 471824 s008  S+    2:42PM   0:15.53 /usr/local/bin/node projectPath/skeleton-starter-flow/node_modules/webpack-dev-server/bin/webpack-dev-server.js --config projectPath/skeleton-starter-flow/webpack.config.js --port 62857 --watchDogPort=62856 -d --inline=false
63910   0.0  1.4  6610328 462032 s008  S+    2:41PM   0:15.44 /usr/local/bin/node projectPath/skeleton-starter-flow/node_modules/webpack-dev-server/bin/webpack-dev-server.js --config projectPath/skeleton-starter-flow/webpack.config.js --port 62833 --watchDogPort=62832 -d --inline=false
63885   0.0  1.4  6610328 460004 s008  S+    2:41PM   0:17.54 /usr/local/bin/node projectPath/skeleton-starter-flow/node_modules/webpack-dev-server/bin/webpack-dev-server.js --config projectPath/skeleton-starter-flow/webpack.config.js --port 62811 --watchDogPort=62810 -d --inline=false
63868   0.0  1.4  6631320 482176 s008  S+    2:41PM   0:16.79 /usr/local/bin/node projectPath/skeleton-starter-flow/node_modules/webpack-dev-server/bin/webpack-dev-server.js --config projectPath/skeleton-starter-flow/webpack.config.js --port 62805 --watchDogPort=62804 -d --inline=false
63844   0.0  1.4  6609304 470744 s008  S+    2:40PM   0:18.38 /usr/local/bin/node projectPath/skeleton-starter-flow/node_modules/webpack-dev-server/bin/webpack-dev-server.js --config projectPath/skeleton-starter-flow/webpack.config.js --port 62790 --watchDogPort=62789 -d --inline=false
64361   0.0  1.3  6603592 438240 s008  S+    3:08PM   0:10.90 /usr/local/bin/node projectPath/skeleton-starter-flow/node_modules/webpack-dev-server/bin/webpack-dev-server.js --config projectPath/skeleton-starter-flow/webpack.config.js --port 51997 --watchDogPort=51996 -d --inline=false
64133   0.0  1.3  6602568 435936 s008  S+    2:50PM   0:11.49 /usr/local/bin/node projectPath/skeleton-starter-flow/node_modules/webpack-dev-server/bin/webpack-dev-server.js --config projectPath/skeleton-starter-flow/webpack.config.js --port 63962 --watchDogPort=63961 -d --inline=false
64072   0.0  1.4  6622104 464300 s008  S+    2:46PM   0:12.92 /usr/local/bin/node projectPath/skeleton-starter-flow/node_modules/webpack-dev-server/bin/webpack-dev-server.js --config projectPath/skeleton-starter-flow/webpack.config.js --port 63045 --watchDogPort=63044 -d --inline=false
64045   0.0  1.4  6624152 476276 s008  S+    2:46PM   0:13.97 /usr/local/bin/node projectPath/skeleton-starter-flow/node_modules/webpack-dev-server/bin/webpack-dev-server.js --config projectPath/skeleton-starter-flow/webpack.config.js --port 62929 --watchDogPort=62928 -d --inline=false
63996   0.0  1.4  6623640 467148 s008  S+    2:44PM   0:13.37 /usr/local/bin/node projectPath/skeleton-starter-flow/node_modules/webpack-dev-server/bin/webpack-dev-server.js --config projectPath/skeleton-starter-flow/webpack.config.js --port 62906 --watchDogPort=62905 -d --inline=false
63979   0.0  1.4  6627736 482912 s008  S+    2:44PM   0:14.87 /usr/local/bin/node projectPath/skeleton-starter-flow/node_modules/webpack-dev-server/bin/webpack-dev-server.js --config projectPath/skeleton-starter-flow/webpack.config.js --port 62902 --watchDogPort=62901 -d --inline=false
```

</p>
</details>

### Versions:
    - Vaadin / Flow version: 17.0.0.alpha6 / 4.0.0.alpha2
    - Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T21:33:14+03:00)
    - Java version: 1.8.0_241
    - Default locale: en_US, platform encoding: UTF-8
    - OS name: "mac os x", version: "10.15.5", arch: "x86_64", family: "mac"
    - Visual Studio Code: Version: 1.47.1

### PR DESCRIPTION
**Pull request by joheriks**
See https://github.com/vaadin/flow/issues/8723#issuecomment-660865512.
Fixes #8723

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java [hunk 1]
```diff
@@ -464,7 +468,7 @@ public String getFailedOutput() {
      * Remove the running port from the vaadinContext and temporary file.
      */
     public void removeRunningDevServerPort() {
-        FileUtils.deleteQuietly(LazyDevServerPortFileInit.DEV_SERVER_PORT_FILE);
```
Comment (denis-anisimov) [inline flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java:467]: I think I don't understand the reason of the issue.

Does JVM exit ?
The current (before the patch) state of code assumes that the port file is 1:1 JVM.
If JVM has exited then I don't understand how this code allows to get the same file name in new JVM.
If JVM has not terminated then why there is a need to modify the code ?

In the second case if JVM has terminated watchdog should terminate the webpack dev server as well.
And it looks like the fix is done in a wrong place ?....

Comment (joheriks) [reply flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java:467]: The JVM doesn't terminate when Jetty restarts from monitored class modification and scanInterval. However, app context is reloaded and all static initializers are rerun, which results in the [handle to the port file](https://github.com/vaadin/flow/blob/2.2/flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java#L658) being lost. This in turns means that `DevModeHandler` can't connect to the existing Webpack dev server, and spans another one unnecessarily. The interleaved output from these concurrently running servers causes terminal problems.

Port file isn't necessarily 1:1 with JVM since it is possible (but maybe not common) to run multiple applications in dev mode simultaneously under the same JVM. Each app will have its own Webpack dev server. AFAIK has of thread group + full file path to frontend build directory ought to be unique for each deployed app and for each new start of the app in another JVM.

Comment (denis-anisimov) [reply flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java:467]: Hmmm.....
`LazyDevServerPortFileInit.DEV_SERVER_PORT_FILE`  can't be lost since JVM is not terminated.
It doesn't matter whether initializers are rerun or not. Class is loaded once and should be there since JVM is alive.

The only thing which I missed is: the app is loaded via another classloader after Jetty restart even though JVM is not 
terminiated.
That's why `static initializers are rerun`: they are not rerun in fact. Classes are loaded by another classloader so that previous initializers initialized differerent classes (in a different scope).
Now I see my mistake.

Comment (denis-anisimov) [reply flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java:467]: Hmmm.....
LazyDevServerPortFileInit.DEV_SERVER_PORT_FILE can't be lost since JVM is not terminated.
It doesn't matter whether initializers are rerun or not. Class is loaded once and should be there since JVM is alive.

The only thing which I missed is: the app is loaded via another classloader after Jetty restart even though JVM is not
terminiated.
That's why static initializers are rerun: they are not rerun in fact. Classes are loaded by another classloader so that previous initializers initialized differerent classes (in a different scope).
Now I see my mistake.

Comment (denis-anisimov) [reply flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java:467]: Alright, now I understand the reason by I don't understand the solution.....

But that should be a comment in another place.

File: flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java [hunk 2]
```diff
@@ -742,18 +745,21 @@ void join() {
...
-                return File.createTempFile("flow-dev-server", "port");
-            } catch (IOException exception) {
-                throw new UncheckedIOException(exception);
-            }
-        }
 
+    private static File getDevServerPortFile(File npmFolder) {
+        // The thread group is the same in each servlet-container restart
+        String threadGroup = String
+                .valueOf(Thread.currentThread().getThreadGroup().hashCode());
```
Comment (denis-anisimov) [inline flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java:752]: What I don't understand here: why the thread group will be the same after restart ?
Which way it's forced ?

File: flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java [hunk 3]
```diff
@@ -742,18 +745,21 @@ void join() {
...
+
+        // #8723: keep webpack alive when Jetty restarts.
+        // Thread group ID prevents the port file from being picked up after JVM
+        // restart. Frontend path ensures uniqueness when multiple devmode apps
+        // are deployed.
+        String uniqueUid = UUID
+                .nameUUIDFromBytes((threadGroup + frontendBuildPath)
+                        .getBytes(StandardCharsets.UTF_8))
+                .toString();
+        return new File(System.getProperty("java.io.tmpdir"), uniqueUid);
```
Comment (knoobie) [inline flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java:763]: What do you think about using File.createTempFile instead? (https://docs.oracle.com/javase/8/docs/api/java/io/File.html#createTempFile-java.lang.String-java.lang.String-)

Comment (joheriks) [reply flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java:763]: `File::createTempFile` creates a new empty temporary file with a unique name. After Jetty reload there's no way to get the same file name again, to read the port number from.  I believe `File::createTempFile` works like this by design so that temporary files are guaranteed to never clash. In this case we actually need a predictable temporary file name that remains the same throughout Jetty reload.

Comment (knoobie) [reply flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java:763]: You are right! I was thinking about the following: 
- using `File::createTempFile` with a unique prefix `vaadin-webpack-lock` and a suffix `portnumber` 
- this would allow on server start to search in the temp directory for files starting with `vaadin-webpack-lock` and identifying the `portnumber`it used last time

Drawback: This would create a huge problem with running multiple vaadin instances locally at the same time. :(

File: flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java (hunk 2 above)
Comment (joheriks) [reply flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java:752]: That the thread group hash code stays the when Jetty reloads I have only empirically verified, other suggestions welcome. The string used needs to satisfy the following:
- Change when the JVM is restarted
- Remain the same when Jetty reloads and the JVM is not restarted

**Comment by joheriks** [comment]
@denis-anisimov Added IT module `test-jetty-reload` that triggers jetty by touching a dummy file `target/scantrigger`. The test checks that the webpack dev server port remains the same after reload. This kind of tests risk being flaky, please check if you think the Selenium code can be made more robust.

File: flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java (hunk 2 above)
Comment (denis-anisimov) [reply flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java:752]: Thread group hash may stay the same when JVM restarts.

So it fixes the issue (even though there is no proof) but it doesn't fit to your requirements.

When I run simple Main java class all threads have the same hash on every restart.

Comment (denis-anisimov) [reply flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java:752]: Original code contained a JVM id : https://github.com/vaadin/flow/commit/2bc0128d004447e6f67d438f140a74b4c47a8761#diff-023ed25c83cd7d7abab003a4d2ff7607

But `ManagementFactory.getRuntimeMXBean().getName()` takes 5 seconds and totally block any execution (executing it in a separate thread doesn't help). So it's extremely bad idea to use this code.

**Comment by denis-anisimov** [comment]
> @denis-anisimov Added IT module `test-jetty-reload` that triggers jetty by touching a dummy file `target/scantrigger`. The test checks that the webpack dev server port remains the same after reload. This kind of tests risk being flaky, please check if you think the Selenium code can be made more robust.

Apparently the test is failing.

**Comment by joheriks** [comment]
> Apparently the test is failing.

So it the temp file name was not resolved correctly after restart, maybe it works differently on Linux. Back to the drawing board for this.

**Comment by joheriks** [comment]
@denis-anisimov The test should now pass. `maven-jetty-plugin` [does not override system properties](https://www.eclipse.org/jetty/documentation/current/jetty-maven-plugin.html#setting-system-properties) if already set. Since this IT module specifically requires **not** reusing the dev server added `<force>true</force>` option.

File: flow-tests/test-jetty-reload/src/main/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortView.java [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+        unique.setId(UUID_ID);
+        add(unique);
+
+        DevModeHandler handler = DevModeHandler.getDevModeHandler();
+        Span portSpan = new Span(String.valueOf(handler.getPort()));
+        portSpan.setId(WEBPACK_PORT_ID);
+        add(portSpan);
+
+        final NativeButton triggerButton = new NativeButton("Trigger reload",
+                e -> {
```
Comment (denis-anisimov) [inline flow-tests/test-jetty-reload/src/main/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortView.java:51]: Minor : please avoid one letter variable .
Fix only if there are other things to fix as well...

File: flow-tests/test-jetty-reload/src/test/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortIT.java [hunk 5]
```diff
@@ -0,0 +1,68 @@
...
+import net.jcip.annotations.NotThreadSafe;
+import org.apache.commons.lang3.math.NumberUtils;
+import org.junit.Assert;
+import org.junit.Test;
+import org.openqa.selenium.By;
+import org.openqa.selenium.TimeoutException;
+
+import com.vaadin.flow.testutil.ChromeBrowserTest;
+
+@NotThreadSafe
```
Comment (denis-anisimov) [inline flow-tests/test-jetty-reload/src/test/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortIT.java:27]: Any reason to have it ?

File: flow-tests/test-jetty-reload/src/test/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortIT.java [hunk 6]
```diff
@@ -0,0 +1,68 @@
...
+        String initialPort = findElement(
+                By.id(WebpackDevServerPortView.WEBPACK_PORT_ID)).getText();
+        Assert.assertTrue(NumberUtils.isDigits(initialPort));
+
+        // trigger jetty reload
+        findElement(By.id(WebpackDevServerPortView.TRIGGER_RELOAD_ID)).click();
+
+        // keep refreshing until page comes back (the UUID has changed)
+        boolean reconnected = false;
+        for (int i = 0; i < 10; i++) {
```
Comment (denis-anisimov) [inline flow-tests/test-jetty-reload/src/test/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortIT.java:47]: 10 is a magic constant.

I would perhaps use waitUntil with some hardcoded big timeout.
`waitUntil` is effectively doing the same: run the condition until it becomes true over and over again.
So you may just put `getDriver().navigate().refresh();` and return `!initialUUID.equals(
                        findElement(By.id(WebpackDevServerPortView.UUID_ID))
                                .getText()` as the expected condition impl.
Also add a second parameter as a timeout.
That will allow to avoid: magic 10 constant, cycle, reconnected flag, catch an exception.

File: flow-tests/test-jetty-reload/src/main/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortView.java (hunk 4 above)
Comment (joheriks) [reply flow-tests/test-jetty-reload/src/main/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortView.java:51]: Done

File: flow-tests/test-jetty-reload/src/test/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortIT.java (hunk 5 above)
Comment (joheriks) [reply flow-tests/test-jetty-reload/src/test/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortIT.java:27]: At the moment strictly no, since there is only one test. However, I wanted to save feature headaches. This test must be isolated from other as it forces Jetty restart and the annotation is easily forgotten if/when another test method is added to the class.

File: flow-tests/test-jetty-reload/src/test/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortIT.java (hunk 6 above)
Comment (joheriks) [reply flow-tests/test-jetty-reload/src/test/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortIT.java:47]: `waitUntil` checks the condition repeatedly but it doesn't refresh the page. So a single `waitUntil` would need to rely on client side JS repeatedly trying to refresh the page when the connection to the first Jetty is lost (heartbeat missed). (Maybe it would work to call `driver.navigate().refresh()` inside the `waitUntil` but having a side effect there would be uglier in my opinion).

File: flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java (hunk 2 above)
Comment (joheriks) [reply flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java]: Now creates a new UUID and storted it in a special system property, which should a satisfy the above two criteria.

File: flow-tests/test-jetty-reload/src/test/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortIT.java (hunk 6 above)
Comment (denis-anisimov) [reply flow-tests/test-jetty-reload/src/test/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortIT.java:47]: Well, `driver.navigate().refresh()` looks OK for me but I understand your concern about side effect.
What I still don't like : magic `10` number.
Could you make it work as a timeout : define a hardcoded timeout and replace `for` loop with `while` which checks that the current time of execution is less than the initial time `+` timeout value.

Also would be really good to avoid `TimeoutException`  : since your are almost duplicating the `waitUntil` functionality I would just avoid `waitUntil` at all.
But this is optional.

Comment (denis-anisimov) [reply flow-tests/test-jetty-reload/src/test/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortIT.java:47]: -

Comment (joheriks) [reply flow-tests/test-jetty-reload/src/test/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortIT.java]: Done
