### PR TITLE
fix: Log webpack output on failure

### LINKED ISSUE #7472: Non-descriptive error message if webpack.config.js is invalid
Take the Spring Boot starter project and replace `webpack.config.js` with 
```
foo
```

If you run `node_modules/.bin/webpack` manually, you will get
```
ReferenceError: foo is not defined
    at Object.<anonymous> (.../webpack.config.js:1:63)
```

If you run `mvn`, you get
```
2020-02-03 12:15:47.107 ERROR 60528 --- [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Exception sending context initialized event to listener instance of class [com.vaadin.flow.spring.VaadinServletContextInitializer$DevModeServletContextListener]

java.lang.RuntimeException: Unable to initialize Vaadin DevModeHandler
	at com.vaadin.flow.spring.VaadinServletContextInitializer$DevModeServletContextListener.contextInitialized(VaadinServletContextInitializer.java:349) ~[vaadin-spring-12.2.0.alpha1.jar:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4680) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5143) [tomcat-embed-core-9.0.22.jar:9.0.22]
...
Caused by: java.lang.IllegalStateException: Webpack exited prematurely
	at com.vaadin.flow.server.DevModeHandler.<init>(DevModeHandler.java:201) ~[flow-server-2.2.0.alpha10.jar:2.2.0.alpha10]
	at com.vaadin.flow.server.DevModeHandler.createInstance(DevModeHandler.java:298) ~[flow-server-2.2.0.alpha10.jar:2.2.0.alpha10]
	at com.vaadin.flow.server.DevModeHandler.start(DevModeHandler.java:248) ~[flow-server-2.2.0.alpha10.jar:2.2.0.alpha10]

```

This does not even contain a reference to `webpack.config.js` nor to the problem that actually occured in `webpack`

### PR DESCRIPTION
**Pull request by caalador**
Log as error any output from webpack when
webpack exits prematurely.

Closes #7472

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java [hunk 1]
```diff
@@ -469,6 +471,9 @@ private void readLinesLoop(Pattern success, Pattern failure,
                 output.append(cleanLine).append(System.lineSeparator());
             }
 
+            // save output so as it can be used to log exception if run fails
+            cumulativeOutput.append(cleanLine).append(System.lineSeparator());
```
Comment (pleku) [inline flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java:475]: This is a bit confusing as the `if(succeed || failed)` clears it but my assumption is that it is for cases when "webpack fails even before compilation has properly started" or such. It could maybe be commented a bit better or even link to the ticket

File: flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java [hunk 2]
```diff
@@ -654,6 +660,9 @@ private boolean doStartWebpack(DeploymentConfiguration config,
             }
 
             if (!webpackProcess.get().isAlive()) {
+                getLogger().error(
+                    String.format("Webpack failed with the exception:%n%s",
```
Comment (pleku) [inline flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java:664]: Should it say `"Webpack failed before starting compilation with the exception:` ?

File: flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java (hunk 1 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java:475]: succeed and fail clear it so that if it runs again we don't have the old output stored.

**Review by pleku — APPROVED** [review]
