### PR TITLE
fix: add javadocs warning to avoid using ResponseWriter for dirs

### LINKED ISSUE #11046: ResponseWriter.writeResponseContent writes incorrect Content-Length if resourceUrl points to a file system directory
`ResponseWriter.writeResponseContent` uses `connection.getContentLengthLong()` (see https://github.com/vaadin/flow/blob/83ebf7b7a920ce098b9048d10a7d32813d2719e4/flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java#L166-L171). When `resourceUrl` points to a file system directory, this internally translates to a call to `File.length()`, which has the following in the JavaDoc:

> The return value is unspecified if this pathname denotes a directory.

Steps to reproduce it locally:
1. Create SVC app
2. Run `mvn package` (to put some stuff to `/target/classes/META-INF/VAADIN/webapp/VAADIN/build`)
2. Run applicatoin in development mode in a normal manner
3. Run `curl -i "http://localhost:8080/VAADIN/build/." --path-as-is`
4. Observe that content-length in HTTP response doesn't match to the actual amount of text
5. Observe that CURL "hangs" (it waits for more data)

### PR DESCRIPTION
**Pull request by denis-anisimov**
fixes #11046

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java [hunk 1]
```diff
@@ -92,6 +92,13 @@ private ResponseWriter(int bufferSize, boolean brotliEnabled) {
     /**
      * Writes the contents and content type (if available) of the given
      * resourceUrl to the response.
+     * <p>
+     * WARNING: note that this should not be used for {@code resourceUrl} which
+     * represents a directory! For security reasons the directory content should
+     * not be ever printed into the {@code response} and the implementation
+     * which is used for setting content length relies on
+     * {@link URLConnection#getContentLengthLong()} method which returns
+     * incorrect value for a directory.
```
Comment (taefi) [inline flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java:101]:
```suggestion
     * WARNING: note that this should not be used for a {@code resourceUrl} that
     * represents a directory! For security reasons, the directory contents should
     * not be ever written into the {@code response}, and the implementation
     * which is used for setting the content length relies on
     * {@link URLConnection#getContentLengthLong()} method which returns
     * incorrect values for directories.
```

**Review by pleku — APPROVED** [review]
