### PR TITLE
test: fix test to not be run threaded

### LINKED ISSUE #17856: Java 21: Unit test failed when running flow main branch
### Description of the bug

flow unit test failed with running Java 21 

```
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.035 s <<< FAILURE! -- in com.vaadin.flow.i18n.DefaultInstantiatorI18NTest
[09:16:53 ](https://bender.vaadin.com/buildConfiguration/JDKs/453258?buildTab=log&focusLine=10654&logView=flowAware&linesState=10654)      [ERROR] com.vaadin.flow.i18n.DefaultInstantiatorI18NTest.translationFileOnClasspath_instantiateDefaultI18N -- Time elapsed: 0.008 s <<< FAILURE!
[09:16:53 ](https://bender.vaadin.com/buildConfiguration/JDKs/453258?buildTab=log&focusLine=10655&logView=flowAware&linesState=10655)      java.lang.AssertionError
[09:16:53 ](https://bender.vaadin.com/buildConfiguration/JDKs/453258?buildTab=log&focusLine=10656&logView=flowAware&linesState=10656)        at org.junit.Assert.fail(Assert.java:87)
[09:16:53 ](https://bender.vaadin.com/buildConfiguration/JDKs/453258?buildTab=log&focusLine=10657&logView=flowAware&linesState=10657)        at org.junit.Assert.assertTrue(Assert.java:42)
[09:16:53 ](https://bender.vaadin.com/buildConfiguration/JDKs/453258?buildTab=log&focusLine=10658&logView=flowAware&linesState=10658)        at org.junit.Assert.assertTrue(Assert.java:53)
[09:16:53 ](https://bender.vaadin.com/buildConfiguration/JDKs/453258?buildTab=log&focusLine=10659&logView=flowAware&linesState=10659)        at com.vaadin.flow.i18n.DefaultInstantiatorI18NTest.translationFileOnClasspath_instantiateDefaultI18N(DefaultInstantiatorI18NTest.java:95)
[09:16:53 ](https://bender.vaadin.com/buildConfiguration/JDKs/453258?buildTab=log&focusLine=10660&logView=flowAware&linesState=10660)        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[09:16:53 ](https://bender.vaadin.com/buildConfiguration/JDKs/453258?buildTab=log&focusLine=10661&logView=flowAware&linesState=10661)        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[09:16:53 ](https://bender.vaadin.com/buildConfiguration/JDKs/453258?buildTab=log&focusLine=10662&logView=flowAware&linesState=10662)        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
[09:16:53 ](https://bender.vaadin.com/buildConfiguration/JDKs/453258?buildTab=log&focusLine=10663&logView=flowAware&linesState=10663)        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
```

### Expected behavior

build is working

### Minimal reproducible example

- download the currently java 21 version 
  - `https://download.java.net/java/GA/jdk21.0.1/415e3f918a1f4062a0074a2794853d0d/12/GPL/openjdk-21.0.1_linux-x64_bin.tar.gz`

- `mvn -e -B -V -T 6 -q -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn test -am -pl flow-html-components,flow-dnd,flow-plugins`

### Versions

- Vaadin / Flow version: 24.3-SNAPSHOT
- Java version: 21.0.1

### PR DESCRIPTION
**Pull request by caalador**
Instantiator test is not thread safe as after cleans static field

Fixes #17856

### CODE REVIEW

File: flow-server/src/test/java/com/vaadin/flow/server/I18NProviderTest.java [hunk 1]
```diff
@@ -52,33 +54,48 @@ public void no_property_defined_should_leave_with_default_locale()
...
         Assert.assertEquals("Found wrong registry", TestProvider.class,
-                VaadinService.getCurrent().getInstantiator().getI18NProvider()
-                        .getClass());
+                instantiator.getI18NProvider().getClass());
+
+        Field field = DefaultInstantiator.class
+                .getDeclaredField("i18nProvider");
+        field.setAccessible(true);
+        ((AtomicReference<I18NProvider>) field.get(instantiator)).set(null);
+        field.setAccessible(false);
```
Comment (mcollovati) [inline flow-server/src/test/java/com/vaadin/flow/server/I18NProviderTest.java:73]: What about moving this code to a `TestUtil` helper method?
I supposed there could be other tests in the future that may need to clean the `i18provider` field (for example if we add the customized implementation for Spring).

Also, I would call in `@Before` and `@After` methods instead of in the test itself.
I suppose there could be a single method with both annotations.

File: flow-server/src/test/java/com/vaadin/flow/server/I18NProviderTest.java [hunk 2]
```diff
@@ -52,33 +54,48 @@ public void no_property_defined_should_leave_with_default_locale()
...
+                .getInstantiator();
         Assert.assertEquals("Found wrong registry", TestProvider.class,
-                VaadinService.getCurrent().getInstantiator().getI18NProvider()
-                        .getClass());
+                instantiator.getI18NProvider().getClass());
+
+        Field field = DefaultInstantiator.class
+                .getDeclaredField("i18nProvider");
+        field.setAccessible(true);
+        ((AtomicReference<I18NProvider>) field.get(instantiator)).set(null);
```
Comment (mcollovati) [inline flow-server/src/test/java/com/vaadin/flow/server/I18NProviderTest.java:72]: Since the field is static, we can give `null` to `field.get()`.

**Review by mcollovati — CHANGES_REQUESTED** [review]

File: flow-server/src/test/java/com/vaadin/flow/server/I18NProviderTest.java (hunk 2 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/server/I18NProviderTest.java]: done

**Review by mcollovati — APPROVED** [review]
