### PR TITLE
Fix vaadin.launch-browser=true and HTTPS #15496

### LINKED ISSUE #15496: vaadin.launch-browser=true and HTTPS
### Description of the bug

If https is configured the browser is opened with http://localhost:8080 instead of https://localhost:8080,

### Expected behavior

The browser should be opened with https://localhost:8080,

### Minimal reproducible example

Create a self signed certificate and set the server.ssl properties:

    server.ssl.key-store-type=PKCS12
    server.ssl.key-store=classpath:localhost.p12
    server.ssl.key-store-password=password
    server.ssl.key-alias=1

### Versions

- Vaadin / Flow version: 23.3.0
- Java version: 17

### PR DESCRIPTION
**Pull request by atai**
## Description

Fixes #15496 vaadin.launch-browser=true and HTTPS 

This fix brings the behavior of the feature "opening browser" according to the application settings that can be used SSL in a development environment.

I can't check it locally because mvn verify is broken on my development host.

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by mcollovati** [comment]
@atai thank you for the contribution.
We will take a look at this shortly.
In the meanwhile, May I ask you to format the code as explained [in the above comment](#issuecomment-1604013020) and push the changes?

File: vaadin-spring/src/test/java/com/vaadin/flow/spring/DevModeBrowserLauncherHttpsProtoTest.java [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+ * the License.
+ */
+package com.vaadin.flow.spring;
+
+import org.junit.jupiter.api.Assertions;
+import org.junit.jupiter.api.Test;
+import org.springframework.test.context.TestPropertySource;
+
+@TestPropertySource(properties = { "server.port = 1235",
+        "server.ssl.enable = true" })
```
Comment (mcollovati) [inline vaadin-spring/src/test/java/com/vaadin/flow/spring/DevModeBrowserLauncherHttpsProtoTest.java:23]: typo
```suggestion
        "server.ssl.enabled = true" })
```

**Review by mcollovati — CHANGES_REQUESTED** [review]

File: vaadin-spring/src/test/java/com/vaadin/flow/spring/DevModeBrowserLauncherHttpsProtoTest.java (hunk 1 above)
Comment (atai) [reply vaadin-spring/src/test/java/com/vaadin/flow/spring/DevModeBrowserLauncherHttpsProtoTest.java]: Sorry for that. Fixed.

Comment (mcollovati) [reply vaadin-spring/src/test/java/com/vaadin/flow/spring/DevModeBrowserLauncherHttpsProtoTest.java]: No worries

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/DevModeBrowserLauncher.java
Comment (mcollovati) [inline vaadin-spring/src/main/java/com/vaadin/flow/spring/DevModeBrowserLauncher.java:1]: Sorry for being picky, but can you please move the `getUrl` and `getLogger` methods to the original position, under `ready(...)` method?
This way can limit the changes to the merged commit to what is effectively relevant?

Comment (atai) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/DevModeBrowserLauncher.java:1]: Sorry, but I didn't understand what do you mean. 

Obviously, I didn't have the intention to change anything except a few lines of code(I saw that lines 46-88 were changed). Fighting with precise file format is out of scope for me. If you know how to merge only really changed lines - please merge it, if not - just close the PR. 

Probably I will find time to change it again with new knowledge about formatting.

Comment (mcollovati) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/DevModeBrowserLauncher.java:1]: I suppose your IDE changed the order of the methods in the class.
In the original source code the `getUrl` method was on line 90, but in your change it has been moved to line `46`, so it seems the whole method has been modified, but you only changed a couple of lines

Comment (mcollovati) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/DevModeBrowserLauncher.java:1]: I was able to update your PR directly

Comment (atai) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/DevModeBrowserLauncher.java:1]: > I was able to update your PR directly

It would be great. Sorry for that. Next time I will check it.

Comment (mcollovati) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/DevModeBrowserLauncher.java:1]: No problems. The PR now looks goof.
Let me just sync it again with main, then it can be merged.
Thanks again for the contribution.
