### PR TITLE
Fix setClassName to work as specified in javadoc

### LINKED ISSUE #8840: HasStyle.setClassName fails when null is passed
Vaaidn 14.3.2, flow 2.3.2. The following code:

```java
new Button("Foo").setClassName(null);
```

fails with

```
Caused by: java.lang.IllegalArgumentException: Value cannot be null
	at com.vaadin.flow.dom.Element.validateAttribute(Element.java:1448)
	at com.vaadin.flow.dom.Element.setAttribute(Element.java:286)
	at com.vaadin.flow.component.HasStyle.setClassName(HasStyle.java:66)
```

even though `HasStyle.setClassName()` javadoc says

```
     * @param className
     *            a space-separated string of class names to set, or
     *            <code>null</code> to remove all class names
```

### PR DESCRIPTION
**Pull request by caalador**
Fixes #8840

### CODE REVIEW

File: flow-server/src/test/java/com/vaadin/flow/component/HasStyleTest.java [hunk 1]
```diff
@@ -70,6 +70,10 @@ public void removeClassName() {
         component.removeClassName("baz");
         assertClasses(component);
 
+        component.setClassName("removeMe");
+        // setting null to classname should remove class name attribute
+        component.setClassName(null);
```
Comment (pleku) [inline flow-server/src/test/java/com/vaadin/flow/component/HasStyleTest.java:75]: Missing assert or `assertClasses` ?
Technically I would have expected test to go to the `setClassName()` method below

Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/component/HasStyleTest.java]: Moved and fixed. 
I totally forgot the assert as the unfixed fails already on set before the assert.
