### PR TITLE
fix: always wait for navigated event for title

### LINKED ISSUE #21171: Incorrect Browser tab titles in Chromium based browsers
### Description of the bug

There seems to a regression on the following issue https://github.com/vaadin/flow/issues/19868

Example uses Vaadin 24.7.0, when building a production JAR of the application when switching between the different views (empty and hello-world) and then using the browser history to navigate back and forward the title of the browser tab is out of sync as described in the related issue.

Bug is only present on Chromium based browsers, Firefox does not suffer from the issue.

Disabling the react integration by excluding the `flow-react` dependency from the project and setting the necessary configuration flags fixes the issue.

Image

### Expected behavior

Tab titles should always display correctly, regardless of browser of how the page is navigated to.

### Minimal reproducible example

Forked from the original example in the bug, updated to the latest version of Vaadin https://github.com/gert-dubois/vaadinHistoryBug

1. Built a production jar using `mvn clean install -Pproduction`
2. Run the `vaadin-demo-1.0-SNAPSHOT.jar`
3. Navigate between the Empty and HelloWorld view in any Chromium based browsers
4. Use the back and forward button to navigate
5. Tab titles are broken

### Versions

- Vaadin / Flow version: 24.7.0 (issue also occurs in our own project on 24.6.6)
- Java version: 21
- OS version: Windows 11
- Browser version: Chrome 134.0.6998.118, Edge 134.0.3124.72

### PR DESCRIPTION
**Pull request by caalador**
When running with react-router
always wait for vaadin-navigated
event before updating the title.

In these cases the title update is
always from the server.

Fixes #21171

### CODE REVIEW

File: flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx [hunk 1]
```diff
@@ -448,13 +446,22 @@ function Flow() {
         [navigate]
     );
 
-    useEffect(() => {
+  const flowNavigation = () => {
```
Comment (platosha) [inline flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx]: Since this function doesn't use anything from the `Flow` function's local scope, it's better to declare it outside, so that JS only creates this function once.

File: flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx [hunk 2]
```diff
@@ -448,13 +446,22 @@ function Flow() {
...
+    // @ts-ignore
+    window.Vaadin.Flow.navigation = true;
+  };
+
+  useEffect(() => {
+        // @ts-ignore
+        window.addEventListener("popstate", flowNavigation);
```
Comment (platosha) [inline flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx]: Note the effect dependencies (array items at the end of the block, `useEffect(() => { ... }, [dependencies]);`.

I think, there's no need to remove and add back the `flowNavigation` listener during the time Flow component exists on the page, as this function is never changing. So, since `flowNavigation` is independent, we could move the listener to the next `useEffect` block below, which does not have dependencies.

File: flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx (hunk 1 above)
Comment (caalador) [reply flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx]: Moved outside.

File: flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx (hunk 2 above)
Comment (caalador) [reply flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx]: set to the other block

File: flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx [hunk 3]
```diff
@@ -448,7 +455,7 @@ function Flow() {
         [navigate]
     );
 
-    useEffect(() => {
+  useEffect(() => {
```
Comment (platosha) [inline flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx]: unnecessary indentation change, let's undo:
```suggestion
    useEffect(() => {
```
