### PR TITLE
test: enable ignored cases in NavigationTriggerIT

### LINKED ISSUE #10513: Fusion: NavigationTriggerIT fails
Related ticker : https://github.com/vaadin/flow/issues/7572

The `NavigationTriggerIT` has been disabled because of `7572`.
The latter ticket is closed but `NavigationTriggerIT` still fails.

I'm going to refactor the test to disable its part which is failing in fusion.
The functionality should be fixed and restored. The test should be enabled after that.

### PR DESCRIPTION
**Pull request by platosha**
Fixes #10513

### CODE REVIEW

File: flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/NavigationTriggerIT.java [hunk 1]
```diff
@@ -87,7 +77,8 @@ public void testNavigationTriggers_back_forward() {
 
         findElement(By.id("rerouteButton")).click();
         assertMessageCount(7);
-        assertLastMessage("/", NavigationTrigger.PROGRAMMATIC, "rerouted");
+        assertLastMessage("/rerouted", NavigationTrigger.PROGRAMMATIC,
```
Comment (platosha) [inline flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/NavigationTriggerIT.java:80]: The new behaviour seems to be related with the feature https://github.com/vaadin/flow/pull/7608

Debugging revealed, that the `BeforeEvent` now contains pre-resolved `Location` with the URL parameters filled. So the location has `rerouted` in this case.

See https://github.com/vaadin/flow/blob/872bbf45429f1d617a56396c885d3fed8fbd426b/flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java#L703-L758

**Review by haijian-vaadin — APPROVED** [review]
