### PR TITLE
fix: Using a custom RouteRegistry

### LINKED ISSUE #11022: Not possible to extend AbstractRouteRegistry from Vaadin 14.5 onwards
If you want to implement your own routing, one needs to have CustomRouteRegistry extending AbstractRouteRegistry. 

In Vaadin 14.5 and newer versions this will require implementing

public NavigationRouteTarget getNavigationRouteTarget ( String url )
public RouteTarget getRouteTarget ( Class<? extends Component> target, RouteParameters parameters ) 

This will not be straightforward because NavigationRouteTarget does not have a public constructor.

### PR DESCRIPTION
**Pull request by caalador**
## Description

Make it possible to create a custom
RouteRegistry and add test module for it.

Fixes #11022

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/ErrorRouteRegistry.java [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+
+import com.vaadin.flow.router.internal.ErrorTargetEntry;
+
+/**
+ * Interface class for RouteRegistries that can be used to request for error
+ * navigation views for Exceptions.
+ *
+ * @since
+ */
+public interface ErrorRouteRegistry extends Serializable {
```
Comment (pleku) [inline flow-server/src/main/java/com/vaadin/flow/server/ErrorRouteRegistry.java:30]: 🦆 So previously error views feature was only used if you had extended `ApplicationRouteRegistry` but not if you had extended `AbstractRouteRegistry`. So now you can use either since `ApplicationRouteRegistry` extends this interface and now any custom registry can decide itself whether or not enables those. 👍🏻 as this is not a behavior or API change. But if anyone had managed to extend `ApplicationRouteRegistry`, they just need to compile it again.

**Review by pleku — APPROVED** [review]
LGTM, but I'm just wondering if we could avoid the _yet another IT module_ and instead just trust that a "unit test" would be enough - as in if you can write the code, we can expect it to work. And basically just add code that checks the logic for the added parts (error route registry)

**Comment by caalador** [comment]
I feel that for this level of a feature the IT test module is justified as it needs to work on so many levels and be used in navigation etc. I wouldn't feel comfortable with only an it test as on that level we do test the usage with test registries that extend abstract registry.

**Comment by pleku** [comment]
Just noting that this is safe to be picked to 2.6 as even if it adds new API (interface) it actually fixes two bugs with this.

**Comment by pleku** [comment]
Maybe we don't have to pick this to `6.0` as `7.0` is not far away.
