### PR TITLE
fix: set the lock field to a fake lock for unbound session

### LINKED ISSUE #11569: NPE after live reload
In Vaadin 21.0.0.beta1, a session that was [deserializedAsEmpty](https://github.com/vaadin/flow/blob/8.0/flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java#L2175-L2183) (#11304) will be unbound. The `lock` however is transient, leading to the following NPE:
```
java.lang.NullPointerException: null
	at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:720) ~[flow-server-8.0.0.beta1.jar:8.0.0.beta1]
	at com.vaadin.flow.server.VaadinSession.valueUnbound(VaadinSession.java:221) ~[flow-server-8.0.0.beta1.jar:8.0.0.beta1]
	at org.apache.catalina.session.StandardSession.removeAttributeInternal(StandardSession.java:1831) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.session.StandardSession.removeAttribute(StandardSession.java:1317) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.session.StandardSession.removeAttribute(StandardSession.java:1289) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.session.StandardSessionFacade.removeAttribute(StandardSessionFacade.java:153) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at com.vaadin.flow.server.WrappedHttpSession.removeAttribute(WrappedHttpSession.java:126) ~[flow-server-8.0.0.beta1.jar:8.0.0.beta1]
	at com.vaadin.flow.server.VaadinService.readFromHttpSession(VaadinService.java:2169) ~[flow-server-8.0.0.beta1.jar:8.0.0.beta1]
```

Because of #11416
https://github.com/vaadin/flow/blob/32d648beb96fddb2cb811d45f655037b0cfec603/flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java#L220-L222

### PR DESCRIPTION
**Pull request by denis-anisimov**
fixes #11569

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java [hunk 1]
```diff
@@ -203,8 +203,8 @@ public void valueUnbound(HttpSessionBindingEvent event) {
         // the latter case the session field should be set to {@code null}
         // immediately to avoid using HTTP session object which is invalid (all
         // methods throw exceptions).
+        lock();
         try {
-            lock();
```
Comment (caalador) [inline flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java:207]: This change shouldn't be needed as it doesn't change anything apart from the exception message when the lock feature is broken so that both lock() and unlock() throw and unlock exception is shown instead of lock.

File: flow-server/src/test/java/com/vaadin/tests/server/SerializationTest.java [hunk 2]
```diff
@@ -7,18 +7,40 @@
...
+                session.getPendingAccessQueue());
+    }
+
+    public void testSerializeVaadinSession_notProductionMode_disableDevModeSerialization_deserializedSessionHasLockInstance()
+            throws Exception {
+        VaadinSession session = mockSession(false);
+
+        session = serializeAndDeserialize(session);
+
+        assertNotNull(session.getLockInstance());
```
Comment (caalador) [inline flow-server/src/test/java/com/vaadin/tests/server/SerializationTest.java:37]: Could have failure message `"Lock should be available after empty deserialization"` or something to make the possible failure clearer

**Review by caalador — CHANGES_REQUESTED** [review]
Else seems fine.

File: flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java (hunk 1 above)
Comment (denis-anisimov) [reply flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java:207]: This is indeed not needed :
- in the perfect world 
- this PR

So when everything works as expected this change doesn't do anything.
But the reason is the exactly what you said: when/if `lock|()` throws an exception then code goes into `finally` and then 
it's a mixture of additional unexpected things like this issue (when `checkLock` doesn't throw anything then there is another `finally` ) and you get an exception which you can't understand how it happen...
This is exactly what happened here: NPE is thrown but it looks extremely weird since there were many places above where different NPE or ISE should have been thrown.
And I spent significant (far away from a few minutes) to understand how it's possible : why the NPE is thrown _only_ inside `unlock`.

This change doesn't do anything if everything works as expected.
But it will throw a proper exception earlier (before `finally`) when something is broken. And the resulting exception will be the proper exception.
So if in the next time someone accidentally break the code via having a `null` for a lock instance then the exception will be thrown immediately.

As a result : `lock` may not throw an exception. If it throws then it should be outside of `try` since this is not recoverable exception anyhow and it's better to see the exact place/line when the exception is thrown instead decoding the exception which is not a cause but a consequence.

File: flow-server/src/test/java/com/vaadin/tests/server/SerializationTest.java (hunk 2 above)
Comment (denis-anisimov) [reply flow-server/src/test/java/com/vaadin/tests/server/SerializationTest.java]: done

**Review by caalador — APPROVED** [review]
