### PR TITLE
fix: no serverSideRoutes check if no Routes

### LINKED ISSUE #18539: Hilla applications without any Flow routes shouldn't require server side routes entry
### Description of the bug

With Vaadin 24.4.0.alpha Hilla applications without Flow views require server side routes in `routes.tsx` at start-up, which doesn't make much sense:

```
To have working Flow routes add the following to the 'routes.tsx' file:
            - import { serverSideRoutes } from "Frontend/generated/flow/Flow";
            - route '...serverSideRoutes' into the routes definition as shown below:
```

A workaround is to add this entry as it suggests.

### Expected behavior

Flow should show this message only when Flow views/routes are actually present in the project.

### Minimal reproducible example

Can be reproduced with Hilla [integration test](https://github.com/vaadin/hilla/tree/main/packages/java/tests/gradle/single-module) or with [hybrid app](https://github.com/vaadin/flow-hilla-hybrid-example) by removing all Flow views and removing `serverSideRoutes` entry.

### Versions

- Vaadin / Flow version: 24.4.0.alpha2

### PR DESCRIPTION
**Pull request by caalador**
Do not check for the
serverSideRoutes in
routes.tsx in react mode
if no `@Route` annotated
Flow routes found.

Fixes #18539

### CODE REVIEW

**Comment by mshabarov** [comment]
Is this fixes https://github.com/vaadin/flow/issues/18539  ?

**Comment by caalador** [comment]
yes

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java [hunk 1]
```diff
@@ -93,6 +95,7 @@ public class TaskGenerateReactFiles implements FallibleCommand {
      *            the task options
      */
     TaskGenerateReactFiles(Options options) {
+        this.options = options;
         this.frontendDirectory = options.getFrontendDirectory();
```
Comment (mshabarov) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java:99]: `this.frontendDirectory = options.getFrontendDirectory();` now can be removed as you have class field `options` and can access any parameter.

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java [hunk 2]
```diff
@@ -116,7 +119,9 @@ public void execute() throws ExecutionFailedException {
                         UTF_8);
                 Pattern serverImport = Pattern.compile(
                         "import[\\s\\S]?\\{[\\s\\S]?serverSideRoutes[\\s\\S]?\\}[\\s\\S]?from[\\s\\S]?(\"|'|`)Frontend\\/generated\\/flow\\/Flow\\1;");
-                if (!serverImport.matcher(routesContent).find()) {
+                if (!serverImport.matcher(routesContent).find()
+                        && !options.getClassFinder()
+                                .getAnnotatedClasses(Route.class).isEmpty()) {
```
Comment (mshabarov) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java:124]: I suggest to simplify this if clause for better readability, e.g.:

```java
if (hasServerRoutes() && missingServerImport()) {
  // existing codes
}

private boolean hasServerRoutes(//params) {
return !options.getClassFinder()
                                .getAnnotatedClasses(Route.class).isEmpty()
}

private boolean missingServerImport(//params) {
return !serverImport.matcher(routesContent).find();
}
```

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java [hunk 3]
```diff
@@ -131,6 +138,9 @@ public void routesMissingImport_expectionThrown() throws IOException {
 
         FileUtils.write(routesTsx, content, StandardCharsets.UTF_8);
 
+        Mockito.when(classFinder.getAnnotatedClasses(Route.class)).thenReturn(
+                Collections.singleton(TaskGenerateReactFilesTest.class));
```
Comment (mshabarov) [inline flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java:142]: This also needs a test that checks that Flow doesn't throw if import is missing and no Flow routes.

Comment (mshabarov) [inline flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java:142]: `TaskGenerateReactFilesTest` is better to replace to e.g. `DummyRoute` private class.

**Review by mshabarov — CHANGES_REQUESTED** [review]

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java (hunk 1 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java]: Moved

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java (hunk 2 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java]: methodised

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java (hunk 3 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java]: added

Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java]: done

**Review by mshabarov — APPROVED** [review]
