### PR TITLE
fix: Log exception for closed socket

### LINKED ISSUE #12646: IOException - Broken Pipe
### Description of the bug

I found many "broken pipe" errors in my logfile:

```
2021-12-28 08:05:03,544 ERROR | https-jsse-nio-18443-exec-16 | o.a.c.c.C.[Tomcat].[localhost].[/].[springServlet]      | Servlet.service() for servlet [springServlet] in context with path [] threw exception [com.vaadin.flow.server.ServiceException: org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe] with root cause
java.io.IOException: Broken pipe
        at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:62)
        at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:97)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:53)
        at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:532)
        at org.apache.tomcat.util.net.SecureNioChannel.flush(SecureNioChannel.java:124)
        at org.apache.tomcat.util.net.SecureNioChannel.write(SecureNioChannel.java:799)
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1373)
        at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:766)
        at org.apache.tomcat.util.net.SocketWrapperBase.writeBlocking(SocketWrapperBase.java:586)
        at org.apache.tomcat.util.net.SocketWrapperBase.write(SocketWrapperBase.java:530)
        at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.doWrite(Http11OutputBuffer.java:547)
        at org.apache.coyote.http11.filters.ChunkedOutputFilter.doWrite(ChunkedOutputFilter.java:112)
        at org.apache.coyote.http11.Http11OutputBuffer.doWrite(Http11OutputBuffer.java:194)
        at org.apache.coyote.Response.doWrite(Response.java:615)
        at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:340)
        at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:783)
        at org.apache.catalina.connector.OutputBuffer.append(OutputBuffer.java:688)
        at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:388)
        at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:366)
        at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:96)
        at org.springframework.security.web.util.OnCommittedResponseWrapper$SaveContextServletOutputStream.write(OnCommittedResponseWrapper.java:638)
        at com.vaadin.flow.server.StreamResource$Pipe.copy(StreamResource.java:95)
        at com.vaadin.flow.server.StreamResource$Pipe.accept(StreamResource.java:77)
        at com.vaadin.flow.server.communication.StreamResourceHandler.handleRequest(StreamResourceHandler.java:89)
        at com.vaadin.flow.server.communication.StreamRequestHandler.handleRequest(StreamRequestHandler.java:106)
        at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1565)
        at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:302)
        at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:109)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
....
```
                                                                                                                                                         
### Minimal reproducible example

Unfortunatley it is not possible for my to reproduce it. I find many of this errors in the logfile. I do not know when this is coming up. It never occured on my development environment. 

### Versions

- Vaadin / Flow version: 21.0.9
- Java version: 17.0.1
- OS version: CentOS 7.9

### PR DESCRIPTION
**Pull request by caalador**
Instead of throwing an exception if the
client has closed the stream socket, log a
message in debug mode.

Closes #12646

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java [hunk 1]
```diff
@@ -80,6 +82,13 @@ public void accept(OutputStream stream, VaadinSession session)
                 throws IOException {
             try (InputStream input = createInputStream(session)) {
                 copy(session, input, stream);
+            } catch (IOException ioe) {
+                if (!"Broken pipe".equals(ioe.getMessage())) {
```
Comment (Artur-) [inline flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java:86]: nit: This would be a little more readable if it was
```
if (theCase) {
  log
} else {
  throw ioe;
}
```

File: flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java [hunk 2]
```diff
@@ -80,6 +82,13 @@ public void accept(OutputStream stream, VaadinSession session)
...
+                    throw ioe;
+                }
+                LoggerFactory.getLogger(StreamResource.class).debug(
+                        "Broken pipe. Client has most likely cancelled link.",
```
Comment (Artur-) [inline flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java:90]: What does "cancelled link" mean? Should it be something like "The client browser has most likely cancelled the request"?

**Review by Artur- — CHANGES_REQUESTED** [review]

File: flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java (hunk 1 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java:86]: done

File: flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java (hunk 2 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java:90]: :+1: done

**Review by Artur- — APPROVED** [review]
