### PR TITLE
fix: consider local npm packages in bundle validation

### LINKED ISSUE #18106: Production bundle error when running Hilla tests
### Description of the bug

```
[INFO] --- hilla:2.5-SNAPSHOT:build-frontend (default) @ tests-spring-security-jwt ---
[INFO] Reflections took 425 ms to scan 143 urls, producing 9972 keys and 53191 values
[INFO] Scanning classes to find frontend configurations and dependencies...
[INFO] Visited 1000 classes. Took 347 ms.
[INFO] Checking if a production mode bundle build is needed
[ERROR] Error when checking if a production bundle build is needed
java.lang.NumberFormatException: 'file:../../../../ts/form' is not a valid version!
    at com.vaadin.flow.server.frontend.FrontendVersion.<init> (FrontendVersion.java:160)
    at com.vaadin.flow.server.frontend.FrontendVersion.<init> (FrontendVersion.java:128)
    at com.vaadin.flow.server.frontend.BundleValidationUtil.versionAccepted (BundleValidationUtil.java:452)
    at com.vaadin.flow.server.frontend.BundleValidationUtil.lambda$hashAndBundleModulesEqual$2 (BundleValidationUtil.java:434)
...
[INFO] Copying frontend resources from jar files ...
[INFO] Visited 143 resources. Took 38 ms.
[ERROR] Require bundle build due to missing 'config/needs-build' file.
[INFO] Running Vite ...
```

### Expected behavior

No errors

### Minimal reproducible example

https://github.com/vaadin/hilla/pull/1755

### Versions

- Vaadin / Flow version: 24.3.0.alpha
- Java version:
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

### PR DESCRIPTION
**Pull request by mcollovati**
## Description

If a project package.json contains references to local npm pacakges instead of parsable version, the bundle validation fails. This change update the version check in bundle validation to accept also local packages.
For those packages, a bundle re-creation is triggered only if the reference in package.json does not match the one in the stats.

Fixes #18106

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by mcollovati** [comment]
This patch prevents the version parsing exception.
However, currently, the bundle validation might not be able to detect if there are changes in the local package that will require a bundle rebuild.
Rebuild will be triggered if changed components from local packages are imported in fronted source, but not if they are referenced, for example, with `@JsModule` annotation.
This situation should be mitigated once #18365 will be fixed

**Comment by mshabarov** [comment]
I propose for now to go with the implemented solution.

IMO this is quite a rare case for pure Flow apps when development goes in local npm package (otherwise I beileve the hotdeploy mode should be used).
Upon changes in local package, one can `mvn clean` and delete `dev.bundle` file from `src/main/bundles` and he gets a re-bundling then. 

If we get a request to make this happen automatically, we can consider a more advanced solution.

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java [hunk 1]
```diff
@@ -449,8 +450,26 @@ public static boolean hashAndBundleModulesEqual(JsonObject statsJson,
...
+        } catch (NumberFormatException ex) {
+            actualVersion = null;
+        }
+
+        if (expectedVersion == null && actualVersion == null) {
+            return Objects.equals(expected, actual);
+        } else if (expectedVersion == null || actualVersion == null) {
+            // expected or actual version is referencing a local package
+            // while the other one is a parsable version
+            return false;
```
Comment (mshabarov) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java:471]: Are these cases covered with the existing logging? 
If not, they need an additional INFO or DEBUG logging telling why re-bundling is happening.

**Review by mshabarov — CHANGES_REQUESTED** [review]
Small loggin-related question, otherwise looks good.

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java (hunk 1 above)
Comment (mcollovati) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java:471]: Currently, it will log that the dependency has a wrong version in the bundle.
Adding a DEBUG level log that reports both version make sense to help in troubleshooting

Comment (mcollovati) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java]: added log

**Review by mshabarov — APPROVED** [review]
