### PR TITLE
fix: merge property descriptors when getter and setter come from different interfaces

### LINKED ISSUE #20814: Binder / BeanPropertySet does not find setter in nested interface
### Description of the bug

Binder / BeanPropertySet does not find setter in nested interface where Base interface has just the getters

### Expected behavior

Binder should find getter and setter

### Minimal reproducible example

class BeanPropertyTest {

	interface Base  {
		String getInfo();
	}

	interface MyTest extends Base  {
		void setInfo(String value);
	}

	interface MyTest2 extends Base  {

		@Override
		String getInfo();
		void setInfo(String value);

	}

	@Test
	void testBeanProperty1() {
		PropertySet<MyTest> userInfoPropertySet = BeanPropertySet.get(MyTest.class);

		Optional<PropertyDefinition<MyTest, ?>> infoProperty = userInfoPropertySet.getProperty("info");
		assertTrue(infoProperty.isPresent());
		assertNotNull(infoProperty.get().getGetter());
		assertTrue(infoProperty.get().getSetter().isPresent());
	}

	@Test
	void testBeanProperty2() {
		PropertySet<MyTest2> userInfoPropertySet = BeanPropertySet.get(MyTest2.class);

		Optional<PropertyDefinition<MyTest2, ?>> infoProperty = userInfoPropertySet.getProperty("info");
		assertTrue(infoProperty.isPresent());
		assertNotNull(infoProperty.get().getGetter());
		assertTrue(infoProperty.get().getSetter().isPresent());
	}

}

### Versions

- Vaadin / Flow version: 26.0.1
- Java version: 21
- OS version: Win 11

### PR DESCRIPTION
**Pull request by Artur-**
BeanUtil's dedup loop was replacing a read-only descriptor with a write-only one (or vice versa) instead of merging them. This caused BeanPropertySet to lose the getter when a parent interface provided it and a child interface provided the setter.

Fixes #20814

### CODE REVIEW

**Comment by mcollovati** [comment]
Would this also fix #20814?

File: flow-data/src/test/java/com/vaadin/flow/data/binder/BeanPropertySetTest.java [hunk 1]
```diff
@@ -467,6 +467,46 @@ public void setFirstName(String firstName) {
...
 
+    public interface Measurement {
+        double getValue();
+    }
+
+    public interface MutableMeasurement extends Measurement {
+        void setValue(double value);
+    }
+
+    public static class MeasurementBean implements MutableMeasurement {
```
Comment (mcollovati) [inline flow-data/src/test/java/com/vaadin/flow/data/binder/BeanPropertySetTest.java]: Is this class used anywhere? Or is it a test for it missing?

Comment (Artur-) [reply flow-data/src/test/java/com/vaadin/flow/data/binder/BeanPropertySetTest.java]: removed

**Comment by Artur-** [comment]
> Would this also fix #20814?

Seems to do that, added the test from there
