### PR TITLE
fix: return immidiately if VaadinSession is not initialized

### LINKED ISSUE #11961: NPE Exception in Development Mode on Startup (Random)
### Description of the bug / feature

We sometimes get the following exception, just randomly after re-starting a spring boot application with Vaadin 21.x

```log
2021-10-01 11:35:35.604 ERROR 693647 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost]           : Exception Processing /

java.lang.NullPointerException: null
	at com.vaadin.flow.server.VaadinSession.lock(VaadinSession.java:685)
	at com.vaadin.flow.server.VaadinSession.valueUnbound(VaadinSession.java:212)
	at org.apache.catalina.session.StandardSession.removeAttributeInternal(StandardSession.java:1860)
	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:861)
	at org.apache.catalina.session.StandardSession.isValid(StandardSession.java:660)
	at org.apache.catalina.connector.Request.doGetSession(Request.java:3034)
	at org.apache.catalina.connector.Request.getSessionInternal(Request.java:2747)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:512)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

### Versions:
    - Vaadin / Flow version: 21.0.2
    - Java version: 8/11
    - OS version: Ubuntu
    - Browser version (if applicable): Firefox
    - Application Server (if applicable): Tomcat
    - IDE (if applicable): IDEA

### PR DESCRIPTION
**Pull request by denis-anisimov**
fixes #11961

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java [hunk 1]
```diff
@@ -1098,4 +1109,20 @@ public StreamResourceRegistry getResourceRegistry() {
...
+     * The session is initialized if
+     * {@link #refreshTransients(WrappedSession, VaadinService)} has been called
+     * for it. If the session is just created or deserialized but not yet in
+     * real use then it's not initialized and it's state is incomplete.
+     * 
+     * @return whether the session is initialized
+     */
+    private boolean isInitialized() {
+        boolean isInitialized = service != null;
+        assert isInitialized || session == null;
```
Comment (caalador) [inline flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java:1124]: What is the assertion expectation, could have a failure message for clarity on the expectation.

**Review by caalador — CHANGES_REQUESTED** [review]

File: flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java (hunk 1 above)
Comment (denis-anisimov) [reply flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java]: For the record: this is minor self-check assertion and any assertions are internal for Flow developers since users doesn't enable assertions during run. The message doesn't say (and can't say) anything which can't be seen from the code that's why I've not added it.

But let it be.

**Review by caalador — APPROVED** [review]

File: flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java (hunk 1 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java]: I know, but the issue is that if it fails in a build then it's much better to see what failed and not need to go to the code to seek for an answer when there is only an assert failed message.
