### PR TITLE
fix: Allow Gradle builds to use custom sourcesets

### LINKED ISSUE #15738: Gradle build fails if specifying productionMode=true when using a custom sourceset
### Description of the bug

When running a Gradle build with `productionMode = true`, if the Vaadin dependencies are not specified against the `main`  sourceset (e.g. an additional sourceset named `ui` is created and the dependencies listed against `uiImplementation`), or the classes that use Vaadin components are not in the `main` sourceset then the build fails with Vite reporting that dependencies could not be found, e.g.

```
Execution failed for task ':vaadinBuildFrontend'.
> Vite process exited with non-zero exit code.
  Stderr: '[36mvite v4.0.2 [32mbuilding for production...[36m[39m
  transforming...
  Use of eval in "frontend/generated/jar-resources/FlowClient.js" is strongly discouraged as it poses security risks and may cause issues with minification.
  Use of eval in "frontend/generated/jar-resources/FlowClient.js" is strongly discouraged as it poses security risks and may cause issues with minification.
  [32m?[39m 37 modules transformed.
  rendering chunks...
  computing gzip size...
  [2m../build/resources/main/META-INF/VAADIN/webapp/[22m[32mindex.html                                                [39m[1m[2m  0.60 kB[22m[1m[22m
  [2m../build/resources/main/META-INF/VAADIN/webapp/[22m[2mVAADIN/build/[22m[36mgenerated-flow-imports-fallback-e5b0ae68.js  [39m[1m[2m  0.19 kB[22m[1m[22m[2m ? gzip:  0.17 kB[22m
  [2m../build/resources/main/META-INF/VAADIN/webapp/[22m[2mVAADIN/build/[22m[36mgenerated-flow-imports-fc2941af.js           [39m[1m[2m  0.83 kB[22m[1m[22m[2m ? gzip:  0.49 kB[22m
  [2m../build/resources/main/META-INF/VAADIN/webapp/[22m[2mVAADIN/build/[22m[36mFlowBootstrap-feff2646.js                    [39m[1m[2m  3.42 kB[22m[1m[22m[2m ? gzip:  1.45 kB[22m
  [2m../build/resources/main/META-INF/VAADIN/webapp/[22m[2mVAADIN/build/[22m[36mindexhtml-fb749209.js                        [39m[1m[2m 59.60 kB[22m[1m[22m[2m ? gzip: 19.52 kB[22m
  [2m../build/resources/main/META-INF/VAADIN/webapp/[22m[2mVAADIN/build/[22m[36mFlowClient-984d8da1.js                       [39m[1m[2m147.31 kB[22m[1m[22m[2m ? gzip: 49.31 kB[22m
  frontend/generated/jar-resources/lumo-includes.ts(1,23): error TS2307: Cannot find module '@vaadin/vaadin-lumo-styles/color.js' or its corresponding type declarations.
  frontend/generated/jar-resources/lumo-includes.ts(2,28): error TS2307: Cannot find module '@vaadin/vaadin-lumo-styles/typography.js' or its corresponding type declarations.
  frontend/generated/jar-resources/material-includes.ts(1,28): error TS2307: Cannot find module '@vaadin/vaadin-material-styles' or its corresponding type declarations.
  frontend/generated/jar-resources/material-includes.ts(2,28): error TS2307: Cannot find module '@vaadin/vaadin-material-styles' or its corresponding type declarations.
  frontend/generated/jar-resources/tooltip.ts(1,25): error TS2307: Cannot find module '@vaadin/tooltip' or its corresponding type declarations.
  '
```

### Expected behavior

The `vaadinPrepareFrontend` task should successfully copy supporting Javascript assets detected for components in the non-main sourceset into the `frontend/generated/jar-resources/` directory, and the `vaadinBuildFrontend` task should successfully complete, producing a valid JAR that contains a working Vaadin distribution.

### Minimal reproducible example

Create a Gradle project with the following contents:

* build.gradle
```gradle
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.0.0'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'com.vaadin' version '23.3.4'
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://maven.vaadin.com/vaadin-prereleases' }
    maven { url 'https://repo.spring.io/milestone' }
}

sourceSets {
    ui {
        java
    }
    main {
        java {
            compileClasspath += ui.output
            runtimeClasspath += ui.output + ui.runtimeClasspath
        }
    }
}

vaadin {
    productionMode = true
}

dependencies {
    uiImplementation('com.vaadin:vaadin-spring-boot-starter')
    implementation('org.springframework.boot:spring-boot-starter-web')
}

dependencyManagement {
    uiImplementation {
        imports {
            mavenBom "com.vaadin:vaadin-bom:23.3.4"
        }
    }
}

jar {
    enabled = false
}
```

* src/main/java/com/example/demo/DemoApplication.java
```java
package com.example.demo;
            
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

}
```

* src/ui/java/com/example/demo/AppShell.java
```java
package com.example.demo;
            
import com.vaadin.flow.component.page.AppShellConfigurator;
import com.vaadin.flow.server.PWA;

@PWA(name = "Demo application", shortName = "Demo")
public class AppShell implements AppShellConfigurator {
}
```

Run `gradle build`

### Versions

- Vaadin / Flow version: 23.3.4
- Java version: 17.0.4.1 Corretto
- OS version: Windows 10 (although not OS specific)
- Browser version (if applicable): n/a
- Application Server (if applicable): n/a
- IDE (if applicable): n/a

### PR DESCRIPTION
**Pull request by mc1arke**
## Description

When a sourceset other than `main` is used for holding classes using Vaadin components, or for providing a resolution scope for Vaadin dependencies, the `prepareVaadinFrontend` task does not correctly extract the correct Node libraries required by those classes, and the `buildVaadinFrontend` task subsequently fails to complete due to Vite requiring those Node dependencies to have been extracted into the project so failing to find all of its front-end dependencies.

The `VaadinFlowPluginExtension` is being altered to include a `sourceSetName` field, that defaults to `main` for backwards compatibility but allows users to specify a custom sourceset to use for the prepare and build tasks. As the use of a custom sourceset generally implies that different Gradle tasks will be executed for operating on those sourcesets, and a different dependency scope generated for the custom sourceset, fields have also been added to the extension that allow users to override the values the plugin uses, whilst the default values follow the Gradle conventions for both `main` and non-`main` sourcesets.

Fixes #15738

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

File: flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt [hunk 1]
```diff
@@ -532,4 +532,107 @@ class MiscSingleModuleTest : AbstractGradleTest() {
...
+                id 'org.springframework.boot' version '3.0.0'
+                id 'io.spring.dependency-management' version '1.0.11.RELEASE'
+                id("com.vaadin")
+            }
+            
+            repositories {
+                mavenLocal()
+                mavenCentral()
+                maven { url 'https://maven.vaadin.com/vaadin-prereleases' }
+                maven { url 'https://repo.spring.io/milestone' }
```
Comment (mcollovati) [inline flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt:561]: Is this repo really needed? Validation build is failing because of certificate verification.

**Review by mcollovati — CHANGES_REQUESTED** [review]

File: flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt (hunk 1 above)
Comment (mc1arke) [reply flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt]: Removed. The Spring plugins are in Maven Central so a direct mirror isn't required.

File: flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt [hunk 2]
```diff
@@ -532,4 +532,106 @@ class MiscSingleModuleTest : AbstractGradleTest() {
...
+                }
+            }
+            
+            vaadin {
+                productionMode = true
+                sourceSetName = 'ui'
+            }
+            
+            dependencies {
+                uiImplementation('com.vaadin:vaadin-spring-boot-starter')
```
Comment (mcollovati) [inline flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt:581]: This dependency needs the platform BOM, and we should not use it. 
Do we really need it for the test?
Can't we use an artifact produced by current build (e.g `com.vaadin:flow:$flowVersion`)

**Review by mcollovati — CHANGES_REQUESTED** [review]

**Review by mcollovati — APPROVED** [review]
LGTM
As a follow-up, we need to update [documentation](https://vaadin.com/docs/latest/guide/start/gradle/#all-options) adding the configuration properties introduced by this change
