### PR TITLE
fix: remove Lazy annotation from Flow security beans

### LINKED ISSUE #18458: spring-security breaks Vaadin session serialization
### Description of the bug

Given a minimal Vaadin starter project, adding and configuring spring-security as documented here https://vaadin.com/docs/latest/security/enabling-security makes the Vaadin session no longer serializable.

### Expected behavior

The Vaadin session should stay serializable.

### Minimal reproducible example

Start the attached project, navigating to localhost:8080 already produces the serialization exception.

```
org.springframework.context.annotation.ContextAnnotationAutowireCandidateResolver$1
	Start Track ID: 140, Stack depth: 17. Reference stack: 
		- field (class "org.springframework.aop.framework.AdvisedSupport", name: "targetSource", type: "interface org.springframework.aop.TargetSource")
		- object (class "org.springframework.aop.framework.ProxyFactory", org.springframework.aop.framework.ProxyFactory: 0 interfaces []; 0 advisors []; targetSource [org.springframework.context.annotation.ContextAnnotationAutowireCandidateResolver$1@2263eb]; proxyTargetClass=false; optimize=false; opaque=false; exposeProxy=false; frozen=false)
		- field (class "org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor", name: "advised", type: "class org.springframework.aop.framework.AdvisedSupport")
		- object (class "org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor", org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor@e42bae4)
		- field (class "com.vaadin.flow.server.auth.AccessAnnotationChecker$$SpringCGLIB$$0", name: "CGLIB$CALLBACK_0", type: "interface org.springframework.cglib.proxy.MethodInterceptor")
		- object (class "com.vaadin.flow.server.auth.AccessAnnotationChecker$$SpringCGLIB$$0", com.vaadin.flow.server.auth.AccessAnnotationChecker@17c5e11)
		- field (class "com.vaadin.flow.server.auth.AnnotatedViewAccessChecker", name: "accessAnnotationChecker", type: "class com.vaadin.flow.server.auth.AccessAnnotationChecker")
		- object (class "com.vaadin.flow.server.auth.AnnotatedViewAccessChecker", com.vaadin.flow.server.auth.AnnotatedViewAccessChecker@1764e45e)
		- custom writeObject data (class "java.util.CollSer")
		- object (class "java.util.CollSer", java.util.CollSer@79aa49f5)
		- field (class "com.vaadin.flow.server.auth.NavigationAccessControl", name: "checkerList", type: "interface java.util.List")
		- object (class "com.vaadin.flow.spring.security.SpringNavigationAccessControl", com.vaadin.flow.spring.security.SpringNavigationAccessControl@46aea580)
		- custom writeObject data (class "java.util.ArrayList")
		- object (class "java.util.ArrayList", [com.vaadin.flow.spring.security.SpringNavigationAccessControl@46aea580, com.vaadin.flow.spring.scopes.VaadinRouteScope$NavigationListener@5fa5da25])
		- element of array (index: 0)
		- array (class "[Ljava.lang.Object;", size: 2)
		- field (class "java.lang.invoke.SerializedLambda", name: "capturedArgs", type: "class [Ljava.lang.Object;")
		- object (class "java.lang.invoke.SerializedLambda", SerializedLambda[capturingClass=class com.vaadin.flow.component.internal.UIInternals, functionalInterfaceMethod=com/vaadin/flow/shared/Registration.remove:()V, implementation=invokeStatic com/vaadin/flow/component/internal/UIInternals.lambda$addListener$3630f8ab$1:(Ljava/util/List;Ljava/lang/Object;)V, instantiatedMethodType=()V, numCaptured=2])
		- field (class "com.vaadin.flow.spring.scopes.VaadinRouteScope$NavigationListener", name: "beforeEnterListener", type: "interface com.vaadin.flow.shared.Registration")
		- object (class "com.vaadin.flow.spring.scopes.VaadinRouteScope$NavigationListener", com.vaadin.flow.spring.scopes.VaadinRouteScope$NavigationListener@5fa5da25)
		- custom writeObject data (class "java.util.HashMap")
		- object (class "java.util.HashMap", {com.vaadin.flow.spring.scopes.VaadinRouteScope$NavigationListener=com.vaadin.flow.spring.scopes.VaadinRouteScope$NavigationListener@5fa5da25})
		- field (class "com.vaadin.flow.server.Attributes", name: "attributes", type: "class java.util.HashMap")
		- object (class "com.vaadin.flow.server.Attributes", com.vaadin.flow.server.Attributes@799ab9a)
		- field (class "com.vaadin.flow.component.Component", name: "attributes", type: "class com.vaadin.flow.server.Attributes")
		- object (class "com.vaadin.flow.component.UI", com.vaadin.flow.component.UI@66d3dee8)
		- custom writeObject data (class "java.util.HashMap")
		- object (class "java.util.HashMap", {0=com.vaadin.flow.component.UI@66d3dee8})
		- custom writeObject data (class "com.vaadin.flow.server.VaadinSession")
		- object (class "com.vaadin.flow.spring.SpringVaadinSession", com.vaadin.flow.spring.SpringVaadinSession@3c4721dd)
		- custom writeObject data (class "java.util.HashMap")
		- root object (class "java.util.HashMap", {com.vaadin.flow.server.VaadinSession.springServlet=com.vaadin.flow.spring.SpringVaadinSession@3c4721dd, springServlet.lock=java.util.concurrent.locks.ReentrantLock@64617a3a[Unlocked], org.springframework.security.web.csrf.HttpSessionCsrfTokenRepository.CSRF_TOKEN=org.springframework.security.web.csrf.DefaultCsrfToken@7e593620, clusterKey=249d6e06-c49f-46f8-8bec-a8c5aa7362c4_SOURCE:F3FF33B25DF4AC58D816C327D0D1B344, SPRING_SECURITY_SAVED_REQUEST=DefaultSavedRequest [http://localhost:8080/?continue]})
	End Track ID: 140
```

### Versions

Reproduced on Vaadin 24.3.2, jdk17, spring-boot 3.2.1 . See attached minmal project

### PR DESCRIPTION
**Pull request by mcollovati**
## Description

For parameters with Lazy annotation, Spring generates a not-serializable proxy. Since some security beans are used inside Flow listeners, they should be fully serializable (or defined transient, if possible).
This change removes the unnecessary Lazy annotaions, moving the lazy evaluation to VaadinWebSecurity.

Fixes #18458

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java [hunk 1]
```diff
@@ -119,7 +119,7 @@ NavigationAccessControlConfigurer navigationAccessControlConfigurerCustomizer()
      */
     @Bean
     public AnnotatedViewAccessChecker annotatedViewAccessChecker(
-            @Lazy AccessAnnotationChecker accessAnnotationChecker) {
+            AccessAnnotationChecker accessAnnotationChecker) {
```
Comment (knoobie) [inline vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java:122]: Would it also make sense to add `proxyBeanMethods=false` to the `@Configuration` so that all beans in that class aren't proxied? This would also ensure this isn't reintroduced by accident.

File: vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringSecurityAutoConfigurationTest.java [hunk 2]
```diff
@@ -16,10 +16,16 @@
 
 package com.vaadin.flow.spring;
 
+import java.io.ByteArrayInputStream;
+import java.io.ByteArrayOutputStream;
+import java.io.IOException;
```
Comment (czp13) [inline vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringSecurityAutoConfigurationTest.java:21]: probably this is a leftover import (seems we are not using it):
```suggestion
```

File: vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringSecurityAutoConfigurationTest.java [hunk 3]
```diff
@@ -151,11 +182,27 @@ private static void assertThatCustomNavigationAccessCheckerIsUsed(
         Mockito.verify(navigationContext, Mockito.never()).neutral();
     }
 
+    private <T> void assertObjectIsSerializable(T instance) {
+        Object deserialized = Assertions.assertDoesNotThrow(() -> {
+            ByteArrayOutputStream bs = new ByteArrayOutputStream();
+            ObjectOutputStream out = new ObjectOutputStream(bs);
```
Comment (czp13) [inline vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringSecurityAutoConfigurationTest.java:188]: Intellij like this version better:
```suggestion
            try (ObjectOutputStream out = new ObjectOutputStream(bs)) {
                out.writeObject(instance);
            }
```

Maybe we could use it.

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java (hunk 1 above)
Comment (mcollovati) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java:122]: If I recall correctly, `proxyBeanMethods=false` prevents the configuration class to be proxied, not the exposed beans.
Anyway, it makes sense to set that flag, since we have no direct method calls in `SpringSecurityAutoConfiguration`

**Review by czp13 — DISMISSED** [review]
Thank you for the changes! 🙇 I believe most issues have been addressed, with only a minor code modification suggested. It's a very small change, so I am marking this as approved.

File: vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringSecurityAutoConfigurationTest.java (hunk 3 above)
Comment (mcollovati) [reply vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringSecurityAutoConfigurationTest.java]: done

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java (hunk 1 above)
Comment (knoobie) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java:122]: I had the same assumption in the past :) until I've read the javadocs of the flag:

> Specify whether @Bean methods should get proxied in order to enforce bean lifecycle behavior, e.g. to return shared singleton bean instances even in case of direct @Bean method calls in user code. This feature requires method interception, implemented through a runtime-generated CGLIB subclass which comes with limitations such as the configuration class and its methods not being allowed to declare final.

Comment (mcollovati) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java:122]: I read it as "configuration class is proxied so that bean methods will always return the same instance when called by other methods of the class". My understanding is that when, for example, you call `annotatedViewAccessChecker()` from another method inside the `SpringSecurityAutoConfiguration` class, it creates the instance at the first call, and subsequent invocation will return that one instead of a new instance how it would happen if the configuration class is not proxied.
So, `SpringSecurityAutoConfiguration` methods are proxied, but not their return value.
But I may be wrong. I'll double-check it

Comment (knoobie) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java:122]: Good thing to double check! I only remember an old issue where boot also switched all their configuration to false by default, also to increase performance: https://github.com/spring-projects/spring-boot/issues/9068

Comment (knoobie) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java:122]: Before this is blocked: don't worry about it and do it later :)

Comment (mcollovati) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java:122]: I added the flag anyway, since it completely makes sense to avoid proxying in this case.
Thanks for pointing out :+1:

File: vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringSecurityAutoConfigurationTest.java (hunk 3 above)
Comment (czp13) [reply vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringSecurityAutoConfigurationTest.java]: Thanks, Marco!

**Review by czp13 — APPROVED** [review]

**Review by tltv — APPROVED** [review]
