### PR TITLE
fix: reset HTTP session on CLOSED state, not immidiately

### LINKED ISSUE #6959: Cannot invalidate HTTP session from SessionDestroyListener
In #6763 it's suggested that HttpSession can be invalidated from Vaadin SessionDestroyListener, however, when the listener is executed the wrapped session is null.

- Expected behavior:
  I should be able to invalidate the HttpSession after some period of inactivity.
- Actual behavior
  The HttpSession is not available after the Vaadin session has been destroyed.

Vaadin 14.0.11

[Example application](https://github.com/vaadin/flow/files/3851644/v14.zip)

The SessionDestroyListener is:
```
	public void serviceInit(ServiceInitEvent event) {
		event.getSource().addSessionDestroyListener(ev->{
			System.out.println("Vaadin session destroyed");
			VaadinSession vsession = ev.getSession();
			WrappedSession wsession = vsession.getSession();
			if (wsession==null) {
				System.out.println("wrapped session is null");
			} else {
				wsession.invalidate();
			}
		});
	}
```

### PR DESCRIPTION
**Pull request by denis-anisimov**
fixes #6959

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java [hunk 1]
```diff
@@ -376,4 +376,55 @@ public void csrfToken_same_session_shouldBeSame() {
...
+            protected Lock getSessionLock(WrappedSession wrappedSession) {
+                return lock;
+            }
+        };
+
+        VaadinSession vaadinSession = new VaadinSession(mockService);
+        WrappedSession httpSession = Mockito.mock(WrappedSession.class);
+        vaadinSession.refreshTransients(httpSession, mockService);
+
+        vaadinSession.setState(VaadinSessionState.CLOSING);
```
Comment (pleku) [inline flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java:425]: The code from the `VaadinService` calls `vaadinSession.close();` instead of using the setter, but I think the end outcome is the same anyway in regards of this test

**Review by pleku — APPROVED** [review]
