### PR TITLE
fix: pin platform trans. deps with npm CP: #10864

### LINKED ISSUE #10572: [V20] Duplicate Lumo version when using npm
### Description of the bug / feature

When using npm for Vaadin 20, some transitive dependencies are not locked (in particular, `vaadin-overlay`).
This causes duplicates as soon as a newer alpha of the web components is released from the monorepo.

### Minimal reproducible example

Here is how to reproduce the issue:

1. download a V20 project from start.vaadin.com
2. update version in `pom.xml` to 20.0.0.alpha5
3. run with `mvn spring-boot:run`
4. add `vaadin.pnpm.enable = false`
5. run `rm -rf node_modules target`
6. run with `mvn spring-boot:run`

```
Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-lumo-styles" has already been used with this registry
    at eval (webpack-internal:///../node_modules/@vaadin/vaadin-overlay/node_modules/@vaadin/vaadin-lumo-styles/version.js:14:16)
    at Module.../node_modules/@vaadin/vaadin-overlay/node_modules/@vaadin/vaadin-lumo-styles/version.js (http://localhost:8080/VAADIN/build/vaadin-0-c4994e564f66ab02f796.cache.js:3549:1)
    at __webpack_require__ (http://localhost:8080/VAADIN/build/vaadin-bundle-1882670d596991653229.cache.js:64:30)
    at eval (webpack-internal:///../node_modules/@vaadin/vaadin-overlay/node_modules/@vaadin/vaadin-lumo-styles/color.js:6:69)
    at Module.../node_modules/@vaadin/vaadin-overlay/node_modules/@vaadin/vaadin-lumo-styles/color.js (http://localhost:8080/VAADIN/build/vaadin-0-c4994e564f66ab02f796.cache.js:3489:1)
    at __webpack_require__ (http://localhost:8080/VAADIN/build/vaadin-bundle-1882670d596991653229.cache.js:64:30)
    at eval (webpack-internal:///../node_modules/@vaadin/vaadin-overlay/node_modules/@vaadin/vaadin-lumo-styles/mixins/overlay.js:4:67)
    at Module.../node_modules/@vaadin/vaadin-overlay/node_modules/@vaadin/vaadin-lumo-styles/mixins/overlay.js (http://localhost:8080/VAADIN/build/vaadin-0-c4994e564f66ab02f796.cache.js:3501:1)
    at __webpack_require__ (http://localhost:8080/VAADIN/build/vaadin-bundle-1882670d596991653229.cache.js:64:30)
    at eval (webpack-internal:///../node_modules/@vaadin/vaadin-overlay/theme/lumo/vaadin-overlay-styles.js:3:102)```
```

### Expected behavior

All the Vaadin components should use the consistent version (in this case `20.0.0-alpha2`)

### Actual behavior

Pinned components use a fixed version (e.g. `20.0.0-alpha2`) but their transitive dependencies might use newer versions when available (e.g. `20.0.0-alpha3`) causing duplicates and conflicts.

### Versions:

- Vaadin / Flow version: 20.0.0.alpha5 / Flow 7 alpha

### PR DESCRIPTION
**Pull request by pleku**
Uses the same vaadin_versions.json file based pinning as with pnpm.
In case the application has @NpmPackage annotation with a certain version,
then that is used over the platform pinned version. When that is older,
a warning is logged (like with pnpm).
In case a dependency has been pinned directly in package.json, then that
is used over the platform pinned version. When that is older, a warning
is logged (like with pnpm).

Fixes #10572

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java [hunk 1]
```diff
@@ -197,6 +233,8 @@ JsonObject getPackageJson() throws IOException {
             packageJson = Json.createObject();
             packageJson.put(DEP_NAME_KEY, DEP_NAME_DEFAULT);
             packageJson.put(DEP_LICENSE_KEY, DEP_LICENSE_DEFAULT);
+            packageJson.put(DEPENDENCIES, Json.createObject());
+            packageJson.put(DEV_DEPENDENCIES, Json.createObject());
```
Comment (caalador) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java:237]: This isn't needed as there is the `addDefaultObjects(packageJson)` right after this `if` clause.
There were other cases that were missing the default objects so they are checked each time.

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java [hunk 2]
```diff
@@ -52,14 +56,25 @@
...
+
     @Rule
     public TemporaryFolder temporaryFolder = new TemporaryFolder();
 
     private File npmFolder;
 
     private ClassFinder finder;
 
+    private Logger logger = Mockito
+            .spy(LoggerFactory.getLogger(NodeUpdater.class));
```
Comment (caalador) [inline flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java:75]: logger that is not used anywhere?

**Review by caalador — CHANGES_REQUESTED** [review]

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java (hunk 1 above)
Comment (pleku) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java]: done

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java (hunk 2 above)
Comment (pleku) [reply flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java]: Done

**Review by caalador — APPROVED** [review]
