### PR TITLE
fix: require Safari 14 minimum

### LINKED ISSUE #13271: Vaadin 22: Safari 13 should be detected as too old
### Description of the bug

Open https://start.vaadin.com/app on Safari 13. 
The app will appear, but doesn't work properly (there is a lot of js errors on the browser console):

image

### Expected behavior

Safari 13 should be checked to be too old in Vaadin "browser to old" handler.

### Minimal reproducible example

Just open https://start.vaadin.com/app on Safari 13. 

### Versions

- Vaadin / Flow version: 22.0.8
- OS version: macOS
- Browser version (if applicable):  Safari 13

### PR DESCRIPTION
**Pull request by joheriks**
Safari 13 does not support the EventTarget constructor,
used in @vaadin/components-base:
https://caniuse.com/?search=EventTarget()

Fixes #13271

### CODE REVIEW

**Review by caalador — DISMISSED** [review]

File: flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java [hunk 1]
```diff
@@ -606,8 +606,8 @@ public boolean isTooOldToFunctionProperly() {
         if (isEdge() && getBrowserMajorVersion() < 79) {
             return true;
         }
-        // Safari 13+
-        if (isSafari() && getBrowserMajorVersion() < 13) {
+        // Safari 14+
+        if (isSafari() && getBrowserMajorVersion() < 14) {
             if (getOperatingSystemMajorVersion() > 14) {
```
Comment (Artur-) [inline flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java:611]: What is the os check about?

Comment (joheriks) [reply flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java:611]: Looks like a fix to allow any Safari for iPhone: https://github.com/vaadin/flow/issues/11654
But without additional checks if seems we may be setting up for a regression once macOS hits 15...

Comment (Artur-) [reply flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java:611]: But why would any safari on iPhone work?

Comment (Artur-) [reply flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java:611]: Ah, I see... bugs and bugs

**Review by caalador — APPROVED** [review]
