### PR TITLE
fix: reset loading indicator state after each request

### LINKED ISSUE #23223: Loading indicator stays visible if you do many subsequent requests
### Description of the bug

If I e.g. send the cursor position to the server with a small delay, the loading indicator stays visible all the time. The intention of the loading indicator is to show that an operation is in progress and you need to wait for it to finish. However, that is not the case here - you should use the app like you would otherwise.

### Expected behavior

Based on how it works, it seems like the time for showing the loading indicator is extended to include the following request if they happen with a small enough interval. This should maybe change so that "individual" loading indicators are used, which would probably mean that in the "send cursor position" case, no loading indicator would be shown at all

### Minimal reproducible example

https://signals-cases.fly.dev/muc-02

### Versions

- Vaadin / Flow version: 25.1

### PR DESCRIPTION
**Pull request by Artur-**
Changes the loading indicator to reset after each individual request completes, rather than staying visible across rapid successive requests. Previously, the timer would continue across multiple requests, causing the indicator to show even when each individual request was fast.

Now each request gets independent timing - if a request completes before the threshold (default 450ms), the indicator never appears. This fixes the issue with cursor tracking and other scenarios involving many rapid server calls.

Fixes #23223

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-client/src/main/java/com/vaadin/client/communication/RequestResponseTracker.java [hunk 1]
```diff
@@ -122,17 +120,13 @@ public void endRequest() {
...
-            if (terminated || !requestNowOrSoon) {
-                ConnectionIndicator.setState(ConnectionIndicator.CONNECTED);
-            }
-        });
+        // Always reset loading indicator when request ends.
+        // Client-side component will handle timing for each request
+        // independently.
+        // This ensures rapid successive requests get individual timing instead
+        // of
+        // accumulating time across requests.
```
Comment (caalador) [inline flow-client/src/main/java/com/vaadin/client/communication/RequestResponseTracker.java]:
```suggestion
        // of accumulating time across requests.
```
Formatter only parts, but doesn't connect.

**Review by caalador — APPROVED** [review]
