### PR TITLE
Fix race condition in embedding tests

### LINKED ISSUE #8329: DefaultValueInitializationIT.defaultValues_areSetToCorrectValues_withCorrectUpdateCounts fails in 2.3 branch
https://bender.vaadin.com/viewLog.html?buildId=148036&

```
Caused by: org.openqa.selenium.NoSuchElementException: No element with tag <*> found with the attributes [id='value'] using index 0
```
in `flow-tests/test-embedding/test-embedding-generic-compatibility/`.

### PR DESCRIPTION
**Pull request by joheriks**
Fixes #8329. With Chrome dropping native HTML imports and the compatibility mode test for embedded webcomponents relying on polyfill, a race condition had appeared where the shadowroot was not yet attached during test run. Now waits for at least one shadowroot before commencing the test. 

Update: should squash when merging.

### CODE REVIEW

File: flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/EmbeddingChromeBrowserTest.java [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+    @Override
+    protected void open() {
+        super.open();
+
+        // Wait for at least one shadow root to appear. This is to avoid race
+        // conditions where the test starts before the shadow root has been
+        // attached #8329
+        this.waitUntil((driver) -> Boolean.TRUE
+                .equals(this.getCommandExecutor().executeScript(
+                        "return Array.from(document.getElementsByTagName('*')).some(x => x.shadowRoot !== null)")));
```
Comment (denis-anisimov) [inline flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/EmbeddingChromeBrowserTest.java:16]: >x => x.shadowRoot

That didn't work in IE.
Though we don't run our tests in IE but still : is it possible to write this somehow cross-browser ?

Comment (joheriks) [reply flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/EmbeddingChromeBrowserTest.java]: ES5 compat JS.

Comment (denis-anisimov) [reply flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/EmbeddingChromeBrowserTest.java]: No, sorry, I meant `x.shadowRoot` .
I don't know actually what's the output of the compiled production client side code.

But for the previous releases production code produced a code which worked in browsers which don't support web components at all .
In those browsers `shadowRoot` just don't exist at all.

E.g. in IE11 (again: I don't know which browsers we support nowadays) TB has a specific code which checks the element directly in the parent and then tries to use `shadowRoot`.

And IE11 of course doesn't support `=>`.

Comment (joheriks) [reply flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/EmbeddingChromeBrowserTest.java]: I opened the test view in IE8, and the embedded web components just appear as empty tags in the DOM. I don't know if the test is designed to work in IE at all?

Comment (denis-anisimov) [reply flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/EmbeddingChromeBrowserTest.java]: IE 8 ?

IE 8 is not supported for sure.

IE 11 : I don't know.

But yeah, may be it has no sense to care about this at the moment.
