### PR TITLE
Fix integer overflow in Data Provider page number formula

### LINKED ISSUE #8828: Integer overflow in DataCommunicator.fetchFromProvider()
Flow-data 4.0.0.beta1; if Integer.MAX_VALUE is passed in as the value for limit, the `pages` computation overflows and will compute the value of -42949672 which will leave query null, leading to assertion failure at 757

### PR DESCRIPTION
**Pull request by mshabarov**
Fixes #8828

### CODE REVIEW

File: flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java [hunk 1]
```diff
@@ -716,7 +716,7 @@ protected Object getFilter() {
              * Divisor minus one is placed on numerator part to ensure upwards
              * rounding.
              */
-            final int pages = (limit + pageSize - 1) / pageSize;
+            final int pages = (limit - 1) / pageSize + 1;
```
Comment (pleku) [inline flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java:719]: Commenting here even though this is about lines 726-732, but I noticed this from the added test:

It seems that the pages are fetched even if the backend runs out of items. If this is intentional, I would expect to see it as a comment in the code below. Is it intentional ? I can understand if it would have some performance implications for us for checking if the page "was full or not", but on the other hand, bombing the backend with queries for pages that don't exist can have a price too ?

By minimum I would expect a comment in the code that mentions that whether this is intentional or not (for now).
Another thing is that is it documented somehow for the users ?
This behavior was a bit unexpected for me since it is perfectly fine that this method returns less items than what was requested and it there verifies the count anyway stopping any further requests, but it seems that this part in this method does not do it itself.

Comment (mshabarov) [reply flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java:719]: Thanks for catching this. I believe it's just a mistake and there is no reason to send an extra requests to backend if it runs out of items. Non-sense backend requests have much more performance issues than converting Stream to collection and check the result size. So, yes, this should be fixed, possibly within this PR.

Comment (pleku) [reply flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java:719]: As discussed in the daily - a TODO for the code and the test with issue reference will suffice for now.

Comment (mshabarov) [reply flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java:719]: done
