### PR TITLE
fix: ignore missing files in theme processing

### LINKED ISSUE #13885: devserver crash when editing css with emacs
### Description of the bug

Emacs saves a file, devserver notices a temporary file and tries to load it. But then the file is already gone and devserver crashes. No further updates happen before restarting manually.
```
120225 [qtp1625913564-55] DEBUG com.my-themesoftware.rwd.servlets.ContentPreviewImageServlet  - sending fallback image: no previewimage in content 8
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  - node:internal/fs/utils:344
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     throw err;
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     ^
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  - 
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  - Error: ENOENT: no such file or directory, stat '/home/me/my-project/frontend/themes/my-theme/components/.#vaadin-text-field.css'
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at Object.statSync (node:fs:1538:3)
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at /home/me/my-project/target/plugins/application-theme-plugin/theme-copy.js:75:12
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at Array.forEach (<anonymous>)
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at collectFolders (/home/me/my-project/target/plugins/application-theme-plugin/theme-copy.js:73:32)
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at /home/me/my-project/target/plugins/application-theme-plugin/theme-copy.js:77:22
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at Array.forEach (<anonymous>)
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at collectFolders (/home/me/my-project/target/plugins/application-theme-plugin/theme-copy.js:73:32)
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at copyThemeResources (/home/me/my-project/target/plugins/application-theme-plugin/theme-copy.js:39:22)
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at handleThemes (/home/me/my-project/target/plugins/application-theme-plugin/theme-handle.js:169:5)
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at findThemeFolderAndHandleTheme (/home/me/my-project/target/plugins/application-theme-plugin/theme-handle.js:97:23) {
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -   errno: -2,
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -   syscall: 'stat',
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -   code: 'ENOENT',
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -   path: '/home/me/my-project/frontend/themes/my-theme/components/.#vaadin-text-field.css'
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  - }

```

### Expected behavior

theme-copy.js should ignore temporary files. Perhaps ignore all file names starting with a dot, or just file names starting with ".#"

### Minimal reproducible example

The problem does not occur every time a css file is saved in emacs. I'm currenctly using a computer with fast cpu, a lot of ram and the project is on a slow spinner drive. The problem occurs about every 5th time a file is saved. It is a plain java Vaadin 23 project.

### Versions

Vaadin
    23.0.10
Flow
    23.0.7
Java
    JetBrains s.r.o. 17
OS
    amd64 Linux 5.16.9

### PR DESCRIPTION
**Pull request by mcollovati**
## Description

During theme processing, a file detected as existing may be delete before it gets copied, causing a ENOENT (No such file or directory) error. After such failure, dev server live reload stops working. This change catches errors in file copy operations, ignoring ENOENT and propagating other failures.

Fixes #13885
Co-authored by @mijutu

## Type of change

- [X] Bugfix
- [ ] Feature

## Checklist

- [X] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [X] I have added a description following the guideline.
- [X] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by mcollovati** [comment]
I tested the fix manually by creating a huge number of files in the theme directory before starting the application and then deleting most of them in chunks

```
# Create file in theme folder before starting the application
for i in {1..5000}; do touch frontend/themes/app-theme/tempdir/file-$i.txt; done

# Chunk deletion causes file to be delete while theme processing is handling it
for i in {1..5}; do rm frontend/themes/app-theme/tempdir/file-$i*; sleep 1; done
```

Unfortunately, I was unable to replicate the above into an integration test

File: flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js [hunk 1]
```diff
@@ -177,10 +181,26 @@ function checkModules(modules) {
...
+      copyFileSync(fileToCopy, copyTarget);
+    }
+  } catch (error) {
+    handleNoSuchFileError(fileToCopy, error, logger);
   }
 }
 
-export { checkModules, copyStaticAssets, copyThemeResources };
+// Ignores errors due to files missing during theme processing
+// This may happen for example when an IDE creates a temporary files
```
Comment (tepi) [inline flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js:195]: "files" should be "file"?

Comment (mcollovati) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js]: updated

**Review by tepi — APPROVED** [review]
