### PR TITLE
fix: move CSS imports from @Theme to bootstrap JS file

### LINKED ISSUE #22517: Hilla applications using Lumo theme appear receive only base styles
### Description of the bug

In Hilla non-hybrid applications using `@Theme` with V25 snapshot the application loads without Lumo theme styles, as seen below:

Image

Adding `@import '@vaadin/vaadin-lumo-styles/lumo.css';` into the styles.css brings default Lumo styles back.

### Expected behavior

The `@Theme` annotation keeps working usual.

Image

### Minimal reproducible example

Take any Hilla v24 application and upgrade to V25.

Alternatively:

- `$ npm init vaadin@latest`
- Select Hilla and use pre-release
- `$ mvn`

### Versions

- Vaadin / Flow version: V25
- Java version:
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

### PR DESCRIPTION
**Pull request by platosha**
Fixes #22517

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java [hunk 1]
```diff
@@ -186,14 +183,17 @@ private void computeReactClasses(ClassFinder finder) throws IOException {
...
+                && themeDefinition.getTheme() != null;
         for (Entry<String, EntryPointData> entry : entryPoints.entrySet()) {
             EntryPointData entryPoint = entry.getValue();
             for (String className : entryPoint.reachableClasses) {
                 ClassInfo classInfo = visitedClasses.get(className);
                 entryPoint.getModules().addAll(classInfo.modules);
                 entryPoint.getModulesDevelopmentOnly()
                         .addAll(classInfo.modulesDevelopmentOnly);
-                if (classInfo.loadCss) {
+                if (classInfo.loadCss || activeTheme
```
Comment (caalador) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java:195]: the loadCss is always false for all theme files and activeTheme now lets through all theme files even with loadCss false. So the flag can be fully removed.

File: flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java [hunk 2]
```diff
@@ -232,8 +232,8 @@ public void multipleSameEmbedded_cssTargetingDocumentShouldOnlyAddElementsOneTim
                 2l, getCommandExecutor().executeScript(
                         "return document.head.querySelectorAll('link[rel=stylesheet][href^=\"https://fonts.googleapis.com\"]').length"));
         Assert.assertEquals(
-                "Project contains 4 css injections to document and all should be hashed",
-                4l, getCommandExecutor().executeScript(
+                "Project contains 2 css injections to document and all should be hashed",
```
Comment (caalador) [inline flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java]: What global css has embedded applications lost?

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java [hunk 3]
```diff
@@ -561,9 +583,18 @@ private Map<ChunkInfo, List<String>> mergeJavascript(
 
     }
 
-    protected <T> List<String> merge(Map<T, List<String>> css) {
+    protected <T> List<String> merge(Map<T, List<String>> outputFiles) {
+        // Ignore app shell imports and definitions for bundle build detection,
```
Comment (caalador) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java]: Shouldn't app shell imports also be taken into account by flow as they are not added to the general imports anymore even though they were there before?

**Review by caalador — CHANGES_REQUESTED** [review]

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java (hunk 3 above)
Comment (platosha) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java]: Apart from unit tests, the feature that is affected here is the bundle build.

Should the bundle include theme CSS imports? I don't know, but the current implementation didn't. So I assumed that my changes at some point produced a valid failure in the bundle ITs because of including CSS imports again. Ignoring here addresses this failure.

Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java]: @mshabarov what was the state for css in bundles.
From what I see in tests and code I would expect css to be bundles and Theme css especially

File: flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java (hunk 2 above)
Comment (platosha) [reply flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java]: Both are synthetic global side-effect stylesheets that include font-face declarations extracted from `lumo.css` by this code:
https://github.com/vaadin/flow/blob/8bcef188b1a8315b02f63c6ff9366587e8d7a5f9/flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js#L230

Because `@vaadin/vaadin-lumo-styles/lumo.css?inline` is no longer added to `generated-flow-webcomponent-imports.js`, its synthetic global side-effects are missing.

Comment (platosha) [reply flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java]: Is `lumo.css` expected to be in embedded webcomponent? It's presence doesn't seem to affect the test app appearance, apart from this assertion.

Comment (caalador) [reply flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java]: Everything except font-faces should go to the embedded shadowroot.
So the missing ones are lumo-icons and vaadin-grid-sorter-icons I guess, they probably won't then work if used inside an embedded component and probably should if used.

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java (hunk 1 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java:195]: Seems I somehow didn't follow the road correctly and the loadCss flag did filter correctly still as now we have `FrontendDependenciesTest.themeNotDefined_ButReferenced_themeCssNotLoaded:197` failing due to non theme file loaded.

File: flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java (hunk 2 above)
Comment (caalador) [reply flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java]: would it be a problem to have them both in generated-flow-webcomponent-imports and the new appshell-imports?

Comment (platosha) [reply flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java]: Should be possible, will try.

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java [hunk 4]
```diff
@@ -372,6 +395,15 @@ private Map<File, List<String>> process(Map<ChunkInfo, List<CssData>> css,
                     "const loadOnDemand = (key) => { return Promise.resolve(0); }");
         }
 
+        List<String> appShellLines = new ArrayList<>();
+        List<String> appShellCssLines = getCssLines(appShellCssData);
+        if (!appShellCssLines.isEmpty()) {
+            appShellLines.add(IMPORT_INJECT);
```
Comment (caalador) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java:407]: This import inject should be filtered out in merge as I see it failing due to being available twice: 
```
error during build:
src/main/frontend/generated/flow/generated-flow-webcomponent-imports.js (8:9): Identifier "injectGlobalCss" has already been declared
```
Mainly in cases where we have a parent theme that is added also.

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java (hunk 3 above)
Comment (platosha) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java]: I see. Bundles were including the css, but `stats.json` wasn't indicating that, because it didn't consider the new file with their imports. Hope this change helps it: https://github.com/vaadin/flow/pull/22518/commits/9b23bc15c38729b9a8a8a652f89c3adfae637b04
