### PR TITLE
Fix Javadoc rendering in AppShellConfigurator

### LINKED ISSUE #14794: Incorrect Javadoc rendering of example code
### Description of the bug

Some of the Javadoc for Vaadin uses examples such as:

```text
 * <code>
 * &#64;Meta(name = "Author", content = "Donald Duck")
 * &#64;PWA(name = "My Fun Application", shortName = "fun-app")
 * &#64;Inline("my-custom-javascript.js")
 * &#64;Viewport("width=device-width, initial-scale=1")
 * &#64;BodySize(height = "100vh", width = "100vw")
 * &#64;PageTitle("my-title")
 * &#64;Push(value = PushMode.AUTOMATIC, transport = Transport.WEBSOCKET_XHR)
 * public class AppShell implements AppShellConfigurator {
 * }
 * </code>
 ```
 
 This will not display correctly in traditional Javadoc rendering. It will just come out as one long line. This is because `<code>` or `{@code ..}` are not intended for multi-line output.
 
But here comes the interesting part:  Vaadin's own API site can display this correctly. See [this example](https://vaadin.com/api/platform/23.2.3/com/vaadin/flow/component/page/AppShellConfigurator.html) (Vaadin API site) and [compare to this](https://javadoc.io/doc/com.vaadin/flow-server/latest/com/vaadin/flow/component/page/AppShellConfigurator.html) (Javadoc.io site).
 
I think Vaadin's API docs should be readable even from plain-vanilla Javadoc.  The fact that Vaadin's API site can display this "correctly" is (in my mind) an anomaly and Vaadin's Javadoc comments should not be tailored for fit with this, but should instead be tailored to display correctly with plain-vanilla Javadoc rendering. The latter is the one most users will see in their IDE.

 

### Expected behavior

Multi-line Javadoc example code should use `<pre>` so that it displays correctly. 

### Minimal reproducible example

See [this](https://javadoc.io/doc/com.vaadin/flow-server/latest/com/vaadin/flow/component/page/AppShellConfigurator.html) (Javadoc.io site) and note how the example code is just one long line.

### Versions

- Vaadin / Flow version: 23.2
- Java version: not applicable
- OS version: not applicable
- Browser version (if applicable): not applicable
- Application Server (if applicable): not applicable
- IDE (if applicable): not applicable

### PR DESCRIPTION
**Pull request by lbruun**
## Description

Fixes rendering issue of the example code in the Javadoc for the `AppShellConfigurator` class.
See [Javadoc.io](https://javadoc.io/doc/com.vaadin/flow-server/latest/com/vaadin/flow/component/page/AppShellConfigurator.html) and note how the example code in the class header comment is rendered as one long line.

Fixes #14794.

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java [hunk 1]
```diff
@@ -53,7 +53,8 @@
  * application shell class.
  * <p>
  *
- * <code>
+ * Example:
+ * <pre>
```
Comment (caalador) [inline flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java:57]: The `<pre>` should be added around the `<code>` so that we would get a formatted code block and not replace the code block.

**Review by caalador — CHANGES_REQUESTED** [review]

File: flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java (hunk 1 above)
Comment (lbruun) [reply flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java:57]: @caalador : Got it. I take it that you would like to retain the special rendering that Vaadin API site does where `<code>` is rendered on a _grey background_ ? (because in standard Javadoc, you would not be able to see any difference by retaining the `<code>` tag in our example; it would would look exactly the same with or without)

In any case, I've found a few other classes where this is a problem, so I need to update this PR in any case. Might as well fix all places in Flow where this problem occurs in one PR.

Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java:57]: Yes.
Fixing all similar problems at once would be fine.

**Review by caalador — DISMISSED** [review]

File: flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java [hunk 2]
```diff
@@ -53,6 +53,8 @@
  * application shell class.
  * <p>
  *
+ * Example:
+ * <pre>
```
Comment (caalador) [inline flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java:57]:
```suggestion
 * Example:
 * 
 * <pre>
```

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java [hunk 3]
```diff
@@ -78,13 +78,15 @@
...
  * <code>@Configuration</code>.
  * <p>
- * For example <code>
-&#64;EnableWebSecurity
-&#64;Configuration
-public class MyWebSecurity extends VaadinWebSecurity {
-
-}
+ * For example:
+ * <pre>
```
Comment (caalador) [inline vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java:82]:
```suggestion
 * For example:
 * 
 * <pre>
```

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java [hunk 4]
```diff
@@ -72,13 +72,15 @@
...
  * <code>@Configuration</code>.
  * <p>
- * For example <code>
-&#64;EnableWebSecurity
-&#64;Configuration
-public class MySecurityConfigurerAdapter extends VaadinWebSecurityConfigurerAdapter {
-
-}
+ * For example:
+ * <pre>
```
Comment (caalador) [inline vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java:76]:
```suggestion
 * For example:
 * 
 * <pre>
```

**Review by caalador — COMMENTED** [review]
Seems the formatter wants an empty line before `<pre>`

**Comment by lbruun** [comment]
> Seems the formatter wants an empty line before `\<pre\>`

Fixed by a new push.

**Review by caalador — APPROVED** [review]
