### PR TITLE
fix: remove modal component on route refresh

### LINKED ISSUE #20473: Dialog is not updated when doing hotswap
### Description of the bug

Given

```
@Route(value = "overlay", layout = MainLayout.class)
@AnonymousAllowed
public class OverlayView extends VerticalLayout {

    @Override
    protected void onAttach(AttachEvent attachEvent) {
        super.onAttach(attachEvent);

        Dialog dialog = new Dialog("The Dialog");
        dialog.setCloseOnOutsideClick(true);
        dialog.setCloseOnEsc(true);

        dialog.add(new Div("Text nr 1"));

        dialog.open();
    }

}
```

if you are running using HotswapAgent and edit the div text to "Text nr 2", then a dialog with "Text nr 1" remains on screen and a dialog with "Text nr 2" is not added at all. If you manually refresh the page, the dialog with "Text nr 2" is shown

### Expected behavior

The old dialog is closed and the new one opened

### Minimal reproducible example

as above

### Versions

- Vaadin / Flow version: 24.5.3

### PR DESCRIPTION
**Pull request by mcollovati**
## Description

Modal components attached to the UI were not removed or replaced during self-navigation triggered by a route refresh.
This change updates navigation handler to ensure modal components are removed and adds a new navigation trigger for route refresh to differentiate programmatic navigations (e.g., forward actions).
It also modifies Hotswapper to require a full chain refresh when modal components are present.

Fixes #20473

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java [hunk 1]
```diff
@@ -349,10 +349,13 @@ private UIRefreshStrategy computeRefreshStrategy(UI ui,
...
 
+        // A full chain refresh should be triggered if there are modal
+        // components, since they could be attached to UI or parent layouts
+        boolean hasModalComponents = ui.hasModalComponent();
         UIRefreshStrategy refreshStrategy;
         if (!targetChainChangedItems.isEmpty()) {
-            refreshStrategy = targetChainChangedItems.stream()
-                    .allMatch(chainItem -> chainItem == route)
+            refreshStrategy = targetChainChangedItems.stream().allMatch(
+                    chainItem -> chainItem == route && !hasModalComponents)
```
Comment (tepi) [inline flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java:358]: Is this checking `hasModalComponents` for each `chainItem`? If I read this correctly the value of it will not change

Comment (mcollovati) [reply flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java:358]: `allMatch` should stop evaluating the predicate when the condition is true. But effectively, there's no need to iterate at all if there are modal components.
I'll fix it, thanks

Comment (mcollovati) [reply flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java]: done

**Review by tepi — APPROVED** [review]

**Comment by netsrotr** [comment]
We have tested Vaadin 24.5.7 and this fix cause issues on our side with our hotswap -it close opened modal dialogs randomly and influence the browser refresh behavior (e.g. via key F5 in chrome).
It would really help if you would provide any documentation how to setup a working hotswap environment (favor eclipse IDE, but IntelliJ would also fit), where your fix really work. For now we stoped using hotswap because of that, any older version 24.5.x before was better than that, sorry.

**Comment by mcollovati** [comment]
@netsrotr do you mind creating a new ticket, providing a code example (or even better, a sample project) showing how you are using dialogs in the application? This would help us investigate further and see if we missed some use cases.
