### PR TITLE
fix: I18NProvider.translate return same as Component.translate

### LINKED ISSUE #19516: Missing translation files causes an error with translate
### Description of the bug

If an app is missing translation files and you use `new TextField(getTranslation("hello_world"));`, it results with:

Screenshot 2024-06-05 at 12 39 42

In the same scenario, `new TextField(I18NProvider.translate("hello_world"))` results in an exception with a misleading message being thrown:

Screenshot 2024-06-05 at 12 46 42

### Expected behavior

I'd expect the outcome to be same as with `getTranslation`.
Or at least that the message of the thrown Error would mention the missing translation file.

### Minimal reproducible example

Create an app with no `translations.properties` files and try `I18NProvider.translate("hello_world")`

### Versions

- Vaadin / Flow version: 24.5.0.alpha1

### PR DESCRIPTION
**Pull request by caalador**
The I18NProvider.translate should return the
same as Component.translate when no provider
can be found.

Fixes #19516

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/i18n/I18NProvider.java [hunk 1]
```diff
@@ -145,13 +148,14 @@ static String translate(String key, Object... params) {
...
-     *             thrown if no I18NProvider found from the VaadinService
      */
     static String translate(Locale locale, String key, Object... params) {
         return LocaleUtil.getI18NProvider()
-                .orElseThrow(() -> new IllegalStateException(
-                        "I18NProvider is not available via current VaadinService. VaadinService, Instantiator or I18NProvider is null."))
-                .getTranslation(key, locale, params);
+                .map(i18n -> i18n.getTranslation(key, locale, params))
+                .orElseGet(() -> {
+                    LoggerFactory.getLogger(I18NProvider.class).debug(
```
Comment (tltv) [inline flow-server/src/main/java/com/vaadin/flow/i18n/I18NProvider.java]: If we reach this due to VaadinService or Instantiator being null, then exception would make more sense since it's fatal issue. LocaleUtil.getI18NProvider() is just chain of Optional mapping, so I suggest checking for null first for VaadinService and Instantiator, and throw exception if null.

If VaadinService and Instantiator are not null but we still reach here, then just logging that I18NProvider is null is enough. It could be null if all translation files are missing, like in the ticket. 
Message could say "I18NProvider is not available. Missing all translation files can cause this with default I18NProvider."

Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/i18n/I18NProvider.java]: Throwing for missing service or instantiator. Else just returning key as we do for component.
