### PR TITLE
Pass --no-frozen-lockfile in pnpm dev mode to prevent CI failures

### LINKED ISSUE #23530: PiT 25.1: pnpm install fails with ERR_PNPM_LOCKFILE_CONFIG_MISMATCH after version bump from 25.0 to 25.1
### Description of the bug

When migrating `spreadsheet-demo` from Vaadin 25.0.5 to 25.1.0-alpha6, the dev-mode bundle build fails because pnpm install exits with `ERR_PNPM_LOCKFILE_CONFIG_MISMATCH`:

```
ERR_PNPM_LOCKFILE_CONFIG_MISMATCH  Cannot proceed with the frozen installation.
The current "overrides" configuration doesn't match the value found in the lockfile

Update your lockfile using "pnpm install --no-frozen-lockfile"
```

The server starts (Jetty reports `Started ServerConnector`) but the first request triggers pnpm install which fails because the lockfile generated with 25.0.5 doesn't match the overrides in the 25.1.0-alpha6 `package.json`.

This is a regression — the starter passes with 25.0.5 (stable) but fails after bumping to 25.1.0-alpha6 (target).

Note: reproduces consistently on Linux (GitHub Actions, ubuntu-22.04) but not on macOS. Both environments use Node 24.13.0 (from `~/.vaadin`) with npm 11.6.2. The pnpm version is resolved dynamically via `npx pnpm` — the exact version may differ between CI and local.

### Expected behavior

After bumping Vaadin version, Flow's dev-mode should handle the lockfile mismatch automatically (e.g., by running `pnpm install --no-frozen-lockfile` or regenerating the lockfile).

### Minimal reproducible example

```bash
git clone git@github.com:vaadin/spreadsheet-demo.git
cd spreadsheet-demo

# 1. Run with 25.0.5 first (generates pnpm lockfile)
mvn -ntp -B
# wait for "Started ServerConnector", open http://localhost:8080, then stop the server

# 2. Bump to 25.1.0-alpha6
perl -pi -e 's|(\s*<vaadin.version>)[^\s]+(<\/vaadin.version>)|${1}25.1.0-alpha6${2}|g' pom.xml

# 3. Run again — fails with ERR_PNPM_LOCKFILE_CONFIG_MISMATCH
mvn -ntp -B
# wait for "Started ServerConnector", open http://localhost:8080
# First request triggers pnpm install which fails
```

### Versions

- Vaadin / Flow version: 25.1.0-alpha6 (flow 25.1.0-alpha7)
- Passes with: 25.0.5
- Node: 24.13.0 (from `~/.vaadin`), npm: 11.6.2, pnpm: via `npx pnpm`
- OS: Linux (ubuntu-22.04) — does not reproduce on macOS

### PR DESCRIPTION
**Pull request by manolo**
## Summary

- pnpm 10 auto-enables `--frozen-lockfile` when it detects CI environments
  (via `ci-info`, checking `GITHUB_ACTIONS`, `CI`, etc.)
- Flow never requests this: `ciBuild` defaults to `false` in dev mode
- When a user bumps `vaadin.version` and pushes, the stale `pnpm-lock.yaml`
  causes `ERR_PNPM_LOCKFILE_CONFIG_MISMATCH` in CI but works locally
- Fix: explicitly pass `--no-frozen-lockfile` when running pnpm install
  in dev mode (`ciBuild==false`), since Flow is resolving dependencies,
  not reproducing a locked build

## Context

When `ciBuild==true`, Flow already passes `--frozen-lockfile` explicitly.
This change makes the non-CI path equally explicit, preventing pnpm from
silently inheriting a stricter mode based on environment detection.

Fixes #23530

### CODE REVIEW

**Comment by Artur-** [comment]
Why? The lockfile defines the installed versions. When you upgrade Vaadin, you run dev mode or mvn install locally, and that upgrades what is needed. You cannot and should not upgrade a version in the repo and assume ”npm ci” would work. How would even the new lock file end up in the repo if you would do that?

**Comment by manolo** [comment]
The lockfile here is not user-committed, it is generated by Flow during dev mode. When a user bumps `vaadin.version` and pushes, CI runs dev mode but the old `pnpm-lock.yaml` persists. pnpm 10 auto-detects CI via [`ci-info`](https://github.com/watson/ci-info) (checking `GITHUB_ACTIONS`, `CI`, etc.) and activates `--frozen-lockfile` by default, Flow never requests this, the `ciBuild` property defaults to `false`. So the same `pnpm install` works locally but fails in CI.

Independently of the CI issue, `isPlatformMajorVersionUpdated` is inconsistent: it skips the stale lockfile copy for 24.x->25.x but not for 25.0->25.1, even though overrides change between minors too.

That said, a broader fix might be better: Flow could pass `--no-frozen-lockfile` explicitly in dev mode, since it is resolving dependencies, not reproducing a locked build. The version check in this PR helps for the dev-bundle copy path, but in practice a stale lockfile usually already exists on disk and the `if (packageLock.exists()) return` guard fires before the version check is reached.

File: flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/FrontendBuildUtils.java [hunk 1]
```diff
@@ -122,8 +122,7 @@ protected static boolean isPlatformMajorVersionUpdated(ClassFinder finder,
                     .get(NodeUpdater.VAADIN_VERSION).asString());
             FrontendVersion platformsVersion = new FrontendVersion(
                     platformVersion.get());
-            return jsonVersion.getMajorVersion() != platformsVersion
-                    .getMajorVersion();
+            return !jsonVersion.isEqualTo(platformsVersion);
```
Comment (caalador) [inline flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/FrontendBuildUtils.java]: This update can not be done here as the method is `isPlatformMajorVersionUpdated` so it should check just that. 

Any change to the copying logic should be in `copyPackageLockFromBundle` with a new method for checking for any change in the version, but that would make the package-lock stored in the devBundle useless as the use was to get a faster build when the lockfile is available for reference.

**Comment by manolo** [comment]
I agree that changing isPlatformMajorVersionUpdated semantics is not the right approach.

Looking at this more carefully, the cleanest fix is to pass --no-frozen-lockfile explicitly when Flow runs pnpm install in dev mode. The reasoning:

  - Flow is resolving dependencies, not reproducing a locked build, so --frozen-lockfile makes no sense in this context
  - pnpm 10 auto-enables --frozen-lockfile when it detects CI (via ci-info, checking GITHUB_ACTIONS, CI, etc.) - Flow never requests this, but inherits it silently
  - This fixes the problem at the source rather than working around it in the bundle copy logic

A dev mode flag to skip the devbundle copy would work around the symptom but not the cause: even without the bundle copy, a stale pnpm-lock.yaml already on disk triggers the same  ERR_PNPM_LOCKFILE_CONFIG_MISMATCH. The --no-frozen-lockfile approach covers both paths.

I will update the PR but need a clear answer what flowers prefer for this fix

**Comment by caalador** [comment]
I would say run with  `--no-frozen-lockfile` if dev mode build and `ciBuild==false`

**Comment by manolo** [comment]
> I would say run with `--no-frozen-lockfile` if dev mode build and `ciBuild==false`

done

**Review by caalador — APPROVED** [review]
