### PR TITLE
fix: allow server registered return calls

### LINKED ISSUE #13208: JavaScript call with return value does not work with Dialog
### Description of the bug

JavaScript call with return value does not work with Dialog in Vaadin 23, this used to work in Vaadin 22.0.7. See the attached example. 

### Expected behavior

JavaScript with return value, the response call back is executed.

### Minimal reproducible example

@PageTitle("Dialog2")
@Route(value = "dialog2", layout = MainLayout.class)
public class DialogView2 extends VerticalLayout {

    public DialogView2() {
        add(new Button("Open Window", e -> new Window().open()));
    }

    private class Window extends Dialog {

        private Window() {
            add(new Button("Close", e -> close()));
        }

        @Override
        protected void onAttach(AttachEvent attachEvent) {
            super.onAttach(attachEvent);
            UI ui = attachEvent.getUI();
            ui.getPage().fetchCurrentURL(url -> {
                ui.access(() -> Notification.show(url.toString()));
            });
        }
    }
}

### Versions

- Vaadin / Flow version: Vaadin 23.0.0
- Java version: 11

### PR DESCRIPTION
**Pull request by caalador**
Allow return calls for server-side
registered return channel on targeted
node.

Fixes #13208

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/communication/ReturnChannelHandler.java [hunk 1]
```diff
@@ -79,6 +79,16 @@ public String getRpcType() {
...
     }
 
+    @Override
+    protected boolean allowInert(StateNode node) {
+        // Allow calls if a return channel has been registered for the node.
+        final Optional<ReturnChannelMap> returnChannelMap = node
+                .getFeatureIfInitialized(ReturnChannelMap.class);
+        return returnChannelMap.isPresent()
+                ? returnChannelMap.get().hasChannels()
+                : false;
```
Comment (joheriks) [inline flow-server/src/main/java/com/vaadin/flow/server/communication/ReturnChannelHandler.java:89]:
```suggestion
        return node.getFeatureIfInitialized(ReturnChannelMap.class)
                .map(ReturnChannelMap::hasChannels).orElse(false);
```

File: flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ReturnChannelMap.java [hunk 2]
```diff
@@ -164,4 +164,12 @@ public ReturnChannelRegistration get(int channelId) {
         return channels.get(Integer.valueOf(channelId));
     }
 
+    /**
+     * Return if map contains any registered channels.
+     *
+     * @return {@code true} if registered channels exist.
+     */
+    public boolean hasChannels() {
+        return !channels.isEmpty();
```
Comment (joheriks) [inline flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ReturnChannelMap.java:173]: So anything with a registered return channel will respond even if inert. Would it make sense to restrict this to the root (UI) node to not punch additional holes in the modality curtain?

Comment (joheriks) [reply flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ReturnChannelMap.java:173]: Update: let's keep the logic simple for now as we have yet to finalize what should be let through and what should be blocked.

Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ReturnChannelMap.java:173]: As the registrations are only on the server side and get removed on response it shouldn't be a problem in opening up too much also this enables for instance:
```

    protected void execJS(String js,
            SerializableConsumer<String> resultHandler) {
        getElement().executeJs(js)
                .then(String.class, resultHandler);
    }

    private class Window extends Dialog {

        private Window() {
            add(new Button("show url", e-> {
                UI ui = getUI().get();
                execJS("return window.location.href", urlString ->
                        ui.access(() -> Notification.show(urlString))
                );
            }));
        }
    }
```
where the executing js is outside of the dialog, but not on the RootNode.

**Review by joheriks — APPROVED** [review]
