### PR TITLE
fix: use ServletContext classloader as a default classloader for serv…

### LINKED ISSUE #4367: VaadinService classloader is incorrectly set in the CTOR
There is a method `setDefaultClassLoader` which is called in the `VaadinService`CTOR.

(By the way this is horrible that we have protected method which is _intended to be overwritten_ in subclasses which is called in the CTOR but that's another issue).

This method sets the classloader for the `VaadinService` to the `Thread.currentThread().getContextClassLoader()`.

Apparently this is intentional code which is done to be able to acquire appropriate class loader to load application's classes (e.g. UI) (from javadocs).

Not sure whether this is done for OSGi case or not but exactly for OSGi it doesn't work.

It might be that it depends on how OSGi declares and uses Vaadin HTTP servlet.

I have an Activator class which register the servlet via HTTP service (see code below).
I  have to do it as it's in the code (with one more call for `setClassLoader`) otherwise it fails with inability to load `UI` class.

We should take care about this way of activating servlet.

```
public class Activator implements BundleActivator {

    @Override
    public void start(BundleContext ctx) throws Exception {
        Hashtable<String, String> props = new Hashtable<>();
        props.put("osgi.http.whiteboard.servlet.pattern", "/");
        VaadinServlet servlet = new VaadinServlet() {
            @Override
            public void init(ServletConfig servletConfig)
                    throws ServletException {
                super.init(servletConfig);

                getService().setClassLoader(getClass().getClassLoader());
            }
        };

        ctx.registerService(Servlet.class.getName(), servlet, props);

    }

    @Override
    public void stop(BundleContext context) throws Exception {
    }

}
```

### PR DESCRIPTION
**Pull request by denis-anisimov**
…ice (#11308)

Fixes #4367

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java [hunk 1]
```diff
@@ -2395,4 +2376,39 @@ private void runWithServiceContext(Runnable runnable) {
             setCurrent(null);
         }
     }
+
+    /**
+     * Get the name of the CSRF Token attribute in HTTP session.
+     *
+     * @return the attribute name string
+     */
+    public static String getCsrfTokenAttributeName() {
```
Comment (pleku) [inline flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java:2385]: This should not be picked ?

**Review by pleku — CHANGES_REQUESTED** [review]

File: flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java (hunk 1 above)
Comment (denis-anisimov) [reply flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java:2385]: Git is absolutely unable to pick properly.

Thanks.

**Review by pleku — APPROVED** [review]
