### PR TITLE
fix: Do not use --ignore-existing which is only available in npm 6

### LINKED ISSUE #11963: npx: the --ignore-existing argument has been removed.
### Description of the bug / feature
Every build with V22 outputs
```
2021-10-01 14:02:19.138  INFO 91272 --- [onPool-worker-1] c.v.flow.server.frontend.FrontendTools   : using '/usr/local/bin/npx --yes --quiet --ignore-existing pnpm@5.18.10' for frontend package installation
npx: the --ignore-existing argument has been removed.
See `npm help exec` for more information
```

### Minimal reproducible example
1. `vaadin init --pre hellov22`
2. `cd hellov22`
3. `mvn`
 
### Versions:
    - Vaadin / Flow version: 22 alpha 5

### PR DESCRIPTION
**Pull request by Artur-**
While this might break some pnpm case, it will still help more to have consistent behavior across npm versions. Also the cases it might break are already broken for many users (npm 7+)

Fixes #11963

### CODE REVIEW

File: flow-client/src/main/frontend/VaadinDevmodeGizmo.ts [hunk 1]
```diff
@@ -1302,10 +1302,7 @@ export class VaadinDevmodeGizmo extends LitElement {
             <input
               id="toggle"
               type="checkbox"
-              ?disabled=${this.liveReloadDisabled ||
-              ((this.frontendStatus === ConnectionStatus.UNAVAILABLE ||
-                this.frontendStatus === ConnectionStatus.ERROR) &&
-                (this.javaStatus === ConnectionStatus.UNAVAILABLE || this.javaStatus === ConnectionStatus.ERROR))}
+              ?disabled=${this.liveReloadDisabled}
```
Comment (joheriks) [inline flow-client/src/main/frontend/VaadinDevmodeGizmo.ts:1305]: Maybe it could be a separate PR?

Comment (Artur-) [reply flow-client/src/main/frontend/VaadinDevmodeGizmo.ts]: oops, removed

**Review by joheriks — APPROVED** [review]
