### PR TITLE
fix: Store UI reference on start

### LINKED ISSUE #22243: Download progress listener not notified if owner component has been detached
### Description of the bug

Transfer progress listeners use `TransferContext::getUI` for locking the UI. This in turn uses `Component::getUI` at the time when the progress event happens. This means that the listener will not run if the owning component has been detached even though it was attached at the time when the download started.

Furthermore, it's a theoretical race condition to call `Component::getUI` without holding the session lock.

The end result is this exception when progress is reported:
```
java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.component.UI.access(com.vaadin.flow.server.Command)" because the return value of "com.vaadin.flow.server.streams.TransferContext.getUI()" is null
	at com.vaadin.flow.server.streams.TransferProgressAwareHandler$5.onComplete(TransferProgressAwareHandler.java:290) ~[classes/:na]
	at com.vaadin.flow.server.streams.TransferUtil.lambda$1(TransferUtil.java:120) ~[classes/:na]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[na:na]
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116) ~[na:na]
	at com.vaadin.flow.server.streams.TransferUtil.transfer(TransferUtil.java:120) ~[classes/:na]
	at com.vaadin.flow.server.streams.InputStreamDownloadHandler.handleDownloadRequest(InputStreamDownloadHandler.java:101) ~[classes/:na]
	at com.vaadin.flow.server.streams.DownloadHandler.handleRequest(DownloadHandler.java:104) ~[classes/:na]
	at com.vaadin.flow.server.communication.StreamRequestHandler.callElementResourceHandler(StreamRequestHandler.java:194) ~[classes/:na]
	at com.vaadin.flow.server.communication.StreamRequestHandler.handleRequest(StreamRequestHandler.java:119) ~[classes/:na]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1879) ~[classes/:na]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:398) ~[classes/:na]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:106) ~[vaadin-spring-25.0-SNAPSHOT.jar:na]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:710) ~[tomcat-embed-core-11.0.10.jar:6.1]
```

### Expected behavior

The `UI` should be extracted when the download starts so that it's available regardless of what has happened to the owner component while the download goes on.

### Minimal reproducible example

```java
Anchor anchor = new Anchor();
InputStreamDownloadHandler downloadHandler = DownloadHandler.fromInputStream(event -> {
    event.getSession().accessSynchronously(() -> remove(anchor));
    return new DownloadResponse(new ByteArrayInputStream(new byte[] { 'a' }), "test.txt", null, 1);
}).whenComplete(ignore -> Notification.show("Done"));
anchor.setText("Download");
anchor.setHref(downloadHandler);
add(anchor);
```

1. Click the button
2. Watch the exception

### Versions

- Vaadin / Flow version: 25.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by caalador**
Store UI ref to have a correct ui
for TransferProgress even when
element is detached during transfer.

Fixes #22243

### CODE REVIEW

File: flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DetatchedTransferProgressListenerIT.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+        }
+
+    }
+
+    private void waitForStatus(String id, String status) {
+        waitUntil(driver -> {
+            WebElement element = findElement(By.id(id));
+            return element.getText().equals(status);
+        });
+    }
```
Comment (tepi) [inline flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DetatchedTransferProgressListenerIT.java]: Is this used from anywhere?

File: flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DetatchedTransferProgressListenerIT.java [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+import org.openqa.selenium.WebElement;
+
+import static com.vaadin.flow.uitest.ui.DetatchedTransferProgressListenerView.DOWNLOAD_AND_REMOVE;
+import static com.vaadin.flow.uitest.ui.DetatchedTransferProgressListenerView.REMOVED_COMPONENT_DONE;
+
+public class DetatchedTransferProgressListenerIT
+        extends AbstractStreamResourceIT {
+
+    @Test
+    public void downloadRemovesComponent_successfullyUpdatetsUI()
```
Comment (tepi) [inline flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DetatchedTransferProgressListenerIT.java]: Updatets -> Updates

File: flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DetatchedTransferProgressListenerIT.java [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+import org.junit.Assert;
+import org.junit.Test;
+import org.openqa.selenium.By;
+import org.openqa.selenium.TimeoutException;
+import org.openqa.selenium.WebElement;
+
+import static com.vaadin.flow.uitest.ui.DetatchedTransferProgressListenerView.DOWNLOAD_AND_REMOVE;
+import static com.vaadin.flow.uitest.ui.DetatchedTransferProgressListenerView.REMOVED_COMPONENT_DONE;
+
+public class DetatchedTransferProgressListenerIT
```
Comment (tepi) [inline flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DetatchedTransferProgressListenerIT.java]: Detatched -> Detached

File: flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DetatchedTransferProgressListenerView.java [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+import com.vaadin.flow.server.streams.InputStreamDownloadHandler;
+
+@Push
+@Route(value = "com.vaadin.flow.uitest.ui.DetatchedTransferProgressListenerView")
+public class DetatchedTransferProgressListenerView extends Div {
+
+    static final String REMOVED_COMPONENT_DONE = "removed-component-resource-uploaded";
+    static final String DOWNLOAD_AND_REMOVE = "download-and-remove-component";
+
+    public DetatchedTransferProgressListenerView() {
```
Comment (tepi) [inline flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DetatchedTransferProgressListenerView.java]: Detatched -> Detached

Comment (caalador) [reply flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DetatchedTransferProgressListenerView.java]: fixed.

File: flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DetatchedTransferProgressListenerIT.java (hunk 3 above)
Comment (caalador) [reply flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DetatchedTransferProgressListenerIT.java]: fixed.

File: flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DetatchedTransferProgressListenerIT.java (hunk 2 above)
Comment (caalador) [reply flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DetatchedTransferProgressListenerIT.java]: fixed.

File: flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DetatchedTransferProgressListenerIT.java (hunk 1 above)
Comment (caalador) [reply flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DetatchedTransferProgressListenerIT.java]: removed
