### PR TITLE
fix: add mkdirp as default devDependency

### LINKED ISSUE #11621: Webpack compilation fails because of missing 'mkdirp' with latest npm
```
2021-08-23 14:57:52.239  INFO 85514 --- [nPool-worker-19] c.v.base.devserver.DevModeHandlerImpl    : Running webpack to compile frontend resources. This may take a moment, please stand by...
node:internal/modules/cjs/loader:943
  throw err;
  ^

Error: Cannot find module 'mkdirp'
```

npm version 7.20.6

Looks like `target/plugins/stats-plugin/stats-plugin.js` depends on `mkdirp` but the project has no dependency for it

### PR DESCRIPTION
**Pull request by pleku**
Fixes #11621

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java [hunk 1]
```diff
@@ -401,6 +401,7 @@ static void addVaadinDefaultsToJson(JsonObject json) {
         defaults.put("webpack-manifest-plugin", "3.0.0");
         defaults.put("@types/validator", "13.1.0");
         defaults.put("validator", "13.1.17");
+        defaults.put("mkdirp", "^1.0.4");
```
Comment (caalador) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java:404]:
```suggestion
        defaults.put("mkdirp", "1.0.4");
```
We should be strict on the versions and not allow random updates.

**Review by caalador — CHANGES_REQUESTED** [review]

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java (hunk 1 above)
Comment (pleku) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java:404]: Thought so too initially, but in case there is a new version and the platform itself would depend on it, then it might be that we force an older version that has bugs ? Neither option seems good to me, not sure which sucks less

Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java:404]: Platform should be able to override defaults. As they only override older versions if there exists a marking.

**Comment by caalador** [comment]
The build has timed out 2 times. Both have locked up on the `Flow tests for PWA annotation (production mode) .... FAILURE [  01:42 h]` module with 
```
[16:02:38]	[Step 7/11] [INFO] Running webpack ...
[17:44:40]	[Step 7/11] The build Flow Public::Flow Pull Requests Run Validation #18555 {buildId=87085} has been running for more than 120 minutes. Terminating...
```
Need investigation on why it fails on this package and is it a problem with all production builds as the hanging test is the first production build.

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java [hunk 2]
```diff
@@ -401,6 +401,7 @@ static void addVaadinDefaultsToJson(JsonObject json) {
         defaults.put("webpack-manifest-plugin", "3.0.0");
         defaults.put("@types/validator", "13.1.0");
         defaults.put("validator", "13.1.17");
+        defaults.put("mkdirp", "1.0.4");
```
Comment (pleku) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java:404]:
```suggestion
        defaults.put("mkdirp", "0.5.5");
```

**Comment by pleku** [comment]
> Need investigation on why it fails on this package and is it a problem with all production builds as the hanging test is the first production build.

Yeah it fails locally too for production mode. Just get `Running webpack ...` on console and no updates after that

**Comment by caalador** [comment]
Do you get some extra information or exception if you then run `node node_modules\webpack\bin\webpack.js` in the module?

**Comment by pleku** [comment]
I'll have to check again. Now with `0.5.5` the build failed for pwa-prod with
```
[10:51:38][ERROR] Failed to execute goal com.vaadin:flow-maven-plugin:1111.5.0-SNAPSHOT:build-frontend (default) on project flow-test-pwa-prod: Execution default of goal com.vaadin:flow-maven-plugin:1111.5.0-SNAPSHOT:build-frontend failed: Webpack process exited with non-zero exit code.
[10:51:38][ERROR] Stderr: 'TypeError: Cannot read property 'then' of undefined
[10:51:38][ERROR]     at /opt/agent/work/a69251da2b2bb9e9/flow-tests/test-pwa/node_modules/.pnpm/cacache@15.2.0/node_modules/cacache/lib/util/fix-owner.js:112:7
[10:51:38][ERROR]     at async enqueue (/opt/agent/work/a69251da2b2bb9e9/flow-tests/test-pwa/node_modules/.pnpm/compression-webpack-plugin@4.0.1_webpack@4.46.0/node_modules/compression-webpack-plugin/dist/index.js:208:11)
[10:51:38][ERROR]     at async Promise.all (index 3)
[10:51:38][ERROR]     at async /opt/agent/work/a69251da2b2bb9e9/flow-tests/test-pwa/node_modules/.pnpm/compression-webpack-plugin@4.0.1_webpack@4.46.0/node_modules/compression-webpack-plugin/dist/index.js:270:7
[10:51:38][ERROR] ': Unexpected exit value: 1, allowed exit values: [0], executed command [/usr/bin/node, /opt/agent/work/a69251da2b2bb9e9/flow-tests/test-pwa/node_modules/webpack/bin/webpack.js] in directory /opt/agent/work/a69251da2b2bb9e9/flow-tests/test-pwa with environment {PATH=/opt/agent/tools/maven.3.5.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, JDK_14_OPENJDK=/usr/lib/jvm/jdk-14.0.1, INTERN_ARGS=tunnelOptions.hostname=172.16.0.216 serverUrl=http://172.16.1.158:9000, JDK_12_OPENJDK=/usr/lib/jvm/jdk-12.0.1+12, JDK_15_0=/usr/lib/jvm/jdk-15, JDK_11_x64=/usr/lib/jvm/jdk-11.0.4, JDK_11_ORACLE_x64=/usr/lib/jvm/jdk-11.0.4, JDK_13_0=/usr/lib/jvm/jdk-13, TEAMCITY_BUILD_PROPERTIES_FILE=/opt/agent/temp/buildTmp/teamcity.build5430484881783570032.properties, TEAMCITY_BUILDCONF_NAME=Flow Pull Requests Run Validation, MVN_HOME=/opt/apache-maven-3.6.3, JRE_HOME=/usr/lib/jvm/jdk1.8.0_201, JDK_11_OPENJDK_x64=/usr/lib/jvm/jdk-11.0.3+7, JDK_8_COR=/usr/lib/jvm/amazon-corretto-8.212.04.2-linux-x64, JDK_1_8_x64=/usr/lib/jvm/jdk8u212-b03, JDK_HOME=/usr/lib/jvm/jdk1.8.0_201, TEAMCITY_GIT_PATH=/usr/bin/git, PWD=/opt/agent/bin, TEAMCITY_SERVER=https://teamcity.vaadin.com, JDK_12_x64=/usr/lib/jvm/jdk-12.0.2, JDK_13_0_x64=/usr/lib/jvm/jdk-13, JDK_11_COR_x64=/usr/lib/jvm/amazon-corretto-11.0.3.7.1-linux-x64, JDK_16_0_x64=/usr/lib/jvm/jdk-16+36, JDK_18_ORACLE=/usr/lib/jvm/jdk1.8.0_201, JDK_12_ORACLE_x64=/usr/lib/jvm/jdk-12.0.2, IP=172.16.1.158, JDK_12_ORACLE=/usr/lib/jvm/jdk-12.0.2, JDK_1_7_x64=/usr/lib/jvm/jdk1.7.0_80, JDK_13_OPENJDK_x64=/usr/lib/jvm/jdk-13+33, OLDPWD=/opt, JDK_12_OPENJDK_x64=/usr/lib/jvm/jdk-12.0.1+12, JDK_13_x64=/usr/lib/jvm/jdk-13, TMPDIR=/opt/agent/temp/buildTmp, UID=0, TEAMCITY_PROJECT_NAME=Flow Public, JDK_18_OPENJDK=/usr/lib/jvm/jdk8u212-b03, JDK_13_ORACLE_x64=/usr/lib/jvm/jdk-13, JDK_12_0_x64=/usr/lib/jvm/jdk-12.0.2, BUILD_VCS_NUMBER_Flow_FlowPullRequests=1586278bc2919ba47ccb044faa27dfc7f3640ced, M2_HOME=/opt/agent/tools/maven.3.5.4, JDK_14_OPENJDK_x64=/usr/lib/jvm/jdk-14.0.1, JDK_16_OPENJDK=/usr/lib/jvm/jdk-16+36, JDK_11_COR=/usr/lib/jvm/amazon-corretto-11.0.3.7.1-linux-x64, JDK_15_OPENJDK_x64=/usr/lib/jvm/jdk-15, IVY_HOME=/opt/apache-ivy-2.4.0, JDK_1_6_x64=/usr/lib/jvm/jdk1.6.0_45, JDK_16_OPENJDK_x64=/usr/lib/jvm/jdk-16+36, NPM_TOKEN=, SHLVL=1, JDK_15_OPENJDK=/usr/lib/jvm/jdk-15, JDK_16_0=/usr/lib/jvm/jdk-16+36, JAVA_HOME=/usr/lib/jvm/jdk1.8.0_201, JDK_14_0=/usr/lib/jvm/jdk-14.0.1, BASE_API_VERSION=, JDK_12_0=/usr/lib/jvm/jdk-12.0.2, JDK_13_OPENJDK=/usr/lib/jvm/jdk-13+33, JDK_15_0_x64=/usr/lib/jvm/jdk-15, TEAMCITY_AGENT_NAME=TVC-Agent-04, ANT_HOME=/opt/apache-ant-1.10.5, TEAMCITY_PROCESS_PARENT_FLOW_ID=, JDK_1_7=/usr/lib/jvm/jdk1.7.0_80, JDK_1_6=/usr/lib/jvm/jdk1.6.0_45, JDK_16_x64=/usr/lib/jvm/jdk1.6.0_45, JDK_11_OPENJDK=/usr/lib/jvm/jdk-11.0.3+7, TEAMCITY_PROCESS_FLOW_ID=6672383288445, _=/opt/agent/bin/agent.sh, JDK_1_8=/usr/lib/jvm/jdk8u212-b03, TEAMCITY_VERSION=2020.2.1 (build 85633), JDK_18_x64=, JDK_11=/usr/lib/jvm/jdk-11.0.4, JDK_12=/usr/lib/jvm/jdk-12.0.2, BUILD_VCS_NUMBER=1586278bc2919ba47ccb044faa27dfc7f3640ced, JDK_17_x64=/usr/lib/jvm/jdk1.7.0_80, JDK_13_ORACLE=/usr/lib/jvm/jdk-13, JDK_11_ORACLE=/usr/lib/jvm/jdk-11.0.4, JDK_11_0_x64=/usr/lib/jvm/jdk-11.0.4, JDK_8_COR_x64=/usr/lib/jvm/amazon-corretto-8.212.04.2-linux-x64, TEMP=/opt/agent/temp/buildTmp, BUILD_NUMBER=18570, JDK_11_0=/usr/lib/jvm/jdk-11.0.4, HOSTNAME=ip-172-16-1-158, TMP=/opt/agent/temp/buildTmp, JDK_14_0_x64=/usr/lib/jvm/jdk-14.0.1, JDK_13=/usr/lib/jvm/jdk-13, TEAMCITY_CAPTURE_ENV="/usr/lib/jvm/jdk1.8.0_201/jre/bin/java" -jar "/opt/agent/plugins/environment-fetcher/bin/env-fetcher.jar", JDK_16=/usr/lib/jvm/jdk1.6.0_45, JDK_17=/usr/lib/jvm/jdk1.7.0_80, JDK_18=/usr/lib/jvm/jdk1.8.0_201, TEAMCITY_GIT_VERSION=2.20.1.0, HOME=/root}, output was 627 bytes:
[10:51:38][ERROR] TypeError: Cannot read property 'then' of undefined
[10:51:38][ERROR]     at /opt/agent/work/a69251da2b2bb9e9/flow-tests/test-pwa/node_modules/.pnpm/cacache@15.2.0/node_modules/cacache/lib/util/fix-owner.js:112:7
[10:51:38][ERROR]     at async enqueue (/opt/agent/work/a69251da2b2bb9e9/flow-tests/test-pwa/node_modules/.pnpm/compression-webpack-plugin@4.0.1_webpack@4.46.0/node_modules/compression-webpack-plugin/dist/index.js:208:11)
[10:51:38][ERROR]     at async Promise.all (index 3)
[10:51:38][ERROR]     at async /opt/agent/work/a69251da2b2bb9e9/flow-tests/test-pwa/node_modules/.pnpm/compression-webpack-plugin@4.0.1_webpack@4.46.0/node_modules/compression-webpack-plugin/dist/index.js:270:7
[10:51:38][ERROR] -> [Help 1]
```

**Comment by pleku** [comment]
So with `1.0.4` it outputs
```
PS C:\Users\Pekka\workspaces\flow\flow\flow-tests\test-embedding\test-embedding-production-mode> node node_modules\webpack\bin\webpack.js
(node:10176) UnhandledPromiseRejectionWarning: TypeError: invalid options argument
    at optsArg (C:\Users\Pekka\workspaces\flow\flow\flow-tests\test-embedding\test-embedding-production-mode\node_modules\.pnpm\mkdirp@1.0.4\node_modules\mkdirp\lib\opts-arg.js:13:11)
    at NodeOutputFileSystem.mkdirp (C:\Users\Pekka\workspaces\flow\flow\flow-tests\test-embedding\test-embedding-production-mode\node_modules\.pnpm\mkdirp@1.0.4\node_modules\mkdirp\index.js:11:10)
    at C:\Users\Pekka\workspaces\flow\flow\flow-tests\test-embedding\test-embedding-production-mode\node_modules\.pnpm\webpack@4.46.0_webpack-cli@3.3.12\node_modules\webpack\lib\Compiler.js:494:26
    at _next2 (eval at create (C:\Users\Pekka\workspaces\flow\flow\flow-tests\test-embedding\test-embedding-production-mode\node_modules\.pnpm\tapable@1.1.3\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at eval (eval at create (C:\Users\Pekka\workspaces\flow\flow\flow-tests\test-embedding\test-embedding-production-mode\node_modules\.pnpm\tapable@1.1.3\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10176) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10176) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by caalador** [comment]
perhaps it would be enough to add to the plugin package.json files the dependency so for instance for `application-theme-plugin` there would be the addition
```
"dependencies": {
  "mkdirp": "0.5.5",
  "glob": "7.1.6"
}
```

**Comment by caalador** [comment]
Seems something odd was happening on agent 9. Just wanted to know that the dependency addition didn't bring 30min extra to the build.
There should be the addition of 
```
 "dependencies": {
    "mkdirp": "0.5.5",
  }
```
to stats-plugin/package.json also to keep the dependencies correctly. (as that was the one mentioned in the ticket also)

**Comment by pleku** [comment]
> There should be the addition of

Done

**Review by caalador — DISMISSED** [review]

**Review by caalador — APPROVED** [review]
