### PR TITLE
fix: Remove disused plugins from package.json

### LINKED ISSUE #12335: stats-plugin remains in package.json after upgrading from flow 9 beta2 to beta3
### Description of the bug / feature
The `stats-plugin`  was removed but the code in `NodeUpdater.addWebpackPlugins` only adds the needed plugins and does not delete any old plugins

### PR DESCRIPTION
**Pull request by joheriks**
It does not delete them from `target` as this will go away with the next clean.

Fixes #12335

### CODE REVIEW

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java [hunk 1]
```diff
@@ -231,6 +232,16 @@ public void getJsonFileContent_incorrectPackageJsonContent_throwsExceptionWithFi
                 StringContains.containsString("broken-package.json"));
     }
 
+    @Test public void removedDisusedPlugins() throws IOException {
+        File packageJson = new File(npmFolder, "package.json");
+        FileWriter packageJsonWriter = new FileWriter(packageJson);
+        packageJsonWriter.write(
+                "{\"devDependencies\": {\"@vaadin/some-old-plugin\": \"./target/plugins/some-old-plugin\"}}");
```
Comment (Artur-) [inline flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java:239]: Would be good to test the real case also where you have plugin A and B in the file and B should remain

**Review by Artur- — CHANGES_REQUESTED** [review]

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java (hunk 1 above)
Comment (joheriks) [reply flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java]: Thanks, the test was in fact a dud as it checked in the wrong JSON object. Now corrected.

**Review by Artur- — APPROVED** [review]

**Review by Artur- — APPROVED** [review]
