### PR TITLE
fix: don't bootstrap UI for invalid location

### LINKED ISSUE #9443: Malformed URL "/..**" causes Error 500 instead of 404
Steps to reproduce:
1. Navigate to [https://cookbook.vaadin.com/..**](https://cookbook.vaadin.com/..**)

Expected behavior:
404 error

Actual behavior:
500 error

Example stacktrace:
```
java.lang.IllegalArgumentException: Relative path cannot contain .. segments
	at com.vaadin.flow.router.Location.verifyRelativePath(Location.java:322) ~[flow-server-5.0.0.beta1.jar:5.0.0.beta1]
	at com.vaadin.flow.router.Location.parsePath(Location.java:281) ~[flow-server-5.0.0.beta1.jar:5.0.0.beta1]
	at com.vaadin.flow.router.Location.<init>(Location.java:56) ~[flow-server-5.0.0.beta1.jar:5.0.0.beta1]
	at com.vaadin.flow.router.Router.getLocationForRequest(Router.java:148) ~[flow-server-5.0.0.beta1.jar:5.0.0.beta1]
	at com.vaadin.flow.router.Router.resolveNavigationTarget(Router.java:163) ~[flow-server-5.0.0.beta1.jar:5.0.0.beta1]
	at com.vaadin.flow.server.BootstrapUtils.resolvePageConfigurationHolder(BootstrapUtils.java:285) ~[flow-server-5.0.0.beta1.jar:5.0.0.beta1]
	at com.vaadin.flow.server.BootstrapHandler$BootstrapContext.<init>(BootstrapHandler.java:195) ~[flow-server-5.0.0.beta1.jar:5.0.0.beta1]
```

### PR DESCRIPTION
**Pull request by pleku**
Based on #11552 and to be rebased on top of it.

Fixes #9443 for Flow 3+ bootstrapping.

### CODE REVIEW

File: flow-tests/test-root-context/src/test/java/com/vaadin/flow/InvalidLocationIT.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+import org.junit.Test;
+
+import com.vaadin.flow.testutil.ChromeBrowserTest;
+
+public class InvalidLocationIT extends ChromeBrowserTest {
+
+    // #9443
+    @Test
+    public void invalidCharactersOnPath_UiNotServed() {
+        open("..**");
```
Comment (pleku) [inline flow-tests/test-root-context/src/test/java/com/vaadin/flow/InvalidLocationIT.java:29]: Actually this doesn't do what it is supposed to do

File: flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java [hunk 2]
```diff
@@ -166,6 +168,22 @@ protected BootstrapContext createBootstrapContext(VaadinRequest request,
     @Override
     public boolean synchronizedHandleRequest(VaadinSession session,
             VaadinRequest request, VaadinResponse response) throws IOException {
+        try {
+            // #9443 Use error code 400 for bad location and don't create UI
+            // Normally caught by IndexHtmlRequestHandler, but checking here too
+            // for handcrafted requests
+            String pathAndParams = request.getParameter(
+                    ApplicationConstants.REQUEST_LOCATION_PARAMETER);
```
Comment (caalador) [inline flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java:176]: Is it so that a JSBootstrap request is always a redirect as location is only available for statuses  201, 301, 302, 303, 307, 308?
Or is this something we always fill somewhere?

Comment (pleku) [reply flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java:176]: Yes https://vaadin.slack.com/archives/C6RAXJATF/p1629182338073700

Comment (pleku) [reply flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java:176]: If it will be missing things are to 🔥

Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java:176]: That's why I asked. Because if it's not added by use then things will get too interesting.

**Review by caalador — APPROVED** [review]
