### PR TITLE
fix: Handle concurrent file requests

### LINKED ISSUE #11144: java.nio.file.FileSystemAlreadyExistsException: null with latest snapshot
This is from the build log of a Spring snapshot
```
[16:23:06] :	 [Step 3/5] java.nio.file.FileSystemAlreadyExistsException: null
[16:23:06] :	 [Step 3/5] 	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:113) ~[zipfs.jar:1.8.0_201]
[16:23:06] :	 [Step 3/5] 	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326) ~[na:1.8.0_201]
[16:23:06] :	 [Step 3/5] 	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276) ~[na:1.8.0_201]
[16:23:06] :	 [Step 3/5] 	at com.vaadin.flow.server.StaticFileServer.resourceIsDirectory(StaticFileServer.java:146) ~[flow-server-8.0-SNAPSHOT.jar:8.0-SNAPSHOT]
[16:23:06] :	 [Step 3/5] 	at com.vaadin.flow.server.StaticFileServer.isStaticResourceRequest(StaticFileServer.java:118) ~[flow-server-8.0-SNAPSHOT.jar:8.0-SNAPSHOT]
[16:23:06] :	 [Step 3/5] 	at com.vaadin.flow.server.VaadinServlet.serveStaticOrWebJarRequest(VaadinServlet.java:343) ~[flow-server-8.0-SNAPSHOT.jar:8.0-SNAPSHOT]
[16:23:06] :	 [Step 3/5] 	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:289) ~[flow-server-8.0-SNAPSHOT.jar:8.0-SNAPSHOT]
[16:23:06] :	 [Step 3/5] 	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:109) ~[vaadin-spring-18.0-SNAPSHOT.jar:na]
[16:23:06] :	 [Step 3/5] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) [tomcat-embed-core-9.0.45.jar:4.0.FR]
```

Seems like Flow is trying to create multiple file system instances for the same zip file which based on this code can never work: https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/19fb8f93c59dfd791f62d41f332db9e306bc1422/src/jdk.zipfs/share/classes/jdk/nio/zipfs/ZipFileSystemProvider.java#L90-L121

Potentially this happens when you make two requests at the same time for the same static resource

### PR DESCRIPTION
**Pull request by caalador**
Fixes issue with multiple concurrent
requests to jar resource.

Fixes #11144

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java [hunk 1]
```diff
@@ -75,6 +78,10 @@
     public static final Pattern APP_THEME_PATTERN = Pattern
             .compile("^\\/themes\\/[\\s\\S]+?\\/");
 
+    // Mapped uri is for the jar file
+    Map<URI, Integer> openFileSystems = new HashMap<>();
+    private ReentrantLock lock = new ReentrantLock();
```
Comment (fluorumlabs) [inline flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java:83]: Could this be replaced with a synchronization marker and `synchronized(...){}` blocks? The `ReentrantLock` seems to be excessive here as the code doesn't really re-enter.

Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java]: changed

File: flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java [hunk 2]
```diff
@@ -160,6 +170,64 @@ private boolean resourceIsDirectory(URL resource) {
...
+            throw new IllegalArgumentException(syntaxException.getMessage(),
+                    syntaxException);
+        }
+    }
+
+    // Package protected for feature verification purpose
+    FileSystem getFileSystem(URI resourceURI) throws IOException {
+        synchronized (fileSystemLock) {
+            URI fileURI = getFileURI(resourceURI);
+            if (openFileSystems.containsKey(fileURI)) {
```
Comment (fluorumlabs) [inline flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java:191]: `Map.computeIfPresent()` seems to suit better here

Comment (fluorumlabs) [inline flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java:191]: At the first glance `Map.computeIfPresent()` suits better this use

File: flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java [hunk 3]
```diff
@@ -160,6 +170,64 @@ private boolean resourceIsDirectory(URL resource) {
...
+            return fileSystem;
+        }
+    }
+
+    // Package protected for feature verification purpose
+    void closeFileSystem(URI resourceURI) {
+        synchronized (fileSystemLock) {
+            try {
+                URI fileURI = getFileURI(resourceURI);
+                if (!openFileSystems.containsKey(fileURI)) {
```
Comment (fluorumlabs) [inline flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java:209]: At the first glance `Map.computeIfPresent` suits better this use as well

File: flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java [hunk 4]
```diff
@@ -75,6 +77,10 @@
     public static final Pattern APP_THEME_PATTERN = Pattern
             .compile("^\\/themes\\/[\\s\\S]+?\\/");
 
+    // Mapped uri is for the jar file
+    Map<URI, Integer> openFileSystems = new HashMap<>();
+    private Object fileSystemLock = new Object();
```
Comment (fluorumlabs) [inline flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java:82]: Makes me thinking... How many `StaticFileServer` instances could be up simultaneously, serving content from same jars? Let's say, if I have two servlets running.

Probably better to make this `static final`

Comment (fluorumlabs) [reply flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java:82]: Same for the Map

File: flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java (hunk 2 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java]: done

File: flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java (hunk 3 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java]: done

File: flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java (hunk 4 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java]: done

File: flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java [hunk 5]
```diff
@@ -160,6 +170,59 @@ private boolean resourceIsDirectory(URL resource) {
                 && Files.isDirectory(Paths.get(resourceURI));
     }
 
+    private URI getFileURI(URI resourceURI) {
+        try {
+            String scheme = resourceURI.getRawSchemeSpecificPart();
```
Comment (mshabarov) [inline flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java:175]: Does the method `getRawSchemeSpecificPart` return the string like `jar:{url}!/`? It's maybe a question to `getRawSchemeSpecificPart` docs, but I expect `scheme` string to contain `jar`, `http`, `file` or other 'scheme' in terms of URI definition. Could you please comment what options can be for 'scheme' variable here (in JAR case in the other cases)? It would really improve the readability.

Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java:175]: The `getRawSchemeSpecificPart` returns it without the `jar:` so only  `file://....` as we at this point know that it is a jar schemed uri that we handle.

File: flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java [hunk 6]
```diff
@@ -160,6 +170,59 @@ private boolean resourceIsDirectory(URL resource) {
...
+            int jarPartIndex = scheme.indexOf("!/");
+            if (jarPartIndex != -1) {
+                scheme = scheme.substring(0, jarPartIndex);
```
Comment (mshabarov) [inline flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java:178]: In case of JAR, what would be the content of 'scheme'? From the code above, it's going to be path to JAR itself, not to the file inside JAR. I propose to reflect it in the method name or in the javadocs to this method, despite it is private.

Comment (mshabarov) [reply flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java:178]: As at this point we certainly know that `resourceURI` pointing to a JAR, maybe it better to name this method `getJarFileURI`?

Comment (mshabarov) [reply flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java:178]: Or, well, it can be used in other places in the code...

Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java:178]: `Components of all URIs: [<scheme>:]<scheme-specific-part>[#<fragment>]` so it has 2 schemes `jar:` and `file:`  so for instance for a resource URI `jar:file:///C:/Users/mikae/AppData/Local/Temp/junit3995612489514253689/fake.jar!/frontend`
The rawSchemeSpecificPart is `file:///C:/Users/mikae/AppData/Local/Temp/junit3995612489514253689/fake.jar!/frontend`  and the end scheme which we generate a new URI for is `file:///C:/Users/mikae/AppData/Local/Temp/junit3995612489514253689/fake.jar`

Comment (mshabarov) [reply flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java:178]: Thanks for clarifications! For me it is something that needs a comment in the code containing similar clarifications like you provided above. But up to you to add it. I've never used `rawSchemeSpecificPart` to be honest and these evolutions of the URI in this method are really hard to understand without some knowledge of `rawSchemeSpecificPart`.

File: flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java (hunk 5 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java:195]: documented method

File: flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java [hunk 7]
```diff
@@ -323,6 +339,193 @@ public void directoryIsNotResourceRequest() throws Exception {
...
+                        } catch (Exception e) {
+                            return new Result(e);
+                        }
+                        return new Result(null);
+                    };
+                    return callable;
+                }).collect(Collectors.toList());
+
+        ExecutorService executor = Executors.newFixedThreadPool(THREADS);
+        List<Future<Result>> futures = executor.invokeAll(folderNotResource);
```
Comment (mshabarov) [inline flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java:444]: not blocking: Not sure this method start the threads simultaneously.
To make the threads call file server concurrently with a higher probability, I would propose to use a synchronisers, for example `CountDownLatch `.

**Review by mshabarov — APPROVED** [review]

File: flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java (hunk 7 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java:444]: It executes 5 threads at once and without the fix the failure rate for the test was 100% of the executions.

Comment (mshabarov) [reply flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java:444]: Thanks! Make sense, so let's ignore my comment then.
