### PR TITLE
fix: Import all document styles using style tags

### LINKED ISSUE #16231: CSSImport does not override Lumo
### Description of the bug

The loading order of CSS described in https://vaadin.com/docs/latest/advanced/css-loading-order is
1. The Lumo theme.
2. Application-specific bundled CSS added with a `@CssImport'.
3. Styles added on the Java side via Page::addStylesheet().
4. Application-specific unbundled CSS added with @StyleSheet.
5. Parent theme.
6. Current theme.

This works as expected when running with Vite except that `@CssImport` does not override the Lumo theme.

image

### Expected behavior

Lumo styles should always be only default styles and everything else should override

### Minimal reproducible example

-

### Versions

- Vaadin / Flow version: 24.0.0

### PR DESCRIPTION
**Pull request by Artur-**
This adds to comments into `<head>`: `CSSImport end` and `Stylesheet end`. The corresponding styles are always inserted right before these comments so the order of CSS imports is maintained, even when you do not add styles in the order that they should override each other.

After this, it should be easy to support hot reload for the theme CSS

Fixes #16231

### CODE REVIEW

File: flow-client/src/main/java/com/vaadin/client/ResourceLoader.java [hunk 1]
```diff
@@ -639,8 +638,27 @@ public void inlineStyleSheet(String styleSheetContents,
 
             addCssLoadHandler(styleSheetContents, event, styleSheetElement);
 
-            getHead().appendChild(styleSheetElement);
+            addBeforeComment(styleSheetElement, "Stylesheet end");
+        }
+    }
+
+    private void addBeforeComment(Element element, String comment) {
+        elemental.dom.Node commentNode = findComment(getHead(), comment);
```
Comment (mshabarov) [inline flow-client/src/main/java/com/vaadin/client/ResourceLoader.java:646]: `commentNode` might be `null` (which signals a bug in the code most likely, because the comment node is expected), so would it be better to fail fast if nothing was found?

File: flow-server/src/main/resources/META-INF/frontend/theme-util.js [hunk 2]
```diff
@@ -42,21 +42,48 @@ const createLinkReferences = (css, target) => {
...
+
+  let beforeThis = undefined;
+  if (referenceComment) {
+    const comments = Array.from(document.head.childNodes).filter(elem => elem.nodeType === Node.COMMENT_NODE);
+    const container = comments.find(comment => comment.data.trim() === referenceComment);
+    if (container) {
+      beforeThis = container;
+    }
+  }
+  document.head.insertBefore(styleTag, beforeThis);
```
Comment (mshabarov) [inline flow-server/src/main/resources/META-INF/frontend/theme-util.js:68]: What does insertBefore do if the beforeThis is undefined? :thinking_face: 
Apparently it doesn't throw error, but will it add the tag to the end?

**Review by mshabarov — CHANGES_REQUESTED** [review]

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java [hunk 3]
```diff
@@ -78,6 +96,11 @@ private JsonObject getBasicStats() {
                     dependency.getValue());
         }
 
+        bundleImports.set(bundleImports.length(),
+                "./generated/jar-resources/theme-util.js");
+        frontendHashes.put("theme-util.js",
```
Comment (mshabarov) [inline flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java:101]: Off-topic: just realised that the refactoring with adding new `theme-util.js` file will trigger app bundle rebuild in the projects after upgrading to 24.0.x. Not a big problem, but good to avoid such a things for 24.0.

Comment (Artur-) [reply flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java:101]: None of this should go into 24.0. Why would it trigger a rebuild when upgrading to 24.1 except for when you use an app specific bundle, and then you rebuilt anyway?

File: flow-server/src/main/resources/META-INF/frontend/theme-util.js (hunk 2 above)
Comment (Artur-) [reply flow-server/src/main/resources/META-INF/frontend/theme-util.js:68]: It will append

Comment (Artur-) [reply flow-server/src/main/resources/META-INF/frontend/theme-util.js:68]: "The node before which newNode is inserted. If this is null, then newNode is inserted at the end of node's child nodes."

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java (hunk 3 above)
Comment (mshabarov) [reply flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java:101]: Yes, right. I thought this fix will target 24.0 as well, but not.

File: flow-client/src/main/java/com/vaadin/client/ResourceLoader.java [hunk 4]
```diff
@@ -639,8 +638,27 @@ public void inlineStyleSheet(String styleSheetContents,
...
+        getHead().insertBefore(element, commentNode);
+    }
+
+    private elemental.dom.Node findComment(HeadElement head, String comment) {
```
[the remark this answers is not in the document]
Comment (Artur-) [reply flow-client/src/main/java/com/vaadin/client/ResourceLoader.java]: Fixed

File: flow-client/src/main/java/com/vaadin/client/ResourceLoader.java (hunk 1 above)
Comment (Artur-) [reply flow-client/src/main/java/com/vaadin/client/ResourceLoader.java]: Added error logging for that case. Sounds better than showing a blank page

**Review by mshabarov — APPROVED** [review]
