### PR TITLE
fix: Tasks are sorted for execution

### LINKED ISSUE #9893: Order of TS code generation and npm install changed
### Description of the bug / feature
With Vaadin 19 alpha 3, the order of npm install and TS code generation is:
1. generate TS code
2. npm install

This enables e.g. using the generated TS code in a postinstall script if you so please

With the latest Flow snapshot, the order is suddenly the other way around:
1. npm install
2. generate TS code

Now using TS code in a postinstall script is impossible

If this is caused by #9839 there does not even seem to be a reason to change the order

### Expected behavior
This is a breaking change that should not be there

### Actual behavior
It should behave like before

### PR DESCRIPTION
**Pull request by caalador**
NodeTasks are now sorted before
execution so that they are always
executed in a predefined order.

Fixes #9893

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java [hunk 1]
```diff
@@ -507,7 +510,29 @@ public Builder withNodeDownloadRoot(URI nodeDownloadRoot) {
...
+        TaskGenerateConnect.class,
+        TaskGenerateBootstrap.class,
+        TaskUpdatePackages.class,
+        TaskRunNpmInstall.class,
+        TaskInstallWebpackPlugins.class,
+        TaskCopyFrontendFiles.class,
+        TaskCopyLocalFrontendFiles.class,
+        TaskUpdateWebpack.class,
+        TaskUpdateImports.class,
+        TaskUpdateThemeImport.class
```
Comment (mshabarov) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java:534]: Awesome to have this order here, because it does not only guard the application behaviour from reordering, but also gives a clarity to the devs how the tasks should go. Great!

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java [hunk 2]
```diff
@@ -557,6 +575,13 @@ private NodeTasks(Builder builder) {
 
         }
 
+        if (builder.createMissingPackageJson) {
```
Comment (mshabarov) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java:578]: Doesn't really matter now, but why is this block has been moved to another place?

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java [hunk 3]
```diff
@@ -667,9 +692,38 @@ private FrontendDependenciesScanner getFallbackScanner(Builder builder,
...
+    /**
+     * Find index of command for which it is assignable to.
+     * @param command command to find execution index for
+     * @return index of command or -1 if not available
+     */
+    private int getIndex(FallibleCommand command) {
+        return IntStream.range(0, commandOrder.size())
+                .filter(i -> commandOrder.get(i)
+                        .isAssignableFrom(command.getClass())).findFirst()
+                .orElse(-1);
```
Comment (mshabarov) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java:727]: If some command from resulted command list is not present in the expected ordering command list, then why not throw the exception?
That might happens when someone adds a new Task for execution, but forgets to add it into the ordering list, and the order of this Task matters.

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java [hunk 4]
```diff
@@ -0,0 +1,97 @@
...
+        commandsField.setAccessible(true);
+        final List<FallibleCommand> commands = (List<FallibleCommand>) commandsField
+                .get(nodeTasks);
+
+        Assert.assertEquals("No commands should be added initially, "
+                        + "update mock builder so that we don't automatically add any tasks!",
+                0, commands.size());
+
+        // Assemble the command list with random order
+        commands.addAll(commandsMock);
```
Comment (mshabarov) [inline flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java:54]: Hmm, does this really modify the field?

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java [hunk 5]
```diff
@@ -0,0 +1,97 @@
...
+                executionOrder.add(command);
+                return null;
+            }).when(mock).execute();
+        }
+
+        Collections.shuffle(commands);
+
+        return commands;
+    }
+}
```
Comment (mshabarov) [inline flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java:97]:
```suggestion
}

```

**Review by mshabarov — COMMENTED** [review]
Awesome to have this order here, because it does not only guard the application behaviour from reordering, but also gives a clarity to the devs how the tasks should go. Great!

One more test for catching the case, when some new Task is added for execution, but not added to ordering, should be added IMO (If I got this feature properly).

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java (hunk 4 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java:54]: It should return the actual instance of the List and it's that List value from the field that we are modifying and not the field itself.

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java (hunk 5 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java:97]: done

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java (hunk 4 above)
Comment (mshabarov) [reply flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java:67]: Yep, got it. Thanks!

**Review by mshabarov — APPROVED** [review]

**Review by mshabarov — APPROVED** [review]

**Comment by mshabarov** [comment]
@caalador does this need to be CP'ed? I assume target/5.0 and target/2.5 ?

**Comment by caalador** [comment]
As the cleanup is not cherry picked to any version this should not be picked either.
