### PR TITLE
fix: order only dependencies inside package.json

### LINKED ISSUE #11294: Do not sort main keys in package.json
### Description of the bug / feature
Please do not touch the main keys of `package.json`. The order that `npm init` creates the keys is just fine, you should not sort those alphabetically. `npm install` also only sorts the dependencies, I have never seen it change the other parts of `package.json`

This has apparently been introduced as a side effect of #7431 

### Minimal reproducible example
```
vaadin init --pre packagejson
cd packagejson
mvn
```

### Expected behavior
The `name` field should still be first in `package.json`

### Actual behavior
The `name` field is moved below `dependencies` and `devDependencies`

### Versions:
    - Vaadin / Flow version: 21 alpha 7

### PR DESCRIPTION
**Pull request by denis-anisimov**
fixes #11294

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java [hunk 1]
```diff
@@ -253,6 +254,13 @@ JsonObject getPackageJson() throws IOException {
             packageJson.put(DEP_LICENSE_KEY, DEP_LICENSE_DEFAULT);
             packageJson.put(DEPENDENCIES, Json.createObject());
             packageJson.put(DEV_DEPENDENCIES, Json.createObject());
+        } else {
+            if (!packageJson.hasKey(DEPENDENCIES)) {
+                packageJson.put(DEPENDENCIES, Json.createObject());
+            }
+            if (!packageJson.hasKey(DEV_DEPENDENCIES)) {
+                packageJson.put(DEV_DEPENDENCIES, Json.createObject());
+            }
```
Comment (caalador) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java:263]: Why do we specifically need these?
Would probably be better to remove both from the null case and have a `addDefaultObjects(packageJson)`
```
    static void addDefaultObjects(JsonObject json) {
        computeIfAbsent(json, DEPENDENCIES, Json::createObject);
        computeIfAbsent(json, DEV_DEPENDENCIES, Json::createObject);
   }
```

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java [hunk 2]
```diff
@@ -125,7 +125,31 @@ public void execute() {
...
+            sortObject(deps);
+        }
+        if (json.hasKey(DEV_DEPENDENCIES)) {
+            JsonObject deps = json.get(DEV_DEPENDENCIES);
+            sortObject(deps);
+        }
+        if (json.hasKey(VAADIN_DEP_KEY)) {
+            JsonObject vaadin = json.get(VAADIN_DEP_KEY);
+            sortObject(vaadin);
+        }
```
Comment (caalador) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java:139]: sortObject should handle the check so we would here only have
```
sortObject(json, DEPENDENCIES);
sortObject(json, DEV_DEPENDENCIES);
sortObject(json, VAADIN_DEP_KEY);
```

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java [hunk 3]
```diff
@@ -125,7 +125,31 @@ public void execute() {
...
+    private void sortObject(JsonObject object) {
+        JsonObject ordered = orderKeys(object);
+        for (String key : object.keys()) {
+            object.remove(key);
+        }
+        // add ordered keys back
+        for (String key : ordered.keys()) {
+            JsonValue value = ordered.get(key);
+            object.put(key, value);
+        }
```
Comment (caalador) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java:152]: I would rather than removing and adding just create a new object and set that
```
private void sortObject(JsonObject json, String key) {
  if(json.hasKey(key)) {
    json.put(key, orderKeys(json.get(key)));
  }
}
```

**Review by caalador — CHANGES_REQUESTED** [review]

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java (hunk 1 above)
Comment (denis-anisimov) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java:263]: done

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java (hunk 2 above)
Comment (denis-anisimov) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java:139]: done

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java (hunk 3 above)
Comment (denis-anisimov) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java:152]: If you are talking about adding and creating an object for `dependencies` and other keys then you are breaking the order via adding and removing.
-Removing will remove the object.
-Adding will add it into the end.

So adding and removing is _exactly_ what I'm trying to avoid here: I don't want to break the existing order which is exactly one of the complains in the ticket.

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java [hunk 4]
```diff
@@ -125,7 +125,24 @@ public void execute() {
...
+            return;
+        }
+        JsonObject object = json.get(key);
+        JsonObject ordered = orderKeys(object);
+        Stream.of(object.keys()).forEach(object::remove);
+        // add ordered keys back
+        Stream.of(ordered.keys()).forEach(prop -> {
+            JsonValue value = ordered.get(prop);
+            object.put(prop, value);
+        });
```
Comment (caalador) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java:145]: What is the added value of removing and adding the values when we already have the correct ordered object?

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java (hunk 3 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java]: Still shouldn't they always stay in the order          DEPENDENCIES - DEV_DEPENDENCIES - VAADIN_DEP_KEY
as they are always set in that order. 
But I guess they might expect moving them around wouldn't make us touch the top object ordering.

**Review by caalador — APPROVED** [review]
