### PR TITLE
Don't handle dynamic resources by the DevModeHandler

### LINKED ISSUE #8500: File download via StreamResource not working when the file name contains one or more spaces
### Description of the bug
File download via StreamResource not working when the file name contains one or more spaces. Spring Boot with `vaadin-spring-boot-starter` is used.

It seems #5360 causes the issue.

### Minimal reproducible example
[stream-resource-demo.zip](https://github.com/vaadin/flow/files/4729484/stream-resource-demo.zip)

### Expected behavior
File download is working

### Actual behavior
HTTP 400 Bad Request

### Versions:
    - Vaadin version: 16.0.0
    - Spring Boot: 2.2.6
    - Java version: 11
    - OS version: MacOS
    - Browser version: Chrome 80

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #8500

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java [hunk 1]
```diff
@@ -117,8 +117,8 @@ public boolean handleRequest(VaadinSession session, VaadinRequest request,
     }
 
     /**
-     * Parse the pathInfo for id data.
-  s   * <p>
+     * Parse the pathInfo for id data. s *
```
Comment (caalador) [inline flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java:120]: This seems like a simm type of someone (probably me) going for a save with ctrl+s so it should just be cleaned away.
