### PR TITLE
fix: don't set text based on template parsing data

### LINKED ISSUE #10106: All content of a @Id mapped element are removed from the DOM
### Description of the bug / feature
If you have a template / component that modifies its child elements dynamically, you cannot use it with a `LitTemplate` as Flow will remove all the created children.

### Minimal reproducible example

```java
@JsModule("./views/empty/empty-view.ts")
@Tag("empty-view")
public class EmptyView extends LitTemplate {

    @Id
    private Div root;
}
```

```ts
import { customElement, html, LitElement, PropertyValues, query } from "lit-element";

@customElement("empty-view")
export class EmptyView extends LitElement {
  @query("#root")
  private root!: HTMLElement;

  createRenderRoot() {
    // Do not use a shadow root
    return this;
  }
  render() {
    return html`<div id="root"></div>`;
  }

  protected firstUpdated(_changedProperties: PropertyValues) {
    super.firstUpdated(_changedProperties);
    this.root.innerText = "Hello";
  }
}
```

### Expected behavior
You see "Hello" in the view

### Actual behavior
The view is empty. If you remove the `@Id` mapping, then you see "Hello"

### Versions:
    - Vaadin / Flow version: 18

### PR DESCRIPTION
**Pull request by denis-anisimov**
If @Id-mapped component has no children then it gets the text from the template which is
an empty string in many cases. This may break the content of the comonent when the
content is set on the client side (e.g. Lit template without shadow root).

fixes #10106

### CODE REVIEW

File: flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/ChildOrderIT.java [hunk 1]
```diff
@@ -163,28 +163,29 @@ public void prependTextsFromServer_textsAreAddedBeforeExistingOnes() {
         assertNodeOrder(container, "Client text");
 
         clickAndWaitForContainerToChange(container, "prependChildToContainer2");
-        assertNodeOrder(container, "Server text 1Client text");
+        assertNodeOrder(container, "Client text", "Server text 1");
```
Comment (caalador) [inline flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/ChildOrderIT.java:166]: Why has the order changed so that server text is appended when it should be prepended as per test name and click target?

**Review by caalador — CHANGES_REQUESTED** [review]

File: flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/ChildOrderIT.java (hunk 1 above)
Comment (denis-anisimov) [reply flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/ChildOrderIT.java:166]: I don't know about the test name: this is a revert.
The behavior is exactly the same as it was before introducing parsing template and set Text value:
https://github.com/vaadin/flow/blob/b735ebb640416bd84a6dc519ca2deb5811592779/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/ChildOrderIT.java#L166

Comment (caalador) [reply flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/ChildOrderIT.java:166]: Thanks. Yes the naming is confusing, but the PR explains it clearer that it prepends server texts, but client is always first:
```
* Change the order of how nodes are attached to the client Now the index 0 considers the first server-side mapped node after all
the client-side-only nodes. * Add a test with DOM manipulation from the CTOR.
```

**Review by caalador — APPROVED** [review]
