### PR TITLE
fix: delay requests to dev-server during restart

### LINKED ISSUE #17006: java.net.ConnectException: Connection refused when vite is restarting
### Description of the bug

It seems like any incoming request causes a long stack trace like
```
java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:673) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:535) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:585) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:666) ~[na:na]
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:532) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:637) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:783) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1672) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1581) ~[na:na]
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529) ~[na:na]
	at com.vaadin.base.devserver.AbstractDevServerRunner.serveDevModeRequest(AbstractDevServerRunner.java:713) ~[vaadin-dev-server-24.1.0.jar:na]
	at com.vaadin.flow.server.StaticFileServer.serveStaticResource(StaticFileServer.java:254) ~[flow-server-24.1.0.jar:24.1.0]
	at com.vaadin.flow.server.VaadinServlet.serveStaticOrWebJarRequest(VaadinServlet.java:430) ~[flow-server-24.1.0.jar:24.1.0]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:385) ~[flow-server-24.1.0.jar:24.1.0]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:106) ~[vaadin-spring-24.1.0.jar:na]
```

if the request comes in when the Vite server is being restarted. In this case, the log before the stack trace was
```
2023-06-12T16:57:56.397+03:00  INFO 29776 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [vite] target/vaadin-dev-server-settings.json changed, restarting server...
2023-06-12T16:57:56.397+03:00  INFO 29776 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [vite] vite.generated.ts changed, restarting server...
2023-06-12T16:57:56.432+03:00  INFO 29776 --- [io-25497-exec-4] c.vaadin.flow.spring.SpringInstantiator  : The number of beans implementing 'I18NProvider' is 0. Cannot use Spring beans for I18N, falling back to the default behavior
2023-06-12T16:57:57.597+03:00 ERROR 29776 --- [io-25497-exec-6] o.a.c.c.C.[.[.[/].[springServlet]        : Servlet.service() for servlet [springServlet] threw exception
```

### Expected behavior

A request that comes in while the Vite server is restarting should wait until the Vite server is restarted, and then be handled normally

### Minimal reproducible example

````
npx @vaadin/cli init hello
cd hello
mvn
```

When started, in another terminal
```
touch vite.generated.ts &&  while [ 1 ] ; do  curl http://localhost:8080 ; done
```


### Versions

- Vaadin / Flow version: 24.1.0

### PR DESCRIPTION
**Pull request by mcollovati**
## Description

The dev-server may restart itself when some resources are modified. In this situation incoming requests fails with a connection exception until the server is ready again.
This change introduces a check that delays requests that happen during dev-server restart until the reboot operation has completed.

Fixes #17006

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+/**
+ * Monitors for dev server restarts.
+ *
+ * Analyzes dev server logs lines to identify restarts.
+ *
+ * Allows to block an execution when a restart is happening and to resume it
```
Comment (mshabarov) [inline vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java:32]:
```suggestion
 * Allows to block dev-server requests processing when a restart is happening and to resume it
```

File: vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+    void parseLine(String line) {
+        if (restarting.matcher(line).find()) {
+            serverRestarting();
+        } else if (restarted.matcher(line).find()) {
+            serverRestarted();
+        }
+    }
+
+    /**
+     * Blocks execution during dev-server restarts.
```
Comment (mshabarov) [inline vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java:68]:
```suggestion
     * Blocks requests to dev-server during dev-server restarts.
```

File: vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevServerOutputTracker.java [hunk 3]
```diff
@@ -191,16 +209,56 @@ public DevServerOutputTracker(InputStream inputStream, Pattern success,
             }
             monitor.countDown();
         });
+    }
 
+    /**
+     * Gets a guard object that blocks the current execution when dev-server is
```
Comment (mshabarov) [inline vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevServerOutputTracker.java:215]:
```suggestion
     * Gets a guard object that blocks the current request to dev-server when dev-server is
```

File: vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java [hunk 4]
```diff
@@ -0,0 +1,115 @@
...
+     */
+    public void waitForServerReady() {
+        lock.lock();
```
Comment (mshabarov) [inline vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java:71]: Just an idea: what happens if restart of the dev-server fails (e.g. because of TS compilation errors), would the http request thread be waiting infinitely? Maybe we can lock the thread with a timeout after which the thread can just continue and give not found to the browser?

File: vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java [hunk 5]
```diff
@@ -0,0 +1,115 @@
...
+ *
+ * Analyzes dev server logs lines to identify restarts.
+ *
+ * Allows to block an execution when a restart is happening and to resume it
+ * once the restart is completed.
+ */
+class RestartMonitor {
+    private final Lock lock = new ReentrantLock();
+    private final Condition serverRestartedCondition = lock.newCondition();
+    private boolean serverRestarting = false;
```
Comment (mshabarov) [inline vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java:38]: Should it be `volatile` ? I don't remember if Lock synchronisation is enough for visibility.

**Review by mshabarov — CHANGES_REQUESTED** [review]
Minor suggestions before making a local testing.

File: vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java (hunk 5 above)
Comment (mcollovati) [reply vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java:38]: It should not be required IIRC, but we can make it `volatile` anyway

File: vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java (hunk 4 above)
Comment (mcollovati) [reply vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java:71]: The restart pattern catches both successful and failed restarts, so the request should never be blocked indefinitely.
Furthermore, the lock is held for a minimum amount of time, just to update the `serverRestarting` variable.
But if we want to be sure, we can set a timeout when waiting on the condition (`serverRestartedCondition.await()`)

Comment (mshabarov) [reply vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java:71]: > The restart pattern catches both successful and failed restarts, so the request should never be blocked indefinitely.

Ok, then I think nothing to worry about.

Comment (mcollovati) [reply vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java:71]: Requests may hang if Vite server crashes, but then you need to restart the application anyway.
But a sensible timeout makes sense. I'll add it

**Review by mshabarov — APPROVED** [review]
Cannot see the problem anymore with this patch. Excellent fix 👍

**Review by mshabarov — APPROVED** [review]
