### PR TITLE
fix!: Revert always load static files from context root (#13795)

### LINKED ISSUE #13190: absolute /VAADIN path for scripts rerefenced by index.html with custom servlet mapping
### Description of the bug
In development mode, `<head>` contains scripts with absolute `/VAADIN/` prefix, e.g.:

```html
<script type="module" src="/VAADIN/@vite/client"></script>
<script type="module" src="/VAADIN/generated/vaadin.ts"></script>
<script type="module" src="/VAADIN/generated/vite-devmode.ts"></script>
```

This only works when Vaadin servlet is mapped to root (`/*`), but fails to load script when a custom servlet mapping (eg `/vaadin/*`) is used, resulting in a blank page.
Problem appears in both plain java (`@WebServlet(urlPatterns=...)`) and spring boot based projects (`vaadin.urlMapping` setting)

To be noted that trying to access resources prepending url mapping does not works for all of them. For example, giving a `/vaadin/*` mapping,  `/vaadin//VAADIN/generated/vaadin.ts` and `/vaadin/VAADIN/generated/vite-devmode.ts` work, but `/vaadin/VAADIN/@vite/client` returns 404.

Similar ticket related to context-path: #12388

### Minimal reproducible example

To reproduce 
- create a new Vaadin 23 project with start.vaadin.com, activating Vite for frontend build
- update `application.properties`, setting a custom url mapping (e.g. `vaadin.urlMapping=/vaadin/*`)
- start application, go http://localhost:8888/vaadin/ and observe that requests starting with /VAADIN results in a 404.

Alternative way to reproduce
- Download plain java starter from https://github.com/vaadin/skeleton-starter-flow
- Add a custom servlet to the projet
   ```java
   @WebServlet(urlPatterns = {"/vaadin/*" }, asyncSupported=true)
   public class MyServlet extends VaadinServlet {
   }
   ```
- Activate Vite support by adding the file `src/main/resources/vaadin-featureflags.properties` with the following content
  ```
  com.vaadin.experimental.viteForFrontendBuild=true
  ```
- start application with `mvn jetty:run`, go http://localhost:8888/vaadin/ and observe that requests starting with /VAADIN results in a 404. 

### Expected behavior

An application configured to use Vite for frontend build should work also with custom servlet mapping.

### Actual behavior

Scripts referenced in index.html are not loaded (HTTP 404) and a blank page is shown.

### Versions:
    - Vaadin / Flow version: 23
    - Java version: 11.0.13
    - OS version: Ubuntu 21.10
    - Development or production mode: development

### PR DESCRIPTION
**Pull request by mshabarov**
Changes static files loading so that:
1. The overall behavior is reverted to that in 23.0, i.e. static files are loaded from /context/servlet/VAADIN instead of /context/VAADIN
2. When using Vite in dev mode, uses the first deployed `VaadinServlet` to serve static resources. If you have both a `/foo/*` and a `/bar/*`mapped servlet, then if `/foo` is the servlet deployed first, also `/bar/` requests will use `/foo/VAADIN` for static resources.

This reverts commit af975389 

Fixes https://github.com/vaadin/flow/issues/14239
Fixes #13190

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java [hunk 1]
```diff
@@ -126,12 +138,47 @@ public void init(ServletConfig servletConfig) throws ServletException {
...
+                        List<String> mappings = new ArrayList<>();
+                        Map<String, ? extends ServletRegistration> servletRegistrations = this
+                                .getServletContext().getServletRegistrations();
+                        if (servletRegistrations != null
+                                && !servletRegistrations.isEmpty()) {
+                            // This should only happen in unit tests
+                            mappings.addAll(servletRegistrations
+                                    .get(this.getServletName()).getMappings());
+                            frontendMapping = mappings.get(0);
+                            Collections.sort(mappings);
```
Comment (taefi) [inline flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java:163]: Is there a need for this `mapping` local variable to be sorted?

File: flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java [hunk 2]
```diff
@@ -548,4 +595,13 @@ private VaadinServletContext initializeContext() {
         return vaadinServletContext;
     }
 
+    /**
+     * For internal use only.
+     *
+     * @return the first vaadin servlet that was reqistered
+     */
+    public static String getFirstMapping() {
+        return frontendMapping;
```
Comment (taefi) [inline flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java:604]: Just a minor suggestion: would it make sense to create uniformity between the field name and its getter (to rename either of them, most likely the field)? It seems we just pick the first mapping from the list of mappings, and then we call it `frontendMapping`, but having a field named this way somehow implies that you could specifically set the `frontendMapping` unless you read the `public void init(ServletConfig servletConfig)` method implementation.

**Review by taefi — APPROVED** [review]

File: flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java (hunk 1 above)
Comment (taefi) [inline flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java:163]: Is there a need for this `mappings` local variable to be sorted?

**Review by taefi — CHANGES_REQUESTED** [review]

File: flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java (hunk 1 above)
Comment (Artur-) [reply flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java:163]: Well ... the mapping should obviously be sorted before `mappings.get(0)`... It is a way to ensure that `frontendMapping` is deterministic as `getMappings()` return a set.

Comment (Artur-) [reply flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java:162]: Changed

File: flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java (hunk 2 above)
Comment (Artur-) [reply flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java:604]: Renamed to `frontendMapping`. Spring sets this through a property and being able to set "the first deployed servlet mapping" makes no sense

**Review by taefi — APPROVED** [review]

**Comment by mshabarov** [comment]
Got these errors when running 23.2.0.beta2 starter with this patch:

```
NetworkOnly.js:93 Uncaught (in promise) no-response: The strategy could not generate a response for 'http://localhost:54524/VAADIN/'. The underlying error is TypeError: Failed to fetch.
    at NetworkOnly._handle (http://localhost:8080/sw.js:3617:19)
    at async NetworkOnly._getResponse (http://localhost:8080/sw.js:1642:24)
```

So it requests `http://localhost:54524/VAADIN/` for some reason and fails.

**Comment by taefi** [comment]
Tested #14239 with the changes in this PR, and it works as expected.

**Comment by Artur-** [comment]
> Got these errors when running 23.2.0.beta2 starter with this patch:
> 
> ```
> NetworkOnly.js:93 Uncaught (in promise) no-response: The strategy could not generate a response for 'http://localhost:54524/VAADIN/'. The underlying error is TypeError: Failed to fetch.
>     at NetworkOnly._handle (http://localhost:8080/sw.js:3617:19)
>     at async NetworkOnly._getResponse (http://localhost:8080/sw.js:1642:24)
> ```
> 
> So it requests `http://localhost:54524/VAADIN/` for some reason and fails.

Vite 3 uses `/VAADIN` and the Vite port as its ping URL (see #13826) so you see this error at least if you shut down the server while keeping the app open. Not sure why you would see it otherwise but also it should have nothing at all to do with this PR

**Comment by mshabarov** [comment]
https://github.com/vaadin/flow/issues/14227 is not solved, but let's fix it in a separate PR.

**Review by taefi — APPROVED** [review]
