### PR TITLE
fix: fail fast if view defines same path for route and route alias

### LINKED ISSUE #19972: Hotswap exception when updating a route class with matching Route  and RouteAlias
### Description of the bug

When modifying this class from a starter project
```
@PageTitle("Hello World")
@Route(value = "", layout = MainLayout.class)
@RouteAlias(value = "", layout = MainLayout.class)
public class HelloWorldView extends HorizontalLayout {

    private TextField name;
    private Button sayHello;

    public HelloWorldView() {
        name = new TextField("Your name29");
```
by changing the "name29" text, the hotswap operation does not complete but throws the following exception. As a result, the view in the browser is not updated without a manual refresh

```
com.vaadin.flow.server.AmbiguousRouteConfigurationException: Navigation targets must have unique routes, found navigation targets 'com.example.application.views.helloworld.HelloWorldView' and 'com.example.application.views.helloworld.HelloWorldView' with the same route.
	at com.vaadin.flow.router.internal.RouteSegment.ambigousException(RouteSegment.java:806)
	at com.vaadin.flow.router.internal.RouteSegment.ambigousTarget(RouteSegment.java:801)
	at com.vaadin.flow.router.internal.RouteSegment.setRouteTarget(RouteSegment.java:487)
	at com.vaadin.flow.router.internal.RouteSegment.addSubRoute(RouteSegment.java:458)
	at com.vaadin.flow.router.internal.RouteSegment.addSubRoute(RouteSegment.java:267)
	at com.vaadin.flow.router.internal.RouteModel.addRoute(RouteModel.java:130)
	at com.vaadin.flow.router.internal.ConfigureRoutes.setRoute(ConfigureRoutes.java:175)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.lambda$setRoute$2df6994$1(AbstractRouteRegistry.java:406)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.lambda$configureWithFullTemplate$ccc9e4ad$1(AbstractRouteRegistry.java:457)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.configure(AbstractRouteRegistry.java:120)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.configureWithFullTemplate(AbstractRouteRegistry.java:456)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.setRoute(AbstractRouteRegistry.java:404)
	at com.vaadin.flow.server.startup.ApplicationRouteRegistry.setRoute(ApplicationRouteRegistry.java:130)
	at com.vaadin.flow.router.RouteConfiguration.setAnnotatedRoute(RouteConfiguration.java:231)
	at com.vaadin.flow.router.internal.RouteUtil.lambda$updateRouteRegistry$14(RouteUtil.java:520)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:174)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.vaadin.flow.router.internal.RouteUtil.lambda$updateRouteRegistry$923b90d8$1(RouteUtil.java:515)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.update(AbstractRouteRegistry.java:131)
	at com.vaadin.flow.router.internal.RouteUtil.updateRouteRegistry(RouteUtil.java:503)
	at com.vaadin.flow.router.internal.RouteRegistryHotswapper.onClassLoadEvent(RouteRegistryHotswapper.java:68)
	at com.vaadin.flow.hotswap.Hotswapper.onHotswapInternal(Hotswapper.java:194)
	at com.vaadin.flow.hotswap.Hotswapper.onHotswap(Hotswapper.java:136)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```

### Expected behavior

It works

### Minimal reproducible example

npm init vaadin@latest
"Debug using HotswapAgent" in IntelliJ 
Modify the view

### Versions

Hilla: 24.5-SNAPSHOT
Flow: 24.5-SNAPSHOT
Vaadin: 24.5-SNAPSHOT
Copilot: 24.5-SNAPSHOT
Frontend Hotswap: Disabled, using pre-built bundle
OS: aarch64 Mac OS X 14.6.1
Java: JetBrains s.r.o. 21.0.3
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Java Hotswap: false
IDE Plugin: ☑ 1.0.0.eap42

### PR DESCRIPTION
**Pull request by mcollovati**
Currently, if a view defines `@Route` and `@RouteAlias` with the same path, the alias is rejected at startup, but there is no evidence of the error.
However, when hot swap is enabled and the view class is reloaded, an exception is thrown.
This change adds an explicit check for duplicate paths, preventing the application from starting if the configuration is invalid.

Fixes #19972

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java [hunk 1]
```diff
@@ -96,6 +100,30 @@ private void checkForConflictingAnnotations(VaadinContext context,
 
         }
 
+        Route routeAnnotation = route.getAnnotation(Route.class);
+        RouteAlias[] aliases = route.getAnnotationsByType(RouteAlias.class);
+        if (routeAnnotation != null && aliases.length > 0) {
```
Comment (caalador) [inline flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java:105]: Technically we don't need the routeAnnotation != null as the inital if checks that the class has a route if there are aliases.

**Review by caalador — APPROVED** [review]

File: flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java (hunk 1 above)
Comment (mcollovati) [reply flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java:105]: I did the check because it is done also in `validateRouteAnnotation`, called later in the method

**Review by caalador — APPROVED** [review]
