### PR TITLE
fix: remove use of commons-io in dev-server

### LINKED ISSUE #22858: PiT 25.0: c.v.b.devserver.AbstractDevServerRunner.handleRequestInternal uses commons-io
### Description of the bug

In linux I can get this error:

```
java.lang.ClassNotFoundException: org.apache.commons.io.IOUtils
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[na:na]
	at com.vaadin.base.devserver.AbstractDevServerRunner.handleRequestInternal(AbstractDevServerRunner.java:684) ~[vaadin-dev-server-25.0.0-beta8.jar:na]
```

You can see that the [AbstractDevServerRunner](https://github.com/vaadin/flow/blob/main/vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java#L41) there are references to commons-io

### Expected behavior

No commons-io usage

### Minimal reproducible example

1. In linux, clone the repo, bump versions and add vaadin-dev
```
git clone git@github.com:vaadin/flow-spring-examples.git
cd flow-spring-examples
perl -pi -e 's|(\s*<'vaadin.version'>)[^\s]+(</'vaadin.version'>)|${1}25.0.0-beta8${2}|g' pom.xml
perl -0777 -pi -e 's|(\n[ 	]*)(</dependencies>\s+(<build>\|<repo\|<dependencyM))|$1 <dependency>$1 <groupId>com.vaadin</groupId>$1 <artifactId>vaadin-dev</artifactId>$1 <scope>compile</scope>$1 </dependency>$1$2|' pom.xml
perl -0777 -pi -e 's|(\s+)(<parent>\s*<groupId>)(org.springframework.boot)(</groupId>\s*<artifactId>)(spring-boot-starter-parent)(</artifactId>\s*)(?:(<version>)([^<]+)(</version>))?(\s*)(.*?)?(\s*</parent>)|${1}${2}'org.springframework.boot'${4}'spring-boot-starter-parent'${6}${7}4.0.0${9}${10}${11}${12}|msg' pom.xml
```

2. diff should lookg like:

```
-        <java.version>17</java.version>
-        <vaadin.version>24.9.6</vaadin.version>
+        <java.version>21</java.version>
+        <vaadin.version>25.0.0-beta8</vaadin.version>
-        <version>3.5.8</version>
+        <version>4.0.0</version>
+        <dependency>
+            <groupId>com.vaadin</groupId>
+            <artifactId>vaadin-dev</artifactId>
+            <scope>compile</scope>
+        </dependency>
```

3. run mvn, there are errors

```
java.lang.ClassNotFoundException: org.apache.commons.io.IOUtils
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[na:na]
	at com.vaadin.base.devserver.AbstractDevServerRunner.handleRequestInternal(AbstractDevServerRunner.java:684) ~[vaadin-dev-server-25.0.0-beta8.jar:na]
```

### Versions

- Vaadin / Flow version:  25.0.0-beta8

### PR DESCRIPTION
**Pull request by caalador**
Remove the usage of commons-io
in vaadin-dev-server module as
it is not required and has been
comming from transitive dependency.

Fixes #22858

### CODE REVIEW

File: vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java [hunk 1]
```diff
@@ -179,7 +178,7 @@ static void run(String command, String... arguments)
         Process process = pb.start();
         int exitCode = process.waitFor();
         if (exitCode != 0) {
-            String output = IOUtils.toString(process.getInputStream(),
+            String output = new String(process.getInputStream().readAllBytes(),
```
Comment (mcollovati) [inline vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java]: nit: can use `StringUtil.toUTF8String(process.getInputStream())`

not a blocker anyway

**Review by mcollovati — APPROVED** [review]

File: vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java (hunk 1 above)
Comment (caalador) [reply vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java]: Changed. It is a bit cleaner.
