### PR TITLE
fix: handle service worker content in production mode when running on non root servlet mapping (#13073)

### LINKED ISSUE #13073: vaadin-spring: service worker not served in production mode when setting vaadin.urlMapping
### Description of the bug

When setting `vaadin.urlMapping` property to move Vaadin url to something different from root path (eg `/vaadin/*`) and running application in production mode, the request to the service worker js file (`sw.js`) fails and an error is reported in browser console

```
The script has an unsupported MIME type ('text/html').
localhost/:1 Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('http://localhost:8080/vaadin/') with script ('http://localhost:8080/vaadin/sw.js'): The script has an unsupported MIME type ('text/html').
```

Trying to access `http://localhost:8080/vaadin/sw.js` url, results in a page with the following content and 404 status code
```
Could not navigate to 'sw.js'
```

### Expected behavior

When setting `vaadin.urlMapping=/vaadin/*` service worker content should be available at `http://localhost:8080/vaadin/sw.js` URL.

### Minimal reproducible example

* Create an app with a public view at start.vaadin.com
* Add `vaadin.urlMapping=/vaadin/*` to your application.properties file
* Build for production with `./mvnw package -Pproduction`
* Run the application (e.g. `java -jar target/myapp-1.0-SNAPSHOT.jar`)
* Access Vaadin app from `http://localhost:8080/vaadin/` and check browser console for errors
  or directly access `http://localhost:8080/vaadin/sw.js`

### Versions

- Vaadin / Flow version: 22.0.5
- Java version: 11.0.13
- OS version: Ubuntu 21.10
- Browser version (if applicable): Chrome 98
- Application Server (if applicable): Tomcat (embedded in Spring Boot)
- IDE (if applicable):

### PR DESCRIPTION
**Pull request by mcollovati**
## Description

In production mode service worker content is loaded from `META-INF/VAADIN/webapp/sw.js` classpath resource. When running on a "non root" servlet mapping, sw.js was not served at all because servlet path was prepended to file name when getting resource from classpath.
This change handles the special case of "sw.js" in `StaticFileServer.getRequestFilename`, in order to ignore servlet path on the returned file name.

Fixes #13073

## Type of change

- [X] Bugfix
- [ ] Feature

## Checklist

- [X] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [X] I have added a description following the guideline.
- [X] The issue is created in the corresponding repository and I have referenced it.
- [X] I have added tests to ensure my change is effective and works as intended.
- [X] New and existing tests are passing locally with my change.
- [X] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java [hunk 1]
```diff
@@ -441,10 +441,15 @@ String getRequestFilename(HttpServletRequest request) {
...
+        //
+        // http://localhost:8888/context/servlet/sw.js
+        // ->
+        // /sw.js
         if (request.getPathInfo() == null) {
             return request.getServletPath();
         } else if (request.getPathInfo().startsWith("/" + VAADIN_MAPPING)
-                || APP_THEME_PATTERN.matcher(request.getPathInfo()).find()) {
+                || APP_THEME_PATTERN.matcher(request.getPathInfo()).find()
+                || request.getPathInfo().startsWith("/sw.js")) {
```
Comment (Artur-) [inline flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java:452]: Does this only concern sw.js or is it a more generic problem? What about the webmanifest etc?

Comment (mcollovati) [reply flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java:452]: In production jar, under `META-INF/VAADIN/webapp/` we seem to only have `sw.js(.gz)` and `index.html(.gz)`; the latter is served by `IndexHtmlRequestHandler`
Other resources seems to be handled by specific `RequestHandler`s, such as `PwaHandler` for webmanifest, sw-runtime-resources-precache.js, offline-stub.html, ....
So it seems to me we only need to add handling for `sw.js`

Comment (Artur-) [reply flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java:452]: It sounds like we are placing `sw.js` in the wrong folder if we need this but if it fixes the issue, it fixes the issue..

**Review by Artur- — APPROVED** [review]
