### PR TITLE
fix: Fall back to InternalServerError when error view rendering fails

### LINKED ISSUE #22146: MainLayout unresponsive after unhandled exception in afterNavigation()
### Description of the bug

While somewhat esoteric, any code in 'afterNavigation' could still throw an exception.
This then navigates to an error view ("HasErrorParameter<Exception>") to display the error, which itself may be annotated
@ParentLayout(MainLayout.class).
If said MainLayout.class derives from AppLayout we can still see the typical navigation around the error display.
However, the navigation is no longer responsive.

### Expected behavior

We expect the navigation to work.

### Minimal reproducible example

See attachment.

### Versions

- Vaadin / Flow version: 24.8.7
- Java version: 21
- OS version: n/a
- Browser version (if applicable): n/a
- Application Server (if applicable): n/a
- IDE (if applicable): n/a

### PR DESCRIPTION
**Pull request by Artur-**
Prevents navigation corruption when error view's parent layout throws an exception during afterNavigation by catching the exception and rendering InternalServerError as fallback.

Fixes #22146

### CODE REVIEW

File: flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java [hunk 1]
```diff
@@ -4697,4 +4697,65 @@ private void navigate(String url) {
...
+    @Layout
+    public static class ThrowingMainLayout extends Component
+            implements RouterLayout, AfterNavigationObserver {
+
+        static List<AfterNavigationEvent> events = new ArrayList<>();
+
+        @Override
+        public void afterNavigation(AfterNavigationEvent event) {
+            events.add(event);
+            if (event.getLocation().getPath().equals("error")) {
```
Comment (Artur-) [inline flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java]:
```suggestion
            if (true) {
```

Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java]: doesn't need the if at all. Can just throw the exception.

File: flow-server/src/main/java/com/vaadin/flow/router/Router.java [hunk 2]
```diff
@@ -303,7 +303,31 @@ private int handleExceptionNavigation(UI ui, Location location,
...
-            return handler.handle(navigationEvent);
+            try {
+                return handler.handle(navigationEvent);
+            } catch (Exception errorHandlingException) {
+                // Error view threw an exception - fall back to
+                // InternalServerError
+                LoggerFactory.getLogger(Router.class).error(
+                        "Exception occurred while rendering error view for '{}'. "
+                                + "Falling back to InternalServerError.",
+                        location.getPath(), errorHandlingException);
```
Comment (caalador) [inline flow-server/src/main/java/com/vaadin/flow/router/Router.java]: The original exception should also be logged as now it will disappear and only the exception failing the exception view rendering is logged.

File: flow-server/src/main/java/com/vaadin/flow/router/Router.java [hunk 3]
```diff
@@ -289,23 +290,52 @@ private int handleExceptionNavigation(UI ui, Location location,
         Optional<ErrorTargetEntry> maybeLookupResult = getErrorNavigationTarget(
                 exception);
 
-        if (maybeLookupResult.isPresent()) {
-            ErrorTargetEntry lookupResult = maybeLookupResult.get();
+        if (maybeLookupResult.isEmpty()) {
+            // No error target available throw runtime exception
+            // this is usually only possible when routeRegistry is not
+            // ApplicationRouteRegistry
+            throw new RuntimeException(exception);
```
Comment (mcollovati) [inline flow-server/src/main/java/com/vaadin/flow/router/Router.java]: nit: it would be good to add a message to the exception to make debug easier.

File: flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java [hunk 4]
```diff
@@ -4697,4 +4697,63 @@ private void navigate(String url) {
...
+                "Navigation should complete with internal server error status.",
+                HttpStatusCode.INTERNAL_SERVER_ERROR.getCode(), result);
+
+        // Should fall back to InternalServerError instead of the custom error
+        // view
+        assertExceptionComponent(InternalServerError.class,
+                "There was an exception while trying to navigate to 'error' with the exception message 'Exception in MainLayout afterNavigation'");
+
+        // Verify that MainLayout's afterNavigation was called at least once
+        Assert.assertFalse(
```
Comment (mcollovati) [inline flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java]: Should this check that afterNavigation is called twice instead?

**Review by mcollovati — CHANGES_REQUESTED** [review]

File: flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java (hunk 4 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java]: done

File: flow-server/src/main/java/com/vaadin/flow/router/Router.java (hunk 3 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/router/Router.java]: Added message. 
Without an logic or runtime error this should never happen as InternalServerError catches Exception

File: flow-server/src/main/java/com/vaadin/flow/router/Router.java [hunk 5]
```diff
@@ -283,29 +284,81 @@ private int handleNavigation(UI ui, Location location,
...
-        } else {
-            throw new RuntimeException(exception);
+        } catch (Exception errorHandlingException) {
+            Logger logger = LoggerFactory.getLogger(Router.class);
+
+            // Error view threw an exception - fall back to
+            // InternalServerError
+            logger.error(
+                    "Exception occurred while rendering error view for '{}'. "
+                            + "Falling back to InternalServerError.",
```
Comment (mcollovati) [inline flow-server/src/main/java/com/vaadin/flow/router/Router.java]: nit: would it be helpful to also print the error view class (`lookupResult.getNavigationTarget()`)?

Actually, the error might not be in the error view itself, but it could be useful to know which view is currently handling the initial error, since it is not reported in the stacktrace.
