### PR TITLE
fix: allow empty segments at start (#10921)

### LINKED ISSUE #10729: After 14.5, Router HasUrlParameter @WildcardParameter doesn't support empty parameters anymore
### Description of the bug / feature
After 14.5, Router HasUrlParameter @WildcardParameter doesn't support empty parameters anymore. Works with 14.4.10. 
### Minimal reproducible example
```
@Route(value = "about", layout = MainView.class)
@PageTitle("About")
@CssImport("./views/about/about-view.css")
public class AboutView extends Div implements HasUrlParameter<String> {
    public AboutView() {
        addClassName("about-view");
        add(new Text("Content placeholder"));
    }
    @Override
    public void setParameter(BeforeEvent beforeEvent, @WildcardParameter String s) {
        System.out.println(">>>"+s);
    }
}
```
### Expected behavior
With code above the standard output for url `http://localhost:8080/about//2/3`, should be just:
`>>>/2/3`
### Actual behavior
The standard output is
```
>>>2/3
>>>VAADIN/build/webcomponentsjs/webcomponents-loader.js
>>>VAADIN/build/vaadin-gizmo-1f1e5ed60cb793a57317.cache.js
>>>VAADIN/static/client/client-4C23589935A74206212F474A719FC41C.cache.js
>>>VAADIN/build/vaadin-bundle-098d1f74dc147d6e9258.cache.js
>>>icons/icon-32x32.png
>>>manifest.webmanifest
>>>sw.js
>>>icons/icon-16x16.png
>>>icons/icon-96x96.png
```
### Versions:
    - Vaadin version: 14.5.3
    - Java version: Amazon Corretto 11.0.10
    - OS version: Windows 10 Pro

### PR DESCRIPTION
**Pull request by caalador**
Fixes a regression with HasUrlParameter by allowing to have an empty segment as first segment for parameters.

Fixes #10729

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/router/internal/PathUtil.java [hunk 1]
```diff
@@ -59,8 +60,8 @@
      * @return path form from input segments.
      */
     public static String getPath(List<String> segments) {
-        return trimPath((segments == null || segments.isEmpty()) ? ""
-                : String.join("/", segments));
+        return trimSegmentsString(
+                segments == null ? "" : String.join("/", segments));
```
Comment (pleku) [inline flow-server/src/main/java/com/vaadin/flow/router/internal/PathUtil.java:64]: nit: I would have gone with same as above
```java
return segments == null ? "" : trimSegmentsString(String.join("/", segments));
```

**Review by pleku — APPROVED** [review]

File: flow-server/src/main/java/com/vaadin/flow/router/internal/PathUtil.java (hunk 1 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/router/internal/PathUtil.java:64]: Well the change went to master already  and it is cognitively clearer. Else would change it to 
```
if(segments == null || segments.isEmpty()) {
  return "";
}
return String.join("/", segments);
```
But now checking the String.join contents I would have expected it to be smarter about empty iterables.
