### PR TITLE
fix: Prevent Vite reload from canceling logout redirect

### LINKED ISSUE #20819: [Dev mode] Vite page reload cancels redirection to the logout page when an authenticated session is invalidated
### Description of the bug

Given an application with views protected by authentication (`HttpServletRequest.getUserPrincipal() != null`) and a logout functionality that redirects the browser to a public page, if frontend reload is enabled (Vite client) on logout the redirection is cancelled and the current page is reloaded.

This happens because the Vaadin Vite websocket proxy gets closed on session invalidation, and Vite client performs a [page reload](https://github.com/vitejs/vite/blob/282496daaca43494feceaa59809f6ceafd62dedd/packages/vite/src/client/client.ts#L245) concurrently with the redirection issued by the logout process via HTTP `Location` header.

image

image

### Expected behavior

The browser is redirected to the configured logout landing page.

### Minimal reproducible example

* Clone or download the Flow spring starter from https://github.com/vaadin/skeleton-starter-flow-spring
* Add Spring Security starter dependency to the POM file
   ```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
   ```
* Create the following views
   ```java
   @Route("login")
   @AnonymousAllowed
   public class LoginView extends Div {
      public LoginView() {
         LoginForm form = new LoginForm();
         form.setAction("login");
         add(form);
      }
   }
   
   @Route("session-ended")
   @AnonymousAllowed
   public class LogoutView extends Div {
       public LogoutView() {
           add(new H1("Landing view"));
           Anchor homeLink = new Anchor("/home", "Home");
           homeLink.setRouterIgnore(true);
           add(homeLink);
       }
   }
   
   @Route("home")
   @RouteAlias("")
   @PermitAll
   public class MainView extends VerticalLayout {
       public MainView(AuthenticationContext authCtx) {
           add(new Button("Invalidate session and redirect", ev -> authCtx.logout()));
       }
   }
   ```
* Configure Spring Security to redirect to `LogoutView` after logout
   ```java
   @Configuration
   public class SecurityConfig extends VaadinWebSecurity {
       @Override
       protected void configure(org.springframework.security.config.annotation.web.builders.HttpSecurity http) throws Exception {
           super.configure(http);
           setLoginView(http, "/login", "/session-ended");
       }
       @Bean
       public UserDetailsManager userDetailsService() {
        UserDetails user =
                User.withUsername("alice").password("{noop}alice").roles("USER").build();
           return new InMemoryUserDetailsManager(user);
       }
   }
   ```
* Enable frontend hotdeploy, both on vaadin-maven-plugin configuration and application.properties
   ```xml
   <plugin>
      <groupId>com.vaadin</groupId>
      <artifactId>vaadin-maven-plugin</artifactId>
      <version>${vaadin.version}</version>
      <configuration>
         <frontendHotdeploy>true</frontendHotdeploy>
      </configuration>
      ...
   </plugin>
   ```
   
   ```java
   vaadin.frontend.hotdeploy=true
   ```
* Start the application, enter the user credentials on the login page and submit the form. On the main view press the **Invalidate session and redirect** button.
* Observe that the login page is shown instead of the logout view

If you disable frontend hotdeploy and try again, after logout the browser is correctly redirected to the logout view.

### Versions

- Vaadin / Flow version: 24.6 (Most likely also all previous versions)
- Java version: 21
- OS version: Linux

### PR DESCRIPTION
**Pull request by mcollovati**
When a user logs out and the session is invalidated, the server closes WebSocket connections with close code 1008 (VIOLATED_POLICY). Vite detects this disconnection and starts polling for reconnection, then reloads the page - canceling any server-initiated redirect.

The fix uses a Promise-based synchronization between Vite's HMR events:

1. On vite:ws:connect, we register a close listener and store a Promise on the WebSocket that resolves with the close code when triggered.

2. On vite:ws:disconnect, we await this Promise to get the close code. Since Vite's notifyListeners awaits our async handler, this creates a synchronization point before Vite checks its willUnload flag.

3. When close code is 1008, we dispatch a beforeunload event to set Vite's internal willUnload flag, preventing the reload.

This approach works because Vite's close handler does not await the Promise returned by onMessage/handleMessage, so our async disconnect handler can complete (setting willUnload) before Vite's willUnload check runs.

Fixes #20819

### CODE REVIEW

File: vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteSessionTracker.java [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+ * <p>
+ * This allows WebSocket connections to be notified when their associated HTTP
+ * session is invalidated, enabling them to close the WebSocket with an
+ * appropriate close code that the client can detect.
+ * <p>
+ * This class is meant only for testing purposes. Do not use it in production.
+ * <p>
+ * For internal use only. May be renamed or removed in a future release.
+ */
+public class ViteSessionTracker {
```
Comment (caalador) [inline vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteSessionTracker.java:34]: Just to keep this more from being used where it's not supposed to should we make this package protected?

Comment (mcollovati) [reply vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteSessionTracker.java:34]: I don't think we can do that since the test code that uses it is in a different package.

**Review by caalador — APPROVED** [review]

File: vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteSessionTracker.java (hunk 1 above)
Comment (mcollovati) [reply vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteSessionTracker.java:34]: To "protect" the class a little bit more, we can make the constructor private and add a `ViteSessionTracker.get(ServletContext)` method, so instantiation and registration are under the class control. But I don't know if it is worth doing that.
