### PR TITLE
fix: Handle translation requests when session is expired

### LINKED ISSUE #23238: i18n requests often fail with stateless authenticaction
### Describe the bug

A Hilla app with i18n feature often fails to fetch and use translations when stateless authentication is used.

### Expected-behavior

A Hilla app with i18n feature should always fetch and use translations successfully when stateless authentication is used.

### Reproduction

I created a sample repo for reproduction: https://github.com/rbrki07/hilla-i18n-stateless-authentication-example/tree/main.

The tag [basic-i18n](https://github.com/rbrki07/hilla-i18n-stateless-authentication-example/tree/basic-i18n) contains a basic i18n integration as described in the [docs](https://vaadin.com/docs/latest/hilla/guides/i18n). If you start the app from this tag, the app can fetch and use the translations without errors: 

https://github.com/user-attachments/assets/120087c2-acd9-4d10-82ee-e500826d7afe

The tag [stateless-auth-loginview](https://github.com/rbrki07/hilla-i18n-stateless-authentication-example/tree/stateless-auth-loginview) adds stateless authentication to the app, as described in the [docs](https://vaadin.com/docs/latest/hilla/guides/security/spring-statelessl). It uses `loginView` as described [here](https://vaadin.com/docs/latest/hilla/guides/security/spring-login#server-configuration). If you start the app from this tag, the app often fails to fetch and use the translations: 

https://github.com/user-attachments/assets/585e9f93-605e-47cf-b154-a718c5aff502

The requests that fail, fail with a status code 403 and the error "session expired".

I also tried a different stateless authentication approach using an `oauth2LoginPage`. The tag [stateless-auth-oauth2loginpage](https://github.com/rbrki07/hilla-i18n-stateless-authentication-example/tree/stateless-auth-oauth2loginpage) contains the app with this implementation. If you start the app from this tag, the app also often fails to fetch and use the translations: 

https://github.com/user-attachments/assets/81201774-0116-4530-9879-a8f568af9401

I tried to analyze and debug the Spring Security Filter Chain to find the root cause for the "session expired" error, but I couldn't find it. That said, I'm not sure if this issue is really related to the way Vaadin authenticates requests internally.

### System Info

* Vaadin Hilla 24.9.4
* Behaviour tested in Safari, Firefox and Chrome

### PR DESCRIPTION
**Pull request by mcollovati**
Implement SessionExpiredHandler in TranslationFileRequestHandler to serve translations even when no active session exists. This allows i18n requests to work correctly with stateless authentication.

Fixes #23238

### CODE REVIEW

**Comment by Artur-** [comment]
What is the session used for in the handler?

**Comment by Artur-** [comment]
Apparently it is not used at all, but there is no way to have a request handler that does not care about the session?

**Comment by mcollovati** [comment]
Exactly. Request Handlers are invoked after the attempt to create/get a Vaadin session is already done.
Maybe a workaround could be implement it as a Vaadin interceptor, but it doesn't seem the correct abstraction to use.

File: flow-server/src/main/java/com/vaadin/flow/i18n/TranslationFileRequestHandler.java [hunk 1]
```diff
@@ -93,9 +96,46 @@ public TranslationFileRequestHandler(I18NProvider i18NProvider,
     @Override
     public boolean synchronizedHandleRequest(VaadinSession session,
             VaadinRequest request, VaadinResponse response) throws IOException {
+        handleTranslationRequest(session.getService(), request, response);
```
Comment (Artur-) [inline flow-server/src/main/java/com/vaadin/flow/i18n/TranslationFileRequestHandler.java]: This could be `request.getService()` instead to be clear that the session is not needed

Comment (mcollovati) [reply flow-server/src/main/java/com/vaadin/flow/i18n/TranslationFileRequestHandler.java]: Good point. I'll fix that.

Comment (mcollovati) [reply flow-server/src/main/java/com/vaadin/flow/i18n/TranslationFileRequestHandler.java]: done

File: flow-server/src/main/java/com/vaadin/flow/i18n/TranslationFileRequestHandler.java [hunk 2]
```diff
@@ -93,9 +96,47 @@ public TranslationFileRequestHandler(I18NProvider i18NProvider,
...
+     *            the response object to which a response can be written
+     * @return {@code true} if the request was handled, {@code false} if this
+     *         handler does not handle the given request type
+     * @throws IOException
+     *             if an IO error occurred
+     */
+    @Override
+    public boolean handleSessionExpired(VaadinRequest request,
+            VaadinResponse response) throws IOException {
+        if (!canHandleRequest(request)) {
```
Comment (Artur-) [inline flow-server/src/main/java/com/vaadin/flow/i18n/TranslationFileRequestHandler.java]: nit: Somehow this looks inverted to me when it could be "if we can handle, handle it, otherwise don't"

Comment (mcollovati) [reply flow-server/src/main/java/com/vaadin/flow/i18n/TranslationFileRequestHandler.java]: update

**Comment by mcollovati** [comment]
> A cleaner way in the future would be to have support for request handlers that do not need session access. There seems to be a few of them in the project

Created #23306 to track this.
