### PR TITLE
fix: Check assets for url handling

### LINKED ISSUE #10426: Impossible to load assets from npm packages in style.css
### Description of the bug / feature
I'm following the documentation to load the assets from npm Package.
https://vaadin.com/docs/v14/flow/styling/custom-theme-configuration/#assets
But I have a 404 error when I'm using it in styles.css.
```
{
  "assets": {
    "@fortawesome/fontawesome-free": {
      "svgs/regular/**": "fontawesome/icons"
    }
  }
}
```
```
.icon-snowflake {
  background-image: url('fontawesome/icons/snowflake.svg');
}
```
It's working if I'm trying to add the image with Java:
```
Image crmImage = new Image(
                "themes/myapp/fontawesome/icons/snowflake.svg",
                "Vaadin Brand");
        add(crmImage);
```
### Minimal reproducible example
Create the view:
```
@NpmPackage(value = "@fortawesome/fontawesome-free", version = "5.15.3")
@Route(value = "about", layout = MainView.class)
@PageTitle("About")
@CssImport("./views/about/about-view.css")
public class AboutView extends Div {

    public AboutView() {
        addClassName("about-view");
        addClassName("icon-snowflake");
        add(new Text("Content placeholder"));
        /*Image crmImage = new Image(
                "themes/myapp/fontawesome/icons/snowflake.svg",
                "Vaadin Brand");
        add(crmImage);*/
        add(new Html("<i class=\"fab fa-vaadin\"></i>"));
    }

}
```

Update styles.css:
```
.icon-snowflake {
    background-image: url('fontawesome/icons/snowflake.svg');
}
```
And theme.json:
```
{
  "assets": {
    "@fortawesome/fontawesome-free": {
      "svgs/regular/**": "fontawesome/icons"
    }
  },
  "importCss": [
    "@fortawesome/fontawesome-free/css/all.min.css"
  ]
}
```
### Expected behavior
The icon as a background image should be there.

### Actual behavior
No icon.
In Vaadin 14.6 alpha I have a 404 error.
In Vaadin 19.0.2, the image is redirected by flow: http://localhost:8080/fontawesome/icons/snowflake.svg
### Versions:
    - Vaadin / Flow version: 14.6.0.alpha1 and 19.0.2
    - Java version: 14
    - OS version: Mac
    - Browser version (if applicable): Chrome
    - Application Server (if applicable): Tomcat (default Spring boot app)
    - IDE (if applicable): IntelliJ

Here is an example project:
[vaadin_19_theme.zip](https://github.com/vaadin/flow/files/6210512/vaadin_19_theme.zip)

The right path seems to be:
```
.icon-snowflake {
    background-image: url('/themes/myapp/fontawesome/icons/snowflake.svg');
}
```

But it won't work if the application has a context path.
With the example project you can try by adding in application.properties:
```
server.servlet.context-path=/context
```

### PR DESCRIPTION
**Pull request by caalador**
If a resource is not found in themes folder
check also any assets that are copied for
the theme.

fixes #10426

### CODE REVIEW

File: flow-server/src/main/resources/plugins/theme-loader/theme-loader.js [hunk 1]
```diff
@@ -52,3 +54,46 @@ module.exports = function (source, map) {
...
+    logger.debug("No defined assets in theme properties");
+    return false;
+  }
+  // Go through each asset module
+  for (let module of Object.keys(assets)) {
+    const copyRules = assets[module];
+    // Go through each copy rule
+    for (let copyRule of Object.keys(copyRules)) {
+      // if file starts with copyRule target check if file with path after copy target can be found
+      if (fileUrl.startsWith(copyRules[copyRule])) {
```
Comment (mshabarov) [inline flow-server/src/main/resources/plugins/theme-loader/theme-loader.js:75]: Should there be a debug logging saying the asset (given in `fileUrl`) is not found in the `node_modules/module/asset_relative_path`. 
Or even throw the exception.

File: flow-server/src/main/resources/plugins/theme-loader/theme-loader.js [hunk 2]
```diff
@@ -52,3 +54,46 @@ module.exports = function (source, map) {
...
+function getThemeProperties(themeFolder) {
+  const themePropertyFile = path.resolve(themeFolder, 'theme.json');
+  if (!fs.existsSync(themePropertyFile)) {
+    return {};
+  }
+  const themePropertyFileAsString = fs.readFileSync(themePropertyFile);
+  if (themePropertyFileAsString.length === 0) {
+    return {};
+  }
+  return JSON.parse(themePropertyFileAsString);
```
Comment (mshabarov) [inline flow-server/src/main/resources/plugins/theme-loader/theme-loader.js:98]: This can be wrapped into `try-catch` and a new meaningful exception can be thrown, explaining where to look to fix the problem.

File: flow-server/src/main/resources/plugins/theme-loader/theme-loader.js (hunk 1 above)
Comment (caalador) [reply flow-server/src/main/resources/plugins/theme-loader/theme-loader.js:75]: There can be multiple assets defined not just one.
Also there is no need for the file to actually be an asset or an existing resource as it could just be something that the server will give out so not finding anything is a ok result.

File: flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java [hunk 3]
```diff
@@ -71,6 +72,19 @@ public void referenceResourcesOnJavaSideForStyling_stylesAreApplied() {
                 driver.getPageSource().contains("HTTP ERROR 404 Not Found"));
     }
 
+    @Test
+    public void nodeAssetInCss_pathIsSetCorrectly() {
+        open();
+        final String resourceUrl = getRootURL()
+            + "/path/themes/app-theme/fortawesome/icons/snowflake.svg";
+        WebElement diceSpan = findElement(By.id(CSS_SNOWFLAKE));
```
Comment (mshabarov) [inline flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java:80]: diceSpan -> snowFlakeSpan

File: flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java [hunk 4]
```diff
@@ -71,6 +72,19 @@ public void referenceResourcesOnJavaSideForStyling_stylesAreApplied() {
...
+        final String expectedImgUrl = "url(\"" + resourceUrl + "\")";
+        Assert.assertEquals(
+            "Background image has been referenced on java page and "
```
Comment (mshabarov) [inline flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java:83]: `... on java page ...` -> `... from styles.css ...`

File: flow-server/src/main/resources/plugins/theme-loader/theme-loader.js (hunk 2 above)
Comment (caalador) [reply flow-server/src/main/resources/plugins/theme-loader/theme-loader.js:98]: This is the same as we use in handle-theme to get the theme.json

File: flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java (hunk 3 above)
Comment (caalador) [reply flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java]: changed

File: flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java (hunk 4 above)
Comment (caalador) [reply flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java]: fixed

**Review by mshabarov — APPROVED** [review]

**Comment by mshabarov** [comment]
@caalador I've added `2.6` and `6.0` CP labels.
