### PR TITLE
fix: Do not load service worker with Vite in 23.0

### LINKED ISSUE #13201: Service worker is loaded but not served when using Vite in 23.0.0
### Description of the bug

When starting an application in development mode using Vite, the following is logged in the browser

```
A bad HTTP response code (404) was received when fetching the script.
localhost/:1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('http://localhost:8080/') with script ('http://localhost:8080/sw.js'): A bad HTTP response code (404) was received when fetching the script.
```

### Expected behavior

Flow should not register a service worker that cannot be loaded

This is fixed for V23.1 in https://github.com/vaadin/flow/pull/12857 and https://github.com/vaadin/flow/pull/12928

### Minimal reproducible example

1. start.vaadin.com
2. Select to use Vite
3. Download
4. `mvn`

### Versions

- Vaadin / Flow version:23

### PR DESCRIPTION
**Pull request by Artur-**
Vite does not serve a service worker in 23.0. It has already been fixed for 23.1 in https://github.com/vaadin/flow/pull/12857 and https://github.com/vaadin/flow/pull/12928

Fixes #13201

### CODE REVIEW

**Comment by vursen** [comment]
As I see, this PR disables the service worker completely for Vite in 23.0 so that it will work neither in prod nor in dev mode. If going this way, any tests testing Vite PWAs don't make sense anymore and should be dropped in this branch.

File: flow-tests/test-frontend/vite-pwa-production-custom-offline-path/src/test/java/com/vaadin/viteapp/MainIT.java [hunk 1]
```diff
@@ -27,7 +27,6 @@
     @Before
     public void init() {
```
Comment (vursen) [inline flow-tests/test-frontend/vite-pwa-production-custom-offline-path/src/test/java/com/vaadin/viteapp/MainIT.java:28]: These tests don't make sense if disabling the service worker completely for Vite.

File: flow-tests/test-frontend/vite-pwa-production/src/test/java/com/vaadin/viteapp/MainIT.java [hunk 2]
```diff
@@ -95,6 +95,5 @@ private void setOfflineAndReload() {
 
     private void openPage(String url) {
         getDriver().get(getRootURL() + url);
-        waitForServiceWorkerReady();
```
Comment (vursen) [inline flow-tests/test-frontend/vite-pwa-production/src/test/java/com/vaadin/viteapp/MainIT.java:98]: These tests don't make sense if disabling the service worker completely for Vite.

**Comment by Artur-** [comment]
> As I see, this PR disables the service worker completely for Vite in 23.0 so that it will work neither in prod nor in dev mode. If this is the case, any tests testing Vite PWAs don't make sense anymore and should be dropped in this branch.

It was unclear to me what actually works in 23.0 regarding Vite + service worker. Does a production build work? In dev mode it does not work at all and there are two PRs that are not included: one for dev and one for production

**Comment by vursen** [comment]
> It was unclear to me what actually works in 23.0 regarding Vite + service worker. Does a production build work? In dev mode it does not work at all and there are two PRs that are not included: one for dev and one for production

Well, it seems that offline should work in production mode in 23.0 because the relevant fix has landed that version: https://github.com/vaadin/flow/commit/3cdb280b460f880be227558c61ae7d642d87c606

It shouldn't work in dev mode though because it was considered a feature and therefore has not been added in 23.0, as far as I understand it.

**Comment by Artur-** [comment]
So should this PR be limited to disabling it in dev mode?

**Comment by vursen** [comment]
> So should this PR be limited to disabling it in dev mode?

From my point of view, yes, it should.

File: flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java [hunk 3]
```diff
@@ -143,7 +144,10 @@ public boolean synchronizedHandleRequest(VaadinSession session,
         }
 
         // modify the page based on the @PWA annotation
-        setupPwa(indexDocument, session.getService());
+        if (!FeatureFlags.get(service.getContext()).isEnabled(FeatureFlags.VITE)
+                && !config.isProductionMode()) {
```
Comment (vursen) [inline flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java:148]:
```suggestion
        if (!FeatureFlags.get(service.getContext()).isEnabled(FeatureFlags.VITE)
                || config.isProductionMode()) {
```

File: flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java [hunk 4]
```diff
@@ -707,7 +707,11 @@ public Document getBootstrapPage(BootstrapContext context) {
                         .exportUsageStatisticsToDocument(document);
             }
 
-            setupPwa(document, context);
+            if (!FeatureFlags.get(context.getService().getContext())
+                    .isEnabled(FeatureFlags.VITE)
+                    && !config.isProductionMode()) {
```
Comment (vursen) [inline flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java:712]:
```suggestion
            if (!FeatureFlags.get(context.getService().getContext())
                    .isEnabled(FeatureFlags.VITE)
                    || config.isProductionMode()) {
```

**Review by vursen — CHANGES_REQUESTED** [review]

**Review by vursen — APPROVED** [review]
