### PR TITLE
fix: Added support for custom frontendDirectory in TaskCopyTemplateFiles

### LINKED ISSUE #14415: Maven goal build-frontend fails with custom frontend folder in V23
### Description of the bug

If you're using custom path for frontend folder, the production build (Maven clean package -Pproduction) fails to execute since it's not finding the lit template .ts (or .js) files.

NOTE: The custom path works in devmode without issues.

### Expected behavior

The lit template files should be found even with custom frontend path just like they did in V14 (worked at least with v14.8.14).

### Minimal reproducible example

My sample project:
[skeleton-starter-flow-spring.zip](https://github.com/vaadin/flow/files/9400974/skeleton-starter-flow-spring.zip)

NOTE: The same results can be achieved with non-spring projects as well.

1. Clone vaadin 23 starter project
```
git clone https://github.com/vaadin/skeleton-starter-flow-spring.git
cd skeleton-starter-flow-spring
git checkout v23
```

2. Rename the 'frontend' directory to 'frontend-moved'
`git mv frontend frontend-moved` 

3. Change frontend directory. Edit maven project file 'pom.xml'. Add 'frontendDirectory' -configuration
```
 <configuration>
  <frontendDirectory>${project.basedir}/frontend-moved</frontendDirectory>
 </configuration>
```
Into 'vaadin-maven-plugin' in 'plugin' section.
NOTE: The 'vaadin-maven-plugin' is in two sections 'build' and 'profiles'.
End result sample:
```
    <plugin>
        <groupId>com.vaadin</groupId>
        <artifactId>vaadin-maven-plugin</artifactId>
        <version>${vaadin.version}</version>
        <configuration>
            <frontendDirectory>${project.basedir}/frontend-moved</frontendDirectory>
        </configuration>
    </plugin>
```
And the production profile example:
```
        <profile>
            <!-- Production mode is activated using -Pproduction -->
            <id>production</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.vaadin</groupId>
                        <artifactId>vaadin-maven-plugin</artifactId>
                        <version>${vaadin.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>build-frontend</goal>
                                </goals>
                                <phase>compile</phase>
                            </execution>
                        </executions>
                        <configuration>
                            <productionMode>true</productionMode>
							<frontendDirectory>${project.basedir}/frontend-moved</frontendDirectory>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
```
4. Import into Eclipse IDE
5. Create a new Lit component (e.g. my-view). 
    NOTE: If you haven't changed the designers frontend folder, remember to change the generated java files `@JsModule` annotations path (in my case  "./frontend/my-view.ts" to "./my-view.ts").
6.  Run maven with goals 
`clean package -Pproduction`

Now the build-frontend goal will fail:
```
[INFO] --- vaadin-maven-plugin:23.1.6:build-frontend (default) @ spring-skeleton ---
[INFO] Reflections took 888 ms to scan 130 urls, producing 9351 keys and 42497 values
[INFO] Scanning classes to find frontend configurations and dependencies...
[INFO] Visited 1940 classes. Took 1858 ms.
[INFO] Visited 118 classes. Took 70 ms.
[WARNING] Using user (package.json) pinned version '23.1.2' of '@vaadin/field-highlighter' which is older than the current platform version '23.1.5'
[INFO] Unable to determine version information. No vaadin-core-versions.json found
[WARNING] Using user (package.json) pinned version '23.1.2' of '@vaadin/field-highlighter' which is older than the current platform version '23.1.5'
[INFO] Skipping `npm install` because the frontend packages are already installed in the folder 'C:\Users\Aleksi\workspace-V23kloonattu\skeleton-starter-flow-spring\node_modules' and the hash in the file 'C:\Users\Aleksi\workspace-V23kloonattu\skeleton-starter-flow-spring\node_modules\.vaadin\vaadin.json' is the same as in 'package.json'
[INFO] Copying frontend resources from jar files ...
[INFO] Visited 129 resources. Took 729 ms.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.123 s
[INFO] Finished at: 2022-08-23T10:27:44+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:23.1.6:build-frontend (default) on project spring-skeleton: Could not execute build-frontend goal: Unable to locate file ./my-view.ts -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

### Versions

- Vaadin / Flow version: 23.1.6
- Java version: 11
- OS version: Windows 10 
- IDE: Eclipse 2021-03 (4.19.0)

### PR DESCRIPTION
**Pull request by MarcinVaadin**
## Description

Added support for custom `frontendDirectory` in `TaskCopyTemplateFiles`. 

I didn't want to implement solution within `FrontendUtils.resolveFrontendPath` as it is referenced during Lit/Polymer templates parsing.

Fixes #14415

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java [hunk 1]
```diff
@@ -70,8 +73,12 @@ public void execute() throws ExecutionFailedException {
...
                         .resolveFrontendPath(projectDirectory, path);
                 if (source == null) {
-                    throw new ExecutionFailedException(
-                            "Unable to locate file " + path);
+                    // Check if not custom frontendDirectory
+                    source = new File(this.frontendDirectory, path);
+                    if (!source.exists()) {
+                        throw new ExecutionFailedException(
+                                "Unable to locate file " + path);
+                    }
```
Comment (taefi) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java:81]: Reading the whole method gives me this sense that it uses the `frontendDirectory` as a fallback value for the path coming from the `@JsModule`. Shouldn't it be looking always into the `frontendDirectory` when defined? Or am I missing a point here?

**Review by taefi — CHANGES_REQUESTED** [review]
Would there be some new Tests to validate this functionality?

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java (hunk 1 above)
Comment (MarcinVaadin) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java:81]: If you check `FrontendUtils.resolveFrontendPath` you will notice that it looks for frontend resources in few different locations:
```
File localFrontendFolder = new File(projectRoot,
                FrontendUtils.FRONTEND);
        File nodeModulesFolder = new File(projectRoot, NODE_MODULES);
        File flowFrontendFolder = new File(nodeModulesFolder,
                "@vaadin/" + DEFAULT_FLOW_RESOURCES_FOLDER);
```
I thought replacing that logic with single call to `this.frontendDirectory` is too risky.

Comment (MarcinVaadin) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java:81]: Yes, there are no tests for custom frontedDirectory for the moment, I will add them.

Comment (taefi) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java:81]: I think we should not replace the whole logic in `FrontendUtils.resolveFrontendPath` since it is handling some order as well. I think the **custom** `frontendDirectory` value should affect the hardcoded `localFrontendFolder` value which always points to `{projectRoot}/frontend`.

**Comment by taefi** [comment]
It seems that the `TaskCopyTemplateFilesTest.java` file has incompatible formatting.

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java [hunk 2]
```diff
@@ -710,8 +710,26 @@ public static InputStream getFrontendFileFromDevModeHandler(
...
      */
     public static File resolveFrontendPath(File projectRoot, String path) {
-        File localFrontendFolder = new File(projectRoot,
-                FrontendUtils.FRONTEND);
+        return resolveFrontendPath(projectRoot, path,
+                new File(projectRoot, FrontendUtils.FRONTEND));
+    }
+
+    /**
+     * Looks up the front file at the given path. If the path starts with
```
Comment (taefi) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java:718]: In the first sentence (I know it comes from the previously existing method) what is it exactly `the front file` referring to? The frontend folder/path?

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java [hunk 3]
```diff
@@ -710,8 +710,26 @@ public static InputStream getFrontendFileFromDevModeHandler(
...
+     * {@code ./}, first look in {@code projectRoot/frontendDirectory}, then in
+     * {@code projectRoot/node_modules/@vaadin/flow-frontend}. If the path does
+     * not start with {@code ./}, look in {@code node_modules} instead.
+     *
+     * @param projectRoot
+     *            the project root folder.
+     * @param path
+     *            the file path.
+     * @param localFrontendFolder
```
Comment (taefi) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java:727]: I would not call the third parameter `localFrontendFolder`. I'm not sure even why it has bean called that before, something like `defaultFronendFolder` could be more meaningful back then. Now, I would suggest to rename it to `frondendFolder` or `frontendDirectory`, as it can hold the "default" or a custom path to the so called `frontend` directory in this method.

**Review by taefi — CHANGES_REQUESTED** [review]

**Review by mshabarov — CHANGES_REQUESTED** [review]
The patch looks good to me, but I propose to add an IT test using production mode to be sure that the copied file is handled correctly and bundled.

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java (hunk 2 above)
Comment (MarcinVaadin) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java:718]: I've just copied the javadocs from existing method ;-) Ok, I will update them.

**Comment by mshabarov** [comment]
@MarcinVaadin the easiest way to make an IT test is not take an existing test module which tests templates, add a custom pom file there (we already have a similar examples in the flow-tests with custom poms) and set production mode and a custom frontend folder in this custom pom file (through the flow-maven-plugin parameters).

**Comment by MarcinVaadin** [comment]
> @MarcinVaadin the easiest way to make an IT test is not take an existing test module which tests templates, add a custom pom file there (we already have a similar examples in the flow-tests with custom poms) and set production mode and a custom frontend folder in this custom pom file (through the flow-maven-plugin parameters).

Well... I've used `vite-production`, it contains `@JsModule("./lit-invalid-imports.ts")` so should be fine.

**Review by taefi — APPROVED** [review]

File: flow-tests/test-frontend/vite-production-custom-frontend/frontend-custom/lit-invalid-imports.ts [hunk 4]
```diff
@@ -0,0 +1,7 @@
+import { customElement } from 'lit/decorators';
+import { customElement as ce2, property } from 'lit/decorators';
+import { state, customElement as ce3, property as p2 } from 'lit/decorators';
+import { unsafeHTML } from 'lit-html/directives/unsafe-html';
+import { classMap } from 'lit-html/directives/class-map';
+
+console.log(customElement, ce2, ce3, property, p2, state, unsafeHTML, classMap);
```
Comment (mshabarov) [inline flow-tests/test-frontend/vite-production-custom-frontend/frontend-custom/lit-invalid-imports.ts:7]: This doesn't look as a good lit element example :) but a hack with imports without "js" extension.
Also, you copied a lots of tests and resources which are not needed here, compression etc.

I would better propose to remove all those tests, images, themes, hacks and so on and use example like this:
1. Simple Java component, exampe: https://github.com/vaadin/flow/blob/master/flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/TestForm.java 
2. Lit component counterpart, exaple https://github.com/vaadin/flow/blob/master/flow-tests/test-root-context/frontend/lit-templates/test-form.js
3. Open page with a Lit component, check that it's properly rendered. Example of the test https://github.com/vaadin/flow/blob/master/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/littemplate/ReattachIT.java

**Review by mshabarov — CHANGES_REQUESTED** [review]

File: flow-tests/test-frontend/vite-production-custom-frontend/frontend-custom/lit-invalid-imports.ts (hunk 4 above)
Comment (MarcinVaadin) [reply flow-tests/test-frontend/vite-production-custom-frontend/frontend-custom/lit-invalid-imports.ts]: Tests simplified

File: flow-tests/test-frontend/vite-production-custom-frontend/frontend-custom/lit-templates/test-form.js [hunk 5]
```diff
@@ -0,0 +1,12 @@
...
+class TestForm extends LitElement {
+
+  render() {
+    return html`
+        <div id="div">Template text</div>
+    `;
+  }
+}
+
+customElements.define('test-form', TestForm);
```
Comment (mshabarov) [inline flow-tests/test-frontend/vite-production-custom-frontend/frontend-custom/lit-templates/test-form.js:12]:
```suggestion
customElements.define('test-form', TestForm);

```

File: flow-tests/test-frontend/vite-production-custom-frontend/src/main/java/com/vaadin/viteapp/littemplate/TestForm.java [hunk 6]
```diff
@@ -0,0 +1,19 @@
...
+@Tag("test-form")
+public class TestForm extends LitTemplate {
+
+    @Id
+    private Div div;
+
+    public TestForm() {
+        div.setText("foo");
+    }
+}
```
Comment (mshabarov) [inline flow-tests/test-frontend/vite-production-custom-frontend/src/main/java/com/vaadin/viteapp/littemplate/TestForm.java:19]:
```suggestion
}

```

**Review by mshabarov — APPROVED** [review]

**Review by mshabarov — APPROVED** [review]

**Review by mshabarov — APPROVED** [review]
