### PR TITLE
Do not force installation of compatible pnpm version when system property `vaadin.ignoreVersionChecks` is set

### LINKED ISSUE #8889: Enable using user PNPM version outside of Vaadin range
### Description of the bug
On our build server we occasionally get this error:
`Unable to update lock within the stale threshold`
The issue seems to be related to [`node-proper-lockfile`](https://github.com/moxystudio/node-proper-lockfile/issues/11) which is used by pnpm.
Our workaround until now was to install pnpm version 5 on our build-server, since they solved [this issue](https://github.com/pnpm/pnpm/issues/594) in that version.
However, Vaadin is now [forcing a pnpm version between 4.4.0 and 4.6.0](https://github.com/vaadin/flow/pull/8452), as newer pnpm version have some [other issues](https://github.com/vaadin/flow/issues/8434), and our workaround doesn't work anymore.

### Minimal reproducible example
Not applicable, it only happens occasionally on slow hardware.

### Expected behavior
We would like to be able to use newer pnpm-version, at least on our build server.
The other issue is less of a problem in our case, as an update doesn't happen that often and we can fix it manually.
So we would like to be able to bypass the forced version of vaadin.

### Actual behavior
Vaadin forces a pnpm Version < 4.6.0, which doesn't work in our case.

### Versions:
    - Vaadin / Flow version: 14.3.0
    - Java version: 11
    - OS version: Windows 10 1903

### PR DESCRIPTION
**Pull request by joheriks**
Fixes #8889.

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java [hunk 1]
```diff
@@ -690,12 +690,20 @@ private String getNonNull(String... valueArray) {
...
-                    getLogger().warn(String.format(
-                            "installed pnpm ('%s', version %s) is not in the compatible versions range (>=%s, <%s), installing supported version locally",
+                    getLogger().warn(
+                            "installed pnpm ('{}', version {}) is not in the compatible versions range (>={}, <{})",
                             String.join(" ", pnpmCommand),
                             pnpmVersion.getFullVersion(),
                             SUPPORTED_PNPM_VERSION.getFullVersion(),
-                            BREAKING_PNPM_VERSION.getFullVersion()));
+                            BREAKING_PNPM_VERSION.getFullVersion());
+                    if (FrontendUtils.skippingVersionCheck()) {
```
[the remark this answers is not in the document]
Comment (joheriks) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java]: Done

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java [hunk 2]
```diff
@@ -690,12 +690,20 @@ private String getNonNull(String... valueArray) {
...
+                        getLogger().info("using '{}' anyway",
+                                String.join(" ", pnpmCommand));
```
[the remark this answers is not in the document]
Comment (joheriks) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java]: Done

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java [hunk 3]
```diff
@@ -676,32 +676,39 @@ private String getNonNull(String... valueArray) {
...
+                    && pnpmVersion.isOlderThan(BREAKING_PNPM_VERSION)) {
+                return pnpmCommand;
+            } else {
+                final String pnpmCommandString = String.join(" ", pnpmCommand);
+                getLogger().warn(
+                        "installed pnpm ('{}', version {}) is not in the compatible versions range (>={}, <{})",
+                        pnpmCommandString, pnpmVersion.getFullVersion(),
+                        SUPPORTED_PNPM_VERSION.getFullVersion(),
+                        BREAKING_PNPM_VERSION.getFullVersion());
+                if (FrontendUtils.skippingVersionCheck()) {
```
Comment (denis-anisimov) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java:701]: Two issues here:  
- skip version check is done after version check. Version check may throw an exception and skip will not skip.
- `FrontendTools` has been created to avoid static things like  `FrontendUtils.skippingVersionCheck`.

`skip version check` flag should be passed to the `FrontendTools`  CTOR.
`FrontendUtils`  as a helper class should contain only helper generic methods.
Everything else should be a state of `FrontendTools` otherwise it goes to the same direction as  `FrontendTools`

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java [hunk 4]
```diff
@@ -489,6 +489,49 @@ public void should_useHomeNpmFirst() throws Exception {
...
+        Assert.assertEquals("expected pnpm version 5.5.0 rejected", 0,
+                pnpmCommand.size());
+    }
+
+    @Test
+    public void getSuitablePnpm_tooNewVersionInstalledAndSkipVersionCheck_accepted()
+            throws Exception {
+        Assume.assumeFalse(
+                tools.getNodeExecutable().isEmpty());
+        String originalPropertyValue = System
```
Comment (denis-anisimov) [inline flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java:516]: Making flag a parameter in the CTOR will allow to test `FrontendTools`  properly: without any system properties.

Every code which sets system property is not thread safe at least: the same property may be modified outside of this test at any time.

**Review by denis-anisimov — CHANGES_REQUESTED** [review]

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java (hunk 3 above)
Comment (joheriks) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java]: Good point! Now uses the found `pnpm` even if the version check failed (i.e., threw `UnknownVersionException`). Also removed the static method `FrontendUtils::skippingVersionCheck`, added ctor parameter, and moved the logic to `FrontendTools`.

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java (hunk 4 above)
Comment (joheriks) [reply flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java]: Done.

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java [hunk 5]
```diff
@@ -297,10 +308,12 @@ public void validateNodeAndNpmVersion() {
             List<String> nodeVersionCommand = new ArrayList<>();
             nodeVersionCommand.add(getNodeExecutable());
             nodeVersionCommand.add("--version"); // NOSONAR
-            FrontendVersion nodeVersion = FrontendUtils.getVersion("node",
+            FrontendVersion foundNodeVersion = FrontendUtils.getVersion("node",
                     nodeVersionCommand);
-            FrontendUtils.validateToolVersion("node", nodeVersion,
-                    SUPPORTED_NODE_VERSION, SHOULD_WORK_NODE_VERSION);
+            if (!ignoreVersionChecks) {
```
Comment (denis-anisimov) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java:313]: I would avoid version check via `getVersion`  at all if it should be ignored anyway: it takes additional time
and it may throw an exception whose catching is always more expensive than just check a condition.

Not blocking though.

The only benefit from the current code is logging about failed version check but this is something we failed internally: the `node` of course has some version and we just not able to detect it. So it's an internal issue which will be ignored anyway. So I don't see why spend significant time on checking something which won't be used anyway.

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java [hunk 6]
```diff
@@ -676,34 +691,42 @@ private String getNonNull(String... valueArray) {
...
-                        e);
+                        "installed pnpm ('{}', version {}) is not in the compatible versions range (>={}, <{})",
+                        pnpmCommandString, pnpmVersion.getFullVersion(),
+                        SUPPORTED_PNPM_VERSION.getFullVersion(),
+                        BREAKING_PNPM_VERSION.getFullVersion());
             }
+        } catch (UnknownVersionException e) {
+            getLogger().warn("error checking pnpm version", e);
+        }
+        if (ignoreVersionChecks) {
```
Comment (denis-anisimov) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java:720]: Same here: check is done after attempt to get a version and check whether it's good enough.
Why just don't return immediately without any checks in case  `ignoreVersionChecks`?

**Review by denis-anisimov — APPROVED** [review]

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java (hunk 5 above)
Comment (joheriks) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java]: After more consideration, I agree. My initial line of thinking was that the log about incompatible pnpm would be good anyway. And it's "ignore" version checks rather than "skip" version checks. However, if one is setting this flag one probably knows what one is doing.

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java (hunk 6 above)
Comment (joheriks) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java]: Done.

**Review by denis-anisimov — APPROVED** [review]
