### PR TITLE
fix: Accept newer framework managed versions

### LINKED ISSUE #9793: PNPM overrides version with platform version
When using pnpm if you want to depend on a non platform version of a vaadin component the npm version will be overridden with the platform defined version.

e.g. if the platform npm version of vaadin-charts is 6.3.1 and you add a dependency for vaadin-charts 9.0.0 that has the npm version 7.0.0 then as the version is still framework managed as NpmPackage will update the version versions.json  for forcing versions will get the platform version 6.3.1 instead of the expected 7.0.0

If the version is set manually to 7.0.0 in package.json it will override the platform version but in this case also the java package need to be updated.

For a sample project see https://github.com/vaadin/vaadin-charts/issues/557

### PR DESCRIPTION
**Pull request by caalador**
Any framework managed version that is newer
than the version in platform versions should be
left as is as the version probably is from an updated
annotation.

Fixes #9793

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java [hunk 1]
```diff
@@ -99,4 +120,20 @@ private boolean isUserChanged(String key, JsonObject vaadinDep,
...
+     * @return Vaadin dependencies or empty object
+     */
+    private JsonObject collectFrameworkVersions(JsonObject packageJson) {
+        if (packageJson.hasKey(VAADIN_DEP_KEY) && packageJson
+                .getObject(VAADIN_DEP_KEY).hasKey(dependenciesKey)) {
+            return packageJson.getObject(VAADIN_DEP_KEY)
+                    .getObject(dependenciesKey);
+        }
+        return Json.createObject();
+    }
```
Comment (pleku) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java:138]: This is just code duplication from the beginning of `collectUserManagedDependencies`, maybe just make that method reuse the object fetched here ?

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java [hunk 2]
```diff
@@ -46,15 +48,34 @@
     JsonObject getFilteredVersions(JsonObject versions) {
         JsonObject json = Json.createObject();
         for (String key : versions.keys()) {
-            if (!userManagedDependencies.hasKey(key)) {
-                json.put(key, versions.getString(key));
-            } else {
+            if (userManagedDependencies.hasKey(key)) {
                 json.put(key, userManagedDependencies.getString(key));
```
Comment (pleku) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java:52]: Should we opt for newer platform managed dependency when possible ?
One scenario is when people downgrade due to an issue - then I think this will work. But then when they update the platform version later on, the old version stays there forever ?
Another scenario is when people upgrade a version before it is released in platform - then this works but the override stays there forever and the downside of the first scenario happens and the version is not updated anymore ? 

For pnpm the node_modules etc. are never deleted (at least by `TaskUpdatePackages`) since it only checks for the version upgrade in `!enablePnpm`

Comment (pleku) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java:52]: Should we just make the upgrade possible but not downgrade ? Then basically they have to downgrade the whole platform version to be able to downgrade a component.

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java [hunk 3]
```diff
@@ -558,6 +557,95 @@ public void runPnpmInstall_customNpmRcFileFound_npmRcFileIsNotGenerated()
...
+                        Json.parse("{ \"@vaadin/vaadin-overlay\":\""
+                                + PINNED_VERSION + "\"}"))
+                        .toJson());
+        task.execute();
+
+        File overlayPackageJson = new File(getNodeUpdater().nodeModulesFolder,
+                "@vaadin/vaadin-overlay/package.json");
+
+        // The resulting version should be the one specified via platform
+        // versions file
```
Comment (pleku) [inline flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java:594]: This comment is the opposite of what is expected below ?

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java [hunk 4]
```diff
@@ -558,6 +557,95 @@ public void runPnpmInstall_customNpmRcFileFound_npmRcFileIsNotGenerated()
...
+        JsonObject overlayPackage = Json.parse(FileUtils
+                .readFileToString(overlayPackageJson, StandardCharsets.UTF_8));
+        Assert.assertEquals(customOverlayVersion,
+                overlayPackage.getString("version"));
+    }
+
+    @Test
+    public void runPnpmInstall_vaadinVersionNewerThanPinned_installedOverlayVersionIsNotSpecifiedByPlatform()
```
Comment (pleku) [inline flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java:602]: (same comment as in code earlier) Is this the expectancy that we would want to have ? That users stay on the old version until they manually remove it. Doesn't seem like a good way

**Review by pleku — CHANGES_REQUESTED** [review]

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java (hunk 1 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java:138]: :+1:

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java (hunk 4 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java:602]: ? This tests that when we find a npm annotation with a version newer than the one in platform versions that we don't take the version from platform, but use the found annotated version.

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java (hunk 3 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java:594]: fixed

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java (hunk 2 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java:52]: I can't say. 
At the time of making there was quite a long debate on if it should be possible for the user to set only newer or also give the choice to have an older version.
The end result then was that the user can put in what he want's and we won't touch it if it never matches the framework found version.

Comment (pleku) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java:52]: Yeah, then it is actually the same as with Maven - when you add your own overrides, you have to remember to remove those too or swear when you don't. So lets keep it.

But it might help if we could log a warning that "you've pinned an older version of vaadin-party-parrot than what comes with vaadin x.y.z" so that people could mayhaps realize that they can remove the pin. Can you add something like that ?

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java (hunk 4 above)
Comment (pleku) [reply flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java:601]: Right, I misunderstood the test context as `vaadin` is not the same as `platform` ..

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java (hunk 2 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java:52]: Added warning into logs for the older version.

File: flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java (hunk 4 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java:601]: Changed the test name to be more clear that it's the version that flow has found and written to the package.json

**Review by pleku — APPROVED** [review]
