### PR TITLE
Remove obsolete for(;;); prefix from JSON responses

### LINKED ISSUE #17728: JSON Requests Returning "for(;;);" Prefix Causing WAF Issues
### Describe the bug

I have identified a significant bug in our application related to JSON requests. All JSON requests are returning a "for(;;);" prefix, which is causing issues with our Web Application Firewall (WAF) due to JSON misformatting.

### Expected-behavior

_No response_

### Reproduction
Any request with the format ?v-r=uidl&v-guild=X (X --> any number)
Inspect the response received, and you will find a "for(;;);" prefix before the expected JSON data.

### System Info

Application Version: Vaadin 24.1.7 Maven
Operating System: MacOS / Windows 11

### PR DESCRIPTION
**Pull request by Artur-**
The for(;;); prefix was added in 2008 to prevent JSON hijacking attacks via script tag injection. This protection is now obsolete due to modern browser security features:

- CORB/ORB blocks cross-origin script execution of JSON responses
- Content-Type enforcement prevents MIME sniffing
- CORS prevents unauthorized cross-origin reads
- SameSite cookies prevent credential leakage

The prefix causes issues with modern security infrastructure:
- WAF/ModSecurity blocks due to invalid JSON format
- Incompatible with API security standards
- Requires custom bypass rules in security tools

Changes:
- Server: Remove prefix wrapping in UIDL, Push, and Bootstrap handlers
- Client: Remove unwrapping logic and obsolete helper methods
- Tests: Update to expect plain JSON responses
- Remove wrapJsonForClient(), stripJSONWrapping(), parseWrappedJson()

The UIDL protocol is internal (client and server update together), so there are no backwards compatibility concerns.

Fixes #17728

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java [hunk 1]
```diff
@@ -2083,19 +2083,15 @@ public static String createCriticalNotificationJSON(String caption,
             json.set("locales", JacksonUtils.createObjectNode());
             json.set("meta", meta);
             json.put(ApplicationConstants.SERVER_SYNC_ID, -1);
-            return wrapJsonForClient(json);
+            return json.toString();
         } catch (Exception e) {
             getLogger().warn(
                     "Error creating critical notification JSON message", e);
-            return wrapJsonForClient(JacksonUtils.createObjectNode());
+            return JacksonUtils.createObjectNode().toString();
```
Comment (mcollovati) [inline flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java:2090]: I guess this line is basically like `return "{}"`;

Comment (Artur-) [reply flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java:2090]: Yes
