### PR TITLE
fix: Pass javaResourceFolder to Options in DevModeInitializer (#23440) (CP: 25.0)

### LINKED ISSUE #23438: Legacy Theme components style not included when running in dev mode with gradle
### Description of the bug

When I start my application with bootRun in gradle, the components style are not used at all.

It works correctly when using a production build or when using maven.

This problem is only with legacy components style defined as follows:

File src/main/frontend/themes/THEME_NAME/components/vaadin-text-field.css
`[part='input-field'] { box-shadow: inset 0 0 0 3px red; }`

File src/main/resources/vaadin-featureflags.properties
`com.vaadin.experimental.themeComponentStyles=true`

The effect seems to be that the file frontend/generated/theme-THEME_NAME.components.generated.js is not generated correctly with gradle in development mode. It is missing the following entry:
```
registerStyles(
        'vaadin-text-field',
        unsafeCSS(vaadinTextFieldCss.toString())
      );
```

### Expected behavior

The components style are applied.

### Minimal reproducible example

A minimum example is available here: 
[theme-bug-reproducer.zip](https://github.com/user-attachments/files/25183222/theme-bug-reproducer.zip)

If you run the example with gradle bootRun, the text field is shown without component style (no red border).
If you run the example with maven, the component style is applied to th text field (red border).

### Versions

- Vaadin / Flow version: 25.0.4
- Java version: 21
- OS version: Windows 11
- Browser version (if applicable): Not relevant
- Application Server (if applicable): Not relevant
- IDE (if applicable): IntelliJ IDEA

### PR DESCRIPTION
**Pull request by Artur-**
DevModeInitializer was creating an Options object without setting javaResourceFolder, causing TaskUpdateSettingsFile to overwrite it with an empty string. This broke legacy theme component styles in Gradle dev mode because the Vite theme plugin couldn't find vaadin-featureflags.properties in the correct location.

Fixes #23438

### CODE REVIEW

File: vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java [hunk 1]
```diff
@@ -227,6 +227,7 @@ public static DevModeHandler initDevModeHandler(Set<Class<?>> classes,
                 .withFrontendGeneratedFolder(
                         new File(frontendFolder + GENERATED))
                 .withBuildDirectory(config.getBuildFolder());
+                .setJavaResourceFolder(config.getJavaResourceFolder());
```
Comment (caalador) [inline vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java]:
```suggestion
                .withBuildDirectory(config.getBuildFolder())
                .setJavaResourceFolder(config.getJavaResourceFolder());
```

**Review by caalador — CHANGES_REQUESTED** [review]
