### PR TITLE
fix: make IPhone version above 14.7 browsers allowed for Vaadin

### LINKED ISSUE #11654: Google app on iOS shows "browser too old" for Vaadin apps
The user agent the Google App reports is
```
Mozilla/5.0 (iPhone; CPU iPhone OS 14_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/117.0.321844219 Mobile/15E148 Safari/604.1
```

For reference, Safari on the same iOS device reports
```
Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1
```

The Google App user agent does not contain the version information at all. Therefore, the logic added in #6518 by @bennewi  looks at the webkit version. In this case it is 605.1.15 which according to the logic in the code is too old but in reality is Safari 14.1.

The user agent on latest Safari on desktop is
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15
```
which makes me think that either the wikipedia page with webkit versions is completely wrong or then Safari does not report the actual web kit version used.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #11654

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java [hunk 1]
```diff
@@ -87,6 +87,8 @@
     private static final String EDGE_18 = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; ServiceUI 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763";
     private static final String EDGE_79 = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 Edg/79.0.309.71";
 
+    private static final String IPHONE_14_7 = "Mozilla/5.0 (iPhone; CPU iPhone OS 14_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/117.0.321844219 Mobile/15E148 Safari/604.1";
```
Comment (caalador) [inline flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java:90]:
```suggestion
    private static final String GOOGLE_APP_IPHONE_14_7 = "Mozilla/5.0 (iPhone; CPU iPhone OS 14_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/117.0.321844219 Mobile/15E148 Safari/604.1";
```

File: flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java [hunk 2]
```diff
@@ -606,6 +608,10 @@ public void testIos11Firefox() {
         assertEngineVersion(bd, 604.3f);
     }
 
+    public void testIphone14_7IsNotOld() {
+        assertNotTooOld(IPHONE_14_7);
```
Comment (caalador) [inline flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java:612]:
```suggestion
        assertNotTooOld(GOOGLE_APP_IPHONE_14_7);
```

**Review by caalador — COMMENTED** [review]
Would be more explicit on the app that the test string is for.

**Review by caalador — APPROVED** [review]
Probably needs merge from master to get the error pattern fixed for the failing test.

**Comment by denis-anisimov** [comment]
> Probably needs merge from master to get the error pattern fixed for the failing test.

right...

**Review by mshabarov — APPROVED** [review]

**Review by caalador — APPROVED** [review]
