### PR TITLE
fix: extract browser details earlier

### LINKED ISSUE #23396: ExtendedClientDetails not available during UI Init Event
### Description of the bug

ui.getPage().getExtendedClientDetails() has the following Java Doc:

> Browser details are automatically collected and sent during UI initialization, making them immediately available. 

However when calling `getExtendedClientDetails` during a `uiInit(UIInitEvent event)` it's not initialized yet.

The underlying problem seems to be that https://github.com/vaadin/flow/blob/0940ac1fd8736f74dcbabb2a219f6418676ba545/flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java#L157-L158 fires the UIInitEvent before the browser details have been extracted in https://github.com/vaadin/flow/blob/0940ac1fd8736f74dcbabb2a219f6418676ba545/flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java#L175

### Expected behavior

Possible options:
* `ExtendedClientDetails` are available during the UIInitEvent
* There is some kind of other Event like `ExtendedClientDetailsInitallyRetrieved` or `AfterUIInitEvent` that can be utilized without requiring to explicitly fetch `ExtendedClientDetails` (again) during UI init
* It should be maybe somehow possible to change/extend the UI class so that users can customize the behavior themselfs. Currently this is not possible because for example the `uiClass` parameter in https://github.com/vaadin/flow/blob/0940ac1fd8736f74dcbabb2a219f6418676ba545/flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java#L153-L157 is ignored

### Minimal reproducible example

N/A See referenced code above

### Versions

- Vaadin / Flow version: 25.0.5

### PR DESCRIPTION
**Pull request by caalador**
Extract the browserDetails earlier
so that they are available when
UiInitListeners are fired.

Fixes #23396

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java [hunk 1]
```diff
@@ -1359,6 +1360,9 @@ protected BootstrapContext createAndInitUI(Class<? extends UI> uiClass,
         ui.doInit(request, session.getNextUIid(), context.getAppId());
         session.addUI(ui);
 
+        // Parse browser details from request parameters and store in UI
+        extractAndStoreBrowserDetails(request, ui);
```
Comment (Artur-) [inline flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java]: Does it make any difference if this is done here or before `doIniit`?

Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java]: It should not.  I'll update the positioning.
