### PR TITLE
chore: Fix initalizing to devServers

### LINKED ISSUE #10018: DevModeHandlerTest.start_twoInstances_secondInstanceUsesAnotherPort fails at times
Often one devServer fails the webpack build with:

```
ERROR in Entry module not found: Error: Can't resolve '/tmp/junit7702281413292110741/target/flow-frontend/VaadinDevmodeGizmo.js' in '/tmp/junit7702281413292110741/frontend'

ERROR in ../target/index.ts
Module not found: Error: Can't resolve '@vaadin/flow-frontend/Flow' in '/tmp/junit7702281413292110741/target'
 @ ../target/index.ts 15:0-50 16:33-37
 @ ./generated/vaadin.ts

ERROR in /tmp/junit7702281413292110741/target/index.ts
../target/index.ts
[tsl] ERROR in /tmp/junit7702281413292110741/target/index.ts(18,20)
      TS2307: Cannot find module '@vaadin/flow-frontend/Flow' or its corresponding type declarations.
```

but at times the test fails even when the build passes for both.

### PR DESCRIPTION
**Pull request by caalador**
Don't start third devServer in middle.

Fixes #10018

### CODE REVIEW

File: flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java [hunk 1]
```diff
@@ -591,14 +591,6 @@ public void start_twoInstances_secondInstanceUsesAnotherPort()
         // remove the "singleton" instance to be able to start another one
         removeDevModeHandlerInstance();
 
-        // since the timeout is quite big the server port still should be
```
Comment (denis-anisimov) [inline flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java:594]: This comment should not be removed I guess.

**Review by denis-anisimov — CHANGES_REQUESTED** [review]

File: flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java (hunk 1 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java:594]: Comment returned.

**Review by denis-anisimov — APPROVED** [review]
