### PR TITLE
fix: check postinstall before run

### LINKED ISSUE #12861: Check that a package contains a postinstall script before trying to run it
### Description of the bug

If postinstall is enabled for a package that doesn't have a postinstall script, you will see something like
```
npm ERR! Missing script: "postinstall"
npm ERR!
npm ERR! Did you mean one of these?
npm ERR!     npm install # Install a package
npm ERR!     npm uninstall # Remove a package
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
```

### Expected behavior

Flow should check if there is a postinstall script before trying to run it

### Minimal reproducible example

-

### Versions

- Vaadin / Flow version: 23 alpha 3

### PR DESCRIPTION
**Pull request by caalador**
Check that there is a postinstall
script available before executing
it to not receive error in the logs.

Fixes #12861

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java [hunk 1]
```diff
@@ -428,6 +428,19 @@ private void runNpmInstall() throws ExecutionFailedException {
             if (!packageFolder.exists()) {
                 continue;
             }
+            try {
+                JsonObject packageJson = TaskGeneratePackageJson
+                        .getJsonFileContent(
+                                new File(packageFolder, "package.json"));
+                if (!containsPostinstallScript(packageJson)) {
+                    continue;
```
Comment (Artur-) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java:436]: This should log a message on debug level because the situation is unexpected

Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java:439]: added debug logging

**Review by Artur- — APPROVED** [review]
