### PR TITLE
fix!: update old browser check to verify compatibility with Vaadin 25+

### LINKED ISSUE #23026: Is this still the correct check for V25?
https://github.com/vaadin/flow/blame/6351f7656904694f79fdf3e7a7e3d489abc1405f/flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java#L321

(changed two years ago)
```java
    private void redirectToOldBrowserPageWhenNeeded(Document indexDocument) {
        addScript(indexDocument, """
                if (!('CSSLayerBlockRule' in window)) {
                    window.location.search='v-r=oldbrowser';
                }
                """);
    }
```

### PR DESCRIPTION
**Pull request by knoobie**
## Description

Update old browser check to ensure that Vaadin 25 compatible application can be detected. Vaadin's web-components require `popover` to be available.

Fixes #23026 

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by knoobie** [comment]
Used the function recommended by MDN to verify if popover is available. https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/popover 

Tested the function standalone on MacOS / Windows 10 where it returns `true` (correctly) and Windows 7 with a legacy firefox where this function returns `false`.

File: flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java [hunk 1]
```diff
@@ -320,7 +320,7 @@ private void addStyleTagReferences(Document indexDocument,
 
     private void redirectToOldBrowserPageWhenNeeded(Document indexDocument) {
         addScript(indexDocument, """
-                if (!('CSSLayerBlockRule' in window)) {
+                if (!Object.hasOwn(HTMLElement.prototype, "popover") {
```
Comment (Artur-) [inline flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java]:
```suggestion
                if (!Object.hasOwn(HTMLElement.prototype, "popover")) {
```

Comment (knoobie) [reply flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java]: thanks.. and I just removed that second ).. stupid me
