### PR TITLE
Fix for issue #20092

### LINKED ISSUE #20092: VaadinSessionScopes for all sessions are destroyed when any single session expires
### Description of the bug

After upgrading to Vaadin 24, I noticed a strange new warning:
```
2024-09-27 19:15:33,106 [Catalina-utility-1] WARN : Invocation of destroy method failed on bean with name 'myBean': java.lang.IllegalStateException: Can't access session while another session is locked by the same thread. This restriction is intended to help avoid deadlocks.
```

The bean `MyBean` is a bean annotated with `@Scope(VaadinSessionScope.VAADIN_SESSION_SCOPE_NAME)`, i.e., it is a session-scoped bean.

I added some debugging and this is the stack trace when that error is emitted:
```
2024-09-27 19:15:33,104 [Catalina-utility-1] WARN : MyBean: stop() invoked with session com.vaadin.flow.server.VaadinSession@29bab2d4 != com.vaadin.flow.server.VaadinSession@fd8ac40 locked
java.lang.Throwable: HERE
	at com.example.MyBean.stop(MyBean.java:40) ~[classes/:?]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:211) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.run(DisposableBeanAdapter.java:195) ~[spring-beans-6.1.12.jar:6.1.12]
	at com.vaadin.flow.spring.scopes.BeanStore.doDestroy(BeanStore.java:110) ~[vaadin-spring-24.4.8.jar:?]
	at com.vaadin.flow.spring.scopes.VaadinSessionScope$SessionBeanStore.doDestroy(VaadinSessionScope.java:61) ~[vaadin-spring-24.4.8.jar:?]
	at com.vaadin.flow.spring.scopes.BeanStore.execute(BeanStore.java:154) ~[vaadin-spring-24.4.8.jar:?]
	at com.vaadin.flow.spring.scopes.BeanStore.destroy(BeanStore.java:98) ~[vaadin-spring-24.4.8.jar:?]
	at com.vaadin.flow.spring.scopes.VaadinSessionScope$SessionBeanStore.lambda$new$a4a1fe4f$2(VaadinSessionScope.java:53) ~[vaadin-spring-24.4.8.jar:?]
	at com.vaadin.flow.server.VaadinService.lambda$fireSessionDestroy$9c853e43$1(VaadinService.java:657) ~[flow-server-24.4.8.jar:24.4.8]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2092) [flow-server-24.4.8.jar:24.4.8]
	at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:725) [flow-server-24.4.8.jar:24.4.8]
	at com.vaadin.flow.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:2057) [flow-server-24.4.8.jar:24.4.8]
	at com.vaadin.flow.server.VaadinService.accessSession(VaadinService.java:2024) [flow-server-24.4.8.jar:24.4.8]
	at com.vaadin.flow.server.VaadinSession.access(VaadinSession.java:1029) [flow-server-24.4.8.jar:24.4.8]
	at com.vaadin.flow.server.VaadinService.fireSessionDestroy(VaadinService.java:631) [flow-server-24.4.8.jar:24.4.8]
	at com.vaadin.flow.server.VaadinSession.valueUnbound(VaadinSession.java:208) [flow-server-24.4.8.jar:24.4.8]
	at org.apache.catalina.session.StandardSession.removeAttributeInternal(StandardSession.java:1432) [catalina.jar:10.1.25]
	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:679) [catalina.jar:10.1.25]
	at org.apache.catalina.session.StandardSession.isValid(StandardSession.java:508) [catalina.jar:10.1.25]
	at org.apache.catalina.session.ManagerBase.processExpires(ManagerBase.java:604) [catalina.jar:10.1.25]
	at org.apache.catalina.session.ManagerBase.backgroundProcess(ManagerBase.java:587) [catalina.jar:10.1.25]
	at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:4787) [catalina.jar:10.1.25]
        ... etc ...
```
Basically what is happening is that session A is being shutdown, but this is causing the Spring scope associated with session B to be shutdown.

Tell this appears to be the result of some incorrect logic in `VaadinSessionScope`:
```java
public class VaadinSessionScope extends AbstractScope {
                
    public static final String VAADIN_SESSION_SCOPE_NAME = "vaadin-session";
                            
    private static class SessionBeanStore extends BeanStore {
            
        private final Registration sessionDestroyListenerRegistration;
            
        private SessionBeanStore(VaadinSession session) {
            super(session);
            if (session instanceof SpringVaadinSession) {
                sessionDestroyListenerRegistration = null;
                ((SpringVaadinSession) session)
                        .addDestroyListener(event -> destroy());
            } else {
                sessionDestroyListenerRegistration = session.getService()
                        .addSessionDestroyListener(event -> destroy());   // WRONG!
            }   
        }   
```
The problem is that the method `VaadinService.addSessionDestroyListener()` will deliver a notification for **every** session that is destroyed, but `VaadinSessionScope` should only be concerned with its own session. So it needs to ignore notifications for other, unrelated sessions, e.g., like this:
```java
            } else {
                sessionDestroyListenerRegistration = session.getService()
                        .addSessionDestroyListener(event -> {
                            if (event.getSession() == session)
                                destroy();
                        });
            }   
        }   
```
As a result of this bug, if there are two `VaadinSession`s and one of them expires, both of them will have their `VaadinSessionScope`'s destroyed. One particular side effect is that beans in the still-alive session are `destroy()`'ed and in the process they may try to lock their `VaadinSession`, but the dead `VaadinSession`'s lock is already locked, generating the warning. Of course all kinds of other disasters could happen depending on the specific application.

### Expected behavior

A session's Spring scope should not be shutdown when some other session expires.

### Minimal reproducible example

None currently available; the problem should be obvious.

### Versions

* Vaadin / Flow version: 24.4.12
* Java version: 17
* OS version: Mac OS 14.6.1
* Browser version: Firefox 130.0.1
* Application Server: Tomcat 10.1.28

### PR DESCRIPTION
**Pull request by archiecobbs**
## Description

Fix for #20092: `VaadinSessionScope`s for all sessions are destroyed when any single session expires.

* Add new method `VaadinSession.addSessionDestroyListener()` for when you just want one destroy notificatios for a single session, instead of geting notifications for all sessions via `VaadinService.addSessionDestroyListener()`.

* Refactor the Spring scopes to take advantage of the new method to fix an inefficiency.

* Mark `SpringVaadinSession`, which is now empty and useless, for deprecation.

Fixes #20092 (see further discussion there)

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by mshabarov** [comment]
@archiecobbs thank you for the contribution!

**Comment by caalador** [comment]
Seems good apart from the formatting. 
Could you run `mvn formatter:format -pl flow-server,vaadin-spring` and push the formatted sources.

**Comment by archiecobbs** [comment]
> Could you run `mvn formatter:format -pl flow-server,vaadin-spring` and push the formatted sources.

Done in 7f8ab58271. Thanks.

**Review by caalador — APPROVED** [review]

**Review by tepi — APPROVED** [review]

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinSession.java [hunk 1]
```diff
@@ -15,62 +15,25 @@
...
-     *
-     * @see VaadinService#addSessionInitListener(SessionInitListener)
-     *
-     * @param listener
-     *            the vaadin service session destroy listener
-     */
-    public void addDestroyListener(SessionDestroyListener listener) {
-        destroyListeners.add(listener);
-    }
-
```
Comment (tepi) [inline vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinSession.java:75]: Could you please deprecate these methods instead of removing them? They are public API so could not be removed until a major version. The vaadin-spring module was missing from the api-diff check so this did not stand out earlier.

**Review by tepi — CHANGES_REQUESTED** [review]
Please see comment about `SpringVaadinSession`

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinSession.java (hunk 1 above)
Comment (archiecobbs) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinSession.java]: > Could you please deprecate these methods instead of removing them? 

Oops, sorry about that - thanks. Should be fixed in d518484fd7.

Comment (archiecobbs) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinSession.java]: Oops, hang on, I still need to figure out how to deal with `fireSessionDestroy()`...

**Review by tepi — APPROVED** [review]

**Review by caalador — APPROVED** [review]

**Comment by archiecobbs** [comment]
Thanks!
