### PR TITLE
fix: Propagate forceInstantiation and recreateLayoutChain flags through forward/reroute

### LINKED ISSUE #20988: refreshCurrentRoute(true) doesn't work on forward or reroute
### Description of the bug

Calling UI.getcurrent().refreshCurrentRoute() is supposed to rebuild the current route-target and optionally the whole layout-chain, see parameter refreshRouteChain, but if I use it to refresh a route that triggers a redirect (forward/reroute) in beforeEnter() vaadin seems to discard any new created route-component (including layouts) and reuse previous.

I think the problem is, that in 
```com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.forward(NavigationEvent, BeforeEvent)``` and ```com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.reroute(NavigationEvent, BeforeEvent)``` 
the flags "**forceInstantiation**" and "**recreateLayoutChain**" of the current NavigationEvent aren't propagated to the new **NavigationEvent** created by 
```com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.getNavigationEvent(NavigationEvent, BeforeEvent)```

### Expected behavior

The route-chain should also be refreshed/recreated if a redirect was triggered inside beforeEnter() of the route-target.

### Minimal reproducible example

[testrefreshroute.zip](https://github.com/user-attachments/files/18767159/testrefreshroute.zip)

1. Start the Project & open in Browser
2. Click "Option 1"

Attributes in the Session are set:
- test_attribute = value shown in header/appbar
- redirect = flag evaluated in beforeEnter() to trigger redirect
and then refreshCurrentRoute(true) is called (true = refreshRouteChain)

Expected:
header/appbar shows h2 with text "OPTION 1" but nothing shows

Button "Option 2" shows how it should work (= shows Text "OPTION 2" in header/appbar) but without redirects.

### Versions

- Vaadin / Flow version: 24.6.5
- Java version: 17
- OS version: Windows 11
- Browser version (if applicable): Version 132.0.6834.160 (Offizieller Build) (64-Bit)
- Application Server (if applicable): Springboot/Embedded Tomcat
- IDE (if applicable): Eclipse

### PR DESCRIPTION
**Pull request by Artur-**
When refreshCurrentRoute(true) triggers a BeforeEnterObserver that calls forwardTo() or rerouteTo(), the forceInstantiation and recreateLayoutChain flags were lost because the redirect navigation events were created without them. This caused the redirect target to reuse existing component instances instead of creating new ones.

Propagate the flags in three locations:
- AbstractNavigationStateRenderer.getNavigationEvent() for both normal and error redirect paths
- InternalRedirectHandler.handle() for internal redirects

Fixes #20988

### CODE REVIEW

**Comment by Artur-** [comment]
This needs a sanity check although it looks sensible

**Comment by mcollovati** [comment]
I guess this one can merge tests from https://github.com/vaadin/flow/pull/23843, that seems an imcomplete fix

File: flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java [hunk 1]
```diff
@@ -769,6 +814,100 @@ public void handle_normalView_refreshCurrentRouteRecreatesComponents() {
 
     }
 
+    @Test
+    public void handle_refreshCurrentRoute_withForwardTo_recreatesComponents() {
```
Comment (mcollovati) [inline flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java]: I had Claude create the exact same test, but it passed also without the fix.
Is this the case also for this PR, or was just something else missing in mine?

Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java]: I copied over these 2 tests and both pass without any other changes.

Comment (mcollovati) [reply flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java]: The tests in the other PR should be more reliable because they check how many times the layout constructor is called.
The problem with the test in this PR is that it checks `attach` count against the previous navigation.
However, we need to check that `refreshCurrentRoute` recreates the layout when forwarding/rerouting. Thus, counting constructor calls seems like a better approach.

File: flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java [hunk 2]
```diff
@@ -769,6 +814,100 @@ public void handle_normalView_refreshCurrentRouteRecreatesComponents() {
...
+        renderer.handle(new NavigationEvent(router, new Location("rerouting"),
+                ui, NavigationTrigger.PAGE_LOAD));
+
+        assertEquals(1, forwardTargetLayoutAttachCount.get());
+        assertEquals(1, forwardTargetViewAttachCount.get());
+
+        String currentLayoutUUID = forwardTargetLayoutUUID;
+        String currentViewUUID = forwardTargetViewUUID;
+
+        ui.getInternals().clearLastHandledNavigation();
```
Comment (caalador) [inline flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java:878]:
```suggestion
```

This shouldn't make a difference for refresh and can be removed.

File: flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java [hunk 3]
```diff
@@ -769,6 +814,100 @@ public void handle_normalView_refreshCurrentRouteRecreatesComponents() {
...
+        renderer.handle(new NavigationEvent(router, new Location("forwarding"),
+                ui, NavigationTrigger.PAGE_LOAD));
+
+        assertEquals(1, forwardTargetLayoutAttachCount.get());
+        assertEquals(1, forwardTargetViewAttachCount.get());
+
+        String currentLayoutUUID = forwardTargetLayoutUUID;
+        String currentViewUUID = forwardTargetViewUUID;
+
+        ui.getInternals().clearLastHandledNavigation();
```
Comment (caalador) [inline flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java:842]:
```suggestion
```

Doesn't matter for refresh and can be removed.

File: flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java (hunk 1 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java]: It does check against the UUID which is created on construct, but still the tests pass even with the count being on constructor instead of in attach.

Comment (mcollovati) [reply flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java]: > It does check against the UUID which is created on construct

Yeah, but it compares to the UUID created by the previous navigation. It does not check that `refreshCurrentRoute` should call constructor twice. At least the tests in the other PR fail without the fix.

Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java]: The fix does fix the issue in the sample project so I guess the main problem is the tests not testing the correct thing here.

Comment (mcollovati) [reply flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java]: Yes, exactly.

**Comment by mcollovati** [comment]
Can we add the E2E test from #23843?
