### PR TITLE
fix: fix glob pattern in runtime hints registration

### LINKED ISSUE #22526: Native compiled apps do not start with Vaadin 25 beta1
### Description of the bug

```
npm init vaadin@latest v25-native
cd v25-native
mvn -Pproduction -Pnative native:compile
target/v25-native
```

results in
```
Caused by: java.lang.RuntimeException: no DevModeHandlerManager implementation found but but dev server enabled. Either disable by setting vaadin.frontend.hotdeploy=false (and run the build-frontend maven goal) or include the vaadin-dev-server dependency
	at com.vaadin.flow.spring.VaadinServletContextInitializer$DevModeServletContextListener.failFastContextInitialized(VaadinServletContextInitializer.java:528) ~[na:na]
	at com.vaadin.flow.spring.VaadinServletContextInitializer$FailFastServletContextListener.contextInitialized(VaadinServletContextInitializer.java:202) ~[v25-native:na]
```

### Expected behavior

It should start in production mode

### Minimal reproducible example

as above

### Versions

- Vaadin / Flow version:
- Java version:
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

### PR DESCRIPTION
**Pull request by mcollovati**
Fixes the pattern used to register runtime hints for native build to match resources in subfolders.
Also adds some basic tests to ensure main resources are accepted

Fixes #22526

### CODE REVIEW

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinHintsRegistrar.java [hunk 1]
```diff
@@ -50,7 +50,7 @@ public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
                 .forEach(cls -> ref.registerType(cls, MemberCategory.values()));
 
         // Bundles, build info etc
-        hints.resources().registerPattern("META-INF/VAADIN/*");
+        hints.resources().registerPattern("META-INF/VAADIN/**");
         hints.resources().registerPattern("vaadin-i18n/*");
```
Comment (caalador) [inline vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinHintsRegistrar.java:54]: should i18n also be ** or is that always in a single directory?

Comment (mcollovati) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinHintsRegistrar.java:54]: `DefaultI18NProvider` looks for `translations(-*).properties` only in `vaadin-i18n` (`DEFAULT_LOCATION_PATTERN = "classpath*:/vaadin-i18n/*.properties"`), so I think there is no need to look into subfolders.

Comment (mcollovati) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinHintsRegistrar.java:54]: However, I don't remember if we store other resources there

**Review by caalador — APPROVED** [review]
