### PR TITLE
fix: changed suggested classname to dash-case

### LINKED ISSUE #16865: Unify the name for the generated css classes in theme editor
### Description of the bug

The theme editor is suggesting a css classname based on 2 conventions camel case (Java standard) and kebab case (css standard).

For example, `FreeTextSearchFilter-text-field-1`.

The name should be unified and use the css standard.

### Expected behavior

The name should be unified and use the css standard.

For example, `free-text-search-filter-text-field-1`.

### Minimal reproducible example

Start a Vaadin 24.1.beta1 application with the theme editor, edit a text field.

### Versions

- Vaadin / Flow version: Vaadin 24.1.beta1
- Java version: 17
- OS version: Mac

### PR DESCRIPTION
**Pull request by MarcinVaadin**
## Description

Changed suggested classname prefix from UpperCamelCase to lower-dash-case.

image

Fixes #16865

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

File: flow-server/src/test/java/com/vaadin/flow/shared/util/SharedUtilTests.java [hunk 1]
```diff
@@ -127,6 +127,27 @@ public void camelCaseToDashSeparated() {
...
+                SharedUtil.upperCamelCaseToDashSeparated("foo"));
+        Assert.assertEquals("foo-bar",
+                SharedUtil.upperCamelCaseToDashSeparated("fooBar"));
+        Assert.assertEquals("foo--bar",
+                SharedUtil.upperCamelCaseToDashSeparated("foo--bar"));
+        Assert.assertEquals("foo-bar-baz",
+                SharedUtil.upperCamelCaseToDashSeparated("fooBarBaz"));
+        Assert.assertEquals("my-bean-container",
+                SharedUtil.upperCamelCaseToDashSeparated("MyBeanContainer"));
+        Assert.assertEquals("awesome-uRL-factory",
```
Comment (knoobie) [inline flow-server/src/test/java/com/vaadin/flow/shared/util/SharedUtilTests.java:145]: css names with uppercase feels kinda odd, should uRL be lowered as well?

Comment (MarcinVaadin) [reply flow-server/src/test/java/com/vaadin/flow/shared/util/SharedUtilTests.java]: Good point.
