### PR TITLE
fix!: Set proper value of isFromClient when using Focusable focus() and blur()

### LINKED ISSUE #9768: isFromClient in the Focus Listener is always true
In Vaadin 14.4.5, if you add a Focus Listener to a TextField, isFromClient is always true, even if the call comes from the server.

Here is a code to reproduce it:
```
@Route("focus")
public class FocusView extends VerticalLayout {

    public FocusView() {

        TextField textField = new TextField("field");
        textField.addFocusListener(e -> {
            Notification.show(e.isFromClient()?"From client": "Call from backend");
        });
        Button button = new Button("focus", e -> textField.focus());
        add(textField, button);
    }

}
```

### PR DESCRIPTION
**Pull request by TatuLund**
fixes #9768

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/component/FocusNotifier.java [hunk 1]
```diff
@@ -72,8 +72,9 @@ class FocusEvent<C extends Component> extends ComponentEvent<C> {
          *            side, <code>false</code> otherwise
          * @see ComponentEvent
          */
-        public FocusEvent(C source, boolean fromClient) {
-            super(source, fromClient);
+        public FocusEvent(C source, boolean fromClient,
+                @EventData("event.target._nextFocusIsFromClient") boolean eventFromClient) {
```
Comment (mcollovati) [inline flow-server/src/main/java/com/vaadin/flow/component/FocusNotifier.java]: With this change `isFromClient` is always false, since clicking on a text field does not send event data.
Maybe better use a `Boolean` wrapper type and fallback to `fromClient` when null.

**Review by mcollovati — CHANGES_REQUESTED** [review]
The current implementation seems incorrect to me, since it always computes `isFromClient` as false.
It would also be good to add an E2E test in the `test-root-context` module.

File: flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/FocusBlurIT.java [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+import com.vaadin.flow.component.html.testbench.SpanElement;
+import com.vaadin.flow.testutil.ChromeBrowserTest;
+
+public class FocusBlurIT extends ChromeBrowserTest {
+
+    @Override
+    protected String getTestPath() {
+        return "/com.vaadin.flow.uitest.ui.FocusBlurView";
+    }
+
```
Comment (ZheSun88) [inline flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/FocusBlurIT.java]: try to remove this override, i think the flow test struture can automatically resolve the test path based on the test class, i.e. replace the `IT` with `View` etc..

Comment (TatuLund) [reply flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/FocusBlurIT.java]: Done.

File: flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/FocusBlurIT.java
Comment (mcollovati) [inline flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/FocusBlurIT.java:1]: I would also add a test that ensures that client side focus and blur do result in `isFromClient=true`.
For focus, I guess this could be achieved by just making testbench click on the input.
I wonder if we should add an additional field to test client side blur

Comment (TatuLund) [reply flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/FocusBlurIT.java:1]: Did that, I think sending Keys.TAB should blur it.

File: flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/FocusBlurView.java [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+@Route(value = "com.vaadin.flow.uitest.ui.FocusBlurView", layout = ViewTestLayout.class)
+public class FocusBlurView extends Div {
+
+    public FocusBlurView() {
+        Input input = new Input();
+        input.addFocusListener(event -> {
+            Span span = new Span("Focused: " + event.isFromClient());
+            span.setId("focus-event");
+            add(span);
+            input.blur();
```
Comment (mcollovati) [inline flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/FocusBlurView.java]: What about calling blur only if `isFromClient == false`? This could simplify the tests

Comment (TatuLund) [reply flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/FocusBlurView.java]: I refactored the test view, now it works.

**Review by mcollovati — DISMISSED** [review]
