### PR TITLE
fix(TypeScript): Ensure model validators are generated for fields of bean type

### LINKED ISSUE #8821: TS Form: @NotNull validation doesn't work with object type property
Given:
Contact.java
```
@Entity
public class Contact extends AbstractEntity implements Cloneable {

    @ManyToOne
    @JoinColumn(name = "company_id")
    @JsonIgnoreProperties("employees")
    @NotNull
    private Company company;
    ...
```
and Company.java
```
@Entity
public class Company extends AbstractEntity {
  private String name;
  ...
}
```
A form for Contact, with a combobox for the company property. I could submit the form without selecting a value for the company.
Screenshot 2020-08-05 at 14 42 44

The code is in https://github.com/vaadin-learning-center/crm-tutorial-typescript/tree/haijian/use-ts-form

A workaround now is to manually add a Required validator to the company id property, i.e
```
this.binder.for(this.binder.model.company.id).addValidator(new class extends Required<Number>{
      validate(value: number){
        return value > 0;
      }
    });
```

### PR DESCRIPTION
**Pull request by platosha**
Fixes #8821

### CODE REVIEW

File: flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java [hunk 1]
```diff
@@ -110,5 +110,6 @@ public String stringNullable() {
         @Nullable MyEntity nullableEntity;
         @Nullable List<Optional<String>> nullableList;
         @Nullable Optional<String>[][] nullableMatrix;
+        @Nullable @NotNull MyEntity nullableNotNullEntity;
```
Comment (knoobie) [inline flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java:113]: This combination of annotations doesn't look right. I think `@Nullable` has to be removed.

Comment (platosha) [reply flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java:118]: Thanks a lot for the quick feedback. I agree, this does look strange. This is just a test fixture code, it does not matter much which of supported annotations are listed here.

Let me kindly a related question though, because I think I have a use case for this strange combination. Consider below:

```java
class MySelection {
  long id;
  // ...
}

class MyForm {
  // @Nullable?
  @NotNull
  MySelection selection; 
}
```

We generate TypeScript definitions corresponding to the Java beans above. When doing that, we assume everything to be kind of a `@Nonnull` by default, so that the TypeScript interfaces are strict, nicely require initialisation of all the fields on creation, and guarantee a value presence when are being read.

However, when it comes to binding a form with a combo-box to the `selection` field, the following is expected:
- The combo-box is empty by default, unless an initial value is provided or selected by the user. That’s why I’d add `@Nullable` to make the generated TypeScript type interface for `MyForm` allow `selection` to be undefined. We need to explicitly opt-out from the “all the data must be defined” assumption.
- The empty combo-box errors when submitted. That’s why I’d add the `@NotNull` validation constrain.

Do you have any suggestions for how to more reasonably express that kind of a field in Java?

Comment (knoobie) [reply flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java:118]: From a java point of view combining both annotation doesn't make sense (and probably (not tested; just a guess) some validation frameworks are going to complain about it). My understanding for this kind of TS "magic" is that "java is always first". Meaning that I create the bean / pojo / dto / object with the annotations or re-use an existing piece of code and just add vaadin as presentation layer. 

Examples:

```java
class Person {

  String doctorate;

  @NotNull
  String name;

  @NotNull
  Address mainAddress;

  List<Address> secondaryAddresses;

}

class Address {

  @NotNull
  String street;
  // ... and more
}
```

Given this example; I would expect the following from vaadin to generate:

 * __optional__ text-input for doctorate
 * __required__ text-input for name
 * __required__ layout for mainAddress (in this example a simple text-field)
 * button "Add Secondary Address" which creates a new layout for an address input + a "Delete this secondary address button"

or am I mistaken that the Java Bean Validation says that every property is optional until otherwise specified via annotation?

Comment (Haprog) [reply flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java:118]: @platosha Did I get the use case right that `selection` of `MyForm` (in the above example) is supposed to be a required field so that a null value is not considered valid (for submission), but it's "nullable" in the sense that we need to be able to store or refer to the state of the form when the user has not yet filled in the `selection` field?

So internally we need to be able to know that this field is null/empty even though it is a required field that must not be null for validation/submission.

Comment (Haprog) [reply flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java:118]: I agree that combining annotations like `@NotNull` and `@Nullable` makes no sense at least if they would be visible in user projects. If we need an additional annotation, better naming would be required for it.

Comment (platosha) [reply flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java]: @knoobie very good point. Thanks again for your detailed response.

@Haprog yes, that’s the use case.

Looks like it is a problem in the way our existing TS magic works. Perhaps have to reconsider our defaults in there to make our generated TypeScript fields nullable by default, as they work in Java. This change is not in scope of this PR, so to be done separately.

For now I removed the annotation from the fixture.
