### PR TITLE
fix: Remove presence check on item refresh

### LINKED ISSUE #14170: [Grid] lazy loading refreshItem will pass PageSize = Integer.MAX_VALUE
### Description of the bug

in grid using lazy data loading, when we call method `GridLazyDataView.refreshItem(data)`. it will call the callback method `fetchCallback` of `public V setItems(     com.vaadin.flow.data.provider.CallbackDataProvider.FetchCallback<T, F> fetchCallback )` with q.getPageSize = Integer.MAX_VALUE -> will load huge data.

This causes program very slow. see below code for detailed bug.

image

### Expected behavior

getPageSize = configurable. Default = 50.
Also ensure when call `refreshItem` will not change current position of the edited item in the grid.

### Minimal reproducible example

N/A

### Versions

- Vaadin / Flow version: 23
- Java version: 17
- OS version: N/A
- Browser version (if applicable):N/A
- Application Server (if applicable):N/A
- IDE (if applicable):N/A

### PR DESCRIPTION
**Pull request by MarcinVaadin**
## Description

Moved item presence check to dataProvider to prevent fetching all items

Fixes #14170 

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java [hunk 1]
```diff
@@ -123,12 +124,11 @@ public Stream<T> getItems() {
...
     public void refreshItem(T item) {
         Objects.requireNonNull(item, NULL_ITEM_ERROR_MESSAGE);
-        //@formatter:off
-        getItems()
-                .filter(i -> equals(item, i))
-                .findFirst()
-                .ifPresent(i -> dataProviderSupplier.get().refreshItem(item));
-        //@formatter:on
+        SerializablePredicate<T> filter = i -> equals(item, i);
+        if (dataProviderSupplier.get().fetch(new Query(filter)).findAny()
```
Comment (mshabarov) [inline flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java:128]: `SerializablePredicate` is used only for in memory data as far as I remember. So for callback data providers it wouldn't be used and the query in fact would fetch from 0 to int max.

**Review by taefi — APPROVED** [review]
