### PR TITLE
fix: prevent blocking when closing ViteWebSocketConnection

### LINKED ISSUE #20445: Server shutdown waits forever for ViteWebsocketConnection to close
### Description of the bug

Sometimes in development mode, when shutting down the server it does not fully shutdown but remains waiting after outputting
```
2024-11-12T09:09:05.329+02:00  INFO 56504 --- [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2024-11-12T09:09:05.338+02:00  WARN 56504 --- [ionShutdownHook] o.s.b.f.support.DisposableBeanAdapter    : Invocation of destroy method failed on bean with name 'inMemoryDatabaseShutdownExecutor': org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-224]
2024-11-12T09:09:05.339+02:00  INFO 56504 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2024-11-12T09:09:05.340+02:00  INFO 56504 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
```

Stack trace seems to indicate that it waits for Vite websocket connections to close, and it waits forever
```
"WebSocket background processing" #5033 [111647] daemon prio=5 os_prio=31 cpu=2.45ms elapsed=614.82s tid=0x000000012f131c00 nid=111647 waiting on condition  [0x000000030ad02000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@21.0.4/Native Method)
	- parking to wait for  <0x00000004058ba9f0> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(java.base@21.0.4/LockSupport.java:221)
	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@21.0.4/CompletableFuture.java:1864)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@21.0.4/ForkJoinPool.java:4013)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@21.0.4/ForkJoinPool.java:3961)
	at java.util.concurrent.CompletableFuture.waitingGet(java.base@21.0.4/CompletableFuture.java:1898)
	at java.util.concurrent.CompletableFuture.get(java.base@21.0.4/CompletableFuture.java:2072)
	at com.vaadin.base.devserver.viteproxy.ViteWebsocketConnection.close(ViteWebsocketConnection.java:147)
	at com.vaadin.base.devserver.viteproxy.ViteWebsocketProxy.close(ViteWebsocketProxy.java:101)
	at com.vaadin.base.devserver.viteproxy.ViteWebsocketEndpoint.onClose(ViteWebsocketEndpoint.java:115)
	at org.apache.tomcat.websocket.WsSession.fireEndpointOnClose(WsSession.java:733)
	at org.apache.tomcat.websocket.WsSession.doClose(WsSession.java:590)
	at org.apache.tomcat.websocket.WsSession.doClose(WsSession.java:556)
	at org.apache.tomcat.websocket.WsSession.checkExpiration(WsSession.java:1028)
	at org.apache.tomcat.websocket.WsWebSocketContainer.backgroundProcess(WsWebSocketContainer.java:1070)
	at org.apache.tomcat.websocket.BackgroundProcessManager.process(BackgroundProcessManager.java:87)
	at org.apache.tomcat.websocket.BackgroundProcessManager$WsBackgroundThread.run(BackgroundProcessManager.java:135)
```

It might be that Vite or some other part is in a broken state when this happens and the original issue might originate from having a server running, closing the laptop lid for the night, opening it in the morning and continuing using the server.

### Expected behavior

Websocket proxies should close properly or at least time out after a short while so the server is shut down

### Minimal reproducible example

-

### Versions

- Vaadin / Flow version: 24.6.0.alpha2

### PR DESCRIPTION
**Pull request by mcollovati**
## Description

This change prevents ViteWebSocketConnection to waiting indefinitely on close, waiting at most 500 milliseconds for the client websocket close request to complete.

Fixes #20445

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java [hunk 1]
```diff
@@ -144,9 +146,21 @@ public void send(String message)
...
+                CompletableFuture<WebSocket> closeRequest = client
+                        .sendClose(CloseCodes.NORMAL_CLOSURE.getCode(), "");
+                try {
+                    closeRequest.get(500, TimeUnit.MILLISECONDS);
+                } catch (TimeoutException e) {
+                    getLogger().debug("Timed out waiting for close request");
+                }
+            }
+        } else {
+            // Websocket client has not
```
Comment (Artur-) [inline vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java:161]: has not what?

Comment (mcollovati) [reply vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java:161]: You can choose whatever you want :grin: .

It should have been `// Websocket client connection has not been established`. I forgot to type a couple of characters.

**Review by Artur- — APPROVED** [review]

**Review by caalador — APPROVED** [review]
