### PR TITLE
fix: do not open FileSystem for unknown schemes

### LINKED ISSUE #11230: Fail accessing static resources from other jar:  java.nio.file.FileSystemNotFoundException: Provider "war" not installed
### Description of the bug
The new method resourceIsDirectory in StaticFileServer class generates an exception for resources that have protocol "jar:war:file", when vaadin spring boot application is started standalone (java -jar xxxx.jar)

### Minimal reproducible example
the exception is raised when a static resource enclosed in another jar (different than the running one) is tried to be accessed
e.g: 
Access to resource logo.png: http://localhost:8080/other-folder/logo.png

Maven project other-component has the image:
src/main/resources/META-INF/resources/other-folder/logo.png

Maven spring boot application other-vaadin-app has compilation dependency other-component 

This worked in flow-server version 2.5.3.

### Expected behavior
No exception raised
### Actual behavior
Exception raised: java.nio.file.FileSystemNotFoundException: Provider "war" not installed
### Versions:
    - Vaadin / Flow version: 14.6.3, Flow: 2.6.3
    - Spring boot: 2.4.5
    - Java version: 11
    - OS version: Ubuntu 20.04
    - Browser version (if applicable): not applicable
    - Application Server (if applicable): vaadin spring boot maven structure
    - IDE (if applicable): not applicable

### PR DESCRIPTION
**Pull request by caalador**
Don't open a filesystem for unknown schemes
that are probably custom for container and
have no FileSystem Provider implementation added.

Fixes #11230

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java [hunk 1]
```diff
@@ -199,6 +199,10 @@ private URI getFileURI(URI resourceURI) {
     FileSystem getFileSystem(URI resourceURI) throws IOException {
         synchronized (fileSystemLock) {
             URI fileURI = getFileURI(resourceURI);
+            if (!fileURI.getScheme().equals("file")) {
+                throw new IOException(
+                        "Can not read scheme '" + fileURI.getScheme() + "'");
```
Comment (pleku) [inline flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java:204]: Should it output the full uri for debugging purposes to be able to figure out the causing resource ? The catching block only logs this error its message.

Or since the code is not actually doing anything itself, but just checking if it is a directory, maybe the message could reflect that "this is fine" and the error can be "ignored".

File: flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java [hunk 2]
```diff
@@ -374,6 +376,56 @@ public void directoryIsNotResourceRequest() throws Exception {
...
+                "jar:war:" + warFile.toURI().toURL().toString() + "!/"
+                        + archiveFile.getName() + "!/frontend");
+
+        setupRequestURI("", "", "/frontend/.");
+        Mockito.when(servletService.getStaticResource("/frontend/."))
+                .thenReturn(folderResourceURL);
+
+        Assert.assertTrue(
+                "Request should return as static request as we can not determine non file resources in jar files.",
+                fileServer.isStaticResourceRequest(request));
```
Comment (pleku) [inline flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java:426]: How difficult would it be to add a unit test that actually verifies that the serving of the jar from the jar works, meaning that also `serveStaticResource` method call would be checked for this case ? As we don't have a regression test for that either but the added code here could help in adding the test case

**Review by pleku — COMMENTED** [review]
Looking good, couple of questions

File: flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java (hunk 1 above)
Comment (knoobie) [reply flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java:204]: Just a question or hint - this whole "resource" handling is quite tricky.. I've seen multiple issues on spring / spring boot over the last years with the same problems.. the amount of "protocol" and combinations is just absurd.. (e.g. jar, war, wsjar, zip, bundle..)

I'm not sure if you have looked around, but there is a handy spring framework class that handles this in spring, which could be used to get some ideas how they do it?

https://github.com/spring-projects/spring-framework/blob/main/spring-core/src/main/java/org/springframework/core/io/support/PathMatchingResourcePatternResolver.java

File: flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java (hunk 2 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java:425]: It would seem like we would need to unzip the initial jar to be able to check the secondary jar content.

File: flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java (hunk 1 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java]: Yes I'm certain that we can not support everything, but should only take care of the basic one and use the old resolution for anything else.

Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java]: Added more info to the exception.

File: flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java (hunk 2 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java:425]: Added test to show expectation of feature.

File: flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java [hunk 3]
```diff
@@ -374,6 +376,110 @@ public void directoryIsNotResourceRequest() throws Exception {
...
+        warFile.createNewFile();
+        Path warArchive = warFile.toPath();
+
+        try (ZipOutputStream warOutputStream = new ZipOutputStream(
+                Files.newOutputStream(warArchive))) {
+            // Create a file to the zip
+            warOutputStream.putNextEntry(new ZipEntry(archiveFile.getName()));
+            warOutputStream.write(Files.readAllBytes(tempArchive));
+
+            warOutputStream.closeEntry();
```
Comment (pleku) [inline flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java:462]: This creation code could be extracted and reused for both added tests instead of 1-1 duplication

**Review by pleku — CHANGES_REQUESTED** [review]

File: flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java [hunk 4]
```diff
@@ -374,6 +376,110 @@ public void directoryIsNotResourceRequest() throws Exception {
...
+
+        Assert.assertTrue(
+                "Request should return as static request as we can not determine non file resources in jar files.",
+                fileServer.isStaticResourceRequest(request));
+
+        folder.delete();
+    }
+
+    @Test
+    public void jarInaJar_fileIsLoadedCorrectly()
```
Comment (pleku) [inline flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java:431]: To me test name is invalid, it should be `isStaticResource_jarInAJar_detectsAsStaticResources`

File: flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java [hunk 5]
```diff
@@ -374,6 +376,110 @@ public void directoryIsNotResourceRequest() throws Exception {
         folder.delete();
     }
 
+    @Test
+    public void jarWarFileScheme_() throws IOException {
```
Comment (pleku) [inline flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java:380]: To me test name is invalid, it should be `isStaticResource_jarWarFileScheme_detectsAsStaticResources`

**Review by pleku — CHANGES_REQUESTED** [review]

File: flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java (hunk 5 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java]: done

File: flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java (hunk 4 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java]: done

File: flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java (hunk 2 above)
Comment (pleku) [reply flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java:399]: Just noting that we don't still have tests that the actual serving of the files will work (which I intended), only that those are detected properly.

File: flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java (hunk 3 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java]: done

File: flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java (hunk 2 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java:399]: Serving of files is tested for instance in `serveStaticResource` and jar resources are mainly served by the ServletContainer due to the spec. Any classResource that we serve should have their own test already.

**Review by pleku — APPROVED** [review]

**Comment by knoobie** [comment]
Has the bot a problem because this isn't targeting master?

**Comment by caalador** [comment]
Could be. I'll make a PR for master and have that trickle down instead. Even though I have used the bot for automating from  2.7 to 2.6.

**Comment by estronque** [comment]
Thanks, the fix works!
