### PR TITLE
fix: use default JSR-380 error messages in client-side validators

### LINKED ISSUE #8385: Pass java default validation message in annotations to client
Right now only custom messages given as argument of the annotation are  passed to the validator, generator should have a way to get the default message of the annotation when the user does not provide one

### PR DESCRIPTION
**Pull request by vlukashov**
- the default error messages in the built-in client-side validators are  interpolated in the same way as on the server-side
 - custom error messages (e.g. `@Size(message = "my message {min} {max}")` are not interpolated

Fixes #8385

### CODE REVIEW

File: flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts [hunk 1]
```diff
@@ -145,25 +230,41 @@ export class Digits extends AbstractValidator<string> {
...
   validate = (value: any) => validator.isAfter(value);
 }
 export class FutureOrPresent extends AbstractValidator<any> {
+  constructor(attrs?: ValidatorAttributes) {
+    super({ message: 'must be a date in the present or in the future', ...attrs });
+  }
   validate = () => { throw new Error('Form Validator for FutureOrPresent not implemented yet') };
 }
 
+function regexp(attrs: PatternAttributes | string | RegExp) {
```
Comment (Haprog) [inline flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts:257]: Why isn't this method name prefixed with underscore like the similar helpers above?

File: flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts [hunk 2]
```diff
@@ -145,25 +230,41 @@ export class Digits extends AbstractValidator<string> {
...
+}
+
 export class Pattern extends AbstractValidator<string> {
   regexp: RegExp;
   constructor(attrs: PatternAttributes | string | RegExp) {
-    super(typeof attrs === 'string' || attrs instanceof RegExp ? {} : attrs);
-    this.regexp = typeof attrs === 'string' ? new RegExp(attrs)
-      : attrs instanceof RegExp ? attrs
-        : typeof attrs.regexp === 'string' ? new RegExp(attrs.regexp) : attrs.regexp;
+    super({ message: `must match "${regexp(attrs)}"`, ..._asValidatorAttributes(attrs) });
```
Comment (Haprog) [inline flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts:266]: This isn't exactly the same message as in https://beanvalidation.org/2.0/spec/#builtinconstraints where it is `must match the following regular expression: {regexp}` I think it would be clearer to use this longer version.

File: flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts (hunk 1 above)
Comment (vlukashov) [reply flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts]: Good catch!

File: flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts (hunk 2 above)
Comment (vlukashov) [reply flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts]: Nice catch! I copied the messages from the Hibernate implementation, and this one seems to differ from the spec :)
https://github.com/hibernate/hibernate-validator/blob/master/engine/src/main/resources/org/hibernate/validator/ValidationMessages.properties#L19
