### PR TITLE
Only connect to devServer when it is started

### LINKED ISSUE #8858: Lots of "Can't assign requested address" on startup
### Description of the bug
When starting a Vaadin 17 application with a browser window open, the browser window shows the excepted "waiting for frontend compilation" popup. At the same time, a lot of these stack traces are logged in the console
```
2020-08-17 13:03:02.638 ERROR 40521 --- [nio-8080-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

java.net.BindException: Can't assign requested address
	at java.base/sun.nio.ch.Net.connect0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.Net.connect(Net.java:493) ~[na:na]
	at java.base/sun.nio.ch.Net.connect(Net.java:482) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:603) ~[na:na]
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1248) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515) ~[na:na]
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[na:na]
	at com.vaadin.flow.server.DevModeHandler.serveDevModeRequest(DevModeHandler.java:302) ~[flow-server-4.0.0.beta1.jar:4.0.0.beta1]
	at com.vaadin.flow.server.VaadinServlet.serveStaticOrWebJarRequest(VaadinServlet.java:272) ~[flow-server-4.0.0.beta1.jar:4.0.0.beta1]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:225) ~[flow-server-4.0.0.beta1.jar:4.0.0.beta1]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:107) ~[vaadin-spring-14.0.0.beta1.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.37.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:352) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626) ~[tomcat-embed-core-9.0.37.jar:4.0.FR]
```

### Minimal reproducible example
```
git clone https://github.com/Artur-/cant-assign-requested-address
cd  cant-assign-requested-address
mvn
```

### Versions:
    - Vaadin version: 17 beta 1
    - Java version: 13
    - OS version: macOs
    - Browser version (if applicable): Chrome

### PR DESCRIPTION
**Pull request by caalador**
Do not try to connect to the dev server
if it hasn't started yet or startup has failed.

Fixes #8858

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java [hunk 1]
```diff
@@ -298,7 +297,8 @@ public boolean isDevModeRequest(HttpServletRequest request) {
      */
     public boolean serveDevModeRequest(HttpServletRequest request,
             HttpServletResponse response) throws IOException {
-        if (isDevServerFailedToStart.get()) {
+        // Do not serve requests if dev server starting or failed to start.
+        if (isDevServerFailedToStart.get() || !devServerStartFuture.isDone()) {
```
Comment (pleku) [inline flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java:301]: Just curious and checking - what happens now when the previously errored request (for refresh?) will now return `false` to back to `VaadinServlet` ?
Will `StaticFileHandler` take the request or does `VaadinServlet` pass it to `VaadinServletService` ?

Just looking at the code and seeing that the `DevModeHandler` was able the return `dev-mode-not-ready.html` page on these occasions, so wondering what triggered the request which lead to error.

File: flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java [hunk 2]
```diff
@@ -208,12 +208,12 @@ public void webpackNotInstalled_throws() throws Exception {
...
-        exception.expectCause(CoreMatchers.isA(ExecutionFailedException.class));
         // The set executable doesn't work in Windows and will always return
         // false
         boolean systemImplementsExecutable = new File(baseDir, WEBPACK_SERVER)
                 .setExecutable(false);
         if (systemImplementsExecutable) {
+            exception.expectCause(CoreMatchers.isA(ExecutionFailedException.class));
             DevModeHandler.start(configuration, npmFolder,
                     CompletableFuture.completedFuture(null)).join();
         }
```
Comment (pleku) [inline flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java:219]: Should there be a unit test which makes sure that the code is not accidentally removed again and `devServerStartFuture` is considered?

File: flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java (hunk 1 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java:301]: The root problem is that the DevModeHandler handles the reload, but before the handlers are executed the servlet will check for static resources which will after initial init of DevModeHandler check the request path that should it be handled and then try to ask the at that point not running dev server if it has anything for the request.

With the addition of this check we will not do a request to the dev server if it has not yet started making the request hanlding continue to the DevModeHandler:handleRequest which will just return the waiting html page.

Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java:301]: So initially DevModeHandler will return null, but then during init it will not be null
```
        DevModeHandler handler = DevModeHandler.getDevModeHandler();

        if (handler != null && handler.isDevModeRequest(request)
                && handler.serveDevModeRequest(request, response)) {
            return true;
        }
```

File: flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java (hunk 2 above)
Comment (caalador) [reply flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java:219]: The test change is for windows systems that will never execute the start as windows doesn't have executable.

The test at the moment fails 100% of executions as windows will never throw the exception, so if the system (windows) doesn't implement executable then no exception will be thrown either making the test fail.

File: flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java (hunk 1 above)
Comment (pleku) [reply flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java:301]: Right, thanks for the explanation.

**Review by pleku — APPROVED** [review]

**Comment by pleku** [comment]
Apidiff seems drunk
