### PR TITLE
fix: allow spaces between html function call and back tick

### LINKED ISSUE #8881: BundleParser prints 'no template data' when the `html` call is followed by a space
Vaadin 14.3.4, Flow 2.3.4

When a template call to `html` is followed by a space, BundleParser fails to match such code with its regex and will only print `No template data found in ... sources`. 

Example template:

```javascript
import {PolymerElement} from '@polymer/polymer/polymer-element.js';
import {html} from '@polymer/polymer/lib/utils/html-tag.js';
import '@vaadin/vaadin-button/vaadin-button.js';
import '@polymer/iron-icon/iron-icon.js';

class MyButton extends PolymerElement {
    static get template() {
        return html `
            <vaadin-button theme="tertiary">
                <iron-icon icon="vaadin:bell" slot="suffix"></iron-icon>
            </vaadin-button>
    `;
    }

    static get is() {
        return 'my-button';
    }
}

customElements.define(MyButton.is, MyButton);
```

Java code:
```java
package org.vaadin.example;

import com.vaadin.flow.component.Tag;
import com.vaadin.flow.component.dependency.JsModule;
import com.vaadin.flow.component.dependency.Uses;
import com.vaadin.flow.component.icon.IronIcon;
import com.vaadin.flow.component.polymertemplate.PolymerTemplate;
import com.vaadin.flow.templatemodel.TemplateModel;

@Tag("my-button")
@JsModule("./src/my-button.js")
public class MyButton extends PolymerTemplate<TemplateModel> {
}
```

### Expected behavior
Vaadin should parse such template correctly.
### Actual behavior
Vaadin logs  `No template data found in ... sources`.

### PR DESCRIPTION
**Pull request by denis-anisimov**
fixes #8881

### CODE REVIEW

**Review by mshabarov — APPROVED** [review]

File: flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java [hunk 1]
```diff
@@ -90,7 +90,7 @@
      * end character with <code>;}</code> e.g. <code>';}</code>
      */
     private static final Pattern POLYMER_TEMPLATE_PATTERN = Pattern.compile(
-            "get[\\s]*template\\(\\)[\\s]*\\{[\\s]*return[\\s]*html([\\`\\'\\\"])([\\s\\S]*)\\1;[\\s]*\\}");
+            "get[\\s]*template\\(\\)[\\s]*\\{[\\s]*return[\\s]*html\s*([\\`\\'\\\"])([\\s\\S]*)\\1;[\\s]*\\}");
```
Comment (mshabarov) [inline flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java:93]:
```suggestion
            "get[\\s]*template\\(\\)[\\s]*\\{[\\s]*return[\\s]*html[\\s]*([\\`\\'\\\"])([\\s\\S]*)\\1;[\\s]*\\}");
```

**Review by mshabarov — APPROVED** [review]
