### PR TITLE
fix(offline): support offlinePath from PWA annotation

### LINKED ISSUE #8856: Keep V18 compatible with the `offlinePath` property of `@PWA`
When upgrading a Vaadin 12+ app that uses the `@PWA` annotation to Vaadin 18, I want the `offlinePath` property of the `@PWA` annotation to remain working as before, so that my migration is easier. 

The `offlinePath` property in V12+ is a path to a static 'offline page' HTML file that's served by the service worker instead of the bootstrap page when the app is offline. In V18 doing exactly the same does not make sense because the same app shell remains active also when offline. The expectation is that the 'offline page' HTML is displayed in place of the server-side views, not in place of the entire application shell.

One solution to this would be creating a 'compatibility offline view' web component that renders the contents of the custom offline page inside an iframe.

DoD:
 - Having a V17 app with a `@PWA` annotation and a custom `offlinePath`, after an upgrade to V18, when the app goes offline I want to see the content of the custom `offline.html` rendered instead the app shell (i.e. the behavior in V18 remains exactly the same as it is in V17 and no new offline features are available to the app until the developer removes the `offlinePath` property from the `@PWA` annotation).
 - same as above, but instead of using a custom `offlinePath` property, the app has customized content in the default `offline.html` file path -> the presence of the `offline.html` resource is detected and when the app is offline, the content of `offline.html` is rendered instead the app shell
 - when the `offlinePath` property of the `@PWA` annotation is not set, when offline the app renders the app shell. See https://github.com/vaadin/flow/issues/9132.

### PR DESCRIPTION
**Pull request by platosha**
Fixes #8856

### CODE REVIEW

**Review by haijian-vaadin — CHANGES_REQUESTED** [review]
Few findings:
1. the second point of DoD in the ticket seems is not taken into consideration. i.e. 

> same as above, but instead of using a custom offlinePath property, the app has customized content in the default offline.html file path -> the presence of the offline.html resource is detected and when the app is offline, the content of offline.html is rendered instead the app shell

2. in a v17 Spring app, the `offlinePath` is relative to `src/main/resources/META-INF/resources`, in our offline branch, it's relative to `src/main/webapp`, but maybe this is in the scope of #8996.

**Review by haijian-vaadin — DISMISSED** [review]
Let's merge this one, have a new ticket regarding `customized content in the default offline.html file path`

File: flow-server/src/main/java/com/vaadin/flow/server/PWA.java [hunk 1]
```diff
@@ -66,14 +66,15 @@
...
      * Path to the static offline html file.
      *
-     * Defaults to (relative) {@literal offline.html} with default configuration
-     * that is {@literal webapp/offline.html}
+     * Defaults to empty value, meaning that the application shell (`index
+     * .html` file) is used offline.
      *
-     * If offline file is not found, falls back to default offline page.
+     * If offline file is not found, falls back to using the application shell
+     * offline.
```
Comment (joheriks) [inline flow-server/src/main/java/com/vaadin/flow/server/PWA.java:73]: Is that actually correct? I tested `@PWA(offlinePath="notexisting.html)` where `notexisting.html` is not served by the app and the browser replied `This site can’t be reached` rather than falling back to the appshell.

**Review by Haprog — APPROVED** [review]
Looks good.
