### PR TITLE
fix: use JS to get DOM element value instead Selenium getAttribute

### LINKED ISSUE #11210: FrontendLiveReloadIT::liveReloadOnTouchedFrontendFile fails with NPE
### Description of the bug / feature

FrontendLiveReloadIT::liveReloadOnTouchedFrontendFile fails for Flow 6,7,8 with:

```
java.lang.RuntimeException: liveReloadOnTouchedFrontendFile[ANY_Chrome_](com.vaadin.flow.uitest.ui.FrontendLiveReloadIT): run failed 2 times
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:78)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.vaadin.flow.uitest.ui.FrontendLiveReloadIT.liveReloadOnTouchedFrontendFile(FrontendLiveReloadIT.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.vaadin.testbench.parallel.ParallelRunner$TBMethod.invokeExplosively(ParallelRunner.java:490)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.vaadin.testbench.parallel.ParallelRunner$1.evaluate(ParallelRunner.java:464)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:68)
	... 12 more
------- Stderr: -------
Jun 10, 2021 8:20:58 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Jun 10, 2021 8:21:00 AM com.vaadin.testbench.ScreenshotOnFailureRule failed
INFO: Error screenshot written to: /opt/agent/work/a69251da2b2bb9e9/flow-tests/test-live-reload/error-screenshots/liveReloadOnTouchedFrontendFile[ANY_Chrome_](com.vaadin.flow.uitest.ui.FrontendLiveReloadIT).png
Jun 10, 2021 8:21:01 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Jun 10, 2021 8:21:02 AM com.vaadin.testbench.ScreenshotOnFailureRule failed
INFO: Error screenshot written to: /opt/agent/work/a69251da2b2bb9e9/flow-tests/test-live-reload/error-screenshots/liveReloadOnTouchedFrontendFile[ANY_Chrome_](com.vaadin.flow.uitest.ui.FrontendLiveReloadIT).png
```

[Flow_Public_Flow_Pull_Requests_Run_Validation_17874.log](https://github.com/vaadin/flow/files/6630870/Flow_Public_Flow_Pull_Requests_Run_Validation_17874.log)

Screenshot 2021-06-10 at 14 17 26

### PR DESCRIPTION
**Pull request by denis-anisimov**
fixes #11210

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/FrontendLiveReloadIT.java [hunk 1]
```diff
@@ -87,4 +85,10 @@ public void webpackErrorIsShownAfterReloadAndHiddenAfterFix() {
         // then: the error box is not shown and the view is reloaded
         waitForElementNotPresent(By.className("v-system-error"));
     }
+
+    private String getValue(WebElement element) {
+        Object result = getCommandExecutor()
+                .executeScript("return arguments[0].value;", element);
```
Comment (pleku) [inline flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/FrontendLiveReloadIT.java:91]: To be honest, I don't know why the code is not checking for `value` property instead as the target element is `<textarea>`. But I don't want to waste more time here if this works

**Review by pleku — APPROVED** [review]
