### PR TITLE
fix: support serialization of Vaadin scoped beans

### LINKED ISSUE #19967: Serialization of scoped beans fails due to the missing UI instance
### Description of the bug

This issue is tightly connected to kubernetes kit issue: https://github.com/vaadin/kubernetes-kit/issues/140

While discussing with @mcollovati he discovered that as a part of fixing the issue above, there is a need for a fix also in the Flow:

"We need to set the UI threadlocal. Unfortunately we cannot do it in the UI class, because the reference to the bean is held by its parent class Component that is serialized before UI.writeObject() gets called. But we can "fix" this in Flow by adding the thread local logic in Component class. Once this is done, the serialization completes correctly (also needs setting threadlocal in VaadinSession writeObject)"

### Expected behavior

Serialization and the de-serialization works also when the application contains scoped beans (@SessionScope, @UIScope, @RouteScope).

### Minimal reproducible example

See https://github.com/vaadin/kubernetes-kit/issues/140

The Flow fix could be something along these lines.

**com.vaadin.flow.component.Component. Add a Thread Local logic:**
```
@Serial
    private void readObject(ObjectInputStream stream)
            throws IOException, ClassNotFoundException {
        Optional<UI> uiOptional = getUI();
        if (uiOptional.isPresent()) {
            UI ui = uiOptional.get();
            Map<Class<?>, CurrentInstance> old = CurrentInstance.setCurrent(ui);
            try {
                stream.defaultReadObject();
            } finally {
                CurrentInstance.restoreInstances(old);
            }
        }
    }

    @Serial
    private void writeObject(java.io.ObjectOutputStream stream)
            throws IOException {
        Optional<UI> uiOptional = getUI();
        if (uiOptional.isPresent()) {
            UI ui = uiOptional.get();
            Map<Class<?>, CurrentInstance> old = CurrentInstance.setCurrent(ui);
            try {
                CurrentInstance.setCurrent(ui);
                stream.defaultWriteObject();
            } finally {
                CurrentInstance.restoreInstances(old);
            }
        }
    }
```

**VaadinSession improve the existing writeObject with a Thread Local handling:**
```
private void writeObject(java.io.ObjectOutputStream stream)
            throws IOException {
        boolean serializeUIs = true;

        // If service is null it has just been deserialized and should be
        // serialized in
        // the same way again
        if (getService() != null) {
            ApplicationConfiguration appConfiguration = ApplicationConfiguration
                    .get(getService().getContext());
            if (!appConfiguration.isProductionMode() && !appConfiguration
                    .isDevModeSessionSerializationEnabled()) {
                serializeUIs = false;
            }
        }

        Map<Class<?>, CurrentInstance> old = CurrentInstance.setCurrent(this);
            try {
                CurrentInstance.setCurrent(this);
                stream.defaultWriteObject();
            if (serializeUIs) {
                stream.writeObject(uIs);
                stream.writeObject(resourceRegistry);
            } else {
                stream.writeObject(new HashMap<>());
                stream.writeObject(new StreamResourceRegistry(this));
            }
        } finally {
            CurrentInstance.restoreInstances(old);
        }
```

### Versions

- Vaadin / Flow version: 24.4.11
- Java version: 17
- OS version: Mac (M2), Kubernetes Kit 2.2.2

### PR DESCRIPTION
**Pull request by mcollovati**
## Description

Makes sure that VaadinSession and UI thread locals are available during both serialization and deserialization, to allow other libraries to perform inspection and injection of Vaadin scoped beans.

Also refactors VaadinRouteScope to be independent from VaadinService when fetching RouteScopeOwner annotation for the bean, and replaces VaadinSession.unlock() calls with direct access to the lock instance to prevent unwanted push during bean lookup.

Fixes #19967
Part of vaadin/kubernetes-kit#140

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/scopes/VaadinRouteScope.java [hunk 1]
```diff
@@ -369,10 +355,52 @@ private NavigationListener getNavigationListener() {
 
     }
 
+    private record ObjectWithOwner(Object object, RouteScopeOwner owner) {
```
Comment (mshabarov) [inline vaadin-spring/src/main/java/com/vaadin/flow/spring/scopes/VaadinRouteScope.java:358]: Does this need `implements Serializable`?

**Review by mshabarov — COMMENTED** [review]
Do we need to double check CDI and Quarkus add-ons for the similar changes?

**Comment by mcollovati** [comment]
> Do we need to double check CDI and Quarkus add-ons for the similar changes?

Currently, custom logic for handling scoped beans during deserialization is implemented only in Kubernetes Kit and only for Spring.

File: flow-server/src/main/java/com/vaadin/flow/component/Component.java [hunk 2]
```diff
@@ -820,4 +826,38 @@ public void removeFromParent() {
...
+                out.defaultWriteObject();
+            } finally {
+                CurrentInstance.restoreInstances(instances);
+            }
+        } else {
+            out.defaultWriteObject();
+        }
+    }
+
+    @Serial
```
[the remark this answers is not in the document]
Comment (mcollovati) [reply flow-server/src/main/java/com/vaadin/flow/component/Component.java:844]: Yeah, makes sense, even though it is not required

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/scopes/VaadinRouteScope.java (hunk 1 above)
Comment (mcollovati) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/scopes/VaadinRouteScope.java:358]: No. The object is not stored anywhere. It is only used as a carrier of information for other logics.

**Review by mshabarov — APPROVED** [review]
