### PR TITLE
fix: log instead of throwing

### LINKED ISSUE #23686: An application does not start if node_modules cannot be deleted
### Description of the bug

When I run an application in a Docker with node_modules being shared from the host system, then the node_modules folder cannot be deleted. It seems that an application is unable to start when this happens.

The exception is being logged again and again and again
```
2026-02-26T22:24:14.696+02:00 ERROR 1081 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [com.vaadin.flow.server.ServiceException: java.io.UncheckedIOException: java.io.IOException: Unable to delete directory /.../node_modules.] with root cause

java.io.IOException: Unable to delete directory /.../node_modules.
	at com.vaadin.flow.internal.FrontendUtils.deleteDirectory(FrontendUtils.java:1182) ~[flow-server-25.1-SNAPSHOT.jar:25.1-SNAPSHOT]
	at com.vaadin.flow.internal.FrontendUtils.deleteNodeModules(FrontendUtils.java:1156) ~[flow-server-25.1-SNAPSHOT.jar:25.1-SNAPSHOT]
	at com.vaadin.flow.server.frontend.TaskUpdatePackages.cleanUp(TaskUpdatePackages.java:572) ~[flow-build-tools-25.1-SNAPSHOT-shaded.jar:na]
	at com.vaadin.flow.server.frontend.TaskUpdatePackages.updatePackageJsonDependencies(TaskUpdatePackages.java:433) ~[flow-build-tools-25.1-SNAPSHOT-shaded.jar:na]
	at com.vaadin.flow.server.frontend.TaskUpdatePackages.execute(TaskUpdatePackages.java:89) ~[flow-build-tools-25.1-SNAPSHOT-shaded.jar:na]
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:363) ~[flow-build-tools-25.1-SNAPSHOT-shaded.jar:na]
	at com.vaadin.base.devserver.startup.DevModeInitializer.runNodeTasks(DevModeInitializer.java:391) ~[vaadin-dev-server-25.1-SNAPSHOT.jar:na]
	at com.vaadin.base.devserver.startup.DevModeInitializer.lambda$initDevModeHandler$0(DevModeInitializer.java:323) ~[vaadin-dev-server-25.1-SNAPSHOT.jar:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1825) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1474) ~[na:na]
```

### Expected behavior

The app should start

### Minimal reproducible example

Default starter

### Versions

- Vaadin / Flow version:
- Java version:
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

### PR DESCRIPTION
**Pull request by caalador**
Log instead of throwing when node_modules
removal fails in cleanUp.

Fixes #23686

### CODE REVIEW

File: flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java [hunk 1]
```diff
@@ -569,7 +569,15 @@ private int removeLegacyProperties(ObjectNode packageJson)
...
 
     private void cleanUp() throws IOException {
-        FrontendUtils.deleteNodeModules(options.getNodeModulesFolder());
+        try {
+            FrontendUtils.deleteNodeModules(options.getNodeModulesFolder());
+        } catch (IOException exception) {
+            File nodeModules = options.getNodeModulesFolder();
+            log().debug("Exception removing node_modules", exception);
+            log().error(
+                    "Failed to remove '{}'. Remove it manually if there are problems with the build.",
```
Comment (mcollovati) [inline flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java]: nit: it would be nice if we could explain in the error message why Flow is attempting to delete node_module

Comment (caalador) [reply flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java]: added reason to message if not forced clean up

File: flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java [hunk 2]
```diff
@@ -574,8 +574,14 @@ private void cleanUp() throws IOException {
         } catch (IOException exception) {
             File nodeModules = options.getNodeModulesFolder();
             log().debug("Exception removing node_modules", exception);
-            log().error(
-                    "Failed to remove '{}'. Remove it manually if there are problems with the build.",
+            StringBuilder messageWithReason = new StringBuilder(
+                    "Failed to remove '{}'");
+            if (!forceCleanUp) {
+                messageWithReason.append(", due to platform version update");
+            }
```
Comment (mcollovati) [inline flow-build-tools/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java]: `Failed to remove xxx, due to platform version update` looks a bit confusing ti me. I read it as  `we failed to delete the folder because of a platform update`
What about `Removal of {} [due to platform version update] failed.`?
