### PR TITLE
CCDM: consider query string in flow navigate

### LINKED ISSUE #6446: query string should be passed to Flow when using flow.route
When navigating to a server-side view with flow.route I want the query string to be available to the server-side navigation event handlers via `event.getLocation().getQueryParameters()`. With flow-3.0.0.alpha2 this is not the case.

Steps to reproduce:
1. clone the `ccdm` branch of the beverage buddy starter
2. create a navigation link like `<a href="/?foo=bar">Reviews</a>` in the main layout
3. implement the `BeforeEnterObserver` interface in the `ReviewsList` view to receive `BeforeEnterEvent`
4. see that in the event handler `event.getLocation().getQueryParameters()` returns an empty map whereas the expected behavior is that the map contains the `foo=bar` pair.

### PR DESCRIPTION
**Pull request by qtdzz**
Fixes #6446 

This PR sends  the query string (if available) together with pathname to the server when navigating using `flow.navigate`, so that the server view will be able to get the query string from Location object.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/6450)

### CODE REVIEW

File: flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts [hunk 1]
```diff
@@ -114,9 +115,9 @@ export class Flow {
       // The callback to run from server side once the view is ready
       this.container.serverConnected = cancel =>
         resolve(cmd && cancel ? cmd.prevent() : this.container);
-
+      const flowRoute: string = ctx.pathname + (ctx.search ? ctx.search : '');
```
Comment (manolo) [inline flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts]: shouldn't also consider `ctx.hash` ?
