### PR TITLE
fix: reload route configuration upon layout changes

### LINKED ISSUE #20111: Hotswap does not take into account adding or removing @Layout
### Description of the bug

Adding or removing the `@Layout` annotation on a class implementing `RouterLayout` has no effect when using HotSwapAgent. You need to restart the server to see the change.

### Expected behavior

Expected that a server restart is not needed

### Minimal reproducible example

24.5 pre project from Start

### Versions

- Vaadin / Flow version: 24.5.0.beta4

### PR DESCRIPTION
**Pull request by mcollovati**
## Description

When a [At]Layout annotated class is modified, the changes are not propagated to the route registry after hotswap happens. This change updates Route registry layouts configuration and re-registers routes potentially impacted by the change to apply the new settings. It also checks the route target chain for active UIs in order to trigger a page refresh if the layout changes should be applied.

Fixes #20111

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java [hunk 1]
```diff
@@ -610,6 +610,19 @@ public void setLayout(Class<? extends RouterLayout> layout) {
...
+    void updateLayout(Class<? extends RouterLayout> layout) {
+        if (layout == null) {
+            return;
+        }
+        synchronized (layouts) {
+            layouts.entrySet()
+                    .removeIf(entry -> layout.equals(entry.getValue()));
+            if (layout.isAnnotationPresent(Layout.class)) {
+                layouts.put(layout.getAnnotation(Layout.class).value(), layout);
+            }
```
Comment (tepi) [inline flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java:622]: If the `layout` is already in `layouts` map and still has the annotation present, could/should that be a no-op? And only do the removing if that condition is not met?

Comment (mcollovati) [reply flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java:622]: The annotation value might have been changed. We can do an additional check, but I'm not sure it is worth it

Comment (tepi) [reply flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java:622]: Ok, in that case it does not make sense

File: flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java [hunk 2]
```diff
@@ -125,7 +126,7 @@ public static List<Class<? extends RouterLayout>> getParentLayouts(
 
         if (hasRouteAndPathMatches && !route.get().layout().equals(UI.class)) {
             list.addAll(collectRouteParentLayouts(route.get().layout()));
-        } else if (route.get().autoLayout() && hasRouteAndPathMatches
+        } else if (hasRouteAndPathMatches && route.get().autoLayout()
```
Comment (caalador) [inline flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java:129]: #20120 will make this change not needed as the layouts are not stored on load, but used dynamically as is for client layouts also.

Comment (mcollovati) [reply flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java:129]: Great, thanks. I'll revert it.

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java [hunk 3]
```diff
@@ -164,8 +166,10 @@ private void doExecute() throws ExecutionFailedException {
             writeFile(flowTsx, getFileContent(FLOW_TSX));
             writeFile(vaadinReactTsx,
                     getVaadinReactTsContent(routesTsx.exists()));
-            writeFile(new File(frontendGeneratedFolder, LAYOUTS_JSON),
-                    layoutsContent());
+            // writeFile(new File(frontendGeneratedFolder, LAYOUTS_JSON),
+            // layoutsContent());
```
Comment (tepi) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java:170]: nit: commented out code

Comment (mcollovati) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java]: removed commented code

**Review by tepi — APPROVED** [review]
