### PR TITLE
fix: Use JS equals to check whether property value is changed

### LINKED ISSUE #11175: PolymerTemplate converts properties from number to string.
In Vaadin 14.6.1, the type of a number-typed property that had been initialized from an attribute in the JS template, will be converted to `string` when the component is bound with `@Id` in a PolymerTemplate. In Vaadin 14.4.10 the type of the property was not modified.

Observed behavior: (Vaadin 14.6.1) 
- The property `min` of `field1` has type `string`
- The property `min` of `field2` has type `number`

Expected behavior: (Vaadin 14.4.10) 
- The property `min` of `field1` has type `number`
- The property `min` of `field2` has type `number`

```
class TestElement extends PolymerElement {
static get template() {
	return html`
		<vaadin-number-field id="field1" step="0.2" min="0" max="10" has-controls></vaadin-number-field>
		<vaadin-button on-click="test1">Test me</vaadin-button>
		<br>
		
		<vaadin-number-field id="field2" step="0.2" min="0" max="10" has-controls></vaadin-number-field>
		<vaadin-button on-click="test2">Test me</vaadin-button>
		<br>		
	`;
	}
	
	static get is() { return 'test-element'; }
	
	test1() { alert(typeof this.$.field1.min); }
	test2() { alert(typeof this.$.field2.min); }	

}
```

```
@Tag("test-element")
@JsModule("./test-element.js")
@Route("test")
public class TestTemplate extends PolymerTemplate<TemplateModel> {

  @Id("field1")
  private NumberField field1;

  public TestOne() {}
}
```

The actual effects on a component depends on its implementation. It doesn't seem to cause issues with `vaadin-number-field` itself, but other components such as `paper-slider` present incorrect behavior because of this issue:

```
<!-- bound as @Id("slider"), doesn't work because step is "1" (string) -->
<paper-slider id="slider" min="0" max="100" step="1" editable snaps></paper-slider>

<!-- not bound with @Id, work as expected because step is 1 (number)-->
<paper-slider min="0" max="100" step="1" editable snaps></paper-slider>
```

### PR DESCRIPTION
**Pull request by denis-anisimov**
fixes #11175

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: flow-client/src/main/java/com/vaadin/client/WidgetUtil.java [hunk 1]
```diff
@@ -319,4 +321,42 @@ public static native String stringify(JsonObject payload) /*-{
                                                               return value;
                                                               });
                                                               }-*/;
+
+    /**
+     * Checks whether the objects are equal either as Java objects (considering
+     * types and Java {@link Object#equals(Object)} method) or as JS values.
+     * 
+     * @param obj1
+     *            a an object
```
Comment (mshabarov) [inline flow-client/src/main/java/com/vaadin/client/WidgetUtil.java:330]:
```suggestion
     *            a first object to be compared
```

File: flow-client/src/main/java/com/vaadin/client/WidgetUtil.java [hunk 2]
```diff
@@ -319,4 +321,42 @@ public static native String stringify(JsonObject payload) /*-{
...
+     * 
+     * @param obj2
+     *            an object to be compared with {@code a} for deep equality
```
Comment (mshabarov) [inline flow-client/src/main/java/com/vaadin/client/WidgetUtil.java:333]:
```suggestion
     *            a second object to be compared with {@code obj1} for deep equality
```

File: flow-client/src/main/java/com/vaadin/client/WidgetUtil.java [hunk 3]
```diff
@@ -319,4 +321,42 @@ public static native String stringify(JsonObject payload) /*-{
...
+     */
+    public static boolean equals(Object obj1, Object obj2) {
+        return Objects.equals(obj1, obj2) || equalsInJS(obj1, obj2);
+    }
+
+    /**
+     * Checks whether the objects are equal as JS values.
+     * <p>
+     * This check ignores object types and checks the values via JS {@code ==}.
+     * It means that an empty string equals to {@code 0} e.g.
```
Comment (mshabarov) [inline flow-client/src/main/java/com/vaadin/client/WidgetUtil.java:347]: This sentence looks unfinished because of 'e.g.' in the end.

File: flow-client/src/main/java/com/vaadin/client/WidgetUtil.java [hunk 4]
```diff
@@ -319,4 +321,42 @@ public static native String stringify(JsonObject payload) /*-{
...
+     * 
+     * @param obj1
+     *            a an object
```
Comment (mshabarov) [inline flow-client/src/main/java/com/vaadin/client/WidgetUtil.java:350]:
```suggestion
     *            a first object to be compared
```

File: flow-client/src/main/java/com/vaadin/client/WidgetUtil.java [hunk 5]
```diff
@@ -319,4 +321,42 @@ public static native String stringify(JsonObject payload) /*-{
...
+     * 
+     * @param obj2
+     *            an object to be compared with {@code a} for deep equality
```
Comment (mshabarov) [inline flow-client/src/main/java/com/vaadin/client/WidgetUtil.java:353]:
```suggestion
     *            a second object to be compared with {@code obj1} for deep equality
```

File: flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java [hunk 6]
```diff
@@ -79,6 +79,21 @@ public void testBindExistingProperty() {
         assertEquals("foo", element.getTitle());
     }
 
+    public void testBindExistingPropertyWithDifferentType() {
+        //set nuymber as a proeprty value for DOM elememnt
```
Comment (mshabarov) [inline flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java:83]:
```suggestion
        //set number as a property value for DOM element
```

File: flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java [hunk 7]
```diff
@@ -79,6 +79,21 @@ public void testBindExistingProperty() {
...
+        double value= setNumberValue(element, "bar");
+        
+        // set string as a StateTree proeprty value
```
Comment (mshabarov) [inline flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java:86]:
```suggestion
        // set string as a StateTree property value
```

File: flow-client/src/main/java/com/vaadin/client/WidgetUtil.java (hunk 1 above)
Comment (denis-anisimov) [reply flow-client/src/main/java/com/vaadin/client/WidgetUtil.java:330]: This comment doesn't improve anything for me.

The javadocs for the parameters are copied from `Objects::equals` https://docs.oracle.com/javase/8/docs/api/java/util/Objects.html#equals-java.lang.Object-java.lang.Object-

File: flow-client/src/main/java/com/vaadin/client/WidgetUtil.java (hunk 2 above)
Comment (denis-anisimov) [reply flow-client/src/main/java/com/vaadin/client/WidgetUtil.java:333]: This comment doesn't improve anything for me.

The javadocs for the parameters are copied from `Objects::equals` https://docs.oracle.com/javase/8/docs/api/java/util/Objects.html#equals-java.lang.Object-java.lang.Object-

File: flow-client/src/main/java/com/vaadin/client/WidgetUtil.java (hunk 4 above)
Comment (denis-anisimov) [reply flow-client/src/main/java/com/vaadin/client/WidgetUtil.java:350]: See above

File: flow-client/src/main/java/com/vaadin/client/WidgetUtil.java (hunk 5 above)
Comment (denis-anisimov) [reply flow-client/src/main/java/com/vaadin/client/WidgetUtil.java:353]: See above

File: flow-client/src/main/java/com/vaadin/client/WidgetUtil.java (hunk 3 above)
Comment (denis-anisimov) [reply flow-client/src/main/java/com/vaadin/client/WidgetUtil.java:347]: done

File: flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java (hunk 6 above)
Comment (denis-anisimov) [reply flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java:83]: done

File: flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java (hunk 7 above)
Comment (denis-anisimov) [reply flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java:86]: done

File: flow-client/src/main/java/com/vaadin/client/WidgetUtil.java (hunk 1 above)
Comment (mshabarov) [reply flow-client/src/main/java/com/vaadin/client/WidgetUtil.java:330]: Oracle example has `a` as a name of variable. So at least `a` can be replaced by `obj1`. Otherwise `a an object` raise the question what is `a`.

File: flow-client/src/main/java/com/vaadin/client/WidgetUtil.java (hunk 2 above)
Comment (mshabarov) [reply flow-client/src/main/java/com/vaadin/client/WidgetUtil.java:333]: Oracle example has `a` as a name of variable. So at least `a` can be replaced by `obj1`. Otherwise `a an object` raise the question what is `a`.

File: flow-client/src/main/java/com/vaadin/client/WidgetUtil.java (hunk 4 above)
Comment (mshabarov) [reply flow-client/src/main/java/com/vaadin/client/WidgetUtil.java:350]: Oracle example has `a` as a name of variable. So at least `a` can be replaced by `obj1`. Otherwise `a an object` raise the question what is `a`.

File: flow-client/src/main/java/com/vaadin/client/WidgetUtil.java (hunk 5 above)
Comment (mshabarov) [reply flow-client/src/main/java/com/vaadin/client/WidgetUtil.java:353]: Oracle example has `a` as a name of variable. So at least `a` can be replaced by `obj1`. Otherwise `a an object` raise the question what is `a`.

File: flow-client/src/main/java/com/vaadin/client/WidgetUtil.java (hunk 1 above)
Comment (denis-anisimov) [reply flow-client/src/main/java/com/vaadin/client/WidgetUtil.java:330]: `a` is a blind copy paste and just needs to be removed.

done

File: flow-client/src/main/java/com/vaadin/client/WidgetUtil.java (hunk 2 above)
Comment (denis-anisimov) [reply flow-client/src/main/java/com/vaadin/client/WidgetUtil.java:333]: done

File: flow-client/src/main/java/com/vaadin/client/WidgetUtil.java (hunk 4 above)
Comment (denis-anisimov) [reply flow-client/src/main/java/com/vaadin/client/WidgetUtil.java]: done

**Review by mshabarov — APPROVED** [review]
