### PR TITLE
test: Fix flaky ComponentEffectTest with FlushableExecutor

### LINKED ISSUE #22572: Fix flaky tests in ComponentEffectTest
### Description of the bug

The following tests are failing quite often (likely because of timeouts in the wait conditions):
- `effect_triggeredWithNoUILocked_effectRunAsynchronously`
- `effect_triggeredWithOtherUILocked_effectRunAsynchronously`
- `effect_throwExceptionWhenRunningAsynchronously_delegatedToErrorHandler`.

The idea is to use a custom test executor that runs the effect immediately in the same thread and doesn't need a timeout at all. Perhaps the countdown latch won't be needed as well.

### Expected behavior

Tests always pass independently of a CI.

### Minimal reproducible example

See validation builds in CI

### Versions

- Vaadin / Flow version: 25.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by Artur-**
Replace async thread pool execution with a flushable executor that runs tasks synchronously on the test thread. This eliminates race conditions that caused intermittent test failures.

Root cause: Tests created effects dispatched to VaadinTaskExecutor thread pool and waited with CountDownLatch.await(1000ms). If the thread pool was busy, tasks wouldn't execute within timeout, causing flaky failures.

Solution: Implemented FlushableExecutor that queues tasks and executes them synchronously when flushed. This makes tests deterministic and fast.

Changes:
- Add FlushableExecutor class that implements Executor interface
- Add TestService that uses FlushableExecutor instead of thread pool
- Add flushExecutorAndAccessTasks() helper to process queued tasks
- Refactor three flaky tests to use flush instead of CountDownLatch
- Remove unused imports (CountDownLatch, LinkedBlockingQueue, TimeUnit)

Fixes #22572

### CODE REVIEW

File: flow-server/src/test/java/com/vaadin/flow/component/ComponentEffectTest.java [hunk 1]
```diff
@@ -60,12 +58,56 @@
...
+            while (!pendingTasks.isEmpty()) {
+                List<Runnable> tasks = new ArrayList<>(pendingTasks);
+                pendingTasks.clear();
+                tasks.forEach(Runnable::run);
+            }
+        }
+
+        public boolean hasPendingTasks() {
+            return !pendingTasks.isEmpty();
+        }
```
Comment (mcollovati) [inline flow-server/src/test/java/com/vaadin/flow/component/ComponentEffectTest.java]: This method seems unused, perhaps it can be removed

File: flow-server/src/test/java/com/vaadin/flow/component/ComponentEffectTest.java [hunk 2]
```diff
@@ -107,23 +167,20 @@ public void effect_triggeredWithNoUILocked_effectRunAsynchronously() {
...
+            // synchronously
+            flushExecutorAndAccessTasks(session);
 
-            Assert.assertTrue(
-                    "Expected effect to be executed in Vaadin Executor thread",
-                    currentThread.get().getName()
-                            .startsWith("VaadinTaskExecutor-thread-"));
-            assertSame(ui, currentUI.get());
+            assertNotNull("Effect should have been executed",
+                    currentThread.get());
```
Comment (mcollovati) [inline flow-server/src/test/java/com/vaadin/flow/component/ComponentEffectTest.java]: I guess it does not make sense anymore to check the thread name.

File: flow-server/src/test/java/com/vaadin/flow/component/ComponentEffectTest.java [hunk 3]
```diff
@@ -60,12 +58,56 @@
...
+        public boolean hasPendingTasks() {
+            return !pendingTasks.isEmpty();
+        }
+    }
+
+    /**
+     * Test service that uses FlushableExecutor instead of a background thread
+     * pool for deterministic test execution.
+     */
+    private static class TestService extends MockVaadinServletService {
```
Comment (mcollovati) [inline flow-server/src/test/java/com/vaadin/flow/component/ComponentEffectTest.java:93]: nit: we could move the executor field and the `flushExecutorAndAccessTasks` method in this class to keep the test class cleaner.

**Review by mcollovati — COMMENTED** [review]
Some minor non-blocking comments

File: flow-server/src/test/java/com/vaadin/flow/component/ComponentEffectTest.java (hunk 2 above)
Comment (Artur-) [reply flow-server/src/test/java/com/vaadin/flow/component/ComponentEffectTest.java]: I guess it's enough to check that it ran with the correct context

File: flow-server/src/test/java/com/vaadin/flow/component/ComponentEffectTest.java (hunk 3 above)
Comment (Artur-) [reply flow-server/src/test/java/com/vaadin/flow/component/ComponentEffectTest.java:93]: Done

File: flow-server/src/test/java/com/vaadin/flow/component/ComponentEffectTest.java (hunk 1 above)
Comment (Artur-) [reply flow-server/src/test/java/com/vaadin/flow/component/ComponentEffectTest.java]: Done
