### PR TITLE
Don't handle dynamic resources by the DevModeHandler

### LINKED ISSUE #8297: Random "Can't assign requested address" on startup
When starting up a 16.0.0.beta1 Spring Boot Vaadin application, I sometimes see a lot of
```
java.net.BindException: Can't assign requested address
	at java.base/sun.nio.ch.Net.connect0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.Net.connect(Net.java:493) ~[na:na]
	at java.base/sun.nio.ch.Net.connect(Net.java:482) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:603) ~[na:na]
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1248) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515) ~[na:na]
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[na:na]
	at com.vaadin.flow.server.DevModeHandler.serveDevModeRequest(DevModeHandler.java:279) ~[flow-server-3.1.0.beta1.jar:3.1.0.beta1]
	at com.vaadin.flow.server.VaadinServlet.serveStaticOrWebJarRequest(VaadinServlet.java:272) ~[flow-server-3.1.0.beta1.jar:3.1.0.beta1]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:225) ~[flow-server-3.1.0.beta1.jar:3.1.0.beta1]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:117) ~[vaadin-spring-13.0.2.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.27.jar:9.0.27]
```

These seem to stop once the webpack process has finished.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #8297

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java [hunk 1]
```diff
@@ -259,6 +263,9 @@ public boolean isDevModeRequest(HttpServletRequest request) {
      */
     public boolean serveDevModeRequest(HttpServletRequest request,
             HttpServletResponse response) throws IOException {
+        if (isDevServerFailedToStart.get()) {
+            return false;
```
Comment (mshabarov) [inline flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java:267]: Let's add some words in javadoc about that this method returns false in case of dev server failures on startup.

File: flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java [hunk 2]
```diff
@@ -396,6 +396,29 @@ public void startDevModeHandler_prepareTasksThrows_handleThrows()
...
+        try {
+            handler.handleRequest(Mockito.mock(VaadinSession.class),
+                    Mockito.mock(VaadinRequest.class),
+                    Mockito.mock(VaadinResponse.class));
+        } catch (CustomRuntimeException ignore) {
+            // this is expected and we just ignore it
+        }
+        HttpServletRequest request = Mockito.mock(HttpServletRequest.class);
+        HttpServletResponse response = Mockito.mock(HttpServletResponse.class);
+        // The following call will throw an exception without considering the
```
Comment (mshabarov) [inline flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java:415]: If I understand correctly, the call `handler.serveDevModeRequest(request, response);` won't throw and just should return `false`. Do we need to change the comment here?

File: flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java [hunk 3]
```diff
@@ -396,6 +396,29 @@ public void startDevModeHandler_prepareTasksThrows_handleThrows()
...
+        // fact that
+        // dev mode start was unsuccessful and there is no need to serve
+        // requests via serveDevModeRequest
+        handler.serveDevModeRequest(request, response);
```
Comment (mshabarov) [inline flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java:419]: Shouldn't we check the method `serveDevModeRequest` returns `false`?

File: flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java (hunk 2 above)
Comment (denis-anisimov) [reply flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java:415]: Wrong language. It's a Russian phrase construction .
It should be : `would have thrown`.
I will update
