### PR TITLE
fix: Set disabled status for component mapped to an Element

### LINKED ISSUE #8973: Parse initial disabled attribute value from templates
Follow up on #8957, given a template with
```html
<div id="foo" disabled></div>
``` 
The initial attribute value should reflect the `enabled` state on server side for an `@Id` mapped component, like
```java
@Id("foo") Div fooDiv;

fooDiv.isEnabled(); // returns false initially
```
Toggling the disabled state initially for a component in a template can be considered a reasonably common thing to do via designer. The component is then later on enabled via server side Java logic.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #8973

### CODE REVIEW

File: flow-tests/test-root-context/frontend/lit/DisabledLitTemplateElement.js [hunk 1]
```diff
@@ -0,0 +1,14 @@
+import {html, LitElement} from 'lit-element';
+import './lit-template-inner.js';
```
Comment (joheriks) [inline flow-tests/test-root-context/frontend/lit/DisabledLitTemplateElement.js:2]: Unnecessary import

**Review by joheriks — APPROVED** [review]
