### PR TITLE
fix: No react module for Vaadin Router

### LINKED ISSUE #19870: PiT 24.5: routing fails making impossible to run a downloaded hybrid application from start
### Description of the bug

When downloading the test-hybrid preset from start.vaadin.com it does not work and reports this error:

```
[plugin:vite:import-analysis] Failed to resolve import "react-router-dom" from "src/main/frontend/generated/jar-resources/ReactRouterOutletElement.tsx". Does the file exist?
/Users/manolo/Github/platform/platform-in-test-script/tmp/test-hybrid/src/main/frontend/generated/jar-resources/ReactRouterOutletElement.tsx:1:23
1  |  var _jsxFileName = "/Users/manolo/Github/platform/platform-in-test-script/tmp/test-hybrid/src/main/frontend/generated/jar-resources/ReactRouterOutletElement.tsx";
2  |  import { Outlet } from "react-router-dom";
   |                          ^
3  |  import { ReactAdapterElement } from "Frontend/generated/flow/ReactAdapter.js";
4  |  import { jsxDEV as _jsxDEV } from "react/jsx-dev-runtime";
    at TransformPluginContext._formatError (file:///Users/manolo/Github/platform/platform-in-test-script/tmp/test-hybrid/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49159:41)
    at TransformPluginContext.error (file:///Users/manolo/Github/platform/platform-in-test-script/tmp/test-hybrid/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49154:16)
    at normalizeUrl (file:///Users/manolo/Github/platform/platform-in-test-script/tmp/test-hybrid/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:63936:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/manolo/Github/platform/platform-in-test-script/tmp/test-hybrid/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:64068:39
    at async Promise.all (index 0)
    at async TransformPluginContext.transform (file:///Users/manolo/Github/platform/platform-in-test-script/tmp/test-hybrid/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:63995:7)
    at async PluginContainer.transform (file:///Users/manolo/Github/platform/platform-in-test-script/tmp/test-hybrid/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49000:18)
    at async loadAndTransform (file:///Users/manolo/Github/platform/platform-in-test-script/tmp/test-hybrid/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:51822:27)
    at async viteTransformMiddleware (file:///Users/manolo/Github/platform/platform-in-test-script/tmp/test-hybrid/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:61776:24
```

### Expected behavior

it works

### Minimal reproducible example

1. Download the hybrid app from start.vaadin.com, and run it
```
curl -s -f 'https://start.vaadin.com/dl?&preset=test-hybrid&projectName=test-hybrid' -o test-hybrid.zip
unzip test-hybrid.zip
cd test-hybrid
perl -pi -e 's|<java.version>21</java.version>|<java.version>17</java.version>|' pom.xml
./mvnw
```
2. visit the app and see the error in console

### Versions

- Vaadin / Flow version: 24.5.0.alpha14

### PR DESCRIPTION
**Pull request by caalador**
Remove reactOutlet module
if we are not running react,
but are using Vaadin Router
inferred from index.ts

Fixes #19870

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java [hunk 1]
```diff
@@ -144,6 +163,12 @@ class FullDependenciesScanner extends AbstractDependenciesScanner {
         collectScripts(scriptsSet, scriptsSetDevelopment, JavaScript.class);
         cssData = discoverCss();
 
+        if (!reactEnabled) {
+            modulesSet.stream().filter(
+                    module -> module.contains("ReactRouterOutletElement.tsx"))
+                    .findFirst().ifPresent(outlet -> modulesSet.remove(outlet));
```
Comment (mcollovati) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java:169]: nit: can this be simplified as `moduleSet.removeIf(module -> module.contains("ReactRouterOutletElement.tsx"))`

**Review by mcollovati — APPROVED** [review]
Tested with the project mentioned in the linked issue and with the fix, both running in development mode and building the production artifact work fine.

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java (hunk 1 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java]: done

**Review by mcollovati — APPROVED** [review]
