### PR TITLE
fix: Importing binary file in frontend file

### LINKED ISSUE #9926: Importing binary files in TS leads to warning with stacktrace during startup in dev mode
### Description of the bug 
[TaskUpdateImports] Could not read file <somepath>\frontend\src\slider\thumb.png. Skipping applying theme for its imports 
java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at java.base/java.nio.file.Files.readAllLines(Files.java:3330)
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.visitImportsRecursively(AbstractUpdateImports.java:511)
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.handleImports(AbstractUpdateImports.java:555)
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.visitImportsRecursively(AbstractUpdateImports.java:539)
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.handleImports(AbstractUpdateImports.java:555)
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.getUniqueEs6ImportPaths(AbstractUpdateImports.java:352)
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.getModuleLines(AbstractUpdateImports.java:388)
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.collectModules(AbstractUpdateImports.java:301)
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.run(AbstractUpdateImports.java:110)
	at com.vaadin.flow.server.frontend.TaskUpdateImports.execute(TaskUpdateImports.java:376)
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:634)
	at com.vaadin.flow.server.startup.DevModeInitializer.lambda$initDevModeHandler$0(DevModeInitializer.java:379)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
### Expected behavior
Ignore files you cannot parse.
### Actual behavior
See description
### Versions:
    - Vaadin / Flow version: 18.0.1

### PR DESCRIPTION
**Pull request by caalador**
Catch MalformedInputException for reading
file during import visit for frontend files where
file is binary and can not be read as lines.

Fixes #9926

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java [hunk 1]
```diff
@@ -508,8 +511,20 @@ private String toValidBrowserImport(String jsImport) {
...
-                .stream().collect(Collectors.joining("\n"));
+
+        String content = null;
+        try (final Stream<String> contentStream = Files
+                .lines(filePath, StandardCharsets.UTF_8)) {
+            content = contentStream.collect(Collectors.joining("\n"));
+        } catch (UncheckedIOException ioe) {
+            if (ioe.getCause() instanceof MalformedInputException) {
+                getLogger()
+                        .trace("Could not read import file '{}' most likely due to it being binary.",
```
Comment (pleku) [inline flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java:522]: Non-blocking: As a user I don't think I would be able to know what _read import file_ is supposedly doing and if I would need to react to it, but as this is `trace` level it shouldn't matter that much.

**Review by pleku — DISMISSED** [review]

File: flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java (hunk 1 above)
Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java:522]: It's hard to know what to say here. perhaps `Failed to read file '{}' found from import statements. This is probably due to it being a binary file.`

Comment (pleku) [reply flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java:522]: That is better, with maybe an additional "..binary file, in which case it doesn't matter as imports are only in js/ts files." or something.

**Review by pleku — APPROVED** [review]
