### PR TITLE
fix: Populate ActiveStyleSheetTracker during page load for CSS live reload without HotSwap Agent

### LINKED ISSUE #23592: CSS hot reload with `@StyleSheet` does not work without Hotswap Agent in Vaadin 25
### Description of the bug

When migrating to Vaadin 25, CSS files referenced using the `@StyleSheet` mechanism do not hot-reload in the browser. Changes only appear after a manual page refresh, unless Hotswap Agent (or similar tooling) is used.

This differs from the Vaadin 24 theme mechanism, where CSS updates are reflected immediately without requiring a reload.

Actually, `PublicResourcesLiveUpdater` detects file change events, but updates are blocked because `ActiveStyleSheetTracker` reports not active CSS in use. This happens because `ActiveStyleSheetTracker` is currently updated only via Vaadin hotswap hooks.

### Expected behavior

CSS changes should be applied automatically in the browser (live reload), consistent with:

* Vaadin 24 theme behavior
* Documentation on live reload for stylesheets.

### Minimal reproducible example

- Create a Vaadin 25 project (also reproducible with the quickstart tutorial project).
- Add styles.css under: src/main/resources/META-INF/resources/
- Reference it via `@StyleSheet("styles.css")` in AppShellConfigurator.
- Start the app in development mode **without Hotswap agent**.
- Modify and save the CSS file.
- Verify that the change is not immediately applied in the browser

### Versions

- Vaadin / Flow version: 25.0.4
- Java version: 21

### PR DESCRIPTION
**Pull request by mcollovati**
ActiveStyleSheetTracker was only populated by StyleSheetHotswapper.onInit(), which requires a HotSwap Agent. Without one, the tracker stayed empty and PublicResourcesLiveUpdater's file watcher silently skipped all CSS updates.

Register active `@StyleSheet` URLs during normal dev-mode page loading:
- AppShellRegistry.createSettings() tracks AppShell stylesheets
- UIInternals.addComponentDependencies() tracks component stylesheets

Both paths are guarded by !isProductionMode() for zero production overhead.

Also simplify the live reload integration test to rely on the file watcher instead of manually triggering reload via button clicks.

Fixes #23592

### CODE REVIEW

File: flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/StylesheetLiveReloadIT.java [hunk 1]
```diff
@@ -67,6 +68,14 @@ public void detectStylesheetsLocation() throws URISyntaxException {
         resourcesPath = Paths.get(markerUrl.toURI()).getParent();
         updatedImagePath = resourcesPath
                 .resolve(Paths.get("css", "images", "vaadin-logo.png"));
+
+        // The file watcher monitors the source directory, not the build
+        // output. Derive the source path from the target path:
+        // target/classes/META-INF/resources -> project root
```
Comment (caalador) [inline flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/StylesheetLiveReloadIT.java]: Would it be better to have a loop here instead that would for each parent check if the current directory contains `src`?

Comment (mcollovati) [reply flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/StylesheetLiveReloadIT.java]: Good point. It will make the test more reliable

Comment (mcollovati) [reply flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/StylesheetLiveReloadIT.java]: done. Also checking for `pom.xml` to prevent potential problems if a `src` folder is added somewhere else in target classes.
