### PR TITLE
fix: scope bindChildren to default-slot children only

### LINKED ISSUE #23662: Scope bindChildren to the default slot
Some components, such as `Card`, supports an arbitrary number of children as "regular" content and also additional slotted components for special purposes such as `card.setTitle(someComponent)`. 

To allow using `bindChildren` for the regular content, we should relax the restrictions so that components can still be present in other slots without causing conflicts. Instead, we should have a new restriction that components returned from the `bindChildren` factory can't have the `slot` attribute set.

```java
card.setTitle(new Span("My title"));

// Should be fine to bind children even though there's a child component in the `title` slot
card.bindChildren(someSignal, someFactory);

// Should be fine to add a child to the `subtitle` slot even though regular children are bound to a signal
card.setSubtitle(new Span("My subtitle"));
```

### PR DESCRIPTION
**Pull request by Artur-**
bindChildren now only manages children without a slot attribute, allowing named-slot children (e.g. card title, header) to coexist freely with signal-bound content. Add/remove operations for slotted components are permitted while a binding is active.

Fixes #23662

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/dom/ElementEffect.java [hunk 1]
```diff
@@ -438,8 +452,28 @@ private int getCachedChildrenSize() {
...
+                if (parentElement.getChild(actualIndex)
+                        .getAttribute("slot") == null) {
+                    defaultSlotCount++;
+                }
+                actualIndex++;
+            }
+            return actualIndex;
+        }
+
         private LinkedList<Element> parentChildrenToLinkedList() {
```
Comment (platosha) [inline flow-server/src/main/java/com/vaadin/flow/dom/ElementEffect.java]: Nit: I'd rename `parentChildrenToLinkedList()` to smth like `parentDefaultSlotChildrenList()` to reflect the behavior change.

File: flow-server/src/test/java/com/vaadin/flow/dom/ElementEffectTest.java [hunk 2]
```diff
@@ -987,6 +987,179 @@ public void bindChildren_withLocalValueSignalList_parentUpdated() {
...
+                .toList();
+        assertEquals(2, defaultSlotChildren.size());
+        assertEquals("first", defaultSlotChildren.get(0).getComponent()
+                .map(c -> ((TestComponent) c).getValue()).orElse(null));
+        assertEquals("second", defaultSlotChildren.get(1).getComponent()
+                .map(c -> ((TestComponent) c).getValue()).orElse(null));
+        // Slotted child should still be present
+        long slottedCount = parentComponent.getElement().getChildren()
+                .filter(e -> "title".equals(e.getAttribute("slot"))).count();
+        assertEquals(1, slottedCount);
```
Comment (platosha) [inline flow-server/src/test/java/com/vaadin/flow/dom/ElementEffectTest.java]: Would be great to assert the DOM index of the elements, both for those from the signal binding and with a slot.

File: flow-server/src/test/java/com/vaadin/flow/dom/ElementEffectTest.java [hunk 3]
```diff
@@ -987,6 +987,179 @@ public void bindChildren_withLocalValueSignalList_parentUpdated() {
...
+                .map(TestComponent.class::cast).toList();
+
+        assertEquals("last", components.get(0).getValue());
+        assertEquals("first", components.get(1).getValue());
+        assertEquals("middle", components.get(2).getValue());
+
+        // Slotted child should still exist
+        long slottedCount = parentComponent.getElement().getChildren()
+                .filter(e -> e.getAttribute("slot") != null).count();
+        assertEquals(1, slottedCount);
```
Comment (platosha) [inline flow-server/src/test/java/com/vaadin/flow/dom/ElementEffectTest.java]: Would be great to assert the DOM index of the elements here as well.

File: flow-server/src/test/java/com/vaadin/flow/dom/ElementEffectTest.java [hunk 4]
```diff
@@ -987,6 +987,179 @@ public void bindChildren_withLocalValueSignalList_parentUpdated() {
...
+        taskList.remove(taskList.peek().get(0));
+
+        // One signal child + slotted child remain
+        assertEquals(2, parentComponent.getElement().getChildCount());
+        assertEquals("second",
+                ((TestComponent) parentComponent.getChildren().toList().get(0))
+                        .getValue());
+        // Slotted child preserved
+        assertEquals("footer",
+                parentComponent.getElement().getChild(1).getAttribute("slot"));
```
Comment (platosha) [inline flow-server/src/test/java/com/vaadin/flow/dom/ElementEffectTest.java]: Would be great to assert the DOM index of the elements here as well.

**Review by platosha — CHANGES_REQUESTED** [review]
I believe the tests should include assert the resulting DOM index of the elements, both for signal bound and slotted children. I'm mostly concerned with accidental changes in the order in future, consistency matters.

File: flow-server/src/main/java/com/vaadin/flow/dom/ElementEffect.java (hunk 1 above)
Comment (Artur-) [reply flow-server/src/main/java/com/vaadin/flow/dom/ElementEffect.java]: Updated

File: flow-server/src/test/java/com/vaadin/flow/dom/ElementEffectTest.java (hunk 3 above)
Comment (Artur-) [reply flow-server/src/test/java/com/vaadin/flow/dom/ElementEffectTest.java]: Done

File: flow-server/src/test/java/com/vaadin/flow/dom/ElementEffectTest.java (hunk 4 above)
Comment (Artur-) [reply flow-server/src/test/java/com/vaadin/flow/dom/ElementEffectTest.java]: Done

File: flow-server/src/test/java/com/vaadin/flow/dom/ElementEffectTest.java (hunk 2 above)
Comment (Artur-) [reply flow-server/src/test/java/com/vaadin/flow/dom/ElementEffectTest.java]: Done

**Review by platosha — APPROVED** [review]
