### PR TITLE
fix: keep track of css injected to document (#11635)

### LINKED ISSUE #11608: Memory leak in theme generator
### Description of the bug / feature
The logic [here](https://github.com/vaadin/flow/blob/fbcec8dc67543eed9ff2c0228c45432a6d0ace65/flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js#L267) seems to push strong references of themed shadow roots to an array in the global scope but they never get cleaned up.

### Minimal reproducible example
Scroll the page at https://vaadin.com/docs/latest/ds/components/text-field up and down so that new example instances get created and old ones get discarded. Check `window.Vaadin._vaadintheme_docs_globalCss`, which seems to accumulate more and more references to the example shadow roots as you scroll.

### Expected behavior
The shadow root references get cleaned up

### Actual behavior
The array keeps accumulating shadow root references

### PR DESCRIPTION
**Pull request by caalador**
Stops css/fonts from being loaded multiple times to the document with embedded applications.

Closes #11608

Contains fix #11669

### CODE REVIEW

File: flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js [hunk 1]
```diff
@@ -82,7 +82,13 @@ const createLinkReferences = (css, target) => {
 const injectGlobalCssMethod = `
 // target: Document | ShadowRoot
 export const injectGlobalCss = (css, target, first) => {
-  
+  if(target === document) {
+    const hash = getHash(css);
```
Comment (fluorumlabs) [inline flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js:86]: I wonder if it would be any faster to use `Set` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) of `css`. I suppose native hashing would be faster then custom logic + it will handle collisions in a safe manner by design.

Comment (caalador) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js:86]: That would put the css into memory as a duplicate also.
Any changes should be in a ticket as this is just a cherrypick to 14 which will need changes due to theme handling without Fusion.

Comment (fluorumlabs) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js:86]: We have to choose between:
- Memory overhead of having css in Set
- Performance overhead of computing hash every time css is about to be injected into document

Comment (fluorumlabs) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js:86]: > Any changes should be in a ticket as this is just a cherrypick to 14 which will need changes due to theme handling without Fusion.

The chosen approach is not mentioned anywhere in the ticket so I consider it to be an implementation detail, hence commenting in a PR. But fill free to escalate it to the ticket/other involved parties

Comment (caalador) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js:86]: What I was saying is that this is already in in 7,8,9.
Also seeing as this is to fix memory issue the end impact is minimal as it's only for css targeting document and those are usually 1/theme in a project (so 2 for when there is a parent theme etc.)

Comment (fluorumlabs) [reply flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js:86]: Right. Well, nevermind then :)

File: flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java [hunk 2]
```diff
@@ -239,6 +241,22 @@ public VaadinSession getSession() {
             return session;
         }
 
+        /**
+         * Should custom theme be initialized.
+         * @return true if theme should initialize
```
Comment (mshabarov) [inline flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java:246]:
```suggestion
         * @return true if theme should be initialized
```

File: flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java [hunk 3]
```diff
@@ -239,6 +241,22 @@ public VaadinSession getSession() {
...
+         */
+        public boolean isInitTheme() {
+            return initTheme;
+        }
+
+        /**
+         * Set if custom theme should be initialized.
+         * @param initTheme initializeTheme
```
Comment (mshabarov) [inline flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java:254]:
```suggestion
         * @param initTheme enable or disable theme initialisation
```

File: flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java [hunk 4]
```diff
@@ -600,6 +618,15 @@ public Document getBootstrapPage(BootstrapContext context) {
                 handleThemeContents(context, document);
             }
 
+            // To not init theme for webcomponents we use a flag on the dom
+            if (context.isInitTheme() && context.getTheme().isPresent()
+                    && !"".equals(context.getTheme().get().getName())) {
+                head.prependElement("script").attr("type", "text/javascript")
+                        .appendChild(new DataNode(
+                                "window.Vaadin = window.Vaadin || {}; window.Vaadin.theme = window.Vaadin.theme || {};"
+                                        + "window.Vaadin.theme.flowBootstrap = {}"));
```
Comment (mshabarov) [inline flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java:627]: Using `flowBootstrap = {}` makes me think that some data will be included into this field later on. However it's just a flag that the bootstrap request is for application, not for web component. Maybe its better to set it as `window.Vaadin.theme.flowBootstrap = true`?

File: flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java [hunk 5]
```diff
@@ -600,6 +618,15 @@ public Document getBootstrapPage(BootstrapContext context) {
                 handleThemeContents(context, document);
             }
 
+            // To not init theme for webcomponents we use a flag on the dom
+            if (context.isInitTheme() && context.getTheme().isPresent()
```
Comment (mshabarov) [inline flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java:622]: I don't fully understand how memory leaks in injecting global CSS is connected with not init theme for web components, and moreover, why now we decide not to init the theme for web components? Is that a separate bug which also leads to memory leaks, i.e. injecting flow theme (global css) for web components is not needed and is an excessive memory consumption?

Comment (caalador) [reply flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java:622]: WebComponents initialize the theme through the WebComponentBootstrap but this is also run meaning that when we should add the theme only to the shadowroot of the webcomponent we also add it to the document which is not what should happen as only the webComponent should init the theme for itself.

Comment (mshabarov) [reply flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java:622]: Ah, right, so the `WebComponentBootstrapHandler` skips execution of `applyTheme(document)` via this flag in DOM, because `applyTheme(document)` is for "global" CSS. Thanks Mikael!

**Review by mshabarov — APPROVED** [review]
Tested with 14.7 Pre starter project with all types of views. Works as expected. Also checked that `window.Vaadin.theme.injectedGlobalCss` contains one hashed value between navigations and scrolling.
