### PR TITLE
fix: respect spring.devtools.livereload.enabled property

### LINKED ISSUE #22623: Error if Spring Boot livereload is disabled
### Description of the bug

If you set `spring.devtools.livereload.enabled=false` in `application.properties`, you will see an error in the browser:
```
Error in WebSocket connection to ws://localhost:49937/
```

### Expected behavior

The livereload server is not used if it is not enabled

### Minimal reproducible example

new app + above conf

### Versions

- Vaadin / Flow version: 24 and 25

### PR DESCRIPTION
**Pull request by Artur-**
When developers set spring.devtools.livereload.enabled=false, the application should not attempt to establish a WebSocket connection to the Spring Boot livereload server.

This commit fixes the issue by checking the enabled property at the source (SpringDevToolsPortHandler) and propagating the result through the entire chain:

- SpringDevToolsPortHandler: Only assigns port if livereload enabled
- IndexHtmlRequestHandler: Only includes liveReloadPort in config if set
- vaadin-dev-tools.ts: Only creates WebSocket connection if port exists

Fixes #22623

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java [hunk 1]
```diff
@@ -396,7 +396,7 @@ private void addDevTools(Document indexDocument,
         Optional<Backend> maybeBackend = liveReload
                 .map(BrowserLiveReload::getBackend);
 
-        int liveReloadPort = Constants.SPRING_BOOT_DEFAULT_LIVE_RELOAD_PORT;
```
Comment (tepi) [inline flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java:399]: This is the only use for `Constants.SPRING_BOOT_DEFAULT_LIVE_RELOAD_PORT`. Default port seems to be also in `SpringDevToolsPortHandler`. One of them should be removed

Comment (Artur-) [reply flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java:399]: Updated
