### PR TITLE
fix: join servlet context path to Vite base path in dev mode

### LINKED ISSUE #12388: [Vite]: absolute `/VAADIN` path in scripts with non-root context
In development mode, `<head>` contains scripts with absolute `/VAADIN/` prefix, e.g.:
```
<script type="module" src="/VAADIN/@vite/client"></script>
<script type="module" src="/VAADIN/generated/vaadin.ts"></script>
<script type="module" src="/VAADIN/generated/vite-devmode.ts"></script>
```
This only works when the context root is `/`. 

To reproduce, for instance take the [vite-basics test](https://github.com/vaadin/flow/tree/master/flow-tests/test-frontend/vite-basics) and add the following to `jetty-maven-plugin`:s `<configuration>` section in `pom.xml`:
```
    <webApp>
        <contextPath>/context</contextPath>
    </webApp>
```
Start the app, go to `http://localhost:8888/context/` and observe that requests for anything starting with `/VAADIN` results in a 404.

### PR DESCRIPTION
**Pull request by vursen**
## Description

When the user runs a Flow application with a servlet context path specified, Vite's server base path, as well as consequent requests to the Vite server, should start with that context path. The PR takes this approach to address the problem of the app frontend resources not loading correctly when using Vite in combination with a servlet context path. Note, the problem is only specific to the dev mode.

Fixes #12388

## Type of change

- [x] Bugfix

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

File: vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ViteHandler.java [hunk 1]
```diff
@@ -76,6 +77,8 @@ public ViteHandler(Lookup lookup, int runningPort, File npmFolder,
         command.add(getServerConfig().getAbsolutePath());
         command.add("--port");
         command.add(String.valueOf(getPort()));
+        command.add("--base");
+        command.add(getContextPath() + "/VAADIN/");
```
Comment (vursen) [inline vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ViteHandler.java:81]: **TODO:** Consider using the `VAADIN_MAPPING` constant from:

https://github.com/vaadin/flow/blob/6a6be7d2cd037732d9c5f5ddc68485b11081c6ea/flow-server/src/main/java/com/vaadin/flow/server/Constants.java#L367

**Review by platosha — COMMENTED** [review]
Looks good so far!

File: flow-server/src/main/resources/vite.generated.ts [hunk 2]
```diff
@@ -182,40 +181,54 @@ export const vaadinConfig: UserConfigFn = (env) => {
         }
       },
       {
-        name: 'inject-entrypoint-script',
+        name: 'force-remove-spa-middleware',
```
Comment (vursen) [inline flow-server/src/main/resources/vite.generated.ts:184]: **note:** For the separation of concerns, decided to extract this workaround into a separate plugin.

File: flow-server/src/main/resources/vite.generated.ts [hunk 3]
```diff
@@ -182,40 +181,54 @@ export const vaadinConfig: UserConfigFn = (env) => {
...
-                tag: 'script',
-                attrs: { type: 'module', src: '/VAADIN/generated/vite-devmode.ts' },
-                injectTo: 'head'
-              };
-              scripts.push(viteDevModeScript);
+              const basePath = server?.config.base ?? '';
+              return [
+                {
+                  tag: 'script',
+                  attrs: { type: 'module', src: `${basePath}generated/vite-devmode.ts` },
```
Comment (vursen) [inline flow-server/src/main/resources/vite.generated.ts:212]: **note:** For better flexibility, I would prefer the path to be based on the server base path rather than a hard-coded one.

File: flow-server/src/main/resources/vite.generated.ts [hunk 4]
```diff
@@ -94,7 +93,7 @@ export const vaadinConfig: UserConfigFn = (env) => {
   }
   return {
     root: 'frontend',
-    base: basePath,
+    base: '',
```
Comment (vursen) [inline flow-server/src/main/resources/vite.generated.ts:96]: **note:** The `--base` argument overrides the config `base` property.

**Review by platosha — APPROVED** [review]
