### PR TITLE
Prevent StackOverflowError in Composite.

### LINKED ISSUE #5553: Using KeyNotifier inside of Composite.initContent() leads to StackOverflowError
Tried to add a simple key listener for a form inside a composite. Initializing the key listener inisde the initContent method leads to an infinite loop of creating the composite and finally to a stack overflow error.

This example class displays the simple test case to reproduce the error (usable in the normal project starter):

```
import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.Key;
import com.vaadin.flow.component.KeyModifier;
import com.vaadin.flow.component.KeyNotifier;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

@Route("")
public class MainView extends Composite<VerticalLayout> implements KeyNotifier {

    @Override
    protected VerticalLayout initContent() {
        VerticalLayout layout = new VerticalLayout();

        Button button = new Button("Click me",
                event -> Notification.show("Clicked!"));
        layout.add(button);

        addKeyUpListener(Key.ENTER, event -> button.click(), KeyModifier.CONTROL);

        return layout;
    }
}
```

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #5553

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/component/Composite.java [hunk 1]
```diff
@@ -50,6 +50,8 @@
 public abstract class Composite<T extends Component> extends Component {
     private T content;
 
+    private ThreadLocal<Boolean> contentIsInitializing = new ThreadLocal<>();
```
Comment (joheriks) [inline flow-server/src/main/java/com/vaadin/flow/component/Composite.java:53]: `transient`?

File: flow-server/src/main/java/com/vaadin/flow/component/Composite.java [hunk 2]
```diff
@@ -113,12 +115,27 @@ private static String getExceptionMessage(Type type) {
...
+            try {
+                if (Boolean.TRUE.equals(contentIsInitializing.get())) {
+                    throw new IllegalStateException(
+                            "The content is not yet initialized. "
+                                    + "Infinite loop detected: you are calling a code inside 'initContent' "
+                                    + "which directly or indirectly is calling 'getContent'/'initContent'. "
+                                    + "You may not call any method on "
+                                    + Composite.class.getSimpleName()
+                                    + " instance until it initialized (inside 'getContent' or 'initContent'). "
+                                    + "Call methods on the content component instead.");
```
Comment (joheriks) [inline flow-server/src/main/java/com/vaadin/flow/component/Composite.java:127]: I would suggest:
```
The content is not yet initialized. 
Detected direct or indirect call to 'getContent' from 'initContent'. 
You may not call any framework method on a 'Composite' instance before 'initContent' has completed initializing the component .
```
Rationale: The infinite loop symptom is because of our implementation choice, user does not need to be aware since it is prevented by this code. Also the last suggestion to "Call methods on the content component instead" may be assuming too much about what the dev is trying to do.

File: flow-server/src/main/java/com/vaadin/flow/component/Composite.java (hunk 1 above)
Comment (denis-anisimov) [reply flow-server/src/main/java/com/vaadin/flow/component/Composite.java:53]: good point
