### PR TITLE
Fix navigate back to main view don't work in FF and Safari . (#5113)

### LINKED ISSUE #5113: Navigating back to main view don't work in FF and Safari
Navigating with UI.navigate method back to main view (mapped to root) don't work. The URL remains pointing to the previous view and this later may cause some unexpected issues with navigation.

Version: 12.0.6

Reproducible with with following two views:

``` 
@Route
public class MainView extends VerticalLayout {

    public MainView() {
        add(new Header(new Text("First view")));
        Button button = new Button("Go to second",
                event -> UI.getCurrent().navigate(SecondView.class));
        add(button);
    }
}

@Route
public class SecondView extends VerticalLayout {

    public SecondView() {
        add(new Header(new Text("Second view")));
        Button button = new Button("Go back to main (check broser url when back on main view!)",
                event -> UI.getCurrent().navigate(MainView.class));
        add(button);
    }
}
```

### PR DESCRIPTION
**Pull request by sahalsaad**
Fixed #5113

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/5291)

### CODE REVIEW

File: flow-server/src/main/java/com/vaadin/flow/router/Location.java [hunk 1]
```diff
@@ -181,7 +181,7 @@ public String getPathWithQueryParameters() {
 
         String params = queryParameters.getQueryString();
         if (params.isEmpty()) {
-            return basePath;
+            return !basePath.isEmpty() ? basePath : "/";
```
Comment (landi1993) [inline flow-server/src/main/java/com/vaadin/flow/router/Location.java]: This does actually rewrite the URL for context-aware deployed applications to root.


For example: My app is running on `myserver.example.com` under the context `/myapp`. 
This means that a route `@Route("")` is mapped to `myserver.example.com/myapp`.
And a route `@Route("mypage")` is mapped to `myserver.example.com/myapp/mypage`.


When i now `ui.navigate("")`, the URL is rewritten to `myserver.example.com`. Refreshing the page at this URL will result in a 404 since it's nothing deployed on `/`

**Comment by ZheSun88** [comment]
@landi1993 Hi, Which flow/platform version are you using? Recently, we have fixed one issue which looks quite similar to what you are referring, https://github.com/vaadin/flow/issues/5582 . Could you take a look and let me know?

**Comment by landi1993** [comment]
Hi @ZheSun88,
i was using 13.0.6 and 13.0.9 in another project where if found this. I wasn't sure if it came from my navigation / menu extension, so i debugged into. 

We have another project running on 10.0.8 i think - everything's fine here. So i looked into the release changelists and found this commit for flow release 1.0.10.

I just looked into #5582. This is the fix :-) Currently merged into flow 2.0.2 -> platform 14+. Can i expect to see this fix in older releases?

**Comment by ZheSun88** [comment]
Hi @landi1993 , Okay, that is good. I would guess there will be a release for 13.0.X next week. now let us remind the team to pick this change into that release.
