### PR TITLE
fix: do not close external filesystems

### LINKED ISSUE #16908: Vaadin 24 w/ Push + Embedded Jetty 12 - Multiple Issues
### Description of the bug

This all started when we upgraded to Vaadin 24 on our base project. We use embedded Jetty, so we had to upgrade to Jetty 12 to support Servlet 6.

1. The static file server fails to serve `/VAADIN/static/push/vaadinPush.js`.
2. `@PWA` is not present, yet the generated frontend sources expect `sw.js` and `sw-runtime-resources-precache.js`.

As far as I tested, the issues only occur when push is enabled.

image

### Expected behavior

Self-explanatory.

### Minimal reproducible example

https://github.com/oliveryasuna/vaadin24-embedded-jetty12-bug

Run `main` and navigate to http://localhost:8080. Some errors are demonstrated on first page load; more on refresh.

### Versions

- Vaadin version: 24.0.5
- Java version: 17
- OS version: macOS
- Browser version (if applicable): Chrome or Firefox
- Application Server (if applicable): Embedded Jetty
- IDE (if applicable): IntelliJ IDEA

### PR DESCRIPTION
**Pull request by caalador**
If someone else has opened
a fileSystem, do not close
it after we are done.

Thanks to @oliveryasuna for the test module.

Fixes #16908

### CODE REVIEW

File: flow-tests/test-embedded-jetty-12/src/test/java/com/vaadin/flow/server/StaticFileServerTests.java [hunk 1]
```diff
@@ -0,0 +1,144 @@
...
+    @After
+    public void disposeServer() throws Exception {
+        if (server != null) {
+            server.stop();
+
+            server = null;
+        }
+    }
+
+}
```
Comment (mcollovati) [inline flow-tests/test-embedded-jetty-12/src/test/java/com/vaadin/flow/server/StaticFileServerTests.java:144]: newline
```suggestion
}

```

Comment (caalador) [reply flow-tests/test-embedded-jetty-12/src/test/java/com/vaadin/flow/server/StaticFileServerTests.java]: added

**Review by mcollovati — APPROVED** [review]

**Review by mcollovati — APPROVED** [review]
